Repository ZcashFoundation/zebra, pull requests merged in 2020-12, with the labels that each got.

#1407 Decrease the UTXO request timeout
  zebra-consensus/src/script.rs
Labels: A-rust

#1403 Disable the nightly clippy unnecessary_wraps lint
  zebra-chain/src/lib.rs
  zebra-consensus/src/lib.rs
  zebra-network/src/lib.rs
  zebra-script/src/lib.rs
  zebra-state/src/lib.rs
  zebra-test/src/lib.rs
  zebrad/tests/acceptance.rs
Labels: A-rust

#1405 Log peer set ready and unready peers
  zebra-network/src/peer_set/set.rs
Labels: A-rust, C-enhancement

#1427 Run `cargo fmt --all`
  zebra-chain/src/work/difficulty/tests/vectors.rs
  zebra-consensus/src/checkpoint/tests.rs
Labels: A-rust, C-cleanup

#1428 Improve peer set logging hints
  zebra-network/src/peer_set/set.rs
Labels: A-rust, C-cleanup

#1440 Revert "zebrad: remove git pin on metrics dependency"
  Cargo.lock
  Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies

#1441 Improve metrics acceptance test failure messages
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug

#1293 switch to source based coverage
  .github/workflows/coverage.yml
  .gitignore
  zebra-utils/coverage
Labels: A-github-actions, A-infrastructure, C-enhancement

#1453 Downgrade tokio to 0.3.4 to avoid a time wheel panic
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, C-bug

#1459 Add crate dependencies to the release checklist
  book/src/dev/alpha-release-criteria.md
Labels: A-docs, C-enhancement

#1455 Update the zebrad commit whenever any Zebra crate changes
  zebrad/build.rs
Labels: A-rust, C-bug

#1458 Remove unused dependencies found using cargo-udeps
  Cargo.lock
  zebra-consensus/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
Labels: A-dependencies, C-cleanup

#1469 Update release criteria
  book/src/dev/alpha-release-criteria.md
Labels: A-docs

#1465 Stop panicking on side chain contextual validation
  zebra-state/src/service.rs
Labels: A-rust, C-bug

#1470 Disable issue URLs on all timeouts
  zebrad/src/application.rs
Labels: A-rust, C-bug

#1473 Support systems where bash isn't in /usr/bin
  zebra-utils/coverage
Labels: A-rust, C-bug

#1478 Add download, build and run instructions to the README
  README.md
Labels: A-docs, C-enhancement

#1490 Recommend using --locked with `cargo install` by default
  README.md
Labels: A-docs

#1492 README: add a "without --locked" troubleshooting hint
  README.md
Labels: A-docs, C-bug

#1498 Simplify C++ compiler dependency
  README.md
Labels: A-docs, C-cleanup

#1500 Rename State method names
  zebra-state/src/service.rs
  zebra-state/src/service/non_finalized_state.rs
Labels: A-rust, C-cleanup

#1502 README: clang and libclang are different
  README.md
Labels: A-docs, C-bug

#1507 Comment out collecting Sentry stacktraces for now
  zebrad/src/sentry.rs
Labels: A-infrastructure, A-rust, C-cleanup

#1468 Add peer set tracing and unreachable panics
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
Labels: A-rust, C-cleanup

#1456 Remove a redundant argument
  zebra-state/src/service/check.rs
  zebra-state/src/service/check/difficulty.rs
Labels: A-rust, C-cleanup

#1466 Cleanup the ExpandedDifficulty PartialOrd impl
  zebra-chain/src/work/difficulty.rs
Labels: A-rust, C-cleanup

#1512 Remove a redundant pattern match
  zebra-network/src/peer_set/inventory_registry.rs
Labels: A-rust, C-cleanup

#1511 Depend on a tokio commit with the time wheel panic fix
  Cargo.lock
  Cargo.toml
Labels: A-dependencies, C-bug

#1524 Fix occasional acceptance test failures
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug

#1517 Disable issue URLs for "duplicate hash" errors
  zebrad/src/application.rs
  zebrad/src/components/sync/downloads.rs
Labels: A-rust, C-cleanup

#1536 Improve the random port function docs
  zebrad/tests/acceptance.rs
Labels: A-docs, A-rust, C-cleanup

#1493 export new precompute api in zebra-script
  Cargo.lock
  zebra-consensus/src/script.rs
  zebra-consensus/src/transaction.rs
  zebra-script/Cargo.toml
  zebra-script/src/lib.rs
Labels: A-rust, C-bug

#1538 Add a full set of stderr acceptance test functions
  zebra-test/src/command.rs
Labels: A-rust, C-enhancement

#1537 Cleanup acceptance tests using utility functions
  zebrad/tests/acceptance.rs
Labels: A-rust, C-cleanup
