Repository ZcashFoundation/zebra, pull requests merged in 2020-06, with the labels that each got.

#424 Fix a typo in design.md
  design/design.md
Labels: E-easy, Poll::Ready, docs

#427 Fix a typo in a comment in block.rs
  zebra-chain/src/block.rs
Labels: E-easy, Poll::Ready, rust

#426 Document that zebra isn't intended for light wallets
  design/design.md
Labels: E-easy, Poll::Ready, design, docs

#433 Wrap Blocks in Arc throughout codebase
  zebra-network/src/peer/connection.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/internal/response.rs
  zebrad/src/commands/connect.rs
Labels: E-easy

#445 Export ed25519 zebra
  .github/workflows/assign-to-project.yml
  zebra-chain/src/keys/sapling.rs
  zebra-chain/src/lib.rs
  zebra-chain/src/transaction/joinsplit.rs
Labels: infrastructure

#451 Turn off the project workflow, reorg some CI jobs
  .github/workflows/assign-to-project.yml
  .github/workflows/pr.yml
  .github/workflows/push.yml
Labels: infrastructure

#459 Label github action updates as 'infrastructure'
  .github/dependabot.yml
Labels: infrastructure

#475 Create zbot.yml
  .github/zbot.yml
Labels: infrastructure

#478 chain: Verify the solutionSize field in block headers
  zebra-chain/src/equihash_solution.rs
Labels: E-easy, Poll::Ready, consensus, rust

#485 chain: Check the maximum block size when parsing
  zebra-chain/src/block.rs
  zebra-chain/src/block/tests.rs
  zebra-chain/src/serialization.rs
Labels: E-easy, Poll::Ready, consensus, rust

#494 Go back to stable clippy-check
  .github/workflows/pr.yml
Labels: infrastructure

#502 consensus: Add a checkpoint verifier stub
  zebra-chain/src/types.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/lib.rs
Labels: E-easy, Poll::Ready, design, rust

#517 Checkpoint Verifier Tests
  zebra-consensus/src/checkpoint.rs
Labels: E-easy, Poll::Ready, rust
