Repository ZcashFoundation/zebra, pull requests merged in 2020-08, with the labels that each got.

#810 feature: Use the Canopy testnet network protocol version
  zebra-network/src/constants.rs
Labels: A-rust, C-enhancement, E-easy, NU-Canopy, Poll::Ready

#767 Update the BlockHeader fields for Heartwood
  zebra-chain/src/block/header.rs
  zebra-chain/src/block/serialize.rs
  zebra-chain/src/block/tests.rs
Labels: A-consensus, A-rust, E-easy, Poll::Ready

#816 doc: Explain current and minimum network protocol versions
  zebra-network/src/constants.rs
Labels: A-docs, A-rust, C-cleanup, E-easy, Poll::Ready

#811 Move the difficulty tests into their own file
  zebra-chain/src/block/difficulty.rs
  zebra-chain/src/block/difficulty/tests.rs
Labels: A-rust, C-cleanup, E-easy, Poll::Ready

#817 fix: Speed up the block round trip proptest
  zebra-chain/src/block/tests.rs
Labels: A-rust, C-cleanup, E-easy, Poll::Ready

#560 Map out block validation data flow
  design/data-flow.md
Labels: A-consensus, A-docs, C-design, Poll::Ready

#828 fix: Allow PROPTEST_CASES to override the lower block case default
  zebra-chain/src/block/tests.rs
Labels: A-rust, C-bug, E-easy

#675 Use transcripts in block verify tests
  Cargo.lock
  zebra-consensus/Cargo.toml
  zebra-consensus/src/block/tests.rs
Labels: Poll::Pending

#848 Load config after initializing the Terminal
  zebrad/src/application.rs
Labels: C-bug

#854 fix: Reduce the previous block waiting time
  zebra-consensus/src/block.rs
Labels: A-rust, C-bug, E-easy, Poll::Ready

#853 Make sync ignore known hashes
  zebrad/src/commands/start/sync.rs
Labels: A-rust, C-bug, E-med, Poll::Ready

#875 rfc: Update the RFC template to talk about testing and maintenance
  book/src/dev/rfcs/0000-template.md
Labels: A-docs, C-enhancement, E-easy, Poll::Ready

#883 s/infrastructure/A-infrastructure
  .github/dependabot.yml
Labels: A-infrastructure

#886 fix: Tweak the the network listener log
  zebra-network/src/peer_set/initialize.rs
Labels: A-rust, C-cleanup, E-easy

#858 Use transcript in consensus chain tests
  zebra-consensus/src/chain/tests.rs
Labels: A-rust, C-cleanup

#891 fix: Rename ChainVerifier test variables
  zebra-consensus/src/chain/tests.rs
Labels: A-rust, C-cleanup, E-easy

#893 Use an n1-standard-2 machine for node deployments
  .github/workflows/cd.yml
Labels: A-github-actions, A-infrastructure

#895 Fix healthcheck (tracing) endpoint
  .github/workflows/cd.yml
  Dockerfile
Labels: A-infrastructure

#859 Valid generated config acceptance test
  zebra-test/src/command.rs
  zebra-test/src/prelude.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-cleanup, C-enhancement

#838 feature: Implement CompactDifficulty to Work
  zebra-chain/src/block/difficulty.rs
  zebra-chain/src/block/difficulty/tests.rs
Labels: A-consensus, A-rust, C-enhancement, E-easy, Poll::Ready

#763 rfc: Parallel Verification
  book/src/dev/rfcs/0002-parallel-verification.md
Labels: A-consensus, A-docs, C-design, E-hard, Poll::Ready

#903 Remove redundant clones for PathBufs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-cleanup

#904 Try naively parallelizing test and build jobs on our platform matrix
  .github/workflows/ci.yml
Labels: A-github-actions, A-infrastructure

#894 Implement Add for Work
  zebra-chain/src/block/difficulty.rs
  zebra-chain/src/block/difficulty/tests.rs
Labels: A-consensus, A-rust, C-enhancement, E-easy

#708 Make zebra-script wrap the C++ script implementation in zcashconsensus
  .github/workflows/ci.yml
  Cargo.lock
  Dockerfile
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-script/Cargo.toml
  zebra-script/src/lib.rs
  zebra-test/src/prelude.rs
Labels: A-rust, C-enhancement, E-hard, S-blocked

#925 fix: Remove unused dependencies
  Cargo.lock
  zebra-network/Cargo.toml
  zebra-state/Cargo.toml
  zebra-utils/Cargo.toml
Labels: A-dependencies, C-cleanup, E-easy

#926 fix: Remove redundant ConsensusBranchId constants
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-script/src/lib.rs
Labels: A-rust, C-cleanup, E-easy

#930 fix: Remove some deeply-nested instrument spans
  zebrad/src/commands/start/sync.rs
Labels: A-rust, C-bug, C-cleanup

#935 Make acceptance test failures clearer
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug, C-cleanup, E-easy

#941 Make the checkpoint limit test more readable
  zebra-consensus/src/chain/tests.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-cleanup, E-easy

#966 Use zebra favicon for zebra.zfnd.org book
  book/theme/favicon.png
Labels: A-docs

#973 deps: use x25519-dalek's new PartialEq, Eq methods
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/sprout/address.rs
  zebra-chain/src/sprout/joinsplit.rs
  zebra-chain/src/sprout/note/mac.rs
Labels: A-dependencies
