Repository ZcashFoundation/zebra, pull requests merged in 2020-10, with the labels that each got.

#1123 State RFC: remove duplicate validation steps
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-cleanup

#1098 Add Sprout note commitment tree impl and tests
  zebra-chain/src/sprout/tree.rs
Labels: A-rust, NU-Sprout

#1116 Shielded coinbase test blocks
  zebra-test/src/vectors/block-main-0-949-496.txt
  zebra-test/src/vectors/block-main-0-975-066.txt
  zebra-test/src/vectors/block-main-0-982-681.txt
  zebra-test/src/vectors/block-test-0-141-042.bin
  zebra-test/src/vectors/block-test-0-914-678.txt
  zebra-test/src/vectors/block-test-0-925-483.txt
  zebra-test/src/vectors/block-test-1-101-629.txt
  zebra-test/src/vectors/block.rs
Labels: A-rust, C-enhancement, E-easy

#1105 Impl (Add|Sub)(Assign) for ValueCommitment
  zebra-chain/src/sapling/commitment.rs
Labels: A-rust, NU-Sapling

#1118 docs: update readme
  README.md
Labels: A-docs

#1133 Format 'under construction' better in markdown
  README.md
Labels: A-docs

#1062 Add metrics for the sled state
  zebra-state/src/sled_state.rs
Labels: A-rust, C-enhancement, E-easy

#1136 State RFC: Handle duplicate block edge cases
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs

#1144 Fix some "needless lifetime" clippy lints
  zebra-network/src/address_book.rs
  zebra-network/src/peer/connection.rs
Labels: A-rust, C-cleanup

#1145 Add modules and test plans to the RFC template
  book/src/dev/rfcs/0000-template.md
Labels: A-docs, C-enhancement

#1152 Default all GitHub Actions jobs to timeout at 30 minutes
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/firebase.yml
Labels: A-github-actions, A-infrastructure

#1157 Expand the template testing section
  book/src/dev/rfcs/0000-template.md
Labels: A-docs

#1164 Reduce the equihash proptest run time
  zebra-chain/src/work/tests/prop.rs
Labels: A-rust, C-bug, C-cleanup

#1165 Tidy some difficulty code
  zebra-chain/src/work/difficulty.rs
Labels: A-rust, C-cleanup

#1167 Skip the sync tests when ZEBRA_SKIP_NETWORK_TESTS is set
  zebrad/tests/acceptance.rs
Labels: A-rust, C-enhancement

#1175 Activate the standard pull request template by default
  .github/pull_request_template.md
Labels: A-infrastructure

#1185 Add a sync test with 2000 blocks, and make it off by default
  zebrad/tests/acceptance.rs
Labels: A-rust, C-enhancement

#1178 Add team approval to the RFC pull request template
  .github/PULL_REQUEST_TEMPLATE/rfc.md
Labels: A-infrastructure

#1191 Stop assuming Mainnet in Address From impls
  zebra-chain/src/transparent/address.rs
Labels: A-consensus, A-rust, C-bug

#1195 Revise the checkpoint verifier metrics
  zebra-consensus/src/checkpoint.rs
Labels: A-rust, C-bug

#1200 Bind grafana to localhost in metrics instructions
  book/src/user/metrics.md
Labels: A-docs, C-bug

#1211 Update block metrics after async transaction verification
  zebra-consensus/src/block.rs
Labels: A-rust, C-bug

#1215 Force Clippy nightly lints to all warn, never error
  .github/workflows/ci.yml
Labels: A-infrastructure

#1193 Run a block sync in CI with 2 large checkpoints
  .github/workflows/ci.yml
  zebra-state/src/config.rs
  zebra-state/src/sled_state.rs
  zebra-test/src/command.rs
  zebrad/tests/acceptance.rs
Labels: A-github-actions, C-enhancement

#1223 Sync test reliability
  zebrad/src/components/sync.rs
Labels: A-rust, C-bug

#1232 State RFC: Clarify genesis sprout anchors
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-bug

#1196 Implement Expanded to Compact Difficulty Conversion
  zebra-chain/proptest-regressions/work/tests/prop.txt
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/work/difficulty.rs
  zebra-chain/src/work/difficulty/arbitrary.rs
  zebra-chain/src/work/difficulty/tests.rs
  zebra-chain/src/work/difficulty/tests/prop.rs
  zebra-chain/src/work/difficulty/tests/vectors.rs
  zebra-consensus/src/block/tests.rs
Labels: A-consensus, A-rust, C-cleanup, C-enhancement

#1230 Silence a clippy equal arguments warning
  zebra-chain/src/amount.rs
Labels: A-rust, C-cleanup

#1234 Replace into with Some in difficulty::arbitrary
  zebra-chain/src/work/difficulty/arbitrary.rs
Labels: A-rust, C-cleanup

#1235 Add Review and Follow Up to PR Template
  .github/pull_request_template.md
Labels: A-infrastructure, C-enhancement

#1237 State RFC: clarify difficulty
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-cleanup
