Repository ZcashFoundation/zebra, pull requests merged in 2020-09, with the labels that each got.

#979 fix: Improve checkpoint diagnostics
  zebra-consensus/src/checkpoint.rs
Labels: A-rust, C-enhancement, E-med

#978 Make tips independent of the response order
  zebrad/src/commands/start/sync.rs
Labels: A-rust, C-bug, E-med

#984 Move coverage step to common workflow for PRs and pushes to main
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: A-github-actions, A-infrastructure

#963 Implement Inventory Tracking RFC
  zebra-chain/src/transaction/hash.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/inventory_registry.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/protocol/external/inv.rs
Labels: A-rust

#994 Use ok_or for constants in zebra-network
  zebra-consensus/src/block/check.rs
  zebra-network/src/peer/handshake.rs
Labels: A-rust, C-cleanup, E-easy

#990 Improve zebra-state logging and metrics
  Cargo.lock
  zebra-state/Cargo.toml
  zebra-state/src/on_disk.rs
Labels: A-dependencies, A-rust, C-enhancement, E-easy

#996 Add log filters which provide block info
  zebra-utils/zebrad-hash-lookup
  zebra-utils/zebrad-log-filter
Labels: C-enhancement, E-med

#946 Add config path to acceptance tests
  zebrad/src/commands.rs
  zebrad/src/commands/generate.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug, E-easy

#989 Improve zebra-consensus logging and metrics
  zebra-consensus/src/block.rs
  zebra-consensus/src/chain.rs
  zebra-consensus/src/checkpoint.rs
Labels: A-rust, C-enhancement, E-med

#992 If the first ExtendTips hash is bad, discard it and re-check
  zebrad/src/commands/start/sync.rs
Labels: A-rust, C-enhancement, E-med

#991 Always drop the final hash in peer responses
  zebrad/src/commands/start/sync.rs
Labels: A-rust, C-enhancement, E-med

#980 fix: Ignore sync errors when the block is already verified
  zebrad/src/commands/start/sync.rs
Labels: A-rust, C-enhancement, E-hard

#1010 Explicitly pass our config to the start command
  Dockerfile
Labels: A-infrastructure

#870 Implement sighash
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/amount.rs
  zebra-chain/src/lib.rs
  zebra-chain/src/sprout/joinsplit.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-chain/src/transparent/serialize.rs
Labels: A-rust, C-enhancement, E-med, NU-Sapling

#1022 network: fix bug in inventory advertisement handling
  zebra-network/src/peer_set/inventory_registry.rs
Labels: A-rust, C-bug

#993 Increase sync timeouts
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
  zebrad/src/commands/start/sync.rs
Labels: A-rust, C-enhancement, E-hard

#1039 Update the inv message processing comment
  zebra-network/src/peer/handshake.rs
Labels: A-rust, C-cleanup, E-easy

#1042 Downgrade inbound peer requests to debug
  zebrad/src/commands/start.rs
Labels: A-rust, C-bug, E-easy

#1046 Run CI workflow jobs on every PR, just like Cloud Build
  .github/workflows/ci.yml
Labels: A-github-actions, A-infrastructure

#1047 Disable CodeCov annotations via GitHub Checks
  codecov.yml
Labels: A-infrastructure

#1061 Remove an unused zebra-test dependency on tempdir
  zebra-test/Cargo.toml
Labels: A-dependencies, C-cleanup, E-easy

#1067 Split a sentence in a state comment
  zebra-state/src/sled_state.rs
Labels: A-docs, C-cleanup

#1066 Update to `RootHash` in comments
  zebra-chain/src/block/root_hash.rs
Labels: A-docs, C-cleanup, E-easy

#902 RFC: state updates
  book/src/SUMMARY.md
  book/src/dev/rfcs/0005-state-updates.md
Labels: C-design

#1096 Test blocks
  .gitignore
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-test/src/vectors.rs
  zebra-test/src/vectors/block-main-0-000-000.txt
  zebra-test/src/vectors/block-main-0-000-001.txt
  zebra-test/src/vectors/block-main-0-000-002.txt
  zebra-test/src/vectors/block-main-0-000-003.txt
  zebra-test/src/vectors/block-main-0-000-004.txt
  zebra-test/src/vectors/block-main-0-000-005.txt
  zebra-test/src/vectors/block-main-0-000-006.txt
  zebra-test/src/vectors/block-main-0-000-007.txt
  zebra-test/src/vectors/block-main-0-000-008.txt
  zebra-test/src/vectors/block-main-0-000-009.txt
  zebra-test/src/vectors/block-main-0-000-010.txt
  zebra-test/src/vectors/block-main-0-347-499.txt
  zebra-test/src/vectors/block-main-0-347-500.txt
  zebra-test/src/vectors/block-main-0-347-501.txt
  zebra-test/src/vectors/block-main-0-415-000.txt
  zebra-test/src/vectors/block-main-0-419-199.txt
  zebra-test/src/vectors/block-main-0-419-200.txt
  zebra-test/src/vectors/block-main-0-419-201.txt
  zebra-test/src/vectors/block-main-0-434-873.txt
  zebra-test/src/vectors/block-main-0-653-599.txt
  zebra-test/src/vectors/block-main-0-653-600.txt
  zebra-test/src/vectors/block-main-0-653-601.txt
  zebra-test/src/vectors/block-main-0-902-999.txt
  zebra-test/src/vectors/block-main-0-903-000.txt
  zebra-test/src/vectors/block-main-0-903-001.txt
  zebra-test/src/vectors/block-test-0-000-000.txt
  zebra-test/src/vectors/block-test-0-000-001.txt
  zebra-test/src/vectors/block-test-0-000-002.txt
  zebra-test/src/vectors/block-test-0-000-003.txt
  zebra-test/src/vectors/block-test-0-000-004.txt
  zebra-test/src/vectors/block-test-0-000-005.txt
  zebra-test/src/vectors/block-test-0-000-006.txt
  zebra-test/src/vectors/block-test-0-000-007.txt
  zebra-test/src/vectors/block-test-0-000-008.txt
  zebra-test/src/vectors/block-test-0-000-009.txt
  zebra-test/src/vectors/block-test-0-000-010.txt
  zebra-test/src/vectors/block-test-0-207-499.txt
  zebra-test/src/vectors/block-test-0-207-500.txt
  zebra-test/src/vectors/block-test-0-207-501.txt
  zebra-test/src/vectors/block-test-0-279-999.txt
  zebra-test/src/vectors/block-test-0-280-000.txt
  zebra-test/src/vectors/block-test-0-280-001.txt
  zebra-test/src/vectors/block-test-0-583-999.txt
  zebra-test/src/vectors/block-test-0-584-000.txt
  zebra-test/src/vectors/block-test-0-584-001.txt
  zebra-test/src/vectors/block-test-0-903-799.txt
  zebra-test/src/vectors/block-test-0-903-800.txt
  zebra-test/src/vectors/block-test-0-903-801.txt
  zebra-test/src/vectors/block-test-1-028-499.txt
  zebra-test/src/vectors/block-test-1-028-500.txt
  zebra-test/src/vectors/block-test-1-028-501.txt
  zebra-test/src/vectors/block-test-1-095-000.txt
  zebra-test/src/vectors/block.rs
Labels: A-rust, C-cleanup, C-enhancement, E-med

#1106 Use ok_or instead of ok_or_else with unnecessary closure
  zebra-consensus/src/block.rs
Labels: A-rust, C-cleanup

#1090 Tweak State RFC to handle edge cases
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-cleanup, E-easy

#1110 Block test vector comment updates
  zebra-test/src/vectors/block.rs
Labels: C-cleanup

#1111 Send the final checkpoint block to the checkpoint verifier
  zebra-consensus/src/chain.rs
Labels: A-rust, C-bug, C-cleanup
