Repository ZcashFoundation/zebra, pull requests merged in 2020-11, with the labels that each got.

#1255 Fix options order in metrics docker commands
  book/src/user/metrics.md
Labels: A-docs, C-bug

#1260 Clarify CheckpointVerifier errors
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/error.rs
Labels: A-rust, C-cleanup

#1236 Reduce acceptance test sled memory usage
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug

#1227 Call `zebra_test::init` where needed.
  zebra-chain/src/amount.rs
  zebra-chain/src/block/height.rs
  zebra-chain/src/block/tests/prop.rs
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/parameters/tests.rs
  zebra-chain/src/sapling/address.rs
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/keys/tests.rs
  zebra-chain/src/sapling/note/ciphertexts.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/serialization/proptests.rs
  zebra-chain/src/serialization/sha256d.rs
  zebra-chain/src/sprout/address.rs
  zebra-chain/src/sprout/keys.rs
  zebra-chain/src/sprout/note/ciphertexts.rs
  zebra-chain/src/sprout/tree.rs
  zebra-chain/src/transaction/hash.rs
  zebra-chain/src/transaction/memo.rs
  zebra-chain/src/transaction/tests/prop.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-chain/src/transparent/address.rs
  zebra-chain/src/transparent/script.rs
  zebra-chain/src/work/tests/prop.rs
  zebra-consensus/src/block/subsidy/founders_reward.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/parameters/tests.rs
  zebra-network/src/constants.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/types.rs
  zebra-state/src/tests.rs
  zebra-test/src/vectors/block.rs
  zebrad/src/components/sync.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-cleanup

#1263 Add metrics for the non-finalized state and queue
  zebra-state/src/service/memory_state/non_finalized_state.rs
  zebra-state/src/service/memory_state/queued_blocks.rs
Labels: A-rust, C-enhancement, S-blocked

#1283 Pin the version of tarpaulin used for collecting coverage to 0.16.0
  .github/workflows/coverage.yml
Labels: A-dependencies, A-github-actions, A-infrastructure

#1282 Run acceptance tests post-merge with large cached state
  .github/workflows/cd.yml
  Dockerfile
  cloudbuild.yaml
Labels: A-github-actions, A-infrastructure

#1261 Make the checkpoint metrics more accurate
  zebra-consensus/src/checkpoint.rs
Labels: A-rust, C-bug, C-cleanup

#1262 Add a maximum queued height metric to the finalized state
  zebra-state/src/sled_state.rs
Labels: A-rust, C-enhancement

#1289 Replace Target<block::Height> with TargetHeight
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/checkpoint/tests.rs
  zebra-consensus/src/checkpoint/types.rs
Labels: A-rust, C-cleanup

#1292 Add missing anchors to the RFC template
  book/src/dev/rfcs/0000-template.md
Labels: A-docs, C-cleanup

#1300 Linewrap
  .github/workflows/manual-deploy.yml
Labels: A-github-actions, A-infrastructure

#1301 Naming
  .github/workflows/manual-deploy.yml
Labels: A-github-actions, A-infrastructure

#1271 Add internal iterator API for accessing relevant chain blocks
  zebra-state/src/service.rs
  zebra-state/src/service/memory_state/non_finalized_state.rs
Labels: A-rust, C-enhancement

#1313 Move all contextual validation code into its own function
  zebra-state/src/service.rs
  zebra-state/src/service/check.rs
Labels: A-rust, C-cleanup

#1314 Add mdbook stuff to path using environment files/variables
  .github/workflows/docs.yml
Labels: A-docs, A-github-actions, A-infrastructure

#1315 Move chain order assertions to commit_finalized_direct
  zebra-state/src/service/check.rs
  zebra-state/src/sled_state.rs
Labels: A-consensus, A-rust, C-cleanup

#1335 Correctly grep for instance group & region
  .github/workflows/cd.yml
Labels: A-github-actions, A-infrastructure, C-bug, C-cleanup

#1338 Stop using /dev/shm on Linux
  zebra-state/Cargo.toml
  zebra-state/src/config.rs
Labels: A-rust, C-bug, C-cleanup

#1337 Update the max_concurrent_block_requests docs
  zebrad/src/config.rs
Labels: A-docs, C-bug, C-cleanup

#1353 Enable RUST_BACKTRACE=full for test and build/deploy images
  docker/Dockerfile.build
  docker/Dockerfile.test
Labels: A-infrastructure, C-enhancement

#1352 Delete outdated transaction comments
  zebra-consensus/src/transaction.rs
Labels: A-docs, A-rust, C-cleanup

#1361 Basic documentation for zebra-checkpoints
  book/src/dev/zebra-checkpoints.md
Labels: A-docs, C-enhancement

#1363 Temporarily avoid a panic when downcasting to redjubjub::Error fails
  zebra-consensus/src/error.rs
Labels: A-rust, C-bug

#1365 Fix individual crate compilation failures
  tower-batch/Cargo.toml
  zebra-network/Cargo.toml
Labels: A-dependencies, C-bug

#1371 Remove a post-Canopy panic in funding stream block subsidy validation
  zebra-consensus/src/block/check.rs
Labels: A-rust, C-bug

#1373 Downgrade a per-block log to debug level
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-rust, C-bug

#1382 Remove timeout on test job
  .github/workflows/test.yml
Labels: A-github-actions, A-infrastructure, C-cleanup

#1383 Fix typo
  book/src/dev/rfcs/0005-state-updates.md
  zebra-consensus/src/primitives/redjubjub.rs
  zebra-state/src/service/pending_utxos.rs
Labels: A-docs, C-cleanup

#1339 Make debug_stop_at_height and ephemeral work together
  zebra-state/src/service/finalized_state.rs
Labels: A-rust, C-bug, C-cleanup

#1384 Avoid verbose default logs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-rust

#1394 s/TRASPARENT/TRANSPARENT/g
  zebra-state/src/constants.rs
Labels: C-cleanup

#1246 RFC: Contextual Difficulty
  book/src/dev/rfcs/0005-state-updates.md
  book/src/dev/rfcs/0006-contextual-difficulty.md
Labels: A-consensus, A-docs, C-design

#1396 Add an info-level log when UTXO requests are pruned
  zebra-state/src/service.rs
  zebra-state/src/service/pending_utxos.rs
Labels: A-rust, C-enhancement

#1404 Fix a state config comment
  zebra-state/src/config.rs
Labels: A-docs

#1347 Inbound `FindBlocks` and `FindHeaders`
  zebra-chain/src/block.rs
  zebra-chain/src/fmt.rs
  zebra-chain/src/lib.rs
  zebra-network/src/protocol/external/message.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebrad/src/components/inbound.rs
Labels: A-rust, C-enhancement
