Repository ZcashFoundation/zebra, pull requests merged in 2020-07, with the labels that each got.

#574 fix: Adjust bounds on the LockTime Arbitrary impl
  zebra-chain/src/types.rs
Labels: E-easy, Poll::Ready, bug, rust

#585 Add ZIP143 and ZIP243 test vectors
  zebra-chain/src/transaction/tests.rs
  zebra-chain/src/transaction/tests/test_vectors.rs
  zebra-test/src/vectors.rs
Labels: Poll::Ready, rust

#583 Add formal design for syncer
  design/0000-template.md
  design/designs/0001-pipelinable-block-lookup.md
  design/overview.md
Labels: design

#524 Verify blocks between checkpoints
  Cargo.lock
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/lib.rs
  zebra-consensus/src/verify/block.rs
Labels: E-hard, Poll::Ready, consensus, design, rust

#460 Redjubjub signature verifier service
  .github/workflows/coverage.yml
  Cargo.lock
  zebra-consensus/Cargo.toml
  zebra-consensus/src/verify.rs
  zebra-consensus/src/verify/redjubjub.rs
Labels: rust

#629 Consensus refactor
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/checkpoint/list.rs
  zebra-consensus/src/checkpoint/tests.rs
  zebra-consensus/src/checkpoint/types.rs
  zebra-consensus/src/lib.rs
  zebra-consensus/src/redjubjub.rs
  zebra-consensus/src/redjubjub/tests.rs
  zebra-consensus/src/script.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/verify.rs
  zebra-consensus/src/verify/block.rs
  zebrad/src/commands/start.rs
Labels: E-easy, Poll::Ready, rust

#633 fix: Make sure checkpoint heights and hashes are unique
  zebra-consensus/src/checkpoint/list.rs
Labels: E-easy, Poll::Ready, bug, consensus, rust

#650 Put zebrad/Cargo.toml in a nicer order
  zebrad/Cargo.toml
Labels: E-easy, Poll::Ready, dependencies

#657 fix: Use matches!() based on a new nightly clippy lint
  zebra-chain/src/transaction.rs
Labels: E-easy, Poll::Ready, bug, rust

#648 Let zebrad revhex read from stdin
  zebrad/src/application.rs
  zebrad/src/commands.rs
  zebrad/src/commands/revhex.rs
Labels: E-easy, Poll::Ready, bug, docs, rust

#659 fix: Stop revhex on EOF
  zebrad/src/commands/revhex.rs
Labels: E-easy, Poll::Ready, bug, rust

#661 fix: Use the default Zcash port in version messages
  zebra-network/src/peer/handshake.rs
Labels: E-easy, Poll::Ready, bug, rust

#635 fix: Resist CheckpointVerifier memory DoS attacks
  zebra-consensus/src/checkpoint.rs
  zebrad/src/commands/start/sync.rs
Labels: E-easy, Poll::Ready, bug, design, rust

#639 Check for bad heights or hashes in checkpoint lists
  zebra-chain/src/block/tests.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/types.rs
  zebra-consensus/src/checkpoint/list.rs
Labels: E-easy, Poll::Ready, docs, rust

#670 fix: Only launch network endpoints for server commands
  zebrad/src/application.rs
  zebrad/src/commands.rs
Labels: E-easy, Poll::Ready, bug, rust

#679 fix: Only enable tokio components for servers
  zebrad/src/application.rs
Labels: E-easy, Poll::Ready, rust

#674 Hard-Coded Checkpoint Lists
  zebra-chain/src/types.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/checkpoint/list.rs
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
  zebra-consensus/src/checkpoint/tests.rs
  zebra-utils/calculate-checkpoints.sh
  zebra-utils/get-height-size-hash.sh
Labels: E-med, Poll::Ready, consensus, design

#700 fix: Put the peer set config vars together
  zebra-network/src/config.rs
Labels: E-easy, Poll::Pending, rust

#701 fix: Rewrite the config usage comment
  zebrad/src/commands/generate.rs
Labels: E-easy, Poll::Ready, docs, rust

#703 fix: Reduce sync error logs to info or warn
  zebrad/src/commands/start/sync.rs
Labels: E-easy, Poll::Ready, bug

#702 feature: Use the Heartwood protocol version in zebra-network
  Cargo.lock
  zebra-consensus/src/parameters.rs
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/protocol/external/types.rs
Labels: E-easy, Poll::Ready, bug, consensus, rust

#709 network: ensure dropping a Client closes the connection.
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/handshake.rs
Labels: bug

#731 Download genesis
  zebra-consensus/src/checkpoint.rs
  zebrad/src/commands/start/sync.rs
Labels: E-easy, Poll::Ready, bug

#736 Make the CheckpointVerifier handle partial restarts
  zebra-consensus/src/block.rs
  zebra-consensus/src/chain.rs
  zebra-consensus/src/chain/tests.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/checkpoint/tests.rs
  zebra-consensus/src/checkpoint/types.rs
  zebra-state/Cargo.toml
  zebra-state/src/lib.rs
  zebrad/src/commands/start.rs
Labels: E-easy, Poll::Ready, bug, rust

#764 fix: Replace a return with unreachable!
  zebra-consensus/src/checkpoint.rs
Labels: E-easy, Poll::Ready, rust

#761 Hide expected logs in unit tests
  zebra-test/src/lib.rs
Labels: E-easy, Poll::Ready, bug, rust

#762 fix: Update Cargo.lock with zebra crate versions
  zebra-test/src/lib.rs
Labels: E-easy, dependencies

#766 fix: Update comments for Heartwood's hashChainHistoryRoot
  zebra-chain/src/block/header.rs
Labels: E-easy, Poll::Ready, consensus, docs, rust

#748 feature: Check the previous block height in BlockVerifier
  zebra-consensus/Cargo.toml
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/chain/tests.rs
  zebra-consensus/src/checkpoint/tests.rs
Labels: E-easy, Poll::Ready, bug, consensus, rust

#771 feature: Add the MinimumDifficulty consensus parameter
  zebra-consensus/src/parameters.rs
  zebra-consensus/src/parameters/minimum_difficulty.rs
  zebra-consensus/src/parameters/tests.rs
Labels: E-easy, Poll::Ready, consensus, rust

#781 fix: Tweak the RFC template
  book/src/designs/0000-template.md
Labels: E-easy, Poll::Ready, design, docs

#783 fix: allow(dead_code) on some protocol version functions
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/types.rs
Labels: E-easy, Poll::Ready, bug, rust

#774 feature: Update mainnet and testnet checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: E-easy, Poll::Ready

#773 feature: Separate Mainnet and Testnet state
  zebra-state/src/lib.rs
  zebra-state/src/on_disk.rs
  zebra-state/tests/basic.rs
  zebrad/src/commands/start.rs
Labels: E-easy, Poll::Ready, rust

#786 Fix some verifier warnings
  zebra-consensus/src/chain.rs
  zebra-consensus/src/chain/tests.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/checkpoint/list.rs
  zebra-consensus/src/checkpoint/tests.rs
  zebra-state/src/lib.rs
Labels: E-med, Poll::Ready, bug, design, rust

#789 Move the checkpoint list tests to their own file
  zebra-consensus/src/checkpoint/list.rs
  zebra-consensus/src/checkpoint/list/tests.rs
Labels: E-easy, rust

#797 fix: Use types to avoid ChainVerifier inconsistencies
  zebra-consensus/src/block.rs
  zebra-consensus/src/chain.rs
  zebra-consensus/src/chain/tests.rs
Labels: A-rust, E-easy, Poll::Ready
