Repository ZcashFoundation/zebra, pull requests merged in 2021-06, with the labels that each got.

#2228 Split out parsing & validation of test VerificationKey from checking of the signature
  zebra-chain/proptest-regressions/primitives/redpallas/tests/prop.txt
  zebra-chain/src/primitives/redpallas/tests/prop.rs
Labels: A-rust, C-cleanup

#2232 Make debugging easier on proptests with large vectors
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/fmt.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transparent/prop.rs
  zebra-state/src/service/non_finalized_state/arbitrary.rs
Labels: A-rust, C-enhancement, P-Low

#2237 Adjust the benchmark sample size so all benchmarks finish successfully
  zebra-chain/benches/block.rs
Labels: A-rust, C-bug, P-Low

#2238 Standardise clippy lints and require docs
  book/src/dev/rfcs/drafts/data-flow-2020-07-22.md
  tower-batch/src/lib.rs
  tower-batch/tests/ed25519.rs
  tower-batch/tests/worker.rs
  tower-fallback/src/lib.rs
  tower-fallback/tests/fallback.rs
  zebra-chain/benches/block.rs
  zebra-chain/src/block.rs
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/block/header.rs
  zebra-chain/src/block/tests.rs
  zebra-chain/src/lib.rs
  zebra-chain/src/orchard/keys/tests.rs
  zebra-chain/src/primitives/redpallas.rs
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/output.rs
  zebra-chain/src/serialization/arbitrary.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-chain/src/work/difficulty.rs
  zebra-client/src/lib.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/chain.rs
  zebra-consensus/src/chain/tests.rs
  zebra-consensus/src/lib.rs
  zebra-network/src/lib.rs
  zebra-rpc/src/lib.rs
  zebra-script/src/lib.rs
  zebra-state/src/lib.rs
  zebra-state/tests/basic.rs
  zebra-test/src/command.rs
  zebra-test/src/lib.rs
  zebra-test/src/prelude.rs
  zebra-test/src/transcript.rs
  zebra-test/src/vectors.rs
  zebra-test/src/vectors/block.rs
  zebra-test/tests/command.rs
  zebra-test/tests/transcript.rs
  zebra-utils/src/bin/zebra-checkpoints/main.rs
  zebra-utils/src/lib.rs
  zebrad/src/bin/zebrad/main.rs
  zebrad/src/lib.rs
  zebrad/src/sentry.rs
  zebrad/tests/acceptance.rs
Labels: A-docs, C-cleanup, C-enhancement, P-Low

#2242 Update the GitHub and RFC templates based on retrospectives
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/rfc.md
  .github/pull_request_template.md
  book/src/dev/rfcs/0000-template.md
Labels: A-docs, A-infrastructure, C-cleanup, C-enhancement, P-Medium

#2249 Add the database format to the panic metadata
  zebrad/src/application.rs
Labels: A-rust, C-enhancement, P-Low

#2248 Update docs for coinbase maturity for Canopy
  zebra-state/src/constants.rs
Labels: A-consensus, A-docs, C-enhancement, NU-4-Canopy, P-Low

#2243 Add final sapling root test vectors
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/sapling/tree.rs
  zebra-test/src/vectors/block.rs
Labels: A-rust, C-enhancement, NU-1-Sapling, NU-3-Heartwood, NU-5, P-Medium

#2253 Update test job to use the updated state
  .github/workflows/test.yml
Labels: A-github-actions, A-infrastructure

#2247 Create workflow to regenerate cached state disks for tests
  .github/workflows/regenerate-stateful-test-disks.yml
Labels: A-github-actions, A-infrastructure, C-enhancement

#2250 Allow multi-digit Zebra alpha versions in the `zebrad` acceptance tests
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug, I-integration-fail, P-Medium

#2257 Clippy: remove needless borrows
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/sapling/commitment/pedersen_hashes.rs
  zebra-chain/src/serialization/zcash_serialize.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-network/src/peer/handshake.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/non_finalized_state/queued_blocks.rs
Labels: A-rust, C-cleanup, P-Low

#2260 RFC: add more background to atomics
  book/src/dev/rfcs/0011-async-rust-in-zebra.md
Labels: A-docs, C-enhancement, P-Low

#2264 Remove outdated pinned nightly in coverage workflow
  .github/workflows/coverage.yml
Labels: A-github-actions, C-bug, P-Medium

#2269 RFC: Add portability risk for atomics
  book/src/dev/rfcs/0011-async-rust-in-zebra.md
Labels: A-docs, C-enhancement, P-Low

#2290 Upgrade mdbook to 0.4.10
  .github/workflows/docs.yml
Labels: A-dependencies, A-docs, A-github-actions, A-infrastructure

#2278 Security: only apply the outbound connection rate-limit to actual connections
  zebra-network/proptest-regressions/peer_set/candidate_set/tests/prop.txt
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/candidate_set/tests/prop.rs
Labels: A-network, A-rust, C-bug, I-hang, I-slow, I-usability

#2285 Reject V5 transactions before NU5 activation
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-consensus/src/error.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
Labels: A-consensus, A-rust, NU-5

#2294 CI: Clarify duplicate Clippy job name
  .github/workflows/ci.yml
Labels: A-github-actions, C-cleanup, P-Low

#2286 Replace bespoke source-based coverage config with cargo-llvm-cov
  .github/workflows/coverage.yml
Labels: A-github-actions, A-infrastructure, A-rust, P-Optional

#2291 Use Swatinem/rust-cache@v1
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
Labels: A-github-actions, A-infrastructure

#2267 Stop panicking on invalid orchard nullifiers
  zebra-chain/src/orchard/action.rs
  zebra-chain/src/orchard/arbitrary.rs
  zebra-chain/src/orchard/note/nullifiers.rs
  zebra-chain/src/transaction/tests/vectors.rs
Labels: A-rust, C-bug, C-cleanup, NU-5, P-Medium

#2273 Security: stop gossiping failure and attempt times as last_seen times
  zebra-network/src/address_book.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/meta_addr/tests/check.rs
  zebra-network/src/meta_addr/tests/preallocate.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/meta_addr/tests/vectors.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/candidate_set/tests/prop.rs
  zebra-network/src/timestamp_collector.rs
Labels: A-network, A-rust, C-bug, C-security, I-bad-data, I-slow, P-High

#2304 Add missing `std::sync::Mutex` qualifiers in the unit tests
  zebra-network/src/peer_set/candidate_set/tests/prop.rs
  zebra-network/src/peer_set/candidate_set/tests/vectors.rs
Labels: A-rust, C-cleanup, P-Low

#2316 Remove unused dep 'pairing' in zebra-consensus
  Cargo.lock
  zebra-consensus/Cargo.toml
Labels: A-dependencies, A-rust, C-cleanup, P-Low

#2332 Update librustzcash, change zcash_history to work with it
  Cargo.lock
  zebra-chain/src/primitives/zcash_history.rs
Labels: A-dependencies, A-rust, NU-5

#2345 Release Blocker: Depend on a specific git commit for zcash_history
  Cargo.lock
  zebra-chain/Cargo.toml
Labels: A-dependencies, C-bug, P-Medium

#2275 Security: Limit reconnection rate to individual peers
  zebra-chain/src/serialization/date_time.rs
  zebra-network/src/address_book.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/peer_set.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/protocol/external/arbitrary.rs
  zebra-network/src/protocol/external/types.rs
Labels: A-network, A-rust, C-security, I-remote-node-overload, P-Medium

#2347 Add property test strategies for V5 transactions
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/tests/prop.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/tests/prop.rs
  zebra-chain/src/transparent/prop.rs
  zebra-state/src/service/non_finalized_state/arbitrary.rs
Labels: A-rust, C-enhancement, NU-5, P-Medium

#2337 Document required request timeouts due to data dependencies
  zebra-consensus/src/chain.rs
  zebra-consensus/src/transaction.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
Labels: A-docs, C-bug, P-Low

#2341 Client RFC: add BlazeSync and cap-std
  book/src/dev/rfcs/0009-zebra-client.md
Labels: A-docs, C-enhancement, P-Medium

#2356 Upgrade to pin_project 1.0.7 to resolve nightly warnings
  Cargo.lock
  tower-batch/Cargo.toml
  zebra-network/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, A-rust, C-cleanup, P-Medium

#2358 Refactor CandidateSet to use DateTime32 and Duration32
  zebra-network/src/peer_set/candidate_set.rs
Labels: A-network, A-rust, C-cleanup, P-Low

#2363 Document shared to per-spend anchor conversion
  zebra-chain/src/transaction.rs
Labels: A-docs, C-bug, P-Medium

#2349 Add path() method to FinalizedState
  zebra-state/src/service/finalized_state.rs
Labels: A-rust

#2276 Security: Use canonical SocketAddrs to avoid duplicate peer connections, Feature: Send local listener to peers
  zebra-chain/src/serialization.rs
  zebra-chain/src/serialization/arbitrary.rs
  zebra-chain/src/serialization/date_time.rs
  zebra-chain/src/serialization/read_zcash.rs
  zebra-network/src/address_book.rs
  zebra-network/src/config.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/meta_addr/tests/check.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
  zebrad/src/components/inbound.rs
Labels: A-network, A-rust, C-bug, C-security, I-bad-data, I-privacy, I-remote-node-overload, P-Medium

#2277 Gossip dynamic local listener ports to peers
  Cargo.lock
  zebra-network/src/address_book.rs
  zebra-network/src/config.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/peer_set/candidate_set/tests/prop.rs
  zebra-network/src/peer_set/candidate_set/tests/vectors.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/timestamp_collector.rs
  zebra-test/Cargo.toml
  zebra-test/src/lib.rs
  zebra-test/src/net.rs
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
Labels: A-network, A-rust, C-bug, I-usability, P-Low

#2367 Add a note about maybe using the tui crate for zebra-cli
  book/src/dev/rfcs/0009-zebra-client.md
Labels: A-docs, C-design

#2302 Validate transparent inputs and outputs in V5 transactions
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
Labels: A-consensus, A-rust, NU-5

#2351 Update multiple crates to ensure bitvec 0.22.3 is being used
  Cargo.lock
  Cargo.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/lib.rs
  zebra-chain/src/orchard/commitment.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling.rs
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/commitment/pedersen_hashes.rs
  zebra-chain/src/sapling/tree.rs
  zebra-consensus/Cargo.toml
Labels: A-consensus, A-dependencies, A-rust, NU-5

#2376 Remove unicode in Zebra's user agent
  zebra-network/src/constants.rs
Labels: A-network, A-rust, C-bug, I-bad-data, I-usability, P-Medium

#2373 README: update known issues and add inbound network ports
  README.md
  zebra-network/src/config.rs
Labels: A-docs, A-network, P-Medium

#2383 Enable V5 transaction test vectors in the groth16 tests
  zebra-consensus/src/primitives/groth16/tests.rs
Labels: A-rust, C-enhancement, NU-5, P-Medium

#2385 Remove "solution" from the ticket template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: A-infrastructure, C-enhancement

#2382 ZIP-213: Explain how Zebra validates shielded coinbase outputs like other shielded outputs
  zebra-consensus/src/transaction.rs
Labels: A-consensus, A-docs, A-rust, C-enhancement, NU-1-Sapling, NU-5, P-Medium

#2384 Orchard note commitment tree test vectors
  zebra-chain/src/orchard/arbitrary.rs
  zebra-chain/src/orchard/commitment.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/note/nullifiers.rs
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/orchard/tests.rs
  zebra-chain/src/orchard/tests/test_vectors.rs
  zebra-chain/src/orchard/tree.rs
Labels: A-dependencies, A-docs, A-rust, NU-5, P-Medium

#2406 Improve docs and panic messages for zebra_test::command
  zebra-test/src/command.rs
Labels: A-docs, A-rust, C-bug, P-Medium

#2400 Add a verification height to mempool transaction verification requests
  zebra-consensus/src/transaction.rs
Labels: A-rust, C-bug, P-Medium

#2395 Support a minimum protocol version during initial block download
  zebra-network/src/constants.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/types.rs
Labels: A-consensus, A-network, A-rust, C-enhancement, NU-0-Overwinter, NU-5, P-Medium

#2404 Release Blocker: Stop trying to verify coinbase inputs using the script verifier
  zebra-chain/src/transparent.rs
  zebra-consensus/src/script.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
Labels: A-consensus, C-bug, P-High

#2405 Release Blocker? Disable IPv6 tests when $ZEBRA_SKIP_IPV6_TESTS is set
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-test/src/net.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug, I-integration-fail, P-High

#2412 Fix intermittent errors in the groth16 verifier tests
  zebra-consensus/src/primitives/groth16/tests.rs
Labels: A-rust, C-bug, I-integration-fail, P-Medium

#2402 Release Blocker: Stop skipping the cached sync tests in CI
  .github/workflows/regenerate-stateful-test-disks.yml
  .github/workflows/test.yml
Labels: A-github-actions, C-bug, P-High

#2403 Release Blocker: Stop ignoring failed tests in the cached state CI workflow
  .github/workflows/regenerate-stateful-test-disks.yml
  .github/workflows/test.yml
Labels: A-github-actions, A-infrastructure, C-bug, P-High
