Repository ZcashFoundation/zebra, pull requests merged in 2021-03, with the labels that each got.

#1825 Move design/data-flow to rfcs/drafts
  book/src/dev/rfcs/drafts/data-flow-2020-07-22.md
Labels: A-docs, C-cleanup, NU-5-TBC, P-Low

#1811 Upgrade ed25519-zebra to version 2
  Cargo.lock
  zebra-chain/Cargo.toml
Labels: A-consensus, A-rust, NU-4-Canopy

#1823 Add initial support for NU5 to zebra
  zebra-chain/src/block/root_hash.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-network/src/protocol/external/types.rs
Labels: A-consensus, A-rust, C-enhancement, NU-5-TBC, P-Medium

#1840 Replace canopy.pdf instances left in our codebase
  book/src/dev/rfcs/0009-zebra-client.md
  zebra-consensus/src/transaction/check.rs
Labels: A-docs, C-cleanup

#1824 Add transaction version 5
  zebra-chain/src/parameters.rs
  zebra-chain/src/parameters/transaction.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/check.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/tests.rs
Labels: NU-5-TBC, S-blocked

#1844 Add manual deploy workflow for zcashd images
  .github/workflows/zcashd-cd.yml
Labels: A-github-actions, A-infrastructure

#1858 Update and rename zcashd-cd.yml to zcashd-manual-deploy.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-github-actions, A-infrastructure

#1855 Implement outbound connection rate limiting - config rename with alias
  zebra-network/src/config.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
Labels: A-rust, C-security, I-remote-node-overload, I-slow, I-unbounded-growth, NU-5-TBC, P-High

#1852 CandidateSet: Document Listener Port Connections
  zebra-network/src/peer_set/candidate_set.rs
Labels: A-docs, C-bug, P-Medium, S-needs-triage

#1877 Revert "Disable unreliable `sync_large_checkpoints_testnet`"
  zebrad/tests/acceptance.rs
Labels: A-rust, C-enhancement, P-Medium

#1878 Adjust the crawl interval and acceptance test timeout
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug, I-integration-fail, P-Medium

#1887 Revert "Revert "Disable unreliable `sync_large_checkpoints_testnet`""
  zebrad/tests/acceptance.rs
Labels: C-bug, I-integration-fail, P-High

#1891 Document that the listed address is also advertised to peers
  zebra-network/src/config.rs
Labels: A-docs, C-bug, C-security, I-privacy, I-usability, P-Medium

#1888 Document and log trailing message bytes
  zebra-network/src/protocol/external/codec.rs
Labels: A-consensus, A-rust, C-bug, C-security, P-Medium

#1902 Replace smart quotes with ascii quotes
  tower-batch/src/lib.rs
  zebra-chain/src/block/header.rs
  zebra-chain/src/sapling/commitment/pedersen_hashes.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/note.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/sprout/keys.rs
  zebra-chain/src/sprout/note.rs
  zebra-chain/src/sprout/note/mac.rs
  zebra-chain/src/sprout/tree.rs
  zebra-chain/src/transparent/address.rs
  zebra-consensus/src/block/subsidy.rs
  zebra-consensus/src/block/subsidy/founders_reward.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/parameters/subsidy.rs
Labels: A-docs, C-bug, C-cleanup, P-Low

#1923 Disable incremental compilation in coverage builds
  .github/workflows/coverage.yml
Labels: A-github-actions, A-infrastructure, C-bug, I-integration-fail, P-Critical

#1926 Canopy activation state
  .github/workflows/test.yml
Labels: A-github-actions, A-infrastructure, A-rust

#1927 Add final job to ci.yml that passes when all other ci.yml jobs pass
  .github/workflows/ci.yml
Labels: A-github-actions, A-infrastructure, C-enhancement

#1929 clippy: fix inconsistent struct ordering
  tower-batch/tests/ed25519.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/redjubjub.rs
  zebra-state/src/request.rs
Labels: A-rust, C-cleanup, P-Low

#1932 Bump versions for v1.0.0-alpha.5
  Cargo.lock
  README.md
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/tracing/component.rs
Labels: A-rust

#1935 Document that the mandatory checkpoint can change
  zebra-consensus/src/config.rs
Labels: A-docs, C-bug, P-Medium

#1934 Mention git diff --stat in release PR template
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-docs, A-infrastructure

#1713 Use batch optimizations, load params in groth16::Verifier, verify Spend & Output descriptions
  Cargo.lock
  tower-batch/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/primitives/proofs/groth16.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/note/nullifiers.rs
  zebra-chain/src/sapling/output.rs
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/sapling/tree.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/error.rs
  zebra-consensus/src/lib.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/groth16/hash_reader.rs
  zebra-consensus/src/primitives/groth16/params.rs
  zebra-consensus/src/primitives/groth16/tests.rs
  zebra-consensus/src/primitives/redjubjub/tests.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/check.rs
  zebra-network/Cargo.toml
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
Labels: A-consensus, A-rust, NU-1-Sapling, NU-2-Blossom, NU-3-Heartwood, NU-4-Canopy, NU-5-TBC

#1886 V5 transaction rfc
  book/src/dev/rfcs/0010-v5-transaction.md
Labels: C-design

#1097 CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: A-docs

#1945 Rename NU5 to Nu5 to satisfy newly stable clippy::upper-case-acronyms
  zebra-chain/src/block/root_hash.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-network/src/protocol/external/types.rs
Labels: A-rust

#1943 Add some comments and tracing for groth16::Verifier tests
  zebra-consensus/src/primitives/groth16/tests.rs
Labels: A-rust, C-cleanup

#1947 Increase coverage CI timeout
  .github/workflows/coverage.yml
Labels: A-github-actions, C-bug, I-integration-fail, P-High

#1953 Pin coverage.yml nightly to 2021-03-24 for now
  .github/workflows/coverage.yml
Labels: A-github-actions, A-infrastructure

#1949 Add a comment about a zcashd inv message bug
  zebra-network/src/peer/handshake.rs
Labels: A-docs, C-enhancement, P-Low

#1955 Clarify anchor names in V5 transaction RFC
  book/src/dev/rfcs/0010-v5-transaction.md
Labels: A-docs, C-enhancement, P-Medium

#1006 RFC: Transaction diffusion with isolated, minimally-distinguishable Tor connections (Stolon)
  book/src/dev/rfcs/drafts/xxxx-stolon.md
Labels: C-design

#1007 Draft RFC: Initial draft for basic network integration testing
  book/src/dev/rfcs/drafts/xxxx-basic-integration-testing.md
Labels: A-docs, C-design

#1063 RFC: Release process
  book/src/dev/rfcs/drafts/xxxx-release-planning.md
Labels: A-docs, C-design

#1129 Draft RFC: Block subsidy
  book/src/dev/rfcs/drafts/xxxx-block-subsidy.md
Labels: A-docs, C-design

#1964 Avoid pinging old staff for RFCs
  .github/PULL_REQUEST_TEMPLATE/rfc.md
Labels: A-docs, C-cleanup, P-Medium

#1957 Rename RootHash to Commitment based on ZIP-244
  zebra-chain/src/block.rs
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/block/header.rs
  zebra-chain/src/block/serialize.rs
  zebra-chain/src/block/tests/prop.rs
Labels: A-rust, C-enhancement, NU-5-TBC, P-Medium

#1946 Refactor Sapling data and use it in V4
  Cargo.lock
  zebra-chain/src/sapling.rs
  zebra-chain/src/sapling/arbitrary.rs
  zebra-chain/src/sapling/shielded_data.rs
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/sapling/tests.rs
  zebra-chain/src/sapling/tests/prop.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/groth16/tests.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/check.rs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-rust, NU-5-TBC
