Repository ZcashFoundation/zebra, pull requests merged in 2021-01, with the labels that each got.

#1518 Rewrite GetData handling to match the zcashd implementation
  zebra-network/src/peer/connection.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/internal/request.rs
  zebrad/src/components/inbound.rs
Labels: A-rust, C-bug

#1569 Make `cargo run` use `zebrad` by default
  zebrad/Cargo.toml
Labels: C-bug

#1163 Zebra Client Design
  book/src/dev/rfcs/0009-zebra-client.md
Labels: A-docs, C-design

#1568 Log configured network in every log message
  zebrad/src/application.rs
  zebrad/src/commands.rs
Labels: A-rust, C-enhancement

#1560 zebrad acceptance test cleanup
  zebrad/tests/acceptance.rs
Labels: A-rust, C-cleanup

#1589 Panic if the lookahead limit is misconfigured
  zebrad/src/components/sync.rs
Labels: A-rust, C-bug

#1588 Stop failing acceptance tests if their directories already exist
  zebrad/tests/acceptance.rs
Labels: A-infrastructure, A-rust, C-bug, C-cleanup

#1601 Update some comments in zebra-network
  zebra-network/src/peer/handshake.rs
Labels: A-rust, C-cleanup

#1600 Avoid panics when there are multiple failures on the same connection
  zebra-network/src/peer/connection.rs
Labels: A-rust, C-bug, C-cleanup

#1612 Add responsible-disclosure.md
  responsible_disclosure.md
Labels: A-docs

#1629 Explain why we stay connected on Inbound errors
  zebra-network/src/peer/connection.rs
Labels: A-docs, C-cleanup

#1635 Move BoxError to zebrad's lib.rs
  zebrad/src/components/sync.rs
  zebrad/src/lib.rs
Labels: A-rust, C-cleanup

#1642 Change a metrics sentinel to f64::NAN
  zebra-state/src/service/finalized_state.rs
Labels: A-rust, C-bug, C-cleanup

#1653 Document the Inbound service in the start module
  zebrad/src/commands/start.rs
Labels: A-docs, C-cleanup, P-Low

#1535 Add hints to port conflict and lock file panics
  Cargo.lock
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-network/src/lib.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-state/Cargo.toml
  zebra-state/src/constants.rs
  zebra-state/src/lib.rs
  zebra-state/src/service/finalized_state.rs
  zebra-test/src/command.rs
  zebrad/src/application.rs
  zebrad/src/components/metrics.rs
  zebrad/src/components/tracing/endpoint.rs
  zebrad/tests/acceptance.rs
Labels: A-dependencies, A-rust, C-bug, C-cleanup, C-enhancement, P-Low

#1658 Temporally disable sync_large_checkpoints on Windows
  .github/workflows/ci.yml
Labels: A-infrastructure

#1648 Enable Release Drafter workflow
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: A-docs, A-infrastructure

#1660 Specify v5, not 'latest'
  .github/workflows/release-drafter.yml
Labels: A-infrastructure

#1650 Add security disclosure principles
  responsible_disclosure.md
Labels: A-docs, P-Medium
