Repository ZcashFoundation/zebra, pull requests merged in 2021-02, with the labels that each got.

#1663 Mention security disclosure policy in README
  README.md
Labels: A-docs, C-enhancement, P-Low

#1637 Fix shutdown panics
  zebra-chain/src/lib.rs
  zebra-chain/src/shutdown.rs
  zebra-consensus/src/checkpoint.rs
  zebra-network/src/peer/client.rs
  zebrad/src/components/tokio.rs
Labels: P-Low

#1682 Document the impact of the redjubjub channel bound
  zebra-consensus/src/primitives/redjubjub.rs
Labels: A-docs

#1680 Remove an outdated comment in the script verifier
  zebra-consensus/src/script.rs
Labels: A-docs, C-cleanup

#1693 Document that connect_isolated only works on mainnet
  zebra-network/src/isolated.rs
Labels: A-docs

#830 Asynchronous Groth16 verification
  Cargo.lock
  tower-batch/src/service.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/primitives.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/redjubjub.rs
  zebra-consensus/src/transaction.rs
Labels: A-rust, C-enhancement

#1684 Add a comment about a mempool request bug
  zebra-consensus/src/transaction.rs
Labels: A-docs

#1706 Actually use `VerifyCheckpointError::CommitFinalized`
  zebra-consensus/src/checkpoint.rs
Labels: A-docs, A-rust, C-bug, C-cleanup, P-High

#1700 Fix poll_ready usage in ChainVerifier
  zebra-consensus/src/chain.rs
Labels: A-rust, C-bug, C-cleanup, P-High

#1705 Stop using CallAllUnordered in peer_set::add_initial_peers
  zebra-network/src/peer_set/initialize.rs
Labels: A-rust, C-bug, P-High

#1714 Log when the syncer awaits peer readiness
  zebrad/src/components/sync.rs
Labels: A-rust, C-cleanup

#1720 Add excessive detail to the release checklist
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-docs, A-infrastructure

#1715 Document a state_contains bug
  zebrad/src/components/inbound/downloads.rs
  zebrad/src/components/sync.rs
Labels: A-docs, A-rust

#1717 Add draft PR template for release checklist
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-infrastructure

#1722 Clarify the Response::Nil documentation
  zebra-network/src/protocol/internal/response.rs
Labels: A-docs, C-cleanup

#1725 Add beta rust to CI
  .github/workflows/ci.yml
Labels: A-github-actions, A-infrastructure

#1736 Increase the conflict acceptance test launch delay
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug, C-cleanup, P-High

#1734 Revert "Stop using CallAllUnordered in peer_set::add_initial_peers"
  zebra-network/src/peer_set/initialize.rs
Labels: A-rust, C-cleanup, P-Medium

#1733 Make the state usage clearer in script::Verifier
  zebra-consensus/src/script.rs
Labels: A-docs, A-rust, C-cleanup

#1737 Update the call_all comment in Inbound
  zebrad/src/components/inbound.rs
Labels: A-docs, C-cleanup

#1740 Update comments for the inbound service
  zebrad/src/components/inbound.rs
Labels: A-docs, A-rust, C-cleanup

#1726 Fix windows build for large sync tests
  .github/workflows/ci.yml
Labels: A-github-actions, A-infrastructure

#1748 Run CI workflow on push to #main & manual request
  .github/workflows/ci.yml
Labels: A-github-actions, A-infrastructure

#1757 CI: bump build and test timeouts to 60 minutes
  .github/workflows/ci.yml
Labels: A-github-actions, A-infrastructure

#1752 Revert "Change network tests comment in CI"
  .github/workflows/ci.yml
Labels: A-docs, A-github-actions, C-bug, P-High

#1751 Show env vars in CI
  .github/workflows/ci.yml
Labels: A-github-actions, C-bug, C-cleanup, C-enhancement, P-Medium

#1760 Client design: add "one database per key" alternative
  book/src/dev/rfcs/0009-zebra-client.md
Labels: A-docs, C-design, P-Low

#1764 Wake waiting tower-batch clones on close
  tower-batch/src/semaphore.rs
Labels: A-rust, C-bug, C-enhancement, I-hang, P-Medium

#1763 Log initial peer connection failures
  zebra-network/src/peer_set/initialize.rs
Labels: A-rust, C-bug, I-hang, P-Medium

#1749 Make sync logging a bit less verbose
  zebrad/src/components/sync.rs
Labels: A-rust, C-cleanup

#1727 Update PeerSet metrics after every change
  zebra-network/src/peer_set/set.rs
Labels: A-rust, C-bug, P-Low

#1762 Retry DNS resolution on failure
  zebra-network/src/config.rs
Labels: A-rust, C-bug, I-hang, P-Medium

#1709 Fix candidate set address state handling
  zebra-network/src/address_book.rs
  zebra-network/src/lib.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/candidate_set.rs
Labels: A-docs, A-rust, C-bug, C-cleanup, C-design, I-hang, P-High

#1766 Diagnostics for listener conflict CI failures
  zebra-network/src/peer_set/initialize.rs
  zebrad/src/components/metrics.rs
  zebrad/src/components/tracing/endpoint.rs
Labels: A-rust, C-bug, C-enhancement, I-integration-fail, P-High

#1770 Kill running acceptance test nodes on error, and show their output
  zebra-test/src/command.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-enhancement, I-integration-fail, P-High

#1780 Fix the yaml indentation for the docs.yml workflow
  .github/workflows/docs.yml
Labels: A-docs, A-github-actions, A-infrastructure, C-cleanup

#1787 Disable failing docs workflow
  .github/workflows/docs.yml
Labels: A-docs, A-github-actions, A-infrastructure, C-bug, I-integration-fail, P-Critical

#1782 Set ZEBRA_SKIP_NETWORK_TESTS using Windows syntax
  .github/workflows/ci.yml
Labels: A-github-actions, C-bug, I-integration-fail, P-Critical

#1778 Re-enable the macOS conflict acceptance tests
  zebra-test/src/command.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug, P-High

#1779 Fix inverted was_killed logic
  zebra-test/src/command.rs
Labels: A-rust, C-bug, P-Medium

#1789 Disable unreliable `sync_large_checkpoints_testnet`
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug, I-integration-fail, P-High

#1773 Compute the expected body length to reduce heap allocations
  zebra-network/src/protocol/external/codec.rs
Labels: A-rust, C-cleanup, P-Low

#1761 Add the global span to spawned network init tasks
  zebra-network/src/peer_set/initialize.rs
Labels: A-rust, C-bug, P-Low

#1735 Partly revert "Fix poll_ready usage in ChainVerifier"
  zebra-consensus/src/chain.rs
Labels: A-rust, C-bug, C-cleanup, I-hang, I-slow, P-Medium

#1804 zebrad 1.0.0-alpha.3 Release
  Cargo.lock
  README.md
  tower-batch/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/tracing/component.rs
Labels: A-dependencies, A-docs, A-rust, P-Medium

#1810 Update release-checklist.md
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-docs

#1812 Avoid acceptance test port conflicts
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug, I-integration-fail, P-High

#1818 Stop sending blocks and transactions on error
  zebra-network/src/peer/connection.rs
Labels: A-rust, C-bug, I-panic, P-High

#1796 Fix a peer DNS resolution edge case
  zebra-network/src/config.rs
Labels: A-rust, C-bug, I-hang, I-slow, P-High

#1821 Fix a typo in Transaction
  zebra-chain/src/transaction.rs
Labels: A-docs, A-rust, C-bug, P-Low
