Repository ZcashFoundation/zebra, pull requests merged in 2021-12, with the labels that each got.

#3119 Upgrade to vergen 5.1.18, including API changes
  Cargo.lock
  zebrad/Cargo.toml
  zebrad/build.rs
Labels: A-dependencies, P-Low, A-diagnostics

#3124 Revert "Stop returning NotFound errors, use the response instead"
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/internal/request.rs
  zebra-network/src/protocol/internal/response.rs
Labels: C-bug, P-High, I-panic, I-integration-fail, A-network

#3122 Add transaction-verification.json Grafana dashboard
  grafana/transaction-verification.json
Labels: A-infrastructure, C-enhancement, A-diagnostics

#3131 Ignore NotFound errors in the syncer
  zebra-network/src/peer/error.rs
  zebrad/src/components/sync.rs
Labels: C-bug, P-Medium, I-slow, A-network

#3132 Release Zebra v1.0.0-beta.2
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  CHANGELOG.md
  Cargo.lock
  README.md
  tower-batch/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-docs, A-dependencies, P-Medium

#3106 Stop doing thousands of time checks each time we connect to a peer
  Cargo.lock
  deny.toml
  zebra-chain/src/serialization/date_time.rs
  zebra-network/Cargo.toml
  zebra-network/src/address_book.rs
  zebra-network/src/address_book/tests.rs
  zebra-network/src/address_book/tests/prop.rs
  zebra-network/src/address_book/tests/vectors.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/meta_addr/tests/vectors.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/peer_set/set.rs
  zebrad/src/components/inbound.rs
Labels: C-bug, A-dependencies, P-Medium, I-slow, I-integration-fail, A-network

#3162 Security: Limit address book size to limit memory usage
  zebra-network/src/address_book.rs
  zebra-network/src/address_book/tests/prop.rs
  zebra-network/src/address_book/tests/vectors.rs
  zebra-network/src/constants.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebrad/src/components/inbound.rs
Labels: P-Medium, C-security, I-unbounded-growth, A-network

#3169 Add `zebra_test::init_async` helper function
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/peer_set/candidate_set/tests/prop.rs
  zebra-network/src/peer_set/candidate_set/tests/vectors.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-test/src/lib.rs
  zebrad/src/components/mempool/crawler/tests.rs
  zebrad/src/components/mempool/tests/prop.rs
  zebrad/src/components/sync/status/tests.rs
  zebrad/src/components/sync/tests/timing.rs
Labels: P-Low

#3108 Disconnect from outdated peers on network upgrade
  zebra-network/src/constants.rs
  zebra-network/src/peer.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/connector.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer/load_tracked_client.rs
  zebra-network/src/peer/minimum_peer_version.rs
  zebra-network/src/peer/minimum_peer_version/tests.rs
  zebra-network/src/peer/minimum_peer_version/tests/prop.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/set/tests.rs
  zebra-network/src/peer_set/set/tests/prop.rs
  zebra-network/src/protocol/external/arbitrary.rs
  zebra-network/src/protocol/external/types.rs
Labels: P-Medium

#3123 Checking of Sprout anchors in non-finalized state
  zebra-chain/src/sapling/tests/test_vectors.rs
  zebra-chain/src/sprout/joinsplit.rs
  zebra-chain/src/transaction.rs
  zebra-state/src/service/check/anchors.rs
  zebra-state/src/service/check/tests/anchors.rs
  zebra-state/src/service/check/tests/nullifier.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-test/src/vectors/block-main-0-000-395.txt
  zebra-test/src/vectors/block.rs
Labels: P-Medium

#3177 Security: When there are no new peers, stop crawler using CPU and writing logs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/limit.rs
  zebrad/src/application.rs
  zebrad/src/commands/start.rs
Labels: P-Medium, C-security, I-heavy, I-unbounded-growth, A-network, A-diagnostics

#3189 Spawn initial handshakes in separated task
  zebra-network/src/peer_set/initialize.rs
Labels: P-Medium

#3139 Update the State RFC to match the current database format
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-enhancement, P-Low

#3128 Validate JoinSplit proofs
  zebra-chain/src/sapling/output.rs
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/sprout.rs
  zebra-chain/src/sprout/arbitrary.rs
  zebra-chain/src/sprout/commitment.rs
  zebra-chain/src/sprout/joinsplit.rs
  zebra-chain/src/sprout/note/mac.rs
  zebra-chain/src/sprout/note/nullifiers.rs
  zebra-chain/src/transaction.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/groth16/params.rs
  zebra-consensus/src/primitives/groth16/tests.rs
  zebra-consensus/src/primitives/groth16/vectors.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-state/src/service/check/tests/anchors.rs
Labels: P-Medium

#3192 Security: Stop ignoring panics in inbound handshakes
  zebra-network/src/peer_set/initialize.rs
Labels: P-Low, C-security, I-usability, I-bad-data, A-network, A-diagnostics

#3181 Describe `PeerSet`s behavior at a network upgrade's activation height
  zebra-network/src/peer_set/set.rs
Labels: P-Medium

#3180 Integrate JoinSplit verifier
  zebra-chain/src/transaction.rs
  zebra-consensus/src/error.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/groth16/tests.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/check.rs
  zebra-consensus/src/transaction/tests.rs
Labels: P-Medium

#3203 Add diagnostics for peer set hangs
  grafana/network_health.json
  grafana/network_messages.json
  zebra-network/src/peer.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/set/tests.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/internal/request.rs
  zebra-network/src/protocol/internal/response.rs
  zebrad/src/components/inbound/downloads.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/src/components/sync/downloads.rs
Labels: P-High, I-hang, I-slow, I-usability, A-network, A-diagnostics

#3206 Disable Sprout anchor check
  zebra-state/src/service/check/anchors.rs
Labels: C-bug, A-consensus, P-High, I-consensus 💥

#3200 Stop ignoring some connection errors that could make the peer set hang
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/client/tests.rs
  zebra-network/src/peer/client/tests/vectors.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests.rs
  zebra-network/src/peer/connection/tests/vectors.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/unready_service.rs
  zebra-network/src/peer_set/unready_service/tests.rs
  zebra-network/src/peer_set/unready_service/tests/vectors.rs
Labels: C-bug, P-High, I-hang, I-slow, I-integration-fail, A-network

#3237 Silence expected anchor errors in tests
  zebra-state/src/service/check/anchors.rs
  zebra-test/src/lib.rs
Labels: C-bug, P-Low, A-diagnostics, C-testing

#3167 Security: Drop blocks that are a long way ahead of the tip
  zebra-consensus/src/chain.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound.rs
  zebrad/src/components/inbound/downloads.rs
  zebrad/src/components/inbound/tests.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/downloads.rs
  zebrad/src/components/sync/tests/timing.rs
Labels: P-High, C-security, I-hang, I-slow, I-unbounded-growth, A-network

#3191 Fix task handling bugs, so peers are more likely to be available
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
  zebra-network/src/lib.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/policies.rs
  zebrad/src/components/mempool/crawler.rs
  zebrad/src/components/mempool/crawler/tests.rs
  zebrad/src/components/mempool/crawler/tests/prop.rs
  zebrad/src/components/mempool/crawler/tests/timing.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/tests/timing.rs
Labels: C-bug, P-High, I-slow, I-integration-fail, A-network

#3089 Add some proptests for lock time validation
  zebra-chain/src/transparent.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-consensus/src/transaction/tests/prop.rs
Labels: P-Low

#3244 Avoid deadlocks in the address book mutex
  zebra-network/src/address_book.rs
  zebra-network/src/address_book_updater.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/candidate_set/tests/prop.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/set/tests.rs
Labels: P-High, C-security, I-hang, I-slow, A-network

#3269 Example: Replace a now or later instance with the futures::poll! macro
  zebrad/src/components/sync.rs
Labels: C-cleanup, P-Optional, A-network

#3243 Update async correctness docs and the async in Zebra RFC
  book/src/dev/rfcs/0011-async-rust-in-zebra.md
  zebra-network/src/peer/error.rs
  zebra-network/src/peer_set/set.rs
Labels: A-docs, C-enhancement, P-Low

#3270 Refactor code to avoid incorrect clippy::unnecessary_to_owned lint
  zebra-chain/src/block/arbitrary.rs
Labels: C-cleanup, P-Low, C-testing

#3273 Add `peer::Client` tests with zero and multiple readiness checks
  zebra-network/src/peer/client/tests/vectors.rs
Labels: P-Medium, I-panic, I-hang, A-network, C-testing

#3272 Replace `NowOrLater` with `futures::poll!`
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  Cargo.lock
  Cargo.toml
  now-or-later/Cargo.toml
  now-or-later/src/lib.rs
  zebra-test/Cargo.toml
  zebra-test/src/service_extensions.rs
  zebrad/Cargo.toml
  zebrad/src/components/sync.rs
Labels: A-dependencies, C-cleanup, P-Low

#3274 Revert "Stop ignoring some completed Responses"
  zebra-network/src/peer/connection.rs
Labels: C-bug, P-High, I-slow, A-network

#3241 Use `MockedClientHandle` in other tests
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  zebra-network/src/peer.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/client/tests.rs
  zebra-network/src/peer/client/tests/vectors.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/peer_set/set/tests.rs
  zebra-network/src/peer_set/set/tests/prop.rs
  zebra-test/src/lib.rs
  zebra-test/src/service_extensions.rs
  zebrad/src/async_ext.rs
  zebrad/src/async_ext/now_or_later.rs
  zebrad/src/components/sync.rs
  zebrad/src/lib.rs
Labels: C-cleanup, P-Medium, A-network, C-testing

#3246 Re-enable code coverage comments on PRs
  codecov.yml
Labels: A-github-actions, P-Medium, C-testing

#3253 Keep track of background peer tasks
  zebra-network/src/peer.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/client/tests.rs
  zebra-network/src/peer/client/tests/vectors.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/set/tests/prop.rs
Labels: P-Medium, C-security, A-network, A-diagnostics

#3175 Add a copy-state zebrad command, which copies blocks between two state services
  zebrad/src/commands.rs
  zebrad/src/commands/copy_state.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/tokio.rs
Labels: C-enhancement, P-Medium, A-diagnostics

#3137 Draft design for lightwalletd database support
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-design, P-Low

#3154 Check jubjub key correctness independent of redjubjub / jubjub
  zebra-chain/src/orchard/arbitrary.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/sapling/address.rs
  zebra-chain/src/sapling/arbitrary.rs
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/keys/tests.rs
  zebra-chain/src/sapling/output.rs
  zebra-chain/src/sapling/shielded_data.rs
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/check.rs
  zebra-consensus/src/transaction/tests.rs
Labels: P-Medium

#3304 Fix a type resolution error in the tests
  zebra-network/src/meta_addr/tests/prop.rs
Labels: C-bug, P-Medium, C-testing

#3308 Upgrade zcash_proofs to get new derived traits
  Cargo.lock
  Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
Labels: A-dependencies, C-enhancement, P-Medium
