Repository ZcashFoundation/zebra, pull requests merged in 2021-04, with the labels that each got.

#1969 Zebra Client RFC: add mandatory sweep fast startup option
  book/src/dev/rfcs/0009-zebra-client.md
Labels: A-docs, C-design, P-Low

#1972 Document peer set deadlock resistance
  zebra-network/src/peer_set/set.rs
Labels: A-docs, C-enhancement, C-security, I-hang, P-Medium

#1975 Bump redjubjub to 0.4.0
  Cargo.lock
  zebra-chain/Cargo.toml
Labels: A-dependencies

#1920 Implement Trusted Vector Preallocation
  zebra-chain/src/block.rs
  zebra-chain/src/block/header.rs
  zebra-chain/src/sapling/arbitrary.rs
  zebra-chain/src/sapling/output.rs
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/serialization.rs
  zebra-chain/src/serialization/error.rs
  zebra-chain/src/serialization/zcash_deserialize.rs
  zebra-chain/src/serialization/zcash_serialize.rs
  zebra-chain/src/sprout/joinsplit.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/protocol/external.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/inv.rs
Labels: A-rust, C-bug, C-design, C-security, I-bad-data, I-heavy, P-High

#1978 Clean up block commitment enum and parsing
  zebra-chain/src/block.rs
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/block/header.rs
  zebra-chain/src/block/tests/prop.rs
Labels: A-consensus, A-rust, C-cleanup, NU-5-TBC, P-Medium

#1988 Rename the NU5 block commitment variant based on what it commits to
  zebra-chain/src/block/commitment.rs
Labels: A-rust, C-cleanup, NU-5-TBC, P-Medium

#1986 Update tower-batch tests to rand 0.8
  Cargo.lock
  Cargo.toml
  tower-batch/Cargo.toml
  zebra-chain/Cargo.toml
Labels: A-dependencies, C-cleanup, P-Medium

#1984 Clean up use statements in `arbitrary` modules
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/transaction/arbitrary.rs
Labels: A-rust, C-cleanup, P-Low

#1987 Rename the () placeholder to FieldNotPresent
  book/src/dev/rfcs/0010-v5-transaction.md
  zebra-chain/src/sapling.rs
  zebra-chain/src/sapling/arbitrary.rs
  zebra-chain/src/sapling/shielded_data.rs
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/serialize.rs
Labels: A-rust, C-cleanup, NU-5-TBC, P-Medium

#1950 Fix a deadlock between the crawler and dialer, and other hangs
  zebra-network/src/constants.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
Labels: A-rust, C-bug, C-enhancement, C-security, I-hang, I-heavy, I-integration-fail, I-slow, I-usability, P-Medium

#1989 Test the manual eq impl on sapling::ShieldedData<PerSpend>
  zebra-chain/src/sapling/tests/preallocate.rs
  zebra-chain/src/sapling/tests/prop.rs
Labels: A-rust, C-cleanup, C-enhancement, NU-5-TBC, P-Medium

#1985 Add InventoryHash and MetaAddr proptests
  zebra-network/Cargo.toml
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/meta_addr/tests.rs
  zebra-network/src/meta_addr/tests/check.rs
  zebra-network/src/meta_addr/tests/preallocate.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/meta_addr/tests/vectors.rs
  zebra-network/src/protocol/external.rs
  zebra-network/src/protocol/external/arbitrary.rs
  zebra-network/src/protocol/external/tests/preallocate.rs
  zebra-network/src/protocol/external/types.rs
Labels: A-dependencies, A-rust, C-cleanup, P-High

#2003 Refactor the dial action into a From impl
  zebra-network/src/peer_set/initialize.rs
Labels: A-rust, C-cleanup, P-Medium

#2006 clippy: make to_* methods take self by value
  zebra-chain/src/work/difficulty.rs
Labels: A-rust, C-cleanup, P-Medium

#2007 Use meaningful names for select! variables
  zebra-network/src/peer_set/initialize.rs
  zebrad/src/components/tokio.rs
Labels: A-rust, C-cleanup, P-Medium

#2013 clippy: factor common code out of an if-else block
  zebrad/src/application.rs
Labels: A-rust, C-cleanup, P-Medium

#2014 Fix a test failure due to ' debug format changes in Rust
  zebra-chain/src/transaction/memo.rs
Labels: A-rust, C-bug, I-integration-fail, P-Medium

#2016 Stop panicking when Zebra sends a reject without extra data
  zebra-network/src/protocol/external/codec.rs
Labels: A-network, A-rust, C-bug, I-panic, P-Medium

#2004 Security: avoid a single peer providing a majority of Zebra's peer addresses
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
Labels: A-network, A-rust, C-security, I-bad-data, P-Medium

#983 Draft RFC: Treestate management
  book/src/dev/rfcs/drafts/0005-treestate.md
Labels: A-docs, C-design, C-research

#2005 Fix a nightly compile error by patching lexical-core to 0.7.5
  Cargo.lock
  Cargo.toml
Labels: A-dependencies, C-bug, I-integration-fail, P-Medium

#1996 Redesign Transaction V5 serialization, impl trusted vector security, nullifier utility functions
  book/src/dev/rfcs/0010-v5-transaction.md
  zebra-chain/src/sapling.rs
  zebra-chain/src/sapling/arbitrary.rs
  zebra-chain/src/sapling/output.rs
  zebra-chain/src/sapling/shielded_data.rs
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/sapling/tests/preallocate.rs
  zebra-chain/src/sapling/tests/prop.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/sighash.rs
Labels: A-consensus, A-docs, A-rust, C-bug, C-cleanup, C-design, C-enhancement, C-security, I-bad-data, I-heavy, NU-5-TBC, P-Medium

#2017 Add split array serialization functions for Transaction::V5
  zebra-chain/src/serialization.rs
  zebra-chain/src/serialization/tests.rs
  zebra-chain/src/serialization/tests/preallocate.rs
  zebra-chain/src/serialization/tests/prop.rs
  zebra-chain/src/serialization/zcash_deserialize.rs
  zebra-chain/src/serialization/zcash_serialize.rs
  zebra-network/src/protocol/external.rs
  zebra-network/src/protocol/external/codec.rs
Labels: A-rust, C-enhancement, NU-5-TBC, P-Medium

#2012 Speedup proptests for Chain struct in zebra-state
  zebra-chain/src/block/tests/prop.rs
  zebra-chain/src/work/tests/prop.rs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-rust, C-enhancement, P-Medium

#2020 Implement Sapling serialization in Transaction V5
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/block/tests/prop.rs
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/sapling.rs
  zebra-chain/src/sapling/tests/prop.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/tests/prop.rs
  zebra-chain/src/transaction/tests/vectors.rs
Labels: A-consensus, A-dependencies, A-rust, C-design, C-enhancement, NU-5-TBC, P-Medium

#2026 Update dependencies to support Apple M1, fix Windows CI LLVM paths
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
Labels: A-dependencies, A-github-actions, A-infrastructure, A-rust

#2027 Bump ripemd160 from 0.8.0 to 0.9.1 and remove trait import
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/transparent/address.rs
Labels: A-dependencies, A-rust

#2009 Make sure each peer heartbeat has a timeout
  zebra-network/src/peer/handshake.rs
Labels: A-network, A-rust, C-bug, C-cleanup, P-Medium

#2029 Update to vergen 5, add branch, commit time, and build target to the panic metadata, automatically update app version from crate version
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  Cargo.lock
  zebra-chain/src/parameters/network.rs
  zebrad/Cargo.toml
  zebrad/build.rs
  zebrad/src/application.rs
  zebrad/src/components/tracing/component.rs
Labels: A-dependencies, A-rust, C-cleanup, C-enhancement, P-Medium

#2008 Make sure handshake version negotiation always has a timeout
  zebra-network/src/peer/handshake.rs
Labels: A-rust, C-bug, C-cleanup, P-Medium

#2021 Redesign Sapling data model for V5 shared anchor and spends
  book/src/dev/rfcs/0010-v5-transaction.md
  zebra-chain/src/sapling.rs
  zebra-chain/src/sapling/shielded_data.rs
  zebra-chain/src/sapling/tests/prop.rs
  zebra-chain/src/serialization.rs
  zebra-chain/src/serialization/constraint.rs
  zebra-chain/src/serialization/serde_helpers.rs
  zebra-chain/src/serialization/zcash_deserialize.rs
  zebra-chain/src/serialization/zcash_serialize.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/joinsplit.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/tests/vectors.rs
Labels: A-consensus, A-rust, C-cleanup, C-design, C-enhancement, NU-5-TBC, P-Medium

#2037 Stop assuming there will always be a git commit
  zebrad/build.rs
  zebrad/src/application.rs
Labels: A-rust, C-bug, I-integration-fail, P-High

#2045 Revert "Revert "build(deps): bump vergen from 5.1.1 to 5.1.2"" - actually make this change now
  Cargo.lock
  zebrad/Cargo.toml
Labels: A-dependencies, P-Medium

#2046 Cleanup: move spends_per_anchor to TransferData
  zebra-chain/src/sapling/shielded_data.rs
Labels: A-rust, C-cleanup, NU-5-TBC, P-Low

#2036 Clarify CandidateSet state diagram
  zebra-network/src/peer_set/candidate_set.rs
Labels: A-docs, C-bug, P-Low

#2031 Switch to an async mutex for handshake nonces
  zebra-network/src/peer/handshake.rs
Labels: A-rust, C-bug, C-cleanup, C-security, I-hang, I-slow, P-Medium

#2032 Refactor and document correctness for std::sync::Mutex in ErrorSlot
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/error.rs
Labels: A-rust, C-cleanup, P-Low

#2033 Refactor and document correctness for std::sync::Mutex<AddressBook>
  zebra-network/src/address_book.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/timestamp_collector.rs
  zebrad/src/components/inbound.rs
Labels: A-rust, C-bug, C-cleanup, C-security, I-hang, I-slow, P-Medium

#2038 Add the new commit count and git hash to the version
  zebra-chain/src/parameters/network.rs
  zebrad/build.rs
  zebrad/src/application.rs
  zebrad/src/components/tracing/component.rs
Labels: A-rust, C-enhancement, I-usability, P-Low

#2043 Use the default port for configured Zcash listener addresses with no port
  Cargo.lock
  zebra-network/Cargo.toml
  zebra-network/src/config.rs
  zebra-network/src/config/tests.rs
  zebra-network/src/peer_set/initialize.rs
Labels: A-dependencies, A-rust, C-enhancement, I-usability, P-Low

#2034 Add journald support through tracing-journald
  Cargo.lock
  book/src/user/tracing.md
  zebrad/Cargo.toml
  zebrad/src/components/tracing/component.rs
  zebrad/src/config.rs
Labels: A-dependencies, A-docs, A-rust, C-enhancement, P-Low

#2053 Make Zcash string serialization consistent with deserialization
  zebra-chain/src/serialization/write_zcash.rs
  zebra-chain/src/serialization/zcash_serialize.rs
  zebra-network/src/protocol/external/codec.rs
Labels: A-rust, C-cleanup, P-Low

#2054 Clarify a duplicate log message
  zebrad/src/commands/start.rs
Labels: A-rust, C-bug, I-usability, P-Low

#2058 Fix outdated comments in network_upgrade.rs
  zebra-chain/src/parameters/network_upgrade.rs
Labels: A-docs, A-rust, C-cleanup, P-Low

#2069 Document how Zebra does cross-crate proptests
  book/src/dev/proptests.md
Labels: A-docs, C-enhancement, P-Low

#2071 Add extra crate dependencies to the proptest docs
  book/src/dev/proptests.md
Labels: A-docs, C-enhancement, P-Low

#2073 Clippy nightly: disable owned cmp, stop comparing bool using assert_eq
  zebra-chain/src/sapling/keys.rs
  zebra-network/src/isolated.rs
Labels: A-rust, C-cleanup, P-Low

#2072 Rename shielded_data to sapling_shielded_data as needed
  zebra-chain/src/sapling/tests/prop.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-consensus/src/primitives/groth16/tests.rs
  zebra-consensus/src/transaction.rs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-rust, C-cleanup, P-Low

#2075 Parse ConsensusBranchId into NetworkUpgrade for transaction v5
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/tests/vectors.rs
Labels: A-consensus, A-rust, C-enhancement, NU-5-TBC, P-Medium

#2085 Fix CI on main
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/tests/vectors.rs
Labels: A-rust, C-bug, I-integration-fail, NU-5-TBC, P-High

#2084 Remove broken ci-success check
  .github/workflows/ci.yml
Labels: A-github-actions, C-bug, C-cleanup, P-Medium

#2081 Explain how to derive arbitrary impls in the dev docs
  book/src/dev/proptests.md
Labels: A-docs, C-enhancement, P-Medium
