Repository ZcashFoundation/zebra, pull requests merged in 2021-09, with the labels that each got.

#2719 Document consensus rules for version group IDs
  zebra-chain/src/transaction/serialize.rs
Labels: A-docs, A-consensus, C-enhancement, P-Low

#2715 Add a `ChainTipChange` type to `await` chain tip changes
  zebra-chain/src/chain_tip.rs
  zebra-network/src/isolated.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-state/src/arbitrary.rs
  zebra-state/src/lib.rs
  zebra-state/src/service.rs
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/chain_tip/tests/prop.rs
  zebra-state/src/service/chain_tip/tests/vectors.rs
  zebra-state/src/service/tests.rs
  zebra-state/src/tests/setup.rs
  zebra-state/tests/basic.rs
  zebrad/src/commands/start.rs
Labels: A-rust, C-enhancement, P-Medium

#2721 Reset `ChainTipChange`s on chain fork and network upgrade activation
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/parameters/tests.rs
  zebra-state/src/arbitrary.rs
  zebra-state/src/service.rs
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/chain_tip/tests/prop.rs
  zebra-state/src/service/chain_tip/tests/vectors.rs
  zebra-state/src/service/tests.rs
Labels: A-consensus, A-rust, C-enhancement, P-Medium

#2722 Decide if Zebra is at the chain tip
  zebrad/src/components/sync/status.rs
  zebrad/src/components/sync/status/tests.rs
Labels: A-rust

#2747 Remove Clone from Storage
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/storage.rs
  zebrad/src/components/mempool/storage/tests.rs
Labels: A-rust, C-enhancement

#2788 Allow deliberate instances of the clippy::derivable_impls lint
  zebra-consensus/src/config.rs
  zebrad/src/application.rs
  zebrad/src/config.rs
Labels: A-rust, C-cleanup, P-Medium

#2773 Clear mempool at a network upgrade
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/chain_tip/tests/prop.rs
  zebra-state/src/service/chain_tip/tests/vectors.rs
  zebra-state/src/service/tests.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/storage.rs
Labels: A-rust

#2791 Send `Response::Nil` instead of sending empty `Message`s
  zebrad/src/components/inbound.rs
Labels: C-bug, A-rust, C-cleanup, P-Medium, A-network

#2789 Fix an incorrect assertion when the block locator is at the tip
  zebra-chain/src/block/header.rs
  zebra-chain/src/block/tests/preallocate.rs
  zebra-state/src/service.rs
  zebra-state/src/service/tests.rs
Labels: C-bug, A-rust, P-Medium, C-security, I-panic, I-bad-data

#2800 Stop panicking when using sync and async methods on the same ChainTipChange
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/chain_tip/tests/prop.rs
  zebra-state/src/service/chain_tip/tests/vectors.rs
Labels: C-bug, A-rust, P-Medium, I-panic

#2807 Use complete addition instead of incomplete addition inside sinsemilla_commit
  zebra-chain/src/orchard/sinsemilla.rs
Labels: A-consensus, A-rust, NU-5, P-High

#2804 Add metrics for initial peer network protocol versions
  grafana/peers.json
  zebra-network/src/config.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/protocol/external/types.rs
Labels: A-rust, C-enhancement, NU-5, P-Medium, A-network
