Repository ZcashFoundation/zebra, pull requests merged in 2021-11, with the labels that each got.

#2977 Increase maximum request delay for `inbound` tests
  zebrad/src/components/inbound/tests.rs
Labels: P-Low

#2978 Mempool doc
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/config.rs
  zebrad/src/components/mempool/downloads.rs
Labels: A-docs, P-Medium

#2986 Check for duplicate crate dependencies in CI
  .github/workflows/ci.yml
  deny.toml
Labels: A-dependencies, A-github-actions, C-enhancement, P-Medium

#2976 Make `services` field in `MetaAddr` optional
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/tests/check.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
Labels: P-Low

#2996 Update README troubleshooting and beta scope
  README.md
Labels: A-docs, C-enhancement, C-cleanup, P-Low

#2997 Disable an unreliable network test on macOS
  zebra-network/src/peer_set/initialize/tests/vectors.rs
Labels: C-bug, P-Low, I-integration-fail, A-network

#3001 Update README when tagging a new release
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: P-Low

#2994 Update to Tokio 1.13.0
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  deny.toml
  tower-batch/Cargo.toml
  tower-batch/src/semaphore.rs
  tower-batch/src/worker.rs
  tower-batch/tests/ed25519.rs
  tower-batch/tests/worker.rs
  tower-fallback/Cargo.toml
  tower-fallback/tests/fallback.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/block.rs
  zebra-consensus/src/chain.rs
  zebra-consensus/src/checkpoint/tests.rs
  zebra-consensus/src/primitives/ed25519/tests.rs
  zebra-consensus/src/primitives/groth16/tests.rs
  zebra-consensus/src/primitives/redjubjub/tests.rs
  zebra-consensus/src/primitives/redpallas/tests.rs
  zebra-network/Cargo.toml
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connector.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/inventory_registry.rs
  zebra-state/Cargo.toml
  zebra-state/src/service/tests.rs
  zebra-test/Cargo.toml
  zebra-test/src/transcript.rs
  zebra-test/tests/transcript.rs
  zebrad/Cargo.toml
  zebrad/src/application.rs
  zebrad/src/components/inbound/tests.rs
  zebrad/src/components/mempool/crawler.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/src/components/mempool/gossip.rs
  zebrad/src/components/mempool/queue_checker.rs
  zebrad/src/components/mempool/storage/verified_set.rs
  zebrad/src/components/mempool/tests/vector.rs
  zebrad/src/components/metrics.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/downloads.rs
  zebrad/src/components/sync/gossip.rs
  zebrad/src/components/sync/status/tests.rs
  zebrad/src/components/tracing/component.rs
  zebrad/tests/acceptance.rs
Labels: P-Medium

#3006 Some tweaks of the README
  README.md
Labels: A-docs, C-cleanup, P-Low

#2992 Rename `TimestampCollector` to `AddressBookUpdater`
  zebra-network/src/address_book_updater.rs
  zebra-network/src/lib.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
Labels: P-Low

#2974 Add unused seed peers to the AddressBook
  zebra-network/src/address_book_updater.rs
  zebra-network/src/lib.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
Labels: C-bug, P-Medium, I-hang, I-slow, A-network

#3008 Create CompactSize64 for non-message-length fields
  book/src/dev/rfcs/0010-v5-transaction.md
  zebra-chain/src/serialization.rs
  zebra-chain/src/serialization/arbitrary.rs
  zebra-chain/src/serialization/compact_size.rs
  zebra-chain/src/serialization/error.rs
  zebra-chain/src/serialization/read_zcash.rs
  zebra-chain/src/serialization/tests/prop.rs
  zebra-chain/src/serialization/write_zcash.rs
  zebra-chain/src/serialization/zcash_deserialize.rs
  zebra-chain/src/serialization/zcash_serialize.rs
Labels: C-bug, A-consensus, A-rust, P-Medium, A-network

#3013 Re-enable duplicate dependency checking for `inferno`
  deny.toml
Labels: A-dependencies, C-cleanup, P-Low

#3014 Replace read_compactsize and write_compactsize with CompactSizeMessage
  zebra-chain/src/block/header.rs
  zebra-chain/src/block/serialize.rs
  zebra-chain/src/block/tests/preallocate.rs
  zebra-chain/src/serialization/read_zcash.rs
  zebra-chain/src/serialization/tests/prop.rs
  zebra-chain/src/serialization/write_zcash.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transparent/script.rs
  zebra-chain/src/transparent/serialize.rs
  zebra-chain/src/work/equihash.rs
  zebra-chain/src/work/tests/vectors.rs
  zebra-state/src/service.rs
  zebra-state/src/service/tests.rs
Labels: A-rust, C-enhancement, C-cleanup, P-Medium

#3020 Move MetaAddr serialization into zebra_network::protocol::external
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/tests.rs
  zebra-network/src/meta_addr/tests/preallocate.rs
  zebra-network/src/protocol/external.rs
  zebra-network/src/protocol/external/addr.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/tests/preallocate.rs
Labels: A-rust, C-enhancement, NU-5, P-Medium

#3019 Fix verbose add_initial_peers logs
  zebra-network/src/peer_set/initialize.rs
  zebra-state/src/service.rs
Labels: A-rust, C-cleanup, P-Low, I-usability, A-network

#3031 Fix listener address conflicts in network tests
  zebra-network/src/peer_set/initialize/tests/vectors.rs
Labels: C-bug, A-rust, P-Medium, I-integration-fail, A-network

#3017 Validate funding stream amounts in coinbase transaction
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/subsidy.rs
  zebra-consensus/src/block/subsidy/funding_streams.rs
  zebra-consensus/src/block/subsidy/funding_streams/tests.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/error.rs
  zebra-consensus/src/parameters/subsidy.rs
Labels: P-Medium

#3021 Refactor addr v1 serialization using a separate AddrV1 type
  zebra-chain/src/serialization.rs
  zebra-chain/src/serialization/arbitrary.rs
  zebra-chain/src/serialization/read_zcash.rs
  zebra-chain/src/serialization/write_zcash.rs
  zebra-chain/src/serialization/zcash_deserialize.rs
  zebra-chain/src/serialization/zcash_serialize.rs
  zebra-network/src/address_book.rs
  zebra-network/src/config.rs
  zebra-network/src/isolated.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/meta_addr/tests.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/protocol/external.rs
  zebra-network/src/protocol/external/addr.rs
  zebra-network/src/protocol/external/addr/canonical.rs
  zebra-network/src/protocol/external/addr/in_version.rs
  zebra-network/src/protocol/external/addr/v1.rs
  zebra-network/src/protocol/external/arbitrary.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/external/tests/preallocate.rs
  zebra-network/src/protocol/external/tests/prop.rs
Labels: A-rust, C-enhancement, NU-5, P-Medium

#3032 Simplify preallocate tests
  zebra-chain/src/block/tests/preallocate.rs
  zebra-chain/src/orchard/tests/preallocate.rs
  zebra-chain/src/sapling/tests/preallocate.rs
  zebra-chain/src/serialization/arbitrary.rs
  zebra-chain/src/serialization/tests.rs
  zebra-chain/src/serialization/tests/preallocate.rs
  zebra-chain/src/serialization/zcash_deserialize.rs
  zebra-chain/src/sprout/tests/preallocate.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/tests/preallocate.rs
  zebra-network/src/protocol/external/tests/preallocate.rs
Labels: A-rust, C-cleanup, P-Medium

#3030 Security: Avoid reconnecting to peers that are likely unreachable
  zebra-chain/src/serialization/date_time.rs
  zebra-network/src/address_book/tests/prop.rs
  zebra-network/src/constants.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/tests/prop.rs
Labels: P-High, C-security

#3033 Depend on a multiset git commit that includes a bug fix
  Cargo.lock
  deny.toml
  zebra-state/Cargo.toml
Labels: C-bug, A-dependencies, P-Low

#3022 Parse received addrv2 messages
  zebra-chain/src/transaction/tests/preallocate.rs
  zebra-network/src/constants.rs
  zebra-network/src/protocol/external/addr.rs
  zebra-network/src/protocol/external/addr/in_version.rs
  zebra-network/src/protocol/external/addr/v1.rs
  zebra-network/src/protocol/external/addr/v2.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/external/tests/preallocate.rs
  zebra-network/src/protocol/external/tests/prop.rs
  zebra-network/src/protocol/external/tests/vectors.rs
  zebra-test/src/lib.rs
  zebra-test/src/network_addr.rs
  zebrad/src/components/inbound.rs
Labels: C-bug, A-rust, C-enhancement, NU-5, P-Medium, A-network

#3040 Validate funding stream addresses
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/subsidy.rs
  zebra-consensus/src/block/subsidy/founders_reward.rs
  zebra-consensus/src/block/subsidy/funding_streams.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/error.rs
  zebra-consensus/src/parameters/subsidy.rs
Labels: P-Medium

#3054 Stop asking users to report peer errors, fix a common peer error
  zebra-network/src/lib.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/error.rs
  zebrad/src/application.rs
Labels: C-bug, P-Low, I-usability, A-network

#3049 Check MAX_BLOCK_SIGOPS in the block verifier
  Cargo.lock
  zebra-chain/src/block.rs
  zebra-chain/src/block/tests.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/error.rs
  zebra-consensus/src/transaction.rs
  zebra-script/Cargo.toml
  zebra-script/src/lib.rs
  zebra-state/src/service/non_finalized_state/queued_blocks.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
  zebra-test/Cargo.toml
  zebra-test/src/prelude.rs
Labels: A-dependencies, A-consensus, NU-0 Overwinter, P-Medium

#2645 Async Halo2 verifier service
  Cargo.lock
  Cargo.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/note/ciphertexts.rs
  zebra-chain/src/sapling/note/ciphertexts.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/primitives.rs
  zebra-consensus/src/primitives/halo2.rs
  zebra-consensus/src/primitives/halo2/tests.rs
  zebra-consensus/src/primitives/halo2/tests/vectors.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-test/src/vectors.rs
  zebra-test/src/vectors/orchard-shielded-data-1.txt
  zebra-test/src/vectors/orchard-shielded-data-2.txt
  zebra-test/src/vectors/orchard-shielded-data-3.txt
  zebra-test/src/vectors/orchard-shielded-data-4.txt
  zebra-test/src/vectors/orchard_shielded_data.rs
Labels: A-dependencies, A-consensus, A-rust, NU-5, P-Medium

#3039 Verify Halo2 proofs as part of V5 transaction verification
  zebra-consensus/src/primitives/halo2.rs
  zebra-consensus/src/primitives/halo2/tests.rs
  zebra-consensus/src/transaction.rs
Labels: A-consensus, A-rust, NU-5

#3064 Check for panics in the address book updater task
  zebra-network/src/address_book_updater.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
Labels: C-bug, C-cleanup, P-Low, I-usability, A-network

#3071 Implement graceful shutdown for the peer set
  zebra-network/src/peer_set/set.rs
Labels: C-bug, P-Low, I-integration-fail, I-usability, A-network

#3051 Sprout note commitment trees
  README.md
  zebra-chain/src/sprout/tests.rs
  zebra-chain/src/sprout/tests/test_vectors.rs
  zebra-chain/src/sprout/tests/tree.rs
  zebra-chain/src/sprout/tree.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/joinsplit.rs
  zebra-test/src/lib.rs
  zebra-test/src/vectors/block-main-0-000-396.txt
  zebra-test/src/vectors/block-test-0-002-259.txt
  zebra-test/src/vectors/block.rs
Labels: NU Sprout, P-Medium

#3072 Stop downloading unnecessary blocks in Zebra acceptance tests
  zebrad/src/components.rs
  zebrad/src/components/inbound.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/crawler.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/tracing.rs
  zebrad/src/config.rs
  zebrad/src/lib.rs
  zebrad/tests/acceptance.rs
Labels: C-bug, P-Medium, I-integration-fail

#3057 Download Zcash Sapling parameters and load them from cached files
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/manual-deploy.yml
  Cargo.lock
  Cargo.toml
  deny.toml
  docker/Dockerfile.build
  docker/Dockerfile.test
  zebra-consensus/Cargo.toml
  zebra-consensus/examples/download-params.rs
  zebra-consensus/examples/get-params-path.rs
  zebra-consensus/src/chain.rs
  zebra-consensus/src/chain/tests.rs
  zebra-consensus/src/lib.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/groth16/hash_reader.rs
  zebra-consensus/src/primitives/groth16/params.rs
  zebra-consensus/src/primitives/groth16/tests.rs
  zebra-consensus/src/transaction.rs
  zebrad/Cargo.toml
  zebrad/src/commands.rs
  zebrad/src/commands/download.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound/tests.rs
Labels: A-dependencies, NU-1 Sapling, NU Sprout, A-github-actions, C-enhancement

#3077 Speed up CI, and split unrelated and conflicting CI jobs
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: A-github-actions, C-cleanup, P-Medium, I-slow, I-integration-fail

#3078 Shut down channels and tasks on PeerSet Drop
  zebra-network/src/peer_set/set.rs
Labels: C-bug, A-rust, P-Medium, I-panic, I-hang

#3092 Use prepared verifying key for non-batch Groth16 verification
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/groth16/tests.rs
Labels: C-enhancement, P-Low, I-slow

#3093 Sum transaction miner fees in the block verifier
  zebra-consensus/src/block.rs
  zebra-consensus/src/error.rs
Labels: A-consensus, NU Sprout, C-enhancement, P-Medium

#3091 Re-order Zebra startup, so slow services are launched last
  zebra-consensus/src/chain.rs
  zebrad/src/commands/start.rs
  zebrad/src/components.rs
  zebrad/src/components/inbound.rs
  zebrad/src/components/inbound/tests.rs
  zebrad/src/components/tokio.rs
Labels: C-bug, A-rust, P-High, I-integration-fail, A-network

#3090 Security: Stop routing inventory requests by peer address
  Cargo.lock
  zebra-network/Cargo.toml
  zebra-network/src/peer_set/set.rs
Labels: A-dependencies, P-Medium, C-security, I-remote-node-overload, I-bad-data, A-network

#3085 Automatically download and load sprout parameters
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  Cargo.lock
  Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-consensus/src/chain.rs
  zebra-consensus/src/primitives/groth16/params.rs
  zebrad/src/commands/start.rs
Labels: A-dependencies, NU-1 Sapling, NU Sprout, A-rust, C-enhancement, P-Medium, A-network

#3100 Add Sprout anchors to `zebra-state`
  .github/workflows/test.yml
  zebra-chain/src/transaction.rs
  zebra-state/src/constants.rs
  zebra-state/src/error.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
Labels: NU Sprout, P-Medium

#3120 Stop closing connections on unexpected messages, Credit: Equilibrium
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/internal/request.rs
  zebra-network/src/protocol/internal/response.rs
Labels: C-bug, P-Medium, C-security, I-hang, I-slow, I-bad-data, A-network

#3104 Fix slow Zebra startup times, to reduce CI failures
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/set.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/crawler.rs
  zebrad/src/components/sync.rs
Labels: C-bug, P-Low, I-slow, I-usability
