Repository ZcashFoundation/zebra, pull requests merged in 2021-07, with the labels that each got.

#2397 Create a shared Tokio runtime for tests
  Cargo.lock
  zebra-consensus/src/transaction/tests.rs
  zebra-test/Cargo.toml
  zebra-test/src/lib.rs
Labels: A-dependencies, A-rust, C-bug, P-Medium

#2427 Fix failing legacy chain tests
  zebra-chain/src/block/arbitrary.rs
  zebra-state/proptest-regressions/service/tests.txt
  zebra-state/src/service.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/tests.rs
Labels: A-rust, C-bug, P-Medium

#2428 Stop allowing JoinSplit<Halo2>
  zebra-chain/src/primitives/proofs.rs
Labels: A-consensus, A-rust, C-bug, P-Medium

#2318 RedPallas async verifier service
  zebra-consensus/src/error.rs
  zebra-consensus/src/primitives.rs
  zebra-consensus/src/primitives/redpallas.rs
  zebra-consensus/src/primitives/redpallas/tests.rs
Labels: A-rust

#2259 Add notes about note commitment trees storage
  book/src/dev/rfcs/drafts/0005-treestate.md
Labels: A-docs, C-design

#2432 Refactor asynchronous checks in `transaction::Verifier`
  zebra-consensus/src/transaction.rs
Labels: A-consensus, A-rust

#2129 Add ZIP-0244 TxId Digest support
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/orchard/arbitrary.rs
  zebra-chain/src/primitives.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-chain/src/sapling/arbitrary.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/hash.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-chain/src/transaction/txid.rs
  zebra-test/src/lib.rs
  zebra-test/src/zip0244.rs
Labels: A-rust

#2396 Add HistoryTree struct
  zebra-chain/src/history_tree.rs
  zebra-chain/src/lib.rs
  zebra-chain/src/primitives/zcash_history.rs
  zebra-chain/src/primitives/zcash_history/tests/vectors.rs
Labels: A-rust

#2165 Add ZIP-244 signature hash support
  zebra-chain/src/primitives.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-test/src/zip0244.rs
Labels: A-rust

#2301 ZIP-221: Validate chain history commitments in the non-finalized state
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/history_tree.rs
  zebra-chain/src/primitives/zcash_history.rs
  zebra-state/src/error.rs
  zebra-state/src/service.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
  zebra-state/src/tests.rs
Labels: A-rust

#2453 Stop using the wrong name for the coverage action
  .github/workflows/coverage.yml
Labels: A-github-actions, C-bug, P-Medium

#2457 clippy: remove needless borrows
  zebra-chain/src/transaction/hash.rs
  zebra-chain/src/transaction/sighash.rs
Labels: A-rust, C-cleanup, P-Medium

#2413 Modify UTXO and state designs for transparent coinbase output checks
  book/src/dev/rfcs/0004-asynchronous-script-verification.md
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-design, NU---Sprout, P-Medium

#2430 Value pools design
  book/src/dev/rfcs/0012-value-pools.md
Labels: C-design

#2466 Add a TypeNameToDebug formatter to zebra_chain
  zebra-chain/src/fmt.rs
Labels: A-rust, C-enhancement, P-Medium

#2467 Combine near-duplicate Utxo creation functions
  zebra-consensus/src/block.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
  zebra-state/src/tests.rs
  zebra-state/src/utxo.rs
Labels: A-rust, C-cleanup, P-Medium

#2465 Add methods for getting block nullifiers
  zebra-chain/src/block.rs
Labels: A-rust, NU---Sprout, NU-1-Sapling, NU-5, P-Medium

#2463 Use the block verifier and non-finalized state in the cached state tests
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/tests/prop.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-bug, P-High

#2472 Stop ignoring sapling binding signature errors
  zebra-consensus/src/transaction.rs
Labels: A-consensus, A-rust, C-bug, I-consensus 💥, NU-1-Sapling, P-Medium

#2478 Restore the previous non-finalized chain if a block is invalid
  zebra-state/src/service.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
Labels: A-rust, C-bug, I-slow, I-usability, P-Medium

#2481 Move `Utxo` type to zebra-chain
  zebra-chain/src/transparent.rs
  zebra-chain/src/transparent/utxo.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/script.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/queued_blocks.rs
  zebra-state/src/service/pending_utxos.rs
  zebra-state/src/service/tests.rs
  zebra-state/src/tests.rs
Labels: A-rust, C-cleanup, P-Medium

#2456 Update state RFC for incremental trees, value pools, and RocksDB
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, NU---Sprout, NU-0-Overwinter, NU-1-Sapling, NU-5, P-Medium

#2476 Document some consensus-critical finalized state behaviour
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format.rs
Labels: A-consensus, A-docs, C-bug, P-Medium

#2483 Move zebra_state::service::check tests to their own module
  zebra-state/src/service/check.rs
  zebra-state/src/service/check/tests.rs
  zebra-state/src/service/check/tests/vectors.rs
Labels: A-rust, C-cleanup, P-Medium

#2479 When a parent block is rejected, also reject its children
  zebra-state/src/service.rs
Labels: A-consensus, A-rust, C-bug, I-consensus 💥, I-hang, I-panic, S-needs-triage

#2477 Reject duplicate sprout nullifiers in the state
  Cargo.lock
  zebra-state/Cargo.toml
  zebra-state/proptest-regressions/service/check/tests/prop.txt
  zebra-state/src/error.rs
  zebra-state/src/service.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/check/nullifier.rs
  zebra-state/src/service/check/tests.rs
  zebra-state/src/service/check/tests/prop.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-consensus, A-dependencies, A-rust, C-enhancement, NU---Sprout, P-Medium

#2495 Test that non-finalized block rejections reset the state
  zebra-state/src/service.rs
  zebra-state/src/service/check/nullifier.rs
  zebra-state/src/service/check/tests/prop.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
Labels: A-rust, C-enhancement, NU---Sprout, P-Medium

#2407 Calculate incremental note commitment trees
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/orchard/tests.rs
  zebra-chain/src/orchard/tests/test_vectors.rs
  zebra-chain/src/orchard/tests/tree.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/tests.rs
  zebra-chain/src/sapling/tests/test_vectors.rs
  zebra-chain/src/sapling/tests/tree.rs
  zebra-chain/src/sapling/tree.rs
Labels: A-consensus, A-dependencies, A-rust, NU-5

#2487 Test consensus-critical `Amount` deserialization
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/amount.rs
Labels: A-consensus, A-dependencies, A-rust, C-bug, P-Medium

#2501 clippy: remove a needless borrow
  zebra-chain/src/orchard/tests/tree.rs
Labels: A-rust, C-cleanup

#2445 Fix Orchard implementation, refactor, and add more test vectors
  zebra-chain/src/orchard/address.rs
  zebra-chain/src/orchard/arbitrary.rs
  zebra-chain/src/orchard/commitment.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/keys/tests.rs
  zebra-chain/src/orchard/note.rs
  zebra-chain/src/orchard/note/nullifiers.rs
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/orchard/tests.rs
  zebra-chain/src/orchard/tests/tree.rs
  zebra-chain/src/orchard/tests/vectors.rs
  zebra-chain/src/orchard/tests/vectors/group_hash.rs
  zebra-chain/src/orchard/tests/vectors/key_components.rs
  zebra-chain/src/orchard/tests/vectors/sinsemilla.rs
  zebra-chain/src/orchard/tests/vectors/tree.rs
Labels: A-rust

#2503 Pass the finalized state to chain contextual validation
  zebra-state/src/service.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
Labels: A-rust, C-enhancement, P-Medium

#2506 impl iter::Sum<&Amount<C>> for Result<Amount<C>>
  zebra-chain/src/amount.rs
Labels: A-rust, C-enhancement, NU---Sprout, NU-1-Sapling, NU-5, P-Medium

#2502 Add an OrderedUtxo type for transparent spend validation
  zebra-chain/src/transparent.rs
  zebra-chain/src/transparent/utxo.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/script.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/queued_blocks.rs
  zebra-state/src/service/pending_utxos.rs
  zebra-state/src/tests.rs
Labels: A-consensus, A-rust, C-enhancement, NU---Sprout, P-Medium

#2497 Reject duplicate Sapling and Orchard nullifiers
  zebra-state/src/error.rs
  zebra-state/src/service/check/nullifier.rs
  zebra-state/src/service/check/tests/prop.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-consensus, A-rust, C-enhancement, NU-1-Sapling, NU-5, P-Medium

#2504 Rename the nullifier test module
  zebra-state/src/service/check/tests.rs
  zebra-state/src/service/check/tests/nullifier.rs
Labels: A-rust, C-cleanup, P-Medium

#2510 Clarify indexes in `new_ordered_outputs`
  zebra-chain/src/transparent/utxo.rs
Labels: A-rust, C-cleanup, P-Medium

#2511 Reject UTXO double spends
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transparent.rs
  zebra-state/src/error.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/check/tests.rs
  zebra-state/src/service/check/tests/nullifier.rs
  zebra-state/src/service/check/tests/utxo.rs
  zebra-state/src/service/check/utxo.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-consensus, A-rust, C-enhancement, NU---Sprout, P-Medium

#2513 Make nullifier tests faster and consistent with UTXO tests
  zebra-state/src/service/check/tests/nullifier.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/tests.rs
Labels: A-rust, C-cleanup, C-enhancement, NU---Sprout, NU-1-Sapling, NU-5

#2515 rustfmt inside nullifier and utxo proptests
  zebra-state/src/service/check/tests/nullifier.rs
  zebra-state/src/service/check/tests/utxo.rs
Labels: A-rust, C-cleanup

#2533 Update to google-github-actions/setup-gcloud in workflows
  .github/workflows/cd.yml
  .github/workflows/manual-deploy.yml
  .github/workflows/regenerate-stateful-test-disks.yml
  .github/workflows/test.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-github-actions, C-bug, I-integration-fail, P-High

#2542 Disable Rust beta tests in CI, due to a Rust bug
  .github/workflows/ci.yml
Labels: A-github-actions, A-infrastructure, C-bug, I-integration-fail, P-High

#2525 Validate spends of transparent coinbase outputs
  zebra-chain/src/block.rs
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/tests/prop.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transparent.rs
  zebra-chain/src/transparent/utxo.rs
  zebra-consensus/src/transaction/check.rs
  zebra-state/src/constants.rs
  zebra-state/src/error.rs
  zebra-state/src/lib.rs
  zebra-state/src/service.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/check/tests/utxo.rs
  zebra-state/src/service/check/utxo.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/tests/setup.rs
Labels: A-consensus, A-rust, C-enhancement, NU---Sprout, P-Medium

#2458 Track anchors and note commitment trees in zebra-state
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/orchard/shielded_data.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/shielded_data.rs
  zebra-chain/src/sapling/tests/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/sprout/tree.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/joinsplit.rs
  zebra-state/Cargo.toml
  zebra-state/src/constants.rs
  zebra-state/src/error.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/tests.rs
  zebra-state/src/service/finalized_state/tests/prop.rs
  zebra-state/src/service/finalized_state/tests/vectors.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
Labels: A-consensus, A-rust

#2540 Increase coverage for generated chains and proptests
  zebra-chain/src/transaction/arbitrary.rs
  zebra-state/src/constants.rs
  zebra-state/src/service.rs
  zebra-state/src/service/tests.rs
Labels: A-docs, A-rust, C-cleanup, NU-5, P-Low

#2548 Remove unreliable generated chain prevouts tests
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/tests/prop.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
Labels: A-rust, C-bug, I-integration-fail, P-High
