Repository ZcashFoundation/zebra, pull requests merged in 2021-10, with the labels that each got.

#2811 Fix join errors in initial seed peer versions dashboard
  grafana/peers.json
  zebra-network/src/peer/handshake.rs
Labels: C-bug, A-rust, NU-5, P-Medium, A-network

#2817 Fix or disable recent nightly clippy lints
  zebra-chain/src/history_tree.rs
  zebra-chain/src/orchard/commitment.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/primitives/zcash_history.rs
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/keys.rs
  zebra-consensus/src/primitives/groth16/params.rs
  zebra-network/src/peer/connection.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-rust, C-cleanup

#2894 Improve documentation for Beta release
  README.md
  book/src/SUMMARY.md
  book/src/dev/overview.md
  book/src/user/install.md
  book/src/user/requirements.md
  book/src/user/run.md
Labels: P-Medium

#2933 Use `broadcast::Receiver::recv` instead of `next`
  tower-batch/src/worker.rs
Labels: P-Medium
