Repository ZcashFoundation/zebra, pull requests merged in 2021-05, with the labels that each got.

#1965 Async in Zebra RFC
  book/src/dev/rfcs/0011-async-rust-in-zebra.md
Labels: A-docs, C-design, NU-5-TBC, P-Medium

#2111 RFC: add tokio-console/TurboWish prototype
  book/src/dev/rfcs/0011-async-rust-in-zebra.md
Labels: A-docs, C-enhancement, P-Low

#2099 Flesh out redpallas, direct port of redjubjub
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/primitives/redpallas.rs
  zebra-chain/src/primitives/redpallas/constants.rs
  zebra-chain/src/primitives/redpallas/hash.rs
  zebra-chain/src/primitives/redpallas/signature.rs
  zebra-chain/src/primitives/redpallas/signing_key.rs
  zebra-chain/src/primitives/redpallas/tests.rs
  zebra-chain/src/primitives/redpallas/tests/basepoints.rs
  zebra-chain/src/primitives/redpallas/tests/prop.rs
  zebra-chain/src/primitives/redpallas/verification_key.rs
Labels: A-rust, NU-5-TBC

#2118 Update Cargo.lock
  Cargo.lock
Labels: A-dependencies, C-cleanup, P-Low

#2119 Spelling: gossipped -> gossiped
  README.md
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound.rs
  zebrad/src/components/inbound/downloads.rs
Labels: A-docs, C-bug, P-Low

#2100 Validate nConsensusBranchId
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/error.rs
  zebra-consensus/src/transaction/tests.rs
Labels: A-consensus, A-rust, NU-5-TBC, P-Medium

#2126 Make the RFC TOC into a separate step
  CONTRIBUTING.md
Labels: A-docs, C-bug, I-usability, P-Low

#2117 Orchard: disable clippy warnings about comparing a newly created struct
  zebra-chain/src/orchard/keys.rs
Labels: C-bug, I-integration-fail, P-Low

#2138 Explain how to review version bump PRs
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-docs, C-enhancement, P-Medium

#2150 Add a new `zcash_serialize_bytes` utility function
  zebra-chain/src/serialization/zcash_serialize.rs
Labels: A-rust, C-enhancement, NU-5-TBC, P-Medium

#2148 Security: stop panicking on out-of-range version timestamps, Credit: Equilibrium
  zebra-network/src/protocol/external/codec.rs
Labels: A-network, A-rust, C-bug, C-security, I-bad-data, I-panic, P-Medium

#2158 Security: Remove checkout credentials from GitHub actions
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/manual-deploy.yml
  .github/workflows/test.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-github-actions, C-security, P-Medium

#2121 Security: do version checks first, then send a verack response
  zebra-network/src/peer/handshake.rs
Labels: A-network, A-rust, C-bug, C-security, I-bad-data, P-Medium

#2122 Add extra instrumentation for initialize and handshakes
  zebra-network/src/peer/connector.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/initialize.rs
Labels: A-rust, C-bug, I-usability, P-Low

#2149 Security: Avoid silently corrupting invalid times during serialization
  zebra-chain/src/block/serialize.rs
  zebra-chain/src/transaction/lock_time.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
Labels: A-network, A-rust, C-security, I-bad-data, P-Medium

#2155 Security: reject compact sizes greater than the protocol message limit
  zebra-chain/src/block/tests/preallocate.rs
  zebra-chain/src/serialization/read_zcash.rs
  zebra-chain/src/serialization/write_zcash.rs
  zebra-chain/src/work/equihash.rs
Labels: A-network, A-rust, C-security, I-bad-data, P-Medium

#2159 Stop generating V1-V3 transactions for non-finalized state proptests
  zebra-state/proptest-regressions/service/non_finalized_state/tests/prop.txt
  zebra-state/src/service/non_finalized_state/arbitrary.rs
Labels: A-rust, C-bug, I-integration-fail, P-Medium

#2174 Fix some candidate set and meta addr doc links
  zebra-network/src/meta_addr.rs
  zebra-network/src/peer_set/candidate_set.rs
Labels: A-docs, C-bug

#2177 Remove CandidateSet state and add last seen time limit to validate_addrs
  zebra-network/src/peer_set/candidate_set.rs
Labels: A-rust, C-cleanup, P-Medium

#2180 Fix up some doc links
  zebra-chain/src/block/tests/preallocate.rs
  zebra-chain/src/sapling/tests/preallocate.rs
  zebra-chain/src/sprout/tests/preallocate.rs
  zebra-chain/src/transaction/tests/preallocate.rs
  zebra-network/src/protocol/external/tests/preallocate.rs
Labels: A-docs, C-bug, P-Low

#2184 Fix clippy::cmp_owned for (sapling, orchard)::keys with `ConstantTimeEq`
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/sapling/keys.rs
Labels: A-dependencies, A-rust, C-cleanup, C-enhancement, NU-5-TBC, P-Medium

#2186 Remove redundant cmp_owned and comments
  zebra-chain/src/orchard/keys.rs
Labels: A-docs, A-rust, C-cleanup, P-Low

#2179 Derive Arbitrary impls for a bunch of chain and network types
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/header.rs
  zebra-chain/src/serialization.rs
  zebra-chain/src/serialization/arbitrary.rs
  zebra-chain/src/sprout/tree.rs
  zebra-network/Cargo.toml
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/external/types.rs
  zebra-network/src/protocol/internal/request.rs
  zebra-network/src/protocol/internal/response.rs
Labels: A-dependencies, A-rust, C-enhancement, P-Medium

#2194 Clippy nightly: replace a "while let" with a "for" loop
  zebra-test/src/transcript.rs
Labels: A-rust, C-cleanup, P-Low

#2195 Try arbitrary leap seconds
  zebra-chain/src/serialization/arbitrary.rs
Labels: A-rust, C-enhancement, P-Low

#2187 Test Eq/PartialEq for orchard keys
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/keys/tests.rs
Labels: A-rust, C-cleanup, P-Low

#2198 Fix scriptCode serialization and sighash test vectors
  zebra-chain/src/transaction/sighash.rs
  zebra-chain/src/transparent/address.rs
  zebra-chain/src/transparent/script.rs
  zebra-script/src/lib.rs
Labels: A-consensus, A-rust, P-Medium

#2218 Doc: shielded data always contains at least one action
  zebra-chain/src/orchard/shielded_data.rs
Labels: A-docs, C-bug, P-Low

#2208 Make arbitrary block chains pass some genesis checks
  zebra-chain/src/block/arbitrary.rs
  zebra-state/src/service/finalized_state.rs
Labels: A-rust, C-enhancement, NU---Genesis, P-Medium

#2219 Get redpallas tweak proptests working again
  zebra-chain/src/primitives/redpallas/tests/prop.rs
Labels: A-rust, C-cleanup

#2221 Generate test chains that pass basic chain consistency tests
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/tests/preallocate.rs
  zebra-chain/src/block/tests/prop.rs
  zebra-chain/src/transparent/arbitrary.rs
  zebra-chain/src/transparent/prop.rs
  zebra-state/src/service/non_finalized_state/arbitrary.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
Labels: A-rust, C-enhancement, P-Medium

#2222 Minor property test cleanups
  zebra-chain/src/amount.rs
  zebra-chain/src/parameters.rs
  zebra-chain/src/parameters/arbitrary.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transparent/prop.rs
  zebra-state/src/utxo.rs
Labels: A-docs, A-rust, C-cleanup, P-Low

#2223 Fix a log typo: BIP11 -> BIP111
  zebra-network/src/peer/connection.rs
Labels: A-rust, C-bug, P-Low

#2210 Add a DateTime32 type for 32-bit serialized times
  zebra-chain/src/serialization.rs
  zebra-chain/src/serialization/arbitrary.rs
  zebra-chain/src/serialization/date_time.rs
  zebra-network/src/address_book.rs
  zebra-network/src/constants.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/meta_addr/tests/check.rs
  zebra-network/src/meta_addr/tests/vectors.rs
Labels: A-consensus, A-network, A-rust, C-bug, C-cleanup, P-Medium
