Repository ZcashFoundation/zebra, pull requests merged in 2022-08, with the labels that each got.

#4848 fix(test): truncate the number of transactions in send transaction test
  zebra-rpc/src/queue.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: C-bug, P-Critical :ambulance:, I-integration-fail, C-testing, A-rpc, lightwalletd

#4849 fix(test): Skip some RPC tests when ZEBRA_SKIP_NETWORK_TESTS is set
  zebrad/tests/acceptance.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: C-bug, P-Medium :zap:, C-testing, A-rpc, lightwalletd

#3962 Disallow Orchard ivk = 0 on IncomingViewingKey::from & SpendingKey generation
  zebra-chain/src/orchard/address.rs
  zebra-chain/src/orchard/arbitrary.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/keys/tests.rs
Labels: A-rust, NU-5, P-Low :snowflake:

#4867 fix(test): use FuturesOrdered in fallback_verification test
  tower-batch/tests/ed25519.rs
Labels: C-bug, P-Critical :ambulance:, I-integration-fail

#4827 refactor(state): Split the `zebra_state::service::read` module
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/address.rs
  zebra-state/src/service/read/address/balance.rs
  zebra-state/src/service/read/address/tx_id.rs
  zebra-state/src/service/read/address/utxo.rs
  zebra-state/src/service/read/block.rs
  zebra-state/src/service/read/find.rs
  zebra-state/src/service/read/tree.rs
  zebra-state/src/service/read/utxo.rs
Labels: C-cleanup, P-Medium :zap:, A-state

#4869 fix(test): Improve test reliability and performance
  zebra-network/src/peer_set/unready_service.rs
  zebra-network/src/protocol/external/tests/preallocate.rs
  zebrad/tests/acceptance.rs
Labels: C-bug, P-Medium :zap:, I-slow, A-network, C-testing, A-state

#4817 docs(readme): add missing status badges & sections
  README.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, I-usability

#4710 fix(ci): make sure Rust tests actually run in deploy-gcp-tests.yml
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Low :snowflake:, I-integration-fail, C-testing

#4796 change(deps): Enable a `tinyvec` feature to speed up compilation
  Cargo.lock
  tower-batch/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, A-rust, P-Low :snowflake:

#4786 refactor(build): use FHS for deployments and artifacts
  docker/Dockerfile
  docker/zcash-lightwalletd/Dockerfile
  docker/zcash-params/Dockerfile
Labels: A-infrastructure, A-devops, C-enhancement, P-Low :snowflake:, I-usability

#4886 fix(docker): Copy lightwalletd from the correct path during Docker builds
  docker/Dockerfile
  docker/zcash-lightwalletd/Dockerfile
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4890 build(deps): bump vergen from 7.2.1 to 7.3.2
  Cargo.lock
  deny.toml
  zebrad/Cargo.toml
Labels: A-dependencies, P-Low :snowflake:, A-diagnostics

#4919 change(checkpoints): Update block hash checkpoints for mainnet
  zebra-consensus/src/checkpoint/main-checkpoints.txt
Labels: A-consensus, C-enhancement, P-High :fire:, I-slow

#4927 Fix clippy::derive_partial_eq_without_eq in generated gRPC test code
  zebrad/build.rs
Labels: A-rust, C-cleanup, P-Critical :ambulance:, C-testing, lightwalletd, I-build

#4930 change(ci): Disable beta Rust tests and add parameter download logging
  .github/workflows/build-crates-individually.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-integration-os.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  Cargo.toml
Labels: C-bug, A-rust, A-devops, P-Critical :ambulance:, I-slow, I-integration-fail, A-network, C-testing

#4918 fix(tests): Update timeout for Zebra sync tests
  .github/workflows/deploy-gcp-tests.yml
  zebrad/tests/common/launch.rs
  zebrad/tests/common/sync.rs
Labels: C-bug, P-Critical :ambulance:, I-slow, I-integration-fail, C-testing, A-rpc, lightwalletd

#4940 ci(auth): retry `gcloud` authentication if fails
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-delivery.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/delete-gcp-resources.yml
  .github/workflows/deploy-gcp-tests.yml
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: C-bug, A-devops, P-Medium :zap:, I-integration-fail

#4938 Update supported Rust versions in README
  README.md
Labels: A-docs, P-Low :snowflake:, I-usability

#4947 ci(mergify): increase batch sizes
  .github/mergify.yml
Labels: A-devops, P-Critical :ambulance:, I-slow

#4945 fix(ci): Increase CI disk size to 200GB
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-heavy, A-state

#4949 fix(ci): Write cached state images after update syncs, and use the latest image from any commit
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
  book/src/dev/continuous-integration.md
Labels: A-devops, C-enhancement, P-Critical :ambulance:, I-slow, A-state

#4948 change(doc): Increase disk and network requirements for long-term deployment
  README.md
Labels: A-docs, P-Low :snowflake:, A-network, A-state

#4950 fix(ci): Fix a regular expression typo in a full sync job
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#4941 ci(test): run build and test jobs on cargo and clippy config changes
  .github/workflows/build-crates-individually.patch.yml
  .github/workflows/build-crates-individually.yml
  .github/workflows/continous-integration-docker.patch.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/continous-integration-os.patch.yml
  .github/workflows/continous-integration-os.yml
  .github/workflows/coverage.patch.yml
  .github/workflows/coverage.yml
Labels: A-devops, C-enhancement, P-Low :snowflake:

#4961 fix(ci): Increase full sync timeouts for longer syncs
  .github/workflows/deploy-gcp-tests.yml
  zebrad/tests/common/sync.rs
Labels: C-bug, A-rust, A-devops, P-Critical :ambulance:, I-slow, I-integration-fail

#4963 fix(doc): Update disk usage based on recent data
  README.md
Labels: C-bug, A-docs, P-Medium :zap:, A-network, A-state

#4962 fix(ci): Expand cached state disks before running tests
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-heavy, I-integration-fail

#4939 ci(build): deploy long running node instances on release
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-delivery.yml
  book/src/dev/continous-delivery.md
Labels: A-infrastructure, A-devops, C-enhancement, P-Medium :zap:

#4898 build(deps): bump chrono from 0.4.19 to 0.4.20
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/chain_tip/network_chain_tip_height_estimator.rs
  zebra-chain/src/serialization/arbitrary.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/transaction/tests.rs
  zebra-consensus/src/transaction/tests/prop.rs
  zebra-network/Cargo.toml
  zebra-network/src/protocol/external/codec.rs
  zebra-rpc/Cargo.toml
  zebra-state/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, A-rust, P-High :fire:, C-security, I-panic, I-unsound

#4958 fix(ci): Improve Zebra acceptance test diagnostics
  .github/workflows/deploy-gcp-tests.yml
  zebrad/tests/acceptance.rs
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/lightwalletd/wallet_grpc.rs
  zebrad/tests/common/sync.rs
Labels: A-rust, A-devops, P-High :fire:, I-usability, C-testing

#4942 fix(test): Show full Zebra test panic details in CI logs
  Cargo.lock
  zebra-test/Cargo.toml
  zebra-test/src/command.rs
  zebra-test/tests/command.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/sync.rs
Labels: C-bug, A-dependencies, P-Critical :ambulance:, A-diagnostics, C-testing

#4970 ci(deploy): do not run `versioning` job when pushing to `main`
  .github/workflows/continous-delivery.yml
Labels: C-bug, A-infrastructure, A-devops, P-Critical :ambulance:, I-integration-fail

#4972 fix(ci): Update mainnet and testnet checkpoints
  book/src/dev/continuous-integration.md
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-bug, A-consensus, A-devops, P-Critical :ambulance:, I-slow, I-integration-fail

#4973 doc(ci): Document edge cases in sync workflows
  .github/workflows/deploy-gcp-tests.yml
Labels: A-docs, A-devops, C-enhancement, P-High :fire:, C-testing

#4904 fix(network): send height to peers
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer/minimum_peer_version.rs
Labels: C-bug, P-Low :snowflake:, A-network

#4931 Fix clippy::unused_parens
  zebra-state/src/service/check/tests/anchors.rs
Labels: A-rust, C-cleanup, P-Low :snowflake:

#4928 feat(state): Store history trees by height in the non-finalized state
  zebra-chain/src/history_tree.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
Labels: C-enhancement, P-Low :snowflake:, I-slow, A-state

#4804 fix(consensus): Increase the number of blocks checked for legacy transactions
  zebra-state/src/constants.rs
  zebra-state/src/service.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/tests.rs
Labels: C-bug, A-consensus, NU-5, P-Medium :zap:

#4981 ci(concurrency)!: run a single CI workflow as required
  .github/workflows/build-crates-individually.yml
  .github/workflows/continous-delivery.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/continous-integration-os.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/zcash-params.yml
Labels: C-bug, A-infrastructure, A-devops, C-enhancement, P-Critical :ambulance:, I-integration-fail

#4933 Revert: deserialize stored transactions in a rayon thread
  zebra-state/src/service/finalized_state/disk_format/block.rs
Labels: C-bug, P-Medium :zap:, I-slow, A-rpc, lightwalletd

#4957 adds start as default subcommand for zebrad
  zebrad/Cargo.toml
  zebrad/src/application.rs
  zebrad/src/application/entry_point.rs
  zebrad/src/commands.rs
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-enhancement, P-Medium :zap:, I-usability

#5000 fix(ci): Stop cancelling manual full syncs
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#5001 fix(ci): Split a long full sync job
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-slow, I-integration-fail

#5006 v1.0.0-beta.14-release
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/install.md
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-rust, C-enhancement, P-Critical :ambulance:
