Repository ZcashFoundation/zebra, pull requests merged in 2022-03, with the labels that each got.

#3659 feat(build): add arm64 support with cross-compilation
  .github/workflows/cd.yml
  .github/workflows/test.yml
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcash-params.yml
  docker/Dockerfile
Labels: A-devops, P-High :fire:

#3677 feat(codeowners): add code reviewers to the repository
  .github/CODEOWNERS
Labels: A-devops, P-High :fire:

#3628 refactor(test): split lightwalletd test launch into separate methods
  zebrad/tests/acceptance.rs
Labels: C-cleanup, P-Critical :ambulance:, C-testing, A-rpc

#3692 fix(ci): update CI job path triggers
  .github/workflows/ci.patch.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.patch.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.patch.yml
  .github/workflows/test.yml
  .github/workflows/zcash-params.yml
Labels: C-bug, A-devops, P-Low :snowflake:, I-integration-fail

#3700 fix(build): use the correct lightwalletd multistage target
  .github/workflows/zcash-lightwalletd.yml
Labels: A-devops, P-Critical :ambulance:

#3708 fix(review): only assign one reviewer to general Rust reviews
  .github/CODEOWNERS
Labels: C-bug, A-infrastructure, P-High :fire:

#3678 feat(build): add arm64 support with cross-compilation
  .github/workflows/cd.yml
  .github/workflows/test.yml
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcash-params.yml
  docker/Dockerfile
Labels: A-devops, P-Low :snowflake:

#3718 fix(codeowners): avoid multiple reviewer assignments
  .github/CODEOWNERS
Labels: C-bug, A-infrastructure, P-High :fire:

#3705 fix(ci): check for adityapk00/lightwalletd behaviour in test harness
  .github/workflows/ci.yml
  .github/workflows/zcash-lightwalletd.yml
  zebrad/tests/acceptance.rs
Labels: C-bug, P-Critical :ambulance:, I-integration-fail, C-testing, A-rpc

#3719 fix(deps): remove an outdated dependabot ignore rule
  .github/dependabot.yml
Labels: A-dependencies, A-devops, C-cleanup, P-Low :snowflake:

#3728 refactor(build): use OCI Image Format Specification for labels
  .github/workflows/cd.yml
  .github/workflows/test.yml
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcash-params.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-devops, P-Critical :ambulance:

#3685 Implement `sendrawtransaction` RPC
  Cargo.lock
  zebra-rpc/Cargo.toml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebrad/src/commands/start.rs
Labels: A-dependencies, C-enhancement, P-Medium :zap:, A-rpc

#3726 fix(zebrad/ci): skip RPC conflict test when network tests are disabled
  zebrad/tests/acceptance.rs
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, A-rpc

#3738 fix(build): arm64 needs extra time when building from scratch
  .github/workflows/cd.yml
Labels: A-devops, P-Critical :ambulance:, I-integration-fail

#3735 refactor(test): decouple full sync from other tests
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
  .github/workflows/zcash-params.yml
Labels: A-devops, P-High :fire:

#3725 Use a `SerializedBlock` type to help serializing blocks
  Cargo.lock
  zebra-chain/src/block.rs
  zebra-chain/src/block/serialize.rs
  zebra-rpc/Cargo.toml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/vectors.rs
Labels: A-rust, C-enhancement, P-Optional :sparkles:

#3691 1. test(db): add snapshot tests for high-level block and transaction APIs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/block_hashes@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/block_hashes@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/block_hashes@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/block_hashes@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/block_hashes@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/block_hashes@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/blocks@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/blocks@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/blocks@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/blocks@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/blocks@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/blocks@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/tip@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/tip@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/tip@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/tip@no_blocks.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/tip@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/tip@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/tip@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@testnet_2.snap
Labels: P-Medium :zap:, C-testing, A-state

#3744 fix(build, deployment): missing job key and timeout bump for build
  .github/workflows/cd.yml
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
  .github/workflows/zcash-params.yml
Labels: A-devops, P-Critical :ambulance:, I-integration-fail

#3743 doc(ci): explain the different ways .txt files are used
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/test.yml
Labels: C-bug, A-docs, P-Low :snowflake:

#3750 fix(deploy): use correct conditional in job to deploy Mainnet nodes
  .github/workflows/cd.yml
Labels: A-devops, P-Medium :zap:

#3756 fix(test/full-sync): ignore snapshot test file changes
  .github/workflows/test-full-sync.yml
Labels: A-devops, C-cleanup, P-Low :snowflake:, I-slow, C-testing

#3647 Fix typo
  zebra-state/src/service/finalized_state/zebra_db/block.rs
Labels: A-docs, C-cleanup

#3755 fix(zebrad/test): stop excessive logging which causes test hangs
  zebra-chain/src/parameters/network_upgrade.rs
Labels: C-bug, A-rust, P-Critical :ambulance:, I-integration-fail

#3774 fix(ci): revert a test job name change
  .github/workflows/test.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#3758 fix(test/lightwalletd): add an alternative log to the final integration test check
  zebrad/tests/acceptance.rs
Labels: C-bug, P-High :fire:, I-integration-fail, C-testing, A-rpc

#3773 fix(ci): only run the full sync test on mergify queue PRs
  .github/workflows/test-full-sync.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#3775 refactor(ci): use gcloud to search for cached disk state
  .github/workflows/test.yml
Labels: A-devops, P-Critical :ambulance:, I-integration-fail

#3717 2. refactor(db): split the raw disk serialzation format into modules
  .github/workflows/test.yml
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/chain.rs
  zebra-state/src/service/finalized_state/disk_format/shielded.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshot.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
Labels: A-devops, C-cleanup, P-Medium :zap:, A-state

#3765 doc(network): explain optional zebra-network/tor dependencies
  book/src/user/install.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, I-usability

#3767 lint(clippy): warn on manual printing to stdout or stderr
  .cargo/config.toml
  zebra-chain/src/parameters/tests.rs
  zebra-consensus/examples/get-params-path.rs
  zebra-consensus/src/primitives/halo2/tests.rs
  zebra-state/src/service/finalized_state/tests/prop.rs
  zebra-test/src/command.rs
  zebra-test/src/net.rs
  zebra-test/tests/command.rs
  zebra-utils/src/bin/zebra-checkpoints/main.rs
  zebrad/build.rs
  zebrad/src/application.rs
  zebrad/src/commands/generate.rs
  zebrad/src/commands/version.rs
  zebrad/tests/acceptance.rs
Labels: A-devops, C-enhancement, P-Low :snowflake:, I-integration-fail, A-diagnostics

#3706 Refactor `SentTransactionHash` to be a stricter type
  Cargo.lock
  zebra-chain/src/transaction/hash.rs
  zebra-rpc/Cargo.toml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebrad/src/commands/start.rs
Labels: A-rust, C-enhancement, P-Optional :sparkles:, A-rpc

#3791 build(docker): revert supporting arm64
  .github/workflows/cd.yml
  .github/workflows/zcash-params.yml
Labels: A-devops, P-Critical :ambulance:, I-integration-fail

#3777 Enable `checkpoint_sync` by default
  zebra-consensus/src/config.rs
Labels: A-consensus, C-enhancement, P-Medium :zap:, A-state

#3741 3. refactor(db): add disk serialization types for transactions
  book/src/dev/rfcs/0005-state-updates.md
  zebra-state/proptest-regressions/service/check/tests/utxo.txt
  zebra-state/proptest-regressions/service/finalized_state/tests/prop.txt
  zebra-state/proptest-regressions/service/tests.txt
  zebra-state/src/service/finalized_state/arbitrary.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transaction_hashes@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/transactions@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
Labels: A-docs, A-rust, C-enhancement, P-Medium :zap:, A-state

#3806 build(deps): bump actions/checkout from 2.4.0 to 3.0.0
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcash-params.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-dependencies, P-Low :snowflake:

#3812 fix(ci): re-enable manual dispatch for test full sync
  .github/workflows/test-full-sync.yml
Labels: C-bug, A-devops, P-Critical :ambulance:

#3766 refactor(test): cleanup GCP instances on a single PR
  .github/workflows/clean.yml
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
Labels: A-devops, P-Critical :ambulance:, I-integration-fail

#3809 A. fix(shielded): use RwLock for note commitment tree root caches
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/sprout/tree.rs
Labels: A-rust, C-enhancement, P-Medium :zap:

#3759 4. test(db): add large transaction tests
  zebra-chain/benches/block.rs
  zebra-chain/src/block/tests/generate.rs
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/transparent.rs
  zebra-chain/src/transparent/utxo.rs
  zebra-consensus/src/block/tests.rs
  zebra-state/src/arbitrary.rs
  zebra-state/src/request.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/vectors.rs
Labels: P-Medium :zap:, C-testing, A-state

#3794 build(cache): do not use GHA cache for images
  .github/workflows/cd.yml
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcash-params.yml
Labels: A-devops, P-Medium :zap:

#3707 feature(rpc): implement getblock api call
  Cargo.lock
  zebra-chain/src/block.rs
  zebra-chain/src/block/serialize.rs
  zebra-rpc/Cargo.toml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebra-state/src/lib.rs
  zebra-state/src/service.rs
  zebra-state/src/service/tests.rs
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:

#3826 C. Restore `self` ownership in `Chain::push` method
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
Labels: A-rust, C-cleanup, P-Medium :zap:, A-state

#3778 5. refactor(state): split the state service into modules
  zebra-state/src/lib.rs
  zebra-state/src/service.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/block_iter.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/tests.rs
Labels: C-cleanup, P-Medium :zap:, A-state

#3823 fix(ci): change pd-extreme to pd-ssd to avoid quotas
  .github/workflows/test-full-sync.yml
Labels: A-infrastructure, A-devops, P-Low :snowflake:

#3754 feature(rpc): Implement `getbestblockhash` method
  zebra-chain/src/block/hash.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/vectors.rs
Labels: C-enhancement, P-Medium :zap:, A-rpc

#3835 7. feat(state): add a read-only state service stub
  zebra-rpc/Cargo.toml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/tests.rs
  zebra-state/src/tests/setup.rs
  zebra-state/tests/basic.rs
  zebrad/src/commands/copy_state.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
  zebrad/src/components/mempool/tests/vector.rs
Labels: C-enhancement, P-High :fire:, I-slow, A-rpc, A-state

#3846 8. refactor(state): allow shared read access to the finalized state database
  zebra-state/src/service.rs
  zebra-state/src/service/block_iter.rs
  zebra-state/src/service/check/anchors.rs
  zebra-state/src/service/check/nullifier.rs
  zebra-state/src/service/check/utxo.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/arbitrary.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_db/tests.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/finalized_state/zebra_db/arbitrary.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/metrics.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/non_finalized_state.rs
Labels: C-enhancement, P-High :fire:, I-slow, A-state

#3843 doc(db): update database design for read-only state service
  book/src/dev/rfcs/0005-state-updates.md
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
Labels: A-docs, P-Low :snowflake:, I-bad-data, A-state

#3858 change(doc): Link to Conventional Commits specification
  CONTRIBUTING.md
Labels: A-docs, C-enhancement, P-Low :snowflake:

#3818 feat(shielded): Store Sapling & Orchard note commitment trees in finalized and non-finalized state
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshot.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/orchard_trees@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/orchard_trees@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/orchard_trees@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/orchard_trees@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/orchard_trees@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/orchard_trees@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/sapling_trees@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/sapling_trees@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/sapling_trees@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/sapling_trees@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/sapling_trees@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/sapling_trees@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
Labels: C-enhancement, P-Medium :zap:, C-testing, A-state

#3873 fix(ci): path format for cached state rebuild
  .github/workflows/test.yml
Labels: C-bug, A-devops, P-Low :snowflake:

#3863 2a. refactor(rpc): Add the ChainTip and Network to RpcImpl
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebrad/src/commands/start.rs
Labels: C-enhancement, P-High :fire:, A-rpc

#3864 3a. refactor(rpc): use ChainTip for get_best_block_hash
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/service.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/tests.rs
Labels: C-enhancement, P-High :fire:, A-rpc

#3886 fix(ci): remove coverage from mergify because nightly builds fail
  .github/mergify.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#3870 3. fix(state): prevent watch channel deadlocks in the state
  zebra-state/src/service.rs
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/watch_receiver.rs
Labels: C-bug, P-High :fire:, I-hang, A-state, lightwalletd

#3889 feat(consensus): Validate ZIP-212 grace period blocks using checkpoints
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/tests.rs
  zebra-chain/src/parameters/network/tests/prop.rs
Labels: C-bug, A-consensus, P-High :fire:, I-consensus 💥

#3865 4. feat(state): support Request::Transaction in ReadStateService
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read.rs
Labels: C-enhancement, P-High :fire:, A-state, lightwalletd

#3866 5. change(state): split ReadStateService requests into a ReadRequest enum
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/tests.rs
  zebra-state/src/service/read/tests/vectors.rs
  zebra-state/src/service/tests.rs
  zebra-state/tests/basic.rs
  zebra-test/src/transcript.rs
Labels: C-enhancement, P-High :fire:, A-rpc, A-state, lightwalletd

#3854 fix(sync): prevent synchronizer loop when very close to tip
  zebrad/src/components/sync.rs
Labels: C-bug, P-Medium :zap:, I-slow, A-network

#3859 change(test): Print lightwalletd output during integration test
  .github/workflows/test.yml
Labels: A-devops, P-Low :snowflake:, A-diagnostics, C-testing, lightwalletd

#3885 refactor(ci): use improved OIDC for gcloud authentication
  .github/workflows/cd.yml
  .github/workflows/clean.yml
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcash-params.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-infrastructure, A-devops, P-Medium :zap:

#3914 fix(rpc): Update lightwalletd integration test for getblockchaininfo RPC
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:, C-testing, A-rpc, lightwalletd

#3916 change(doc): Simplify the database design using prefix iterators
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-design, P-Low :snowflake:, A-state, lightwalletd

#3929 fix(actions): use a specific shortening length for SHAs
  .github/workflows/cd.yml
  .github/workflows/clean.yml
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcash-params.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-devops, P-Critical :ambulance:, I-integration-fail

#3874 7. change(db): Use smaller keys for height and transaction indexes
  zebra-state/proptest-regressions/service/finalized_state/disk_format/tests/prop.txt
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_by_height_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_by_height_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_by_height_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_by_height_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_by_height_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_by_height_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/hash_by_height_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/hash_by_height_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/hash_by_height_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/hash_by_height_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/hash_by_height_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/hash_by_height_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/height_by_hash_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/height_by_hash_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/height_by_hash_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/height_by_hash_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/height_by_hash_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/height_by_hash_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_by_hash_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_by_hash_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_by_hash_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_by_hash_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
Labels: C-enhancement, P-Medium :zap:, I-slow, A-state, lightwalletd

#3892 T1. add(test): add test API that checks logs for multiple regexes
  zebra-test/src/command.rs
  zebra-test/src/command/to_regex.rs
Labels: C-enhancement, P-Medium :zap:, C-testing, lightwalletd

#3899 T2. add(test): add test API that checks process logs for failures
  zebra-test/src/command.rs
  zebra-test/tests/command.rs
  zebrad/tests/common/sync.rs
Labels: C-enhancement, P-Medium :zap:, C-testing, lightwalletd

#3877 Fix typo
  CONTRIBUTING.md
Labels: do-not-merge

#3942 fix(docs): update running zebra link in readme
  README.md
Labels: C-bug, A-docs, P-Low :snowflake:

#3908 feat(rpc): add getrawtransaction
  Cargo.lock
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-rpc/Cargo.toml
  zebra-rpc/src/lib.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/tests.rs
  zebra-rpc/src/tests/vectors.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/tests/vectors.rs
Labels: P-Medium :zap:, lightwalletd

#3957 fix(ci): fix syntax in some yml workflows
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcash-params.yml
Labels: P-High :fire:

#3961 fix(rpc): ignore an expected error in the RPC acceptance tests
  zebra-test/src/command.rs
  zebra-test/tests/command.rs
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:, C-testing, A-rpc

#3891 feat(rpc): Implement `getblockchaininfo` RPC method
  Cargo.lock
  zebra-chain/src/chain_tip.rs
  zebra-chain/src/chain_tip/mock.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/parameters/tests.rs
  zebra-rpc/Cargo.toml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-state/src/service/chain_tip.rs
  zebra-test/src/command.rs
  zebra-test/tests/command.rs
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:, A-rpc, A-state, lightwalletd

#3944 fix(log): Make sync error logs more user-friendly
  zebrad/src/components/sync.rs
Labels: C-bug, P-Low :snowflake:, I-usability, A-diagnostics

#3970 Update test.patch.yml with lightwalletd job
  .github/workflows/test.patch.yml
Labels: A-devops, C-cleanup, P-Critical :ambulance:

#3964 fix(doc): Fix bugs in the lightwalletd database design
  book/src/dev/rfcs/0005-state-updates.md
Labels: C-bug, A-docs, P-Medium :zap:, lightwalletd

#3949 Repoint zebra image links to our new zfnd.org site for now
  README.md
  zebra-chain/src/lib.rs
  zebra-client/src/lib.rs
  zebra-consensus/src/lib.rs
  zebra-network/src/lib.rs
  zebra-rpc/src/lib.rs
  zebra-script/src/lib.rs
  zebra-state/src/lib.rs
  zebra-test/src/lib.rs
  zebra-utils/src/lib.rs
  zebrad/src/lib.rs
Labels: A-docs, C-cleanup, P-Low :snowflake:

#3956 Fix typos
  zebra-state/src/service/watch_receiver.rs
  zebrad/src/components/sync.rs
Labels: C-cleanup, P-Low :snowflake:

#4000 fix(build): Stop using a test-only method in production code
  Cargo.lock
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint.rs
  zebra-rpc/Cargo.toml
  zebra-state/Cargo.toml
  zebrad/Cargo.toml
Labels: C-bug, A-dependencies, A-rust, P-High :fire:

#3998 Add a job to ci.yml that does `cargo install --locked --path ./zebrad/ zebrad`
  .github/workflows/ci.patch.yml
  .github/workflows/ci.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail

#3997 fix(design): update state RFC to put ordered list values in RocksDB keys
  book/src/dev/rfcs/0005-state-updates.md
Labels: C-bug, A-docs, P-High :fire:, A-state, lightwalletd

#4004 build(deps): bump serde-big-array from 0.3.2 to 0.4.1
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/lib.rs
  zebra-chain/src/orchard/note/ciphertexts.rs
  zebra-chain/src/primitives/proofs/bctv14.rs
  zebra-chain/src/primitives/proofs/groth16.rs
  zebra-chain/src/primitives/zcash_history.rs
  zebra-chain/src/sapling/note/ciphertexts.rs
  zebra-chain/src/serialization/serde_helpers.rs
  zebra-chain/src/sprout/note/ciphertexts.rs
  zebra-chain/src/work/equihash.rs
Labels: A-dependencies, A-rust, C-cleanup, P-Low :snowflake:

#3996 imp(ci): do not invalidate cache between PRs
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
Labels: A-devops, C-enhancement, P-Low :snowflake:

#4016 fix(state): Stop panicking when a state block commit fails
  zebra-state/src/service.rs
Labels: C-bug, P-Low :snowflake:, I-panic, A-diagnostics, A-state
