Repository ZcashFoundation/zebra, pull requests merged in 2022-01, with the labels that each got.

#3314 Fix typos
  zebra-consensus/src/block/subsidy/funding_streams.rs
  zebra-consensus/src/parameters/subsidy.rs
  zebra-consensus/src/primitives/groth16/params.rs
  zebra-state/src/service/pending_utxos.rs
  zebrad/src/commands/download.rs
Labels: A-docs, P-Low

#3293 1. Fix some address crawler timing issues
  zebra-network/src/address_book.rs
  zebra-network/src/address_book_updater.rs
  zebra-network/src/constants.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/internal/response.rs
Labels: P-High, C-security, I-hang, I-slow, I-integration-fail, I-bad-data, A-network, A-diagnostics

#3294 2. Cache unsolicited address messages, and use them as responses
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests/vectors.rs
  zebra-network/src/peer/handshake.rs
Labels: P-High, C-security, I-hang, I-slow, I-integration-fail, I-bad-data, A-network

#3292 Stop ignoring some peers when updating the address book
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/meta_addr/tests/vectors.rs
  zebra-network/src/peer_set/initialize.rs
Labels: C-bug, P-High, C-security, I-hang, I-slow, I-integration-fail, A-network

#3295 3. Cleanup internal network request handler, fix unused request logging
  zebra-network/src/peer/connection.rs
Labels: C-cleanup, :zap: P-Medium, A-network, A-diagnostics

#3324 Add mergify merging queues
  .github/mergify.yml
Labels: A-github-actions, C-enhancement, :fire: P-High

#3168 Fix syncer download order and add sync tests
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/chain_tip.rs
  zebra-chain/src/chain_tip/mock.rs
  zebra-network/src/peer/minimum_peer_version/tests.rs
  zebra-network/src/policies.rs
  zebra-test/src/mock_service.rs
  zebrad/Cargo.toml
  zebrad/src/commands/start.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/downloads.rs
  zebrad/src/components/sync/tests.rs
  zebrad/src/components/sync/tests/vectors.rs
Labels: C-bug, A-dependencies, :zap: P-Medium, I-slow, A-network, A-diagnostics, C-testing

#3325 Cancel heartbeats that are waiting for a peer, rather than hanging Zebra
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/initialize.rs
Labels: C-bug, P-High :fire:, C-security, I-hang, I-slow, A-network

#3316 Update Zebra's allowed duplicate dependencies
  deny.toml
Labels: A-dependencies, C-cleanup, P-Low :snowflake:

#3341 Use the correct conditions and merge method in Mergify
  .github/dependabot.yml
  .github/mergify.yml
Labels: A-devops, P-Critical :ambulance:

#3333 Upgrade to latest redjubjub commit, hasn't been published to crates.io yet
  Cargo.lock
  zebra-chain/Cargo.toml
Labels: P-Medium :zap:

#3319 Document the consensus rules for Sec. 3.8 Note Commitment Trees
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/sprout/tree.rs
Labels: A-docs, P-Low :snowflake:

#3337 Replace `tempdir` dependency with `tempfile`
  Cargo.lock
  deny.toml
  zebra-state/Cargo.toml
  zebra-state/src/config.rs
  zebra-test/Cargo.toml
  zebra-test/tests/command.rs
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
Labels: A-dependencies, P-Low :snowflake:

#3302 T1. Fix isolated connection bugs, improve tests, upgrade dependencies
  Cargo.lock
  deny.toml
  zebra-network/src/isolated.rs
  zebra-network/src/isolated/tests.rs
  zebra-network/src/isolated/tests/vectors.rs
  zebra-network/src/lib.rs
  zebra-network/src/peer/connector.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
Labels: C-bug, A-dependencies, C-enhancement, C-cleanup, P-Medium :zap:, A-network, C-testing

#3283 Fix interstitial sprout anchors check
  .github/workflows/test.yml
  book/src/dev/rfcs/0005-state-updates.md
  zebra-state/src/constants.rs
  zebra-state/src/service/check/anchors.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
Labels: A-consensus, NU-5, P-Medium :zap:

#3374 Ignore unexpected block responses to fix error cascade when synchronizing blocks
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests.rs
  zebra-network/src/peer/connection/tests/prop.rs
  zebra-network/src/peer/connection/tests/vectors.rs
  zebra-network/src/protocol/internal/response.rs
  zebra-test/src/mock_service.rs
Labels: C-bug, P-Medium :zap:, I-slow, A-network

#3317 Document the structure of the `zebra-network` crate
  zebra-network/src/lib.rs
  zebrad/src/commands/start.rs
Labels: A-docs, C-enhancement, P-Low :snowflake:, A-network

#3387 Make the zcash_script versions match in Cargo.lock and Cargo.toml
  Cargo.lock
Labels: C-bug, A-dependencies, P-Low :snowflake:

#3386 Consolidate standard lints into a cargo config file
  .cargo/config.toml
  .gitignore
  tower-batch/src/lib.rs
  tower-batch/tests/ed25519.rs
  tower-batch/tests/worker.rs
  tower-fallback/src/lib.rs
  tower-fallback/tests/fallback.rs
  zebra-chain/benches/block.rs
  zebra-chain/benches/redpallas.rs
  zebra-chain/build.rs
  zebra-chain/src/lib.rs
  zebra-client/src/lib.rs
  zebra-consensus/src/lib.rs
  zebra-network/src/lib.rs
  zebra-rpc/src/lib.rs
  zebra-script/src/lib.rs
  zebra-state/build.rs
  zebra-state/src/lib.rs
  zebra-state/tests/basic.rs
  zebra-test/src/lib.rs
  zebra-test/src/service_extensions.rs
  zebra-test/tests/command.rs
  zebra-test/tests/transcript.rs
  zebra-utils/src/bin/zebra-checkpoints/main.rs
  zebra-utils/src/lib.rs
  zebrad/build.rs
  zebrad/src/bin/zebrad/main.rs
  zebrad/src/lib.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-cleanup, P-Low :snowflake:, A-diagnostics

#3385 Make the Zebra state RFC match the lightwalletd draft design
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, P-Low :snowflake:

#3338 Document the consensus rules for Section 3.6
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-consensus/src/transaction.rs
Labels: A-docs, P-Low :snowflake:

#3303 T2. Add isolated Tor connection API, but don't enable it by default
  Cargo.lock
  deny.toml
  zebra-network/Cargo.toml
  zebra-network/src/config.rs
  zebra-network/src/isolated.rs
  zebra-network/src/isolated/tests/vectors.rs
  zebra-network/src/isolated/tor.rs
  zebra-network/src/isolated/tor/tests.rs
  zebra-network/src/isolated/tor/tests/vectors.rs
  zebra-network/src/lib.rs
  zebra-network/src/peer/connector.rs
  zebra-network/src/peer/handshake.rs
  zebra-test/src/lib.rs
Labels: A-dependencies, C-enhancement, C-security, I-privacy, P-Optional :sparkles:, A-network

#3377 Improve GitHub Actions for faster checks and better readability
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: A-devops, P-High :fire:

#3405 fix (actions): add duplicated workflows with path-ignore
  .github/workflows/ci.patch.yml
  .github/workflows/coverage.patch.yml
  .github/workflows/docs.patch.yml
  .github/workflows/lint.patch.yml
  .github/workflows/test.patch.yml
Labels: A-devops, P-Critical :ambulance:

#3404 fix (zebra-chain): make test and bench targets build using 2021 edition
  zebra-chain/Cargo.toml
Labels: C-bug, A-dependencies, P-Medium :zap:, I-integration-fail

#3399 fix: improve file and directories to be ignored by git and Docker
  .gitignore
  docker/.dockerignore
Labels: A-devops, P-Medium :zap:

#3406 fix(mergify): use low-priority queue for the correct jobs
  .github/mergify.yml
Labels: C-bug, A-devops, P-Low :snowflake:, I-usability

#3392 Security: Stop RocksDB or tokio calling unexpected code when zebrad exits
  zebra-state/src/service/finalized_state.rs
  zebra-test/scripts/shutdown-errors
  zebrad/src/components/tokio.rs
Labels: P-Medium :zap:

#3412 Bump cd workflow timeout to 60 mins
  .github/workflows/cd.yml
Labels: A-infrastructure, A-devops, P-High :fire:

#3408 refactor: Simplify coinbase expiry code so the consensus rule is clear
  zebra-chain/src/transaction/lock_time.rs
  zebra-consensus/src/transaction/check.rs
Labels: A-consensus, A-rust, C-cleanup, NU-5, P-Low :snowflake:

#3403 Release v1.0.0 beta.4
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/install.md
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: P-Critical :ambulance:

#3393 refactor (actions): make better use of variables, secrets and versions
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/manual-deploy.yml
  .github/workflows/regenerate-stateful-test-disks.yml
  .github/workflows/test.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-devops, P-High :fire:

#3409 lint: add extra integer lints, and partially fix some code
  .cargo/config.toml
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/height.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/work/difficulty.rs
  zebra-chain/src/work/u256.rs
  zebra-state/src/service.rs
Labels: A-consensus, C-enhancement, P-Optional :sparkles:, A-network, I-bad-code, A-diagnostics

#3417 fix(network): Add a send timeout to outbound peer messages
  zebra-network/src/constants.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/peer_tx.rs
  zebra-network/src/peer/connection/tests.rs
  zebra-network/src/peer/connection/tests/prop.rs
  zebra-network/src/peer/connection/tests/vectors.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/handshake.rs
Labels: P-Medium :zap:, C-security, I-hang, I-slow, A-network
