Repository ZcashFoundation/zebra, pull requests merged in 2022-05, with the labels that each got.

#4219 test(rpc): Add a script for comparing zcashd and zebrad RPC responses
  zebra-utils/README.md
  zebra-utils/zcash-rpc-diff
Labels: P-Medium :zap:, C-testing, A-rpc, lightwalletd

#4255 fix(ci): garbage collect instances no matter previous steps status
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
Labels: A-consensus, A-infrastructure, A-devops, C-enhancement, P-High :fire:, lightwalletd

#4252 refactor(ci): use docker instead of Konlet for GCP deployments in CI
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
Labels: C-bug, A-infrastructure, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4218 change(rpc): Simplify RPC types and add documentation
  zebra-chain/Cargo.toml
  zebra-chain/src/transparent/address.rs
  zebra-chain/src/transparent/script.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-state/src/lib.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
Labels: A-docs, C-cleanup, P-Medium :zap:, A-rpc, lightwalletd

#4276 fix(ci): use debian for faster mounting and bump readiness time
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4277 fix(ci): typo causing docker run command to split
  .github/workflows/test-full-sync.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4279 feat(ci): clarify lint workflow names
  .github/workflows/lint.patch.yml
  .github/workflows/lint.yml
Labels: A-infrastructure, A-devops, P-Low :snowflake:

#4286 fix(sync): fix testnet syncer loop on large Orchard blocks
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/downloads.rs
Labels: C-bug, NU-5, P-High :fire:, I-hang, I-heavy

#4271 feat(ci)!: add a reusable workflow for deployable integration tests
  .github/workflows/gcp-test-deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test-full-sync.yml
  .github/workflows/test.patch.yml
  .github/workflows/test.yml
  docker/entrypoint.sh
Labels: C-design, A-infrastructure, A-devops, C-enhancement, P-Critical :ambulance:, I-usability, lightwalletd

#4156 Increase block validation timeouts
  zebra-consensus/src/transaction.rs
  zebrad/src/components/sync.rs
Labels: C-bug, NU-5, P-High :fire:, I-hang, I-slow

#4302 change(test): Stop requiring cached lightwalletd state for the send transaction test
  zebrad/tests/acceptance.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
Labels: A-rust, A-devops, P-High :fire:, C-testing, A-rpc, lightwalletd

#4301 refactor(test): fix confusing environmental variable names in Rust code
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/lightwalletd.rs
Labels: C-bug, A-rust, P-Low :snowflake:, I-usability, C-testing

#4308 fix(test): make the full sync tests cache state at `/zebrad-cache`
  zebrad/tests/acceptance.rs
Labels: C-bug, A-rust, P-High :fire:, I-integration-fail, C-testing, lightwalletd

#4223 feat(ci): add `fully_synced_rpc_test` test to CI
  .github/workflows/gcp-test-deploy.yml
  .github/workflows/test.yml
  docker/Dockerfile
  docker/entrypoint.sh
Labels: A-infrastructure, A-devops, C-enhancement, P-High :fire:, lightwalletd

#4311 refactor(lint): check specific files for each job
  .github/workflows/lint.patch.yml
  .github/workflows/lint.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, I-usability, lightwalletd

#4314 fix(ci): add cached state version to disk images
  .github/workflows/gcp-test-deploy.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4317 fix(lint): stop actionlint from failing in main
  .github/workflows/lint.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4313 fix(ci): run sync tests according to the right conditions
  .github/workflows/test.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4332 fix(ci): only update cached states when needed
  .github/workflows/test.yml
Labels: C-bug, A-devops, P-High :fire:, I-slow, C-testing, lightwalletd

#4331 change(deps): update locked version of indirect dependency `crossbeam-channel` to `0.5.4`
  Cargo.lock
Labels: A-dependencies, C-security, P-Optional :sparkles:

#4333 fix(ci): skip tests when doing a manual full sync
  .github/workflows/test.yml
Labels: C-bug, A-devops, P-Medium :zap:, I-slow, C-testing

#4289 feat(util): add a `zebra-tip-height` utility
  zebra-chain/Cargo.toml
  zebra-chain/src/parameters/network.rs
  zebra-utils/src/bin/zebra-checkpoints/main.rs
  zebra-utils/src/lib.rs
  zebrad/src/application.rs
  zebrad/src/commands.rs
  zebrad/src/commands/tip_height.rs
Labels: A-devops, C-enhancement, P-Optional :sparkles:

#4330 change(doc): add transaction index diagram to RFC-0005
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, A-state, lightwalletd

#4267 feat(ci): add `sending_transactions_using_lightwalletd` test to CI
  .github/workflows/gcp-test-deploy.yml
  .github/workflows/test.yml
  docker/entrypoint.sh
  zebrad/tests/acceptance.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/lightwalletd/wallet_grpc.rs
Labels: A-devops, C-enhancement, P-High :fire:, I-usability, lightwalletd

#4342 Fix incorrect AddressBalance name in diagram
  book/src/dev/rfcs/0005-state-updates.md
Labels: C-bug, A-docs, P-Low :snowflake:, A-state, lightwalletd

#4349 v1.0.0-beta.9 release
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/install.md
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-rust, P-High :fire:

#3941 refactor(actions): rename workflow files
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-delivery.yml
  .github/workflows/continous-integration-docker.patch.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/continous-integration-os.patch.yml
  .github/workflows/continous-integration-os.yml
  .github/workflows/deploy-gcp-tests.yml
  .github/workflows/zcash-params.yml
Labels: A-devops, C-enhancement, C-cleanup, P-Medium :zap:

#4359 fix(doc): add support for Mermaid to render graphs
  .github/workflows/docs.yml
  book/book.toml
  book/mermaid-init.js
  book/mermaid.min.js
Labels: A-docs, P-Low :snowflake:

#4364 fix(ci): wrong file being referenced by CI
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4353 cleanup(clippy): Remove redundant bindings, allocations, and generics
  tower-batch/tests/ed25519.rs
  zebrad/src/application.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/tests/vector.rs
Labels: A-rust, C-cleanup, P-Low :snowflake:

#4365 doc(readme): add "old state directories aren't deleted" to known issues
  README.md
Labels: C-bug, A-docs, P-Low :snowflake:, I-usability

#4298 refactor(build): deprecate gcr.io as a registry and build faster
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/zcash-params.yml
  docker/Dockerfile
  docker/zcash-params/Dockerfile
Labels: C-bug, A-infrastructure, A-devops, C-enhancement, P-Critical :ambulance:, lightwalletd

#4370 fix(ci): allow builds over 1 hour and tests without the sentry feature
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-integration-docker.yml
  docker/entrypoint.sh
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4372 fix(deps): drop sentry dependencies when enable-sentry feature is disabled
  zebrad/Cargo.toml
  zebrad/src/components/tracing/component.rs
  zebrad/src/lib.rs
Labels: C-bug, A-dependencies, A-rust, A-devops, P-Medium :zap:

#4287 change(log): Add block hash and height to syncer errors
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/downloads.rs
Labels: C-enhancement, NU-5, P-Low :snowflake:, I-usability, A-diagnostics

#4369 fix(build): put gRPC tests behind an optional feature flag to fix production build issues
  .github/workflows/continous-integration-docker.yml
  .github/workflows/continous-integration-os.yml
  book/src/user/requirements.md
  docker/Dockerfile
  docker/entrypoint.sh
  docker/zcash-params/Dockerfile
  zebrad/Cargo.toml
  zebrad/build.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/sync.rs
Labels: C-bug, A-dependencies, A-rust, A-devops, P-High :fire:, lightwalletd, I-build

#4356 fix(state): return non-finalized UTXOs and tx IDs in address queries
  zebra-rpc/src/methods.rs
  zebra-state/src/service/read.rs
  zebra-utils/README.md
  zebra-utils/zcash-rpc-diff
Labels: C-bug, P-Medium :zap:, I-bad-data, A-diagnostics, A-state, lightwalletd

#4375 fix(ci): make test selection and logging consistent
  .github/workflows/continous-integration-docker.yml
  .github/workflows/continous-integration-os.yml
  docker/Dockerfile
  docker/entrypoint.sh
Labels: A-devops, C-cleanup, P-Medium :zap:, I-usability, A-diagnostics, C-testing, lightwalletd

#4387 Limit output length in some tests
  zebra-test/tests/command.rs
Labels: C-bug, A-rust, A-devops, P-Critical :ambulance:, I-integration-fail, C-testing

#3990 feat(rpc): Implement `z_gettreestate` RPC
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/block.rs
  zebra-chain/src/block/header.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-rpc/src/methods.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read.rs
Labels: A-dependencies, C-enhancement, P-Medium :zap:, A-rpc, A-state, lightwalletd

#4384 fix(rpc): fixes for RPC snapshot tests
  deny.toml
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_address_utxos@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@testnet_10.snap
Labels: A-dependencies, P-Medium :zap:, C-testing, A-rpc, lightwalletd

#4391 0. fix(ci): only use cached state disks with the same state version
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, A-state, lightwalletd

#4268 feat(ci): add `lightwalletd_full_sync` test to CI
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
  .github/workflows/zcash-lightwalletd.yml
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
Labels: A-devops, P-High :fire:, C-testing, lightwalletd

#4269 feat(ci): add `lightwalletd_update_sync` test to CI
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
  docker/entrypoint.sh
Labels: A-devops, C-enhancement, P-High :fire:, I-usability, lightwalletd

#4303 change(test): Require cached lightwalletd state for the send transaction tests
  .github/workflows/continous-integration-docker.yml
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: P-Medium :zap:, I-slow, C-testing, A-rpc, lightwalletd

#4352 tests(rpc): add snapshot tests for rpc methods responses
  Cargo.lock
  deny.toml
  zebra-rpc/Cargo.toml
  zebra-rpc/src/methods/tests.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_address_balance@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_balance@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_utxos@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_utxos@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_best_block_hash@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_best_block_hash@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_info@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_info@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_raw_mempool@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_raw_mempool@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_raw_transaction@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_raw_transaction@testnet_10.snap
Labels: P-Medium :zap:, C-testing, A-rpc, lightwalletd

#4398 Use the latest lightwalletd version
  .github/workflows/zcash-lightwalletd.yml
Labels: A-dependencies, A-devops, P-Critical :ambulance:, I-hang, I-integration-fail, C-testing, A-rpc, lightwalletd

#4397 Fix typos
  .github/workflows/build-docker-image.yml
  .github/workflows/deploy-gcp-tests.yml
  docker/Dockerfile
Labels: A-docs, C-cleanup, P-Low :snowflake:

#4409 change(ci): list cached state files before or after tests
  docker/entrypoint.sh
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-testing, A-state, lightwalletd

#4411 fix(ci): fix errors in Docker entrypoint changes
  docker/entrypoint.sh
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-testing

#4416 fix(ci): stop failing the send transaction test
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, C-testing, A-state, lightwalletd

#4390 change: set NU5 mainnet activation height and current network protocol version
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-network/src/constants.rs
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@mainnet_10.snap
Labels: A-consensus, A-rust, NU-5, P-High :fire:, A-network

#4428 fix(ci): update Cargo.lock check job name in patch workflow
  .github/workflows/continous-integration-os.patch.yml
  .github/workflows/continous-integration-os.yml
Labels: C-bug, A-devops, P-Medium :zap:

#4437 change: document known getaddresstxids RPC bug
  CHANGELOG.md
  README.md
Labels: C-bug, A-docs, P-High :fire:, I-usability, lightwalletd

#4385 1. fix(ci): rebuild cached state before running cached state tests
  .github/workflows/continous-integration-docker.patch.yml
  .github/workflows/continous-integration-docker.yml
Labels: A-devops, P-High :fire:, I-slow, C-testing, A-state, lightwalletd

#4435 change: fail early when using Rust 1.57 and earlier, because they don't work
  README.md
  zebrad/Cargo.toml
Labels: A-docs, A-dependencies, A-rust, A-infrastructure, P-High :fire:

#4392 3. Require network names in cached state disk names
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Medium :zap:, A-state

#4355 2. fix(state): index spending transaction IDs for each address
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/chain/index.rs
Labels: C-bug, P-High :fire:, I-bad-data, A-state, lightwalletd

#4458 fix(doc): Resolve the `getaddresstxids` issue in the README
  README.md
Labels: A-docs, C-cleanup, P-Medium :zap:, lightwalletd

#4455 feat(rpc): Add `z_gettreestate` gRPC tests
  zebra-test/src/vectors/block.rs
  zebra-test/src/vectors/sapling-treestate-main-0-419-201.txt
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
Labels: P-High :fire:, C-testing, lightwalletd

#4466 fix(ci): Make reusable workflow job names match patch job names
  .github/workflows/continous-integration-docker.patch.yml
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-High :fire:, lightwalletd

#4457 fix(ci): Temporarily finish full sync at 99%
  .github/workflows/continous-integration-docker.yml
  zebrad/tests/common/sync.rs
Labels: C-bug, A-rust, A-devops, P-Critical :ambulance:, I-slow, I-integration-fail, C-testing, lightwalletd

#4472 fix(ci): Increase clippy timeout
  .github/workflows/lint.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#4477 fix(ci): set a network env variable to be used in `get-available-disks`
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4483 fix(ci): Temporarily stop full sync at 97%, but send transactions at 100%
  zebrad/tests/acceptance.rs
  zebrad/tests/common/sync.rs
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4486 fix(ci): mount the lwd-cache dir to the `lightwalletd-full-sync`
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#4487 fix(ci): Require cached state for the send transactions test
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: A-devops, P-Medium :zap:, I-slow, C-testing, lightwalletd

#4473 fix(clippy): resolve various clippy warnings
  zebra-chain/src/block/error.rs
  zebra-chain/src/orchard/commitment.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/sprout/commitment.rs
  zebra-chain/src/sprout/tree.rs
  zebra-network/src/peer/handshake.rs
  zebrad/tests/acceptance.rs
Labels: A-rust, C-cleanup, P-Low :snowflake:

#4496 fix(ci): Always run patch jobs that depend on cached cloud disks
  .github/workflows/continous-integration-docker.patch-always.yml
  .github/workflows/continous-integration-docker.patch.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, C-testing, lightwalletd

#4482 feat(ci): add a codespell linting action
  .codespellrc
  .github/workflows/lint.yml
Labels: A-devops, C-enhancement, P-Optional :sparkles:

#4465 change(ci): run coverage on stable
  .github/workflows/coverage.patch.yml
  .github/workflows/coverage.yml
Labels: A-rust, A-infrastructure, A-devops, P-Low :snowflake:

#4504 fix(ci): Permanently fix unreliable sync finished log regex
  zebrad/tests/common/sync.rs
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-testing, lightwalletd

#4469 refactor(ci): allow more time for tests to end gracefully
  .github/workflows/deploy-gcp-tests.yml
Labels: A-devops, C-enhancement, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4453 CI(rpc): Add grpc tests to CI
  .github/workflows/continous-integration-docker.yml
  docker/entrypoint.sh
Labels: A-devops, P-Medium :zap:, C-testing, A-rpc, lightwalletd

#4501 change(sync): Activate the mempool after 2 syncer runs at the chain tip, rather than 4
  zebrad/src/components/sync/recent_sync_lengths.rs
Labels: C-enhancement, P-High :fire:, I-integration-fail, I-usability, lightwalletd

#4518 fix(ci): Add lightwalletd gRPC, clippy, rustfmt patch jobs
  .github/workflows/continous-integration-docker.patch-always.yml
  .github/workflows/continous-integration-docker.patch.yml
  .github/workflows/lint.patch.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, lightwalletd

#4511 feat(rpc): add support for verbosity=1 in getblock
  zebra-chain/src/block/serialize.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/tests/vectors.rs
Labels: C-enhancement, P-Medium :zap:, A-rpc, lightwalletd

#4515 feat(log): Log the tracing level when it is set or reloaded
  Cargo.lock
  zebrad/Cargo.toml
  zebrad/src/components/tracing/component.rs
Labels: A-dependencies, A-rust, C-enhancement, P-Medium :zap:, A-diagnostics, lightwalletd

#4516 change(build): Disable debug logging at compile time in release builds
  zebrad/Cargo.toml
Labels: A-dependencies, A-rust, C-enhancement, P-High :fire:, I-slow, lightwalletd

#4494 fix(doc): Fix the syntax of links in comments
  zebra-chain/src/block.rs
  zebra-chain/src/block/header.rs
  zebra-chain/src/orchard/commitment.rs
  zebra-chain/src/orchard/note.rs
  zebra-chain/src/orchard/shielded_data.rs
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/orchard/tests/vectors/key_components.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/primitives/redpallas/signing_key.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/commitment/pedersen_hashes.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/note/nullifiers.rs
  zebra-chain/src/sapling/output.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/sprout/address.rs
  zebra-chain/src/sprout/commitment.rs
  zebra-chain/src/sprout/joinsplit.rs
  zebra-chain/src/sprout/keys.rs
  zebra-chain/src/sprout/note.rs
  zebra-chain/src/sprout/note/nullifiers.rs
  zebra-chain/src/sprout/tree.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/joinsplit.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-chain/src/transparent/address.rs
  zebra-chain/src/work/difficulty/tests/vectors.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/subsidy/funding_streams.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/check.rs
  zebra-network/src/constants.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/policies.rs
  zebra-network/src/protocol/external/addr/v2.rs
  zebra-rpc/src/methods.rs
  zebra-state/src/request.rs
  zebra-state/src/service/check/nullifier.rs
  zebra-state/src/service/check/utxo.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-test/src/vectors.rs
  zebra-test/src/zip0244.rs
  zebrad/src/application.rs
  zebrad/tests/common/mod.rs
Labels: A-docs, P-High :fire:
