Repository ZcashFoundation/zebra, pull requests merged in 2022-04, with the labels that each got.

#4020 fix(ci): Increase test coverage of state rebuild
  .github/workflows/test.yml
Labels: C-bug, A-devops, P-High :fire:, I-slow, lightwalletd

#4019 change(rfc): Cleanup transparent address index database design
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-cleanup, P-Medium :zap:, lightwalletd

#4021 fix(log): Log CommitmentErrors as hex
  zebra-chain/src/block/commitment.rs
Labels: C-bug, NU-5, P-Low :snowflake:, A-diagnostics

#4046 fix(rpc): Check for panics in the transaction queue
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebrad/src/commands/start.rs
Labels: C-enhancement, P-Low :snowflake:, A-rpc, lightwalletd

#3986 feat(ci): create disk image after a successful full sync test
  .github/workflows/test-full-sync.yml
Labels: A-infrastructure, A-devops, P-High :fire:

#4040 0. change(db): Use Ribbon filters for database index lookups
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: C-enhancement, P-High :fire:, A-state, lightwalletd

#3963 2. feat(db): Add address balance indexes to the finalized state
  zebra-chain/src/transparent/address.rs
  zebra-state/Cargo.toml
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/balance_by_transparent_addr_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/balance_by_transparent_addr_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/balance_by_transparent_addr_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/balance_by_transparent_addr_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/column_family_names.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@no_blocks.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db/arbitrary.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/vectors.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
Labels: A-dependencies, C-enhancement, P-High :fire:, A-state, lightwalletd

#4027 A. change(db): Use LZ4 compression for RocksDB
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: C-enhancement, P-Medium :zap:, A-state, lightwalletd

#3968 fix(ci): validate tests exit code after reading the container logs
  .github/CODEOWNERS
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
  docker/.dockerignore
Labels: A-infrastructure, A-devops, P-Medium :zap:, I-integration-fail

#3978 3. change(db): Store UTXOs by transaction location rather than transaction hash
  .github/workflows/test.yml
  zebra-chain/src/transparent/utxo.rs
  zebra-state/src/constants.rs
  zebra-state/src/request.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/balance_by_transparent_addr_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/balance_by_transparent_addr_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/balance_by_transparent_addr_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/balance_by_transparent_addr_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/disk_format/transparent/arbitrary.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/utxos@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/utxos@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/utxos@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/utxos@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/utxos@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/utxos@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
Labels: C-enhancement, P-High :fire:, A-state, lightwalletd

#4045 B. change(db): Tune database file compaction
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: C-enhancement, P-High :fire:, I-slow, A-state, lightwalletd

#3992 4. change(db): stop storing redundant transparent output fields in the database
  zebra-chain/src/transparent/utxo.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_outpoint_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
Labels: C-enhancement, P-High :fire:, A-state, lightwalletd

#4015 feat(rpc): Implement an RPC transaction queue
  zebra-rpc/src/lib.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/queue.rs
  zebra-rpc/src/queue/tests.rs
  zebra-rpc/src/queue/tests/prop.rs
  zebra-rpc/src/server.rs
  zebrad/src/commands/start.rs
Labels: C-enhancement, P-Medium :zap:, A-rpc, lightwalletd

#4073 refactor(ci): use distinctive names for cached state disks
  .dockerignore
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
  zebra-state/src/constants.rs
Labels: A-infrastructure, A-devops, P-High :fire:, I-integration-fail

#4081 fix(clippy): Ignore clippy drop warnings in tests
  zebra-network/src/peer/client/tests/vectors.rs
  zebra-network/src/peer_set/set/tests/vectors.rs
Labels: A-rust, C-cleanup, P-Low :snowflake:

#4082 change(db): Disable unused rocksdb compression features
  Cargo.lock
  zebra-state/Cargo.toml
Labels: A-dependencies, C-cleanup, P-Low :snowflake:, A-state

#4022 feat(state): add transparent address indexes to the non-finalized state
  zebra-chain/src/block.rs
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/transparent/utxo.rs
  zebra-state/proptest-regressions/service/non_finalized_state/tests/prop.txt
  zebra-state/src/arbitrary.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
  zebra-state/src/service.rs
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/check/tests/utxo.rs
  zebra-state/src/service/check/utxo.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/chain/index.rs
  zebra-state/src/tests/setup.rs
Labels: C-bug, C-enhancement, P-High :fire:, A-state, lightwalletd

#4103 imp(ci): use GitHub Branch Protection checks instead of Mergify
  .github/mergify.yml
Labels: A-devops, C-enhancement, P-Low :snowflake:

#4105 fix(ci): Fix invalid mergify configuration
  .github/mergify.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#3999 6. feat(db): Add a transparent address UTXO index
  Cargo.lock
  deny.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/transparent.rs
  zebra-chain/src/transparent/address.rs
  zebra-chain/src/transparent/script.rs
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/column_family_names.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@no_blocks.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_loc_by_transparent_addr_loc_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_loc_by_transparent_addr_loc_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_loc_by_transparent_addr_loc_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_loc_by_transparent_addr_loc_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@mainnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_balances@testnet_0.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxo_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxo_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxo_data@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxo_data@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxos@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxos@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxos@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxos@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
Labels: A-dependencies, C-enhancement, P-High :fire:, A-state, lightwalletd

#4038 7. feat(db): Add a transparent address transaction index
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/column_family_names.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@no_blocks.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_loc_by_transparent_addr_loc_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_loc_by_transparent_addr_loc_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_loc_by_transparent_addr_loc_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_loc_by_transparent_addr_loc_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_transaction_locations@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_transaction_locations@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_transaction_locations@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_transaction_locations@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
Labels: C-enhancement, P-High :fire:, A-state, lightwalletd

#4094 refactor(queue)!: improve mergify merge throughput
  .github/mergify.yml
Labels: A-devops, C-enhancement, P-Low :snowflake:

#4107 feat(ci): run cached state rebuilds in main branch
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
Labels: A-devops, C-enhancement, P-Critical :ambulance:, I-integration-fail

#4120 ci(Mergify): Fix invalid mergify config on main branch
  .github/mergify.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#4097 8. feat(state): add a query function for transparent address balances
  zebra-chain/src/amount.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxo_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxo_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxo_data@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/address_utxo_data@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/chain/index.rs
  zebra-state/src/service/read.rs
Labels: C-enhancement, P-High :fire:, A-state, lightwalletd

#4123 fix(ci): give enough time to zebra before reading logs
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
Labels: A-infrastructure, A-devops, C-enhancement, P-Critical :ambulance:, I-integration-fail

#3799 change(nu5): use new V5 transaction script verification API
  Cargo.lock
  Cargo.toml
  deny.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/orchard/arbitrary.rs
  zebra-chain/src/orchard/commitment.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/note.rs
  zebra-chain/src/orchard/note/nullifiers.rs
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/orchard/tests/tree.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/primitives/redpallas/batch.rs
  zebra-chain/src/primitives/redpallas/scalar_mul.rs
  zebra-chain/src/primitives/redpallas/signing_key.rs
  zebra-chain/src/primitives/redpallas/verification_key.rs
  zebra-chain/src/primitives/zcash_note_encryption.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-chain/src/serialization/serde_helpers.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-chain/src/transparent/address.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/primitives/halo2/tests.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-network/src/constants.rs
  zebra-network/src/protocol/external/arbitrary.rs
  zebra-network/src/protocol/external/types.rs
  zebra-script/Cargo.toml
  zebra-script/src/lib.rs
  zebra-state/Cargo.toml
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/tests/vectors.rs
  zebra-test/src/vectors/block-test-1-599-200.txt
  zebra-test/src/vectors/block-test-1-599-201.txt
  zebra-test/src/vectors/block.rs
  zebra-test/src/vectors/orchard-shielded-data-1.txt
  zebra-test/src/vectors/orchard-shielded-data-2.txt
  zebra-test/src/vectors/orchard-shielded-data-3.txt
  zebra-test/src/vectors/orchard-shielded-data-4.txt
  zebra-test/src/zip0244.rs
Labels: A-dependencies, A-consensus, C-enhancement, P-Critical :ambulance:, A-network, NU-6, A-state

#4135 1.0.0-beta.8 Release
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/install.md
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-docs, A-dependencies, NU-5, P-Critical :ambulance:

#4067 change(test): Refactor how extra arguments are handled when spawing lightwalled
  Cargo.lock
  zebra-test/Cargo.toml
  zebra-test/src/command.rs
  zebra-test/src/command/arguments.rs
  zebra-test/src/command/arguments/tests.rs
  zebra-test/tests/command.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/sync.rs
Labels: A-rust, P-High :fire:, C-testing, lightwalletd

#4111 9. feat(state): add a query function for transparent UTXOs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/utxo.rs
Labels: C-enhancement, P-High :fire:, A-state, lightwalletd

#3976 change(nu5): disconnect from testnet peers using the first NU5 testnet rules
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-network/src/constants.rs
  zebra-network/src/protocol/external/types.rs
Labels: C-enhancement, NU-5, P-High :fire:, I-slow, A-network

#4144 fix(doc): Fix link to run page in installation docs
  book/src/user/install.md
Labels: C-bug, A-docs, P-Low :snowflake:

#4112 Fix typos
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/queue.rs
  zebra-rpc/src/queue/tests/prop.rs
  zebra-state/src/service/non_finalized_state/chain/index.rs
  zebra-state/src/service/read.rs
Labels: C-bug, A-docs, P-Low :snowflake:

#4148 fix(ci): increase the Zcash parameter fetch timeout
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#4056 refactor: document coinbase rules, refactor to ease understanding
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/error.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/check.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-state/src/service/check/utxo.rs
  zebra-state/src/service/tests.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
Labels: A-docs, A-consensus, C-cleanup, P-Medium :zap:

#4149 fix(ci): share GitHub runner caches between branches
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: A-devops, C-enhancement, P-High :fire:, I-slow

#4119 feat(rpc): implement the get_address_tx_ids RPC method query
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/chain/index.rs
  zebra-state/src/service/read.rs
Labels: C-enhancement, P-Medium :zap:, A-rpc, A-state, lightwalletd

#3860 feat(rpc): Log unrecognized RPC requests
  zebra-rpc/src/server.rs
  zebra-rpc/src/server/tracing_middleware.rs
Labels: C-enhancement, P-Medium :zap:, A-diagnostics, lightwalletd

#4158 fix(test): don't create another 'state' directory when implementing ZebradTestDirExt
  zebrad/tests/acceptance.rs
  zebrad/tests/common/launch.rs
Labels: C-cleanup, P-Optional :sparkles:, C-testing, A-state

#4164 Fix typos
  zebra-state/src/service/read.rs
  zebra-test/src/command/arguments/tests.rs
Labels: A-docs, A-rust, C-cleanup, P-Optional :sparkles:

#4087 feat(rpc): Implement `getaddressutxos` RPC method.
  zebra-chain/src/transparent/script.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
Labels: C-enhancement, P-Medium :zap:, A-rpc, A-state, lightwalletd

#4183 change(verifier): Update Zebra's block hash checkpoints
  book/src/dev/zebra-checkpoints.md
  zebra-consensus/src/checkpoint/README.md
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
  zebra-utils/README.md
Labels: A-consensus, C-enhancement, P-High :fire:, I-integration-fail, lightwalletd

#4157 RPC test with fully synced Zebra
  Cargo.lock
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
Labels: A-dependencies, P-Medium :zap:, C-testing, A-rpc, lightwalletd

#4185 fix(sync): Add an extra block retry, to speed up the initial sync
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/tests/timing.rs
Labels: A-rust, C-enhancement, P-High :fire:, I-slow, I-integration-fail, lightwalletd

#4198 fix(ci): Retry after docker log follow ssh failures
  .github/workflows/test-full-sync.yml
  .github/workflows/test.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4206 fix(ci): do not delete instances from `main` branch on merge
  .github/workflows/clean.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#4184 change(rust): Use link-time optimisation in release builds
  Cargo.toml
  docker/Dockerfile
Labels: A-devops, C-enhancement, P-High :fire:, I-slow, I-integration-fail, lightwalletd

#4068 add(test): Integration test to send transactions using lightwalletd
  Cargo.lock
  deny.toml
  docker/Dockerfile
  zebra-state/src/config.rs
  zebrad/Cargo.toml
  zebrad/build.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/lightwalletd/proto/compact_formats.proto
  zebrad/tests/common/lightwalletd/proto/service.proto
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/lightwalletd/wallet_grpc.rs
  zebrad/tests/common/mod.rs
  zebrad/tests/common/sync.rs
Labels: A-dependencies, P-Medium :zap:, C-testing, A-rpc, lightwalletd

#4215 fix(rpc): Make Zebra RPC compatible with the `zcash-cli` RPC client
  zebra-rpc/src/server/compatibility.rs
Labels: C-bug, P-Medium :zap:, I-usability, A-rpc, lightwalletd

#4217 fix(rpc): Fix some RPC response formats to match `zcashd`
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/vectors.rs
Labels: C-bug, P-Medium :zap:, A-rpc, lightwalletd

#4235 fix(ci): Install cmake to fix zcash-params Dockerfile build failure
  docker/zcash-params/Dockerfile
Labels: C-bug, A-devops, P-Critical :ambulance:

#4212 fix(perf): Decrease the peer handshake timeout to 3 seconds, to speed up the initial sync
  zebra-network/src/constants.rs
Labels: C-enhancement, P-High :fire:, I-slow, A-network, lightwalletd

#4246 fix(ci): Increase docs job timeout
  .github/workflows/docs.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail

#4177 test(rpc): Add Rust tests for lightwalletd sync from Zebra
  zebrad/tests/acceptance.rs
  zebrad/tests/common/failure_messages.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/lightwalletd/wallet_grpc.rs
  zebrad/tests/common/mod.rs
Labels: P-High :fire:, C-testing, A-rpc, lightwalletd

#4248 fix(state): Tweak ephemeral state directory path and improve docs
  zebra-state/src/config.rs
Labels: C-bug, A-docs, P-Low :snowflake:, I-usability, A-state
