Repository ZcashFoundation/zebra, pull requests merged in 2022-09, with the labels that each got.

#4997 fix(log): Increase slow code log thresholds to reduce verbose logs and warnings
  zebra-chain/src/diagnostic.rs
Labels: C-bug, P-Medium :zap:, I-usability, A-diagnostics

#4806 fix(rpc): Isolate RPC queries from the rest of Zebra, to improve performance
  zebra-rpc/src/server.rs
  zebra-rpc/src/server/tests.rs
  zebra-rpc/src/server/tests/vectors.rs
  zebra-rpc/src/tests/vectors.rs
Labels: C-bug, P-High :fire:, C-security, I-slow, I-integration-fail, A-rpc, lightwalletd

#5017 doc(ci): Explain how to resolve duplicate dependency warnings
  book/src/dev/continuous-integration.md
Labels: A-docs, A-devops, C-enhancement, P-Medium :zap:

#4926 change(deps): upgrade zcash_script and zcash dependencies
  Cargo.lock
  Cargo.toml
  deny.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-script/Cargo.toml
Labels: A-dependencies, A-rust, C-enhancement, P-Medium :zap:, I-slow

#5014 fix(ci): improve test output and test reliability
  zebra-chain/src/diagnostic.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/vectors.rs
  zebra-test/src/command.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/launch.rs
Labels: C-cleanup, P-Low :snowflake:, I-integration-fail, C-testing, A-state

#5026 change(doc): Make the release instructions more explicit
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-docs, P-Optional :sparkles:

#5038 fix(doc): Continious integration book doc
  book/src/dev/continuous-integration.md
Labels: C-bug, A-docs, P-Low :snowflake:

#5024 ci(build): re-enable Rust beta tests in ubuntu
  .github/workflows/continous-integration-os.yml
Labels: A-infrastructure, A-devops, P-Low :snowflake:, C-testing

#5045 fix(clippy): Resolve unnecessary borrow lint and remove redundant imports
  zebra-chain/src/block/merkle.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/serialization/sha256d.rs
  zebra-chain/src/sprout/address.rs
  zebra-chain/src/sprout/keys.rs
  zebra-chain/src/sprout/tree.rs
  zebra-chain/src/transaction/auth_digest.rs
  zebra-chain/src/transparent/address.rs
  zebra-chain/src/work/difficulty.rs
  zebra-network/src/protocol/external/types.rs
  zebra-utils/src/bin/zebra-checkpoints/main.rs
  zebrad/tests/common/launch.rs
Labels: A-rust, C-cleanup, P-Low :snowflake:

#5013 Breaking: fix(rpc): Add a config for multi-threaded RPC server requests
  Cargo.lock
  README.md
  zebra-rpc/Cargo.toml
  zebra-rpc/src/config.rs
  zebra-rpc/src/server.rs
  zebra-rpc/src/server/tests/vectors.rs
  zebrad/src/config.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
Labels: C-bug, A-dependencies, P-Medium :zap:, I-slow, C-testing, A-rpc, lightwalletd

#5072 fix(rpc): Disable RPC port conflict tests on Windows and macOS
  zebra-rpc/src/server/tests/vectors.rs
Labels: C-bug, A-rust, P-Critical :ambulance:, I-integration-fail, A-rpc

#5071 change(deps): bump rocksdb from 0.18.0 to 0.19.0
  Cargo.lock
  deny.toml
  zebra-state/Cargo.toml
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
Labels: A-dependencies, A-rust, P-Medium :zap:, A-state

#5070 fix(deny.toml): Change an exception to the earlier pin-project version
  book/src/dev/continuous-integration.md
  deny.toml
Labels: A-docs, A-dependencies, C-cleanup, P-Medium :zap:

#5080 update(doc): Explain how to find errors in CI
  book/src/dev/continuous-integration.md
Labels: A-docs, A-devops, C-enhancement, P-Medium :zap:, C-testing

#5079 ci(resources): delete old disk images created in GCP
  .github/workflows/delete-gcp-resources.yml
Labels: A-infrastructure, A-devops, C-cleanup, P-High :fire:

#5084 fix(cd): Use 200GB disks for managed instances
  .github/workflows/continous-delivery.yml
Labels: C-bug, A-devops, P-Medium :zap:, I-heavy

#5082 fix(ci): delete GCP resources, but keep some recent cached state images
  .github/workflows/delete-gcp-resources.yml
  book/src/dev/continuous-integration.md
Labels: C-bug, A-devops, P-Medium :zap:

#5016 add(test): test disabled `lightwalletd` mempool gRPCs via zebrad logs
  zebra-chain/src/block/hash.rs
  zebra-chain/src/transaction/hash.rs
  zebra-consensus/src/transaction.rs
  zebra-node-services/src/mempool/gossip.rs
  zebra-rpc/src/config.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebra-rpc/src/server/tests/vectors.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/src/components/mempool/storage.rs
  zebrad/src/components/mempool/storage/verified_set.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
  zebrad/tests/common/sync.rs
Labels: P-Medium :zap:, A-diagnostics, C-testing, A-rpc, lightwalletd

#5009 build(deps): bump prost, tonic, tonic-build and console-subscriber
  .github/workflows/build-crates-individually.yml
  .github/workflows/continous-integration-os.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  Cargo.lock
  zebrad/Cargo.toml
Labels: A-dependencies, A-rust, C-enhancement, P-Low :snowflake:

#5097 ci(lint): fetch with depth for `tj-actions/changed-files` on push
  .github/workflows/lint.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#5100 add(doc): Explain how Mergify works, and when it can be used
  book/src/dev/continuous-integration.md
Labels: A-docs, A-devops, P-Medium :zap:, C-testing

#5086 1. fix(ci): Label lwd cached state images with their sync height
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-High :fire:

#5032 fix(test) switch zebrad to a non-blocking tracing logger
  Cargo.lock
  zebra-state/src/service/finalized_state.rs
  zebrad/Cargo.toml
  zebrad/src/application.rs
  zebrad/src/components/tracing/component.rs
  zebrad/src/config.rs
  zebrad/tests/acceptance.rs
Labels: C-bug, P-Medium :zap:, A-diagnostics

#5106 doc(consensus): Document why we do a UTXO check that looks redundant
  zebra-state/src/service.rs
  zebra-state/src/service/pending_utxos.rs
Labels: A-docs, A-consensus, P-Medium :zap:, I-slow, A-state

#5112 tests(config): Upgrade config file tests
  zebrad/tests/acceptance.rs
  zebrad/tests/common/config.rs
  zebrad/tests/common/configs/v1.0.0-beta.12.toml
  zebrad/tests/common/configs/v1.0.0-beta.13.toml
  zebrad/tests/common/configs/v1.0.0-beta.15.toml
Labels: P-Medium :zap:, I-usability, C-testing

#5113 change(ci): Delete cached state images older than 2 days, and check every day
  .github/workflows/delete-gcp-resources.yml
Labels: A-devops, C-enhancement, P-High :fire:, I-heavy, A-state

#5088 fix(ci): Wait 1 day before creating cached state image updates
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-High :fire:, I-heavy

#5128 fix(ci): Make checkpoint disk image names short enough for Google Cloud
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, A-state

#5131 fix(clippy): Fix a new nightly clippy "unwrap_or_else uses default" lint
  zebra-network/src/peer/handshake.rs
  zebrad/src/components/tracing/component.rs
Labels: A-rust, C-cleanup, P-Medium :zap:

#5090 fix(ci): Disable beta Rust tests
  .github/workflows/continous-integration-os.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-heavy, I-build

#5129 fix(ci): Increase the full sync timeout
  book/src/dev/continuous-integration.md
  zebrad/tests/common/sync.rs
Labels: C-bug, A-devops, P-Critical :ambulance:, I-slow, I-integration-fail

#5130 fix(ci): Update Zebra checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-bug, A-devops, P-Critical :ambulance:, I-slow, C-testing

#5124 fix(doc): Explain how image deletion actually works
  .github/workflows/delete-gcp-resources.yml
Labels: C-bug, A-docs, A-devops, P-Low :snowflake:

#5132 1. change(state): Run most StateService read requests without shared mutable chain state
  zebra-state/src/constants.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/find.rs
  zebra-state/src/service/read/find/tests.rs
  zebra-state/src/service/read/find/tests/vectors.rs
  zebra-state/src/tests.rs
  zebra-state/src/util.rs
Labels: C-bug, A-rust, P-Medium :zap:, I-slow, A-state

#4870 feat(net): return peer metadata from `connect_isolated` functions
  zebra-network/src/isolated.rs
  zebra-network/src/isolated/tests/vectors.rs
  zebra-network/src/isolated/tor.rs
  zebra-network/src/lib.rs
  zebra-network/src/peer.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/client/tests.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer/load_tracked_client.rs
  zebra-network/src/peer/minimum_peer_version.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/set/tests/prop.rs
  zebra-network/src/protocol/external.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/tests/acceptance.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
Labels: C-enhancement, P-Medium :zap:, A-network

#5151 fix(doc): Update deny.toml developer docs and file comments
  book/src/dev/continuous-integration.md
  deny.toml
Labels: A-docs, A-dependencies, C-cleanup, P-High :fire:

#5156 fix(docs): Enable all cargo features in Zebra's deployed docs
  .github/workflows/docs.yml
Labels: C-bug, A-docs, A-devops, P-Medium :zap:

#5165 add(devops): Allow manual Release Drafter workflow runs
  .github/workflows/release-drafter.yml
Labels: A-docs, A-devops, C-enhancement, P-High :fire:

#4917 docs(release): add versioning and releases information
  book/src/dev/alpha-release-criteria.md
  book/src/dev/release-process.md
Labels: A-docs, C-enhancement, P-Medium :zap:, I-usability

#5166 fix(ci): Fix full sync failures by adding a job for 1790k blocks
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-slow, I-integration-fail

#5163 chore(build): allow a custom `zebrad` config file path
  docker/Dockerfile
Labels: A-infrastructure, A-devops, C-enhancement, P-Low :snowflake:, I-usability

#5172 fix(ci): Increase full sync time to 32 hours
  zebrad/tests/common/sync.rs
Labels: C-bug, A-rust, A-devops, P-High :fire:, I-slow

#5177 fix(build): a path must exist before creating a file in it
  docker/Dockerfile
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, I-build

#5107 2. change(state): Run AwaitUtxo read requests without shared mutable chain state
  zebra-rpc/src/methods.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/check/nullifier.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/queued_blocks.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/address/balance.rs
  zebra-state/src/service/read/address/tx_id.rs
  zebra-state/src/service/read/address/utxo.rs
  zebra-state/src/service/read/block.rs
  zebra-state/src/service/read/find.rs
  zebra-state/src/service/read/tree.rs
Labels: C-bug, A-rust, P-Medium :zap:, I-slow, A-state

#5138 feat(release): create Docker hub binaries when tagging
  .github/workflows/build-docker-image.yml
  .github/workflows/release-binaries.yml
Labels: A-devops, C-enhancement, P-Medium :zap:

#5152 3. change(state): Move the finalized queue to the StateService
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/queued_blocks.rs
  zebra-state/src/service/queued_blocks/tests.rs
  zebra-state/src/service/queued_blocks/tests/vectors.rs
Labels: C-enhancement, P-Medium :zap:, A-state

#5137 cleanup(state): condenses match arms for redirected StateService requests and moves metrics counting to Request methods
  zebra-state/src/request.rs
  zebra-state/src/service.rs
Labels: C-cleanup, P-Medium :zap:, A-state

#5194 chore: Release Zebra 1.0.0-beta.15
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/install.md
  book/src/user/lightwalletd.md
  book/src/user/run.md
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-docs, A-dependencies, C-enhancement, P-High :fire:

#5133 fix(testnet): look back up to 10,000 blocks on testnet for a legacy chain
  zebra-state/src/constants.rs
  zebra-state/src/service.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/tests.rs
Labels: C-bug, A-consensus, P-Medium :zap:, I-panic, A-diagnostics, A-state

#5200 feat(logs): prints git metadata and platform info when zebrad starts up
  zebrad/src/application.rs
Labels: C-enhancement

#5202 change(dev): Add CHANGELOG checks to PR review template
  .github/pull_request_template.md
Labels: A-docs, A-devops, C-cleanup, P-High :fire:

#5192 fix(ci): Delete Google Cloud test instances after 3 days
  .github/workflows/delete-gcp-resources.yml
  book/src/dev/continuous-integration.md
Labels: A-devops, C-cleanup, P-Medium :zap:, I-cost

#5251 fix(ci): Build zebrad with Rust 1.63 to avoid Zcash parameter download hangs
  .github/workflows/continous-integration-os.patch.yml
  .github/workflows/continous-integration-os.yml
  .github/workflows/coverage.yml
  book/src/user/supported-platforms.md
  docker/Dockerfile
  docker/zcash-params/Dockerfile
Labels: C-bug, A-dependencies, A-devops, P-Critical :ambulance:, I-hang, C-breaking

#5228 change(zebrad): opens the database in a blocking tokio thread, which allows tokio to run other tasks
  zebra-state/src/lib.rs
  zebra-state/src/service.rs
  zebrad/src/commands/copy_state.rs
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
Labels: C-bug, P-Low :snowflake:, I-slow, I-usability, A-state

#5240 doc(ci): Explain how to fix Mergify and Zcash parameter download failures
  book/src/dev/continuous-integration.md
Labels: A-docs, A-devops, P-Medium :zap:, C-trivial

#5256 build(deps): Bump metrics and metrics-exporter-prometheus
  Cargo.lock
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-state/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, A-rust, P-Low :snowflake:, C-trivial

#5190 doc(ci): Fix incorrect docs about Docker build cache order
  .github/workflows/build-docker-image.yml
Labels: A-docs, A-devops, C-cleanup, P-Low :snowflake:, I-cost

#5203 change(release): Automatically split CHANGELOG entries into categories
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: A-devops, C-cleanup, P-Medium :zap:

#5275 fix(release): Fix the config for `release-drafter`
  .github/release-drafter.yml
Labels: A-devops, P-Critical :ambulance:, C-trivial

#5201 change(ci): Combine high and low Mergify queues into a batched queue
  .github/mergify.yml
Labels: A-devops, C-cleanup, P-High :fire:, I-slow, I-cost

#5278 fix(ci): Comment out empty major version list in release drafter
  .github/release-drafter.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#5193 doc(release): Update release template for Docker releases
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-docs, C-cleanup, P-Medium :zap:, C-trivial

#5191 change(ci): Create a new cached state image every 12 hours
  .github/workflows/deploy-gcp-tests.yml
Labels: A-devops, C-cleanup, P-Medium :zap:, I-cost

#5281 doc(ci): List temporary CI errors that should be retried
  book/src/dev/continuous-integration.md
Labels: A-docs, A-devops, P-Medium :zap:, C-trivial

#5134 change(state): Write finalized blocks to the state in a separate thread, to avoid network and RPC hangs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/arbitrary.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
  zebra-state/src/service.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/block_iter.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/arbitrary.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/pending_utxos.rs
  zebra-state/src/service/queued_blocks.rs
  zebra-state/src/service/read/address/balance.rs
  zebra-state/src/service/read/address/tx_id.rs
  zebra-state/src/service/read/address/utxo.rs
  zebra-state/src/service/read/block.rs
  zebra-state/src/service/read/find.rs
  zebra-state/src/service/read/tree.rs
  zebra-state/src/service/tests.rs
  zebra-state/src/service/write.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/mempool/tests/vector.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: C-bug, C-enhancement, P-Medium :zap:, I-slow, A-state

#5292 ci(deploy): retry `gcloud` ssh connections if it fails
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial
