Repository ZcashFoundation/zebra, pull requests merged in 2022-06, with the labels that each got.

#4517 change(deps): Upgrade tracing-subscriber and related dependencies
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
  Cargo.lock
  deny.toml
  tower-batch/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint.rs
  zebra-network/Cargo.toml
  zebra-network/src/address_book.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-state/Cargo.toml
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/zebra_db/metrics.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/tests.rs
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/inbound/downloads.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/src/components/mempool/gossip.rs
  zebrad/src/components/mempool/storage.rs
  zebrad/src/components/mempool/storage/verified_set.rs
  zebrad/src/components/metrics.rs
  zebrad/src/components/sync.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/sync.rs
Labels: A-dependencies, A-rust, C-enhancement, P-High :fire:, A-diagnostics, lightwalletd

#4553 fix(ci): test RPCs with zcash/lightwalletd, to fix post-NU5 failures in adityapk00/lightwalletd
  .github/workflows/zcash-lightwalletd.yml
  zebrad/tests/acceptance.rs
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/failure_messages.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
Labels: A-dependencies, A-devops, P-Critical :ambulance:, I-integration-fail, C-testing, A-rpc, lightwalletd

#4540 ci(mergify): do not create draft PRs if not needed
  .github/mergify.yml
Labels: C-bug, A-docs, A-devops, P-Medium :zap:, I-usability

#4502 doc(user): Explain what Zebra does when it starts up
  book/src/user/startup.md
Labels: A-docs, C-enhancement, NU-5, P-Low :snowflake:, I-usability, A-network, A-state

#4538 change(net): immediately disconnect from pre-NU5 nodes
  zebra-network/src/constants.rs
  zebra-network/src/peer_set/set/tests/vectors.rs
Labels: C-enhancement, NU-5, P-Medium :zap:, A-network

#4514 fix(doc): Fix various doc warnings, part 1
  zebra-chain/src/block.rs
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/block/header.rs
  zebra-chain/src/block/merkle.rs
  zebra-chain/src/history_tree.rs
  zebra-chain/src/orchard/action.rs
  zebra-chain/src/orchard/commitment.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/note.rs
  zebra-chain/src/orchard/note/nullifiers.rs
  zebra-chain/src/orchard/shielded_data.rs
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/parameters/arbitrary.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/primitives/redpallas/batch.rs
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/commitment/pedersen_hashes.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/output.rs
  zebra-chain/src/sapling/shielded_data.rs
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/serialization/arbitrary.rs
  zebra-chain/src/sprout/joinsplit.rs
  zebra-chain/src/sprout/tests/test_vectors.rs
  zebra-chain/src/sprout/tree.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/hash.rs
  zebra-chain/src/transaction/joinsplit.rs
  zebra-chain/src/transaction/unmined.rs
  zebra-chain/src/transparent.rs
  zebra-chain/src/transparent/utxo.rs
  zebra-chain/src/value_balance.rs
  zebra-network/src/address_book.rs
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
  zebra-network/src/isolated/tor.rs
  zebra-network/src/lib.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/peer/client/tests.rs
  zebra-network/src/peer/connector.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/protocol/external/addr/in_version.rs
  zebra-network/src/protocol/external/arbitrary.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/internal/request.rs
  zebra-node-services/src/mempool.rs
  zebra-state/src/arbitrary.rs
  zebra-state/src/request.rs
  zebra-test/src/command.rs
  zebra-test/src/mock_service.rs
  zebrad/src/components/mempool/downloads.rs
Labels: A-docs, P-Low :snowflake:

#4568 docs(release): update `release-checklist.md`
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-devops, P-Low :snowflake:

#4585 update: transaction verification dashboard to show all shielded pool sigs, proofs, nullifiers
  grafana/transaction-verification.json
Labels: C-enhancement, P-Optional :sparkles:, A-diagnostics

#4595 Refactor the release checklist
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: P-Optional :sparkles:

#4599 ci(lightwalletd): Zebra's Dockerfile needs `latest` lwd image
  .github/workflows/zcash-lightwalletd.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, I-build

#4561 fix(doc): Fix various doc warnings, part 2
  zebra-chain/src/sapling/spend.rs
  zebra-consensus/src/transaction.rs
  zebra-network/src/constants.rs
  zebra-network/src/isolated.rs
  zebra-network/src/lib.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/handshake.rs
  zebra-node-services/src/mempool.rs
  zebra-state/src/arbitrary.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/check/difficulty.rs
  zebra-state/src/service/check/nullifier.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/chain/index.rs
  zebra-state/src/service/pending_utxos.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/watch_receiver.rs
  zebra-test/src/command.rs
  zebra-test/src/network_addr.rs
  zebra-test/src/prelude.rs
Labels: A-docs, P-Low :snowflake:

#4564 fix(network): when connecting to peers, ignore invalid ports, and prefer canonical ports
  zebra-network/src/address_book.rs
  zebra-network/src/address_book/tests/prop.rs
  zebra-network/src/address_book/tests/vectors.rs
  zebra-network/src/address_book_updater.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/meta_addr/tests/vectors.rs
  zebra-network/src/peer.rs
  zebra-network/src/peer/priority.rs
  zebra-network/src/peer_set/candidate_set/tests/prop.rs
  zebra-network/src/peer_set/candidate_set/tests/vectors.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/peer_set/set/tests.rs
  zebra-network/src/protocol/external/tests/preallocate.rs
  zebra-network/src/protocol/external/tests/prop.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
Labels: C-bug, P-High :fire:, C-security, I-slow, A-network

#4578 fix(clippy): Resolve some lifetime and reference lints
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/sprout/tree.rs
  zebra-chain/src/transparent/serialize.rs
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/finalized_state/disk_format.rs
Labels: A-rust, C-cleanup, P-Optional :sparkles:

#4614 fix(ci): Disable zcash_rpc_conflict test on macOS
  zebrad/tests/acceptance.rs
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, A-rpc, lightwalletd

#4611 fix(doc): Fix various doc warnings, part 3
  zebra-chain/src/lib.rs
  zebra-chain/src/transparent/utxo.rs
  zebra-consensus/src/lib.rs
  zebra-network/src/isolated/tor.rs
  zebra-network/src/lib.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/peer/priority.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/limit.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/protocol/external/addr.rs
  zebra-network/src/protocol/external/addr/v1.rs
  zebra-network/src/protocol/external/addr/v2.rs
  zebra-network/src/protocol/external/arbitrary.rs
  zebra-network/src/protocol/external/message.rs
  zebra-state/src/lib.rs
  zebra-test/src/lib.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/config.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/src/components/mempool/gossip.rs
  zebrad/src/components/mempool/storage.rs
  zebrad/src/components/mempool/storage/eviction_list.rs
  zebrad/src/components/sync/gossip.rs
  zebrad/src/components/sync/recent_sync_lengths.rs
  zebrad/src/lib.rs
Labels: A-docs, P-High :fire:

#4519 feat(diagnostics): Add tokio-console support to zebrad
  .cargo/config.toml
  Cargo.lock
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/peer_set/initialize.rs
  zebra-rpc/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/tracing/component.rs
Labels: A-dependencies, C-enhancement, P-High :fire:, A-diagnostics, C-testing, lightwalletd

#4523 doc(tests): full sync and lightwalletd tests
  zebrad/tests/acceptance.rs
  zebrad/tests/common/lightwalletd.rs
Labels: P-Medium :zap:

#4624 changelog: Add a draft "breaking changes" section to the next changelog
  CHANGELOG.md
Labels: A-docs, P-Medium :zap:, C-deprecation

#4598 feat(actions): delete old GCP resources
  .github/workflows/delete-gcp-resources.yml
Labels: A-infrastructure, A-devops, C-enhancement, P-Medium :zap:, I-usability

#4627 Use `config.toml` instead of inner attributes for private links
  .cargo/config.toml
  zebra-chain/src/lib.rs
  zebra-consensus/src/lib.rs
  zebra-network/src/lib.rs
  zebra-state/src/lib.rs
  zebra-test/src/lib.rs
  zebrad/src/lib.rs
Labels: A-docs, P-Low :snowflake:

#4631 fix(state): only delete old database directories inside the cache directory
  zebra-state/src/config.rs
  zebrad/src/commands/start.rs
Labels: C-enhancement, P-Medium :zap:, I-heavy, A-state

#4623 breaking(diagnostics): rename "enable-sentry" feature to "sentry"
  book/src/user/requirements.md
  docker/Dockerfile
  docker/zcash-params/Dockerfile
  zebrad/Cargo.toml
  zebrad/src/application.rs
  zebrad/src/components/tracing/component.rs
  zebrad/src/lib.rs
  zebrad/tests/acceptance.rs
Labels: A-dependencies, A-devops, C-cleanup, P-Low :snowflake:, I-usability

#4539 breaking(diagnostics): make zebrad diagnostics into optional compile-time features
  book/src/user/metrics.md
  book/src/user/requirements.md
  book/src/user/tracing.md
  docker/Dockerfile
  docker/zcash-params/Dockerfile
  zebrad/Cargo.toml
  zebrad/src/application.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/metrics.rs
  zebrad/src/components/tracing.rs
  zebrad/src/components/tracing/component.rs
  zebrad/src/components/tracing/endpoint.rs
  zebrad/src/lib.rs
  zebrad/tests/acceptance.rs
Labels: A-dependencies, P-Low :snowflake:, C-security, A-diagnostics, lightwalletd

#4618 cleanup(net): Group PeerSet fields into themes
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/set/tests.rs
  zebra-network/src/peer_set/set/tests/prop.rs
Labels: C-cleanup, P-Optional :sparkles:, A-network

#4636 imp(docs): manage`cargo-mdbook` as a GitHub action
  .github/workflows/docs.yml
Labels: A-devops, C-enhancement, P-Low :snowflake:, I-usability

#4635 ci(docs): test `cargo doc` warnings and errors
  .github/workflows/lint.yml
Labels: A-infrastructure, A-devops, C-enhancement, P-Medium :zap:, I-usability

#4609 feat(clippy): Add `fallible_impl_from` lint
  .cargo/config.toml
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/work/u256.rs
  zebra-network/src/protocol/external/message.rs
Labels: P-Medium :zap:

#4654 Add a "Rust doc" patch job
  .github/workflows/lint.patch.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail

#4586 feat(state): delete old database directories
  zebra-state/src/config.rs
  zebra-state/src/lib.rs
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:

#4640 feat(ci): build each crate individually
  .github/workflows/build-crates-individually.patch.yml
  .github/workflows/build-crates-individually.yml
  .github/workflows/continous-integration-os.yml
Labels: A-devops, C-enhancement, P-High :fire:, I-build

#4641 doc: add tokio-console page in book dev section
  book/src/dev/tokio-console.md
Labels: A-docs

#4662 fix(panic): Reduce the minimum lookahead limit, and fix a config panic
  zebrad/src/components/sync.rs
Labels: C-bug, P-High :fire:, I-slow, I-usability, A-network

#4668 fix(ci): update OS patch jobs for Rust & feature changes
  .github/workflows/continous-integration-os.patch.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail

#4637 fix(build): add `beta` rust to CI
  .github/workflows/continous-integration-os.yml
Labels: A-devops, C-enhancement, P-Medium :zap:, I-build

#4656 fix(ci): Remove redundant build-chain-no-features job
  .github/workflows/continous-integration-os.patch.yml
  .github/workflows/continous-integration-os.yml
Labels: A-devops, C-cleanup, P-Low :snowflake:

#4669 fix(ci): actually create a cached state image after running a sync
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail

#4660 fix(log): Add some missing tracing spans
  zebra-network/src/address_book_updater.rs
  zebra-network/src/peer_set/candidate_set.rs
Labels: C-bug, P-Low :snowflake:, A-network, A-diagnostics

#4675 fix(ci): Split instance and volume creation out of the test job
  .github/workflows/deploy-gcp-tests.yml
Labels: A-devops, C-enhancement, P-Critical :ambulance:, I-slow, I-integration-fail, lightwalletd

#4679 fix(sync): Slightly increase some syncer defaults
  zebrad/src/components/sync.rs
  zebrad/src/config.rs
Labels: C-bug, P-High :fire:, I-slow, A-network

#4676 tests(config): Add tests for old configs
  Cargo.lock
  zebra-network/Cargo.toml
  zebra-network/src/config.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/config.rs
  zebrad/tests/common/config.toml
  zebrad/tests/common/launch.rs
Labels: P-Medium :zap:, I-usability, C-testing

#4663 fix(ci): Ignore lightwalletd hangs for now
  zebrad/tests/acceptance.rs
Labels: C-bug, A-rust, P-Critical :ambulance:, I-integration-fail, lightwalletd

#4690 refactor(ci): Split `docker run` into launch, `logs`, and `wait`
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, C-testing

#4689 Warn the user when Zebra doesn't recognize the format of `zebrad.toml`
  zebrad/src/application.rs
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:, I-usability, A-diagnostics

#4694 feat(log): Show the current network upgrade in progress logs
  Cargo.lock
  zebra-consensus/src/checkpoint.rs
  zebrad/Cargo.toml
  zebrad/src/commands/start.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/progress.rs
  zebrad/src/components/tracing.rs
  zebrad/src/components/tracing/fmt.rs
Labels: C-enhancement, C-cleanup, P-High :fire:, A-diagnostics

#4693 doc(serialize): Improve ZcashSerialize docs
  zebra-chain/src/serialization/error.rs
  zebra-chain/src/serialization/zcash_deserialize.rs
  zebra-chain/src/serialization/zcash_serialize.rs
Labels: A-docs, C-cleanup, P-Optional :sparkles:

#4667 lint(clippy): add `unwrap_in_result` lint
  .cargo/config.toml
  zebra-chain/src/amount.rs
  zebra-chain/src/block.rs
  zebra-chain/src/block/header.rs
  zebra-chain/src/block/serialize.rs
  zebra-chain/src/history_tree.rs
  zebra-chain/src/orchard/commitment.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/primitives/zcash_history.rs
  zebra-chain/src/sapling/address.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/serialization/compact_size.rs
  zebra-chain/src/serialization/date_time.rs
  zebra-chain/src/serialization/zcash_serialize.rs
  zebra-chain/src/sprout/tree.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/lock_time.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/txid.rs
  zebra-chain/src/transparent.rs
  zebra-chain/src/value_balance.rs
  zebra-chain/src/work/difficulty.rs
  zebra-chain/src/work/equihash.rs
  zebra-consensus/src/checkpoint.rs
  zebra-network/src/address_book.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/client/tests.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/protocol/external/addr/v2.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/internal/response.rs
  zebra-rpc/src/methods.rs
  zebra-script/src/lib.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/block_iter.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/chain/index.rs
  zebra-test/src/command.rs
  zebrad/src/application.rs
  zebrad/src/components/mempool/storage.rs
  zebrad/src/components/mempool/storage/verified_set.rs
  zebrad/src/components/tokio.rs
  zebrad/src/components/tracing/endpoint.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
Labels: C-cleanup, P-Low :snowflake:, C-security, I-panic, A-diagnostics

#4708 change(checkpoints): update mainnet and testnet checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-enhancement, P-Medium :zap:, I-slow

#4680 doc(features): Document optional `zebrad` features and clean up README
  README.md
  zebrad/src/config.rs
  zebrad/src/lib.rs
Labels: A-docs, C-enhancement, C-cleanup, P-Critical :ambulance:

#4714 Release Zebra 1.0.0-beta.12
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/install.md
  book/src/user/lightwalletd.md
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: P-High :fire:

#4687 fix(network messages): add limits to rejection message and reason
  zebra-network/src/protocol/external/message.rs
Labels: C-bug, P-Medium :zap:, I-remote-node-overload, A-network

#4704 fix(ci): Split Docker logs into sprout, other checkpoints, and full validation
  .github/workflows/deploy-gcp-tests.yml
Labels: A-devops, C-enhancement, P-Critical :ambulance:, I-integration-fail

#4709 fix(ci): make full sync go all the way to the tip
  zebrad/tests/acceptance.rs
  zebrad/tests/common/sync.rs
Labels: A-rust, A-devops, P-High :fire:, I-slow, C-testing, lightwalletd

#4639 fix(state): Update column family names to match Zebra's database design
  book/src/dev/rfcs/0004-asynchronous-script-verification.md
  book/src/dev/rfcs/0005-state-updates.md
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_header_by_height_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_header_by_height_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_header_by_height_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_header_by_height_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_header_by_height_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/block_header_by_height_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/column_family_names.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@no_blocks.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_loc_by_hash_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_loc_by_hash_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_loc_by_hash_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_loc_by_hash_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_loc_by_hash_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tx_loc_by_hash_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_out_loc_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_out_loc_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_out_loc_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/utxo_by_out_loc_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/chain/index.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
Labels: C-cleanup, P-Low :snowflake:, A-state, lightwalletd
