Repository ZcashFoundation/zebra, pull requests merged in 2022-02, with the labels that each got.

#3450 Restore coverage to use latest nightly
  .github/workflows/coverage.yml
Labels: A-infrastructure, A-devops, P-Low :snowflake:

#3446 refactor: address comments from #3415: Prepare for changes in ZIP-244
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/chain.rs
  zebra-consensus/src/script.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-consensus/src/transaction/tests/prop.rs
  zebra-script/src/lib.rs
Labels: P-Medium :zap:

#3453 fix(mergify): restrict merges with unresolved threads
  .github/mergify.yml
Labels: A-devops, P-Critical :ambulance:

#3454 fix(mergify): put PRs with no priority label in the low priority queue
  .github/mergify.yml
Labels: C-bug, A-devops, P-High :fire:, I-usability

#3455 fix(network): increase state concurrency and syncer lookahead
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound.rs
  zebrad/src/components/inbound/downloads.rs
  zebrad/src/components/sync/downloads.rs
Labels: C-bug, P-Low :snowflake:, I-slow, I-usability, A-network

#3255 1. Create an API for a missing inventory registry, but don't register any missing inventory yet
  zebra-chain/src/serialization/constraint.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set.rs
  zebra-network/src/peer_set/inventory_registry.rs
  zebra-network/src/peer_set/inventory_registry/tests.rs
  zebra-network/src/peer_set/inventory_registry/tests/vectors.rs
  zebra-network/src/peer_set/inventory_registry/update.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/set/tests.rs
  zebra-network/src/peer_set/set/tests/vectors.rs
  zebra-network/src/protocol/external/inv.rs
Labels: C-enhancement, P-Medium :zap:, C-security, I-remote-node-overload, I-bad-data, A-network

#3465 2. Route peer requests based on missing inventory
  zebra-consensus/src/transaction/tests.rs
  zebra-network/src/isolated/tor/tests/vectors.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/inventory_registry/tests/vectors.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/set/tests/vectors.rs
  zebra-state/src/service/non_finalized_state/queued_blocks.rs
Labels: C-enhancement, P-Medium :zap:, C-security, I-slow, I-remote-node-overload, A-network

#3479 Use string literal to format unreachable message
  zebra-chain/src/transaction/sighash.rs
Labels: A-rust, C-cleanup, P-High :fire:

#3483 Use string literal to format unreachable message in test
  zebrad/src/components/inbound/tests.rs
Labels: A-rust, C-cleanup, P-High :fire:

#3460 docs: document consensus rules from 4.4 Spend Descriptions
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-consensus/src/transaction.rs
Labels: A-docs, P-Medium :zap:

#3452 docs: document consensus rules from 4.3 JoinSplit Descriptions
  zebra-chain/src/sprout/joinsplit.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/check.rs
Labels: A-docs, P-Medium :zap:

#3463 fix(network): only send responded updates on handshake/ping/pong
  zebra-network/src/peer/handshake.rs
Labels: C-bug, I-slow, P-Optional :sparkles:, A-network

#3401 Support large block heights
  zebra-chain/src/block/height.rs
  zebra-chain/src/sapling/tests/prop.rs
  zebra-chain/src/serialization/error.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/lock_time.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/transaction/check.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-consensus/src/transaction/tests/prop.rs
  zebra-state/src/service/check/tests/anchors.rs
  zebra-state/src/service/check/tests/nullifier.rs
  zebra-state/src/service/check/tests/utxo.rs
  zebra-state/src/service/check/utxo.rs
Labels: C-bug, A-consensus, A-rust, P-Medium :zap:, C-security, I-panic

#3516 fix(actions): typo in paths filtering keyword
  .github/workflows/ci.patch.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.patch.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.patch.yml
  .github/workflows/docs.yml
  .github/workflows/lint.patch.yml
  .github/workflows/lint.yml
  .github/workflows/test.patch.yml
  .github/workflows/test.yml
  .github/workflows/zcash-params.yml
Labels: A-devops, P-Critical :ambulance:

#3495 Chain Tip Estimate Test: Log chain progress while Zebra is syncing
  zebrad/src/commands/start.rs
Labels: P-Medium :zap:, A-network, A-diagnostics, C-testing

#3466 3. Send notfound when Zebra doesn't have a block or transaction
  zebra-network/src/lib.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/peer.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests/prop.rs
  zebra-network/src/peer/connector.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer/minimum_peer_version.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/peer_set/inventory_registry.rs
  zebra-network/src/peer_set/inventory_registry/tests.rs
  zebra-network/src/peer_set/inventory_registry/tests/prop.rs
  zebra-network/src/peer_set/inventory_registry/tests/vectors.rs
  zebra-network/src/peer_set/set/tests/vectors.rs
  zebra-network/src/protocol/external/inv.rs
  zebra-network/src/protocol/internal.rs
  zebra-network/src/protocol/internal/response.rs
  zebra-network/src/protocol/internal/response_status.rs
  zebrad/src/components/inbound.rs
  zebrad/src/components/inbound/downloads.rs
  zebrad/src/components/inbound/tests.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/src/components/sync/downloads.rs
  zebrad/src/components/sync/tests/vectors.rs
Labels: C-enhancement, P-Medium :zap:, A-network

#3527 fix(network): allow more inbound than outbound connections
  Cargo.lock
  zebra-network/Cargo.toml
  zebra-network/src/config.rs
  zebra-network/src/config/tests.rs
  zebra-network/src/config/tests/vectors.rs
  zebra-network/src/constants.rs
Labels: A-dependencies, P-Medium :zap:, C-security, I-remote-node-overload, A-network

#3505 4. Avoid repeated requests to peers after partial responses or errors
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-network/src/isolated.rs
  zebra-network/src/isolated/tor.rs
  zebra-network/src/lib.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/peer.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/client/tests.rs
  zebra-network/src/peer/client/tests/vectors.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests/prop.rs
  zebra-network/src/peer/connection/tests/vectors.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer/minimum_peer_version/tests.rs
  zebra-network/src/peer_set/inventory_registry.rs
  zebra-network/src/peer_set/inventory_registry/tests/prop.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/set/tests/vectors.rs
  zebra-network/src/protocol/external/addr.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/external/types.rs
  zebra-network/src/protocol/internal.rs
  zebra-network/src/protocol/internal/request.rs
  zebra-network/src/protocol/internal/response.rs
  zebra-network/src/protocol/internal/response_status.rs
  zebra-state/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/inbound.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/tests/timing.rs
  zebrad/src/components/sync/tests/vectors.rs
Labels: C-bug, P-Medium :zap:, C-security, I-slow, I-remote-node-overload, A-network

#3537 fix(test): simplify resource conflict test to avoid CI failures
  zebrad/tests/acceptance.rs
Labels: P-High :fire:

#3541 fix(clippy): new lints in nightly Rust
  zebra-consensus/src/checkpoint/list/tests.rs
  zebra-network/src/protocol/external/codec.rs
Labels: A-rust, C-cleanup, P-Optional :sparkles:

#3543 Full chain synchronization acceptance tests
  zebrad/tests/acceptance.rs
Labels: A-rust, P-Medium :zap:, C-testing

#3542 Check coinbase data is at least 2 bytes long
  zebra-chain/src/transparent/serialize.rs
Labels: C-bug, A-consensus, NU Sprout, P-Medium :zap:, I-consensus 💥, I-bad-data

#3522 Ignore non-verack and non-version messages in handshake
  zebra-network/src/peer/handshake.rs
Labels: C-bug, P-Medium :zap:, I-slow, I-usability, A-network

#3459 refactor(test): dockerize tests and run sync in detached mode
  .github/workflows/ci.yml
  .github/workflows/coverage.patch.yml
  .github/workflows/docs.patch.yml
  .github/workflows/regenerate-stateful-test-disks.yml
  .github/workflows/test.patch.yml
  .github/workflows/test.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-devops, P-Medium :zap:

#3550 fix(test): create disk from image before mounting
  .github/workflows/test.yml
Labels: A-devops, P-Medium :zap:

#3558 fix(clippy): allow unprivileged runs of clippy
  .github/workflows/lint.yml
Labels: A-devops, P-Medium :zap:

#3557 fix(actions): allow branches with dots in the name
  .github/workflows/cd.yml
  .github/workflows/test.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-devops, P-High :fire:

#3552 fix(ci): delete a redundant "test all" job
  .github/workflows/test.yml
Labels: A-rust, A-devops, C-cleanup, P-Low :snowflake:, I-usability

#3547 Allow forcing `zebrad` to use color output
  zebrad/src/components/tracing/component.rs
  zebrad/src/config.rs
  zebrad/tests/acceptance.rs
Labels: A-devops, C-enhancement, P-Optional :sparkles:

#3525 doc(README): update README goals and performance troubleshooting
  README.md
  book/src/user/run.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, I-slow, I-usability

#3568 refactor(state): split the database module
  .github/workflows/test.yml
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/arbitrary.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/tests.rs
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
  zebra-state/src/service/finalized_state/tests.rs
  zebra-state/src/service/finalized_state/tests/prop.rs
  zebra-state/src/service/finalized_state/tests/vectors.rs
Labels: A-docs, A-rust, A-devops, C-cleanup, P-Medium :zap:

#3574 fix(ci): make the purpose of each sync test clearer
  .github/workflows/test.yml
Labels: A-docs, A-devops, P-Medium :zap:, I-usability

#3567 fix(rfc): rename some lightwalletd database types
  book/src/dev/rfcs/0005-state-updates.md
Labels: A-docs, C-design, P-Low :snowflake:

#3555 fix(test): make full sync test more accurate
  Cargo.lock
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/checkpoint/list.rs
  zebra-consensus/src/lib.rs
  zebrad/Cargo.toml
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
Labels: A-dependencies, A-devops, P-Medium :zap:, A-diagnostics, C-testing

#3562 fix(test): make full sync test more efficient
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:, I-slow, A-network, C-testing

#3580 refactor(mergify): better test requirements and merge conditions
  .github/mergify.yml
  .github/workflows/ci.patch.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.patch.yml
  .github/workflows/coverage.yml
  .github/workflows/test.patch.yml
Labels: A-devops, P-Critical :ambulance:

#3539 1. fix(state): use the new `increase_nofile_limit` function from rlimit 0.7.0
  Cargo.lock
  zebra-state/Cargo.toml
  zebra-state/src/config.rs
Labels: A-dependencies, A-rust, C-enhancement, P-Medium :zap:, I-panic, I-usability

#3592 fix(ci): also check for duplicate dependencies with optional features off
  .github/workflows/ci.yml
  deny.toml
Labels: C-bug, A-dependencies, A-devops, P-High :fire:

#3561 fix(actions): run coverage collection when pushing to main
  .github/workflows/coverage.patch.yml
  .github/workflows/coverage.yml
Labels: A-infrastructure, A-devops, P-Medium :zap:

#3606 fix(consensus): update Zebra's hard-coded blockchain checkpoint lists
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
  zebra-utils/README.md
Labels: C-enhancement, NU-5, P-High :fire:

#3578 2. refactor(state): move all RocksDB API calls to the disk_db module
  zebra-state/src/config.rs
  zebra-state/src/lib.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/arbitrary.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format.rs
Labels: C-cleanup, P-Medium :zap:, A-state

#3579 3. refactor(state): move database reads and writes to a new zebra_db module
  .github/workflows/test.yml
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/arbitrary.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
  zebra-state/src/service/tests.rs
Labels: A-devops, C-cleanup, P-Medium :zap:, A-state

#3615 security(rust): forbid non-ascii identifiers
  .cargo/config.toml
Labels: A-devops, P-Low :snowflake:, C-security, I-bad-code

#3612 doc(utils): simplify zebra-checkpoints summary
  zebra-utils/README.md
Labels: C-bug, A-docs, P-Low :snowflake:

#3619 test(lightwalletd): add a lightwalletd integration test
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:, C-testing, A-rpc

#3627 fix(test): only run lightwalletd test when the ZEBRA_TEST_LIGHTWALLETD env var is set
  zebrad/tests/acceptance.rs
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, A-rpc

#3590 4. doc(state): explain how Zebra stays below Windows open file limits
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: A-docs, C-cleanup, P-Medium :zap:, A-state

#3607 5. refactor(state): split database writes into separate functions
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
Labels: A-rust, C-cleanup, P-Medium :zap:, A-state

#3643 fix(test): check for zebrad test output in the correct order
  zebra-test/src/command.rs
  zebrad/tests/acceptance.rs
Labels: C-bug, P-High :fire:, I-integration-fail, C-testing

#3617 6. refactor(state): split database access into modules by Zebra types
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/metrics.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
Labels: C-cleanup, P-Medium :zap:, A-state
