Repository ZcashFoundation/zebra, pull requests merged in 2022-10, with the labels that each got.

#5307 1. fix(rpc): Fix slow getblock RPC (verbose=1) using transaction ID index
  zebra-rpc/src/methods.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/block.rs
  zebra-utils/zcash-rpc-diff
Labels: C-bug, P-Medium :zap:, I-slow, A-rpc

#5309 fix(ci): Reduce false positives for the `C-trivial` label
  .github/release-drafter.yml
Labels: C-bug, A-devops, C-trivial

#5313 fix(docker): Make default command work in docker images, disable optional listener ports
  docker/Dockerfile
Labels: C-bug, A-devops, P-High :fire:, C-security, I-panic, I-usability, I-privacy

#5323 Suggestion for "write non-finalized blocks": Check for block heights more efficiently
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
Labels: A-rust, C-enhancement, P-Optional :sparkles:, C-trivial

#5300 fix(clippy): Allow a clippy::bool_to_int_with_if
  zebra-rpc/src/server/tests/vectors.rs
Labels: C-bug, A-rust, C-cleanup, P-Low :snowflake:, A-diagnostics, C-trivial

#5320 fix(docker): Use correct TOML syntax in Docker zebrad.toml
  docker/Dockerfile
Labels: C-bug, A-devops, P-Medium :zap:, I-usability

#5310 fix(test): Allow more time between thread CPU slices in db_init_outside_future_executor
  zebra-test/src/mock_service.rs
  zebrad/tests/acceptance.rs
Labels: C-bug, A-rust, P-High :fire:, I-integration-fail, C-testing, C-trivial

#5322 fix(test): resolve a timing issue in mempool test
  zebrad/src/components/mempool/tests/vector.rs
Labels: C-bug, A-rust, S-needs-triage, P-Medium :zap:, C-testing, A-state, C-trivial

#5308 fix(deps): Update yanked versions of cpufeatures (orchard/aes), ed25519 (tor), and quick-xml (flamegraph)
  Cargo.lock
Labels: C-bug, A-dependencies, A-rust, P-High :fire:, C-security, I-crash, I-unsound, C-feature

#5331 ci(lint): do not fail linter on `push` events
  .github/workflows/lint.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#5330 ci(ssh): connect using `ssh-compute` action by Google
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#5314 change(doc): Update README and release checklist for the release candidate
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  README.md
Labels: A-docs, A-devops, C-enhancement, P-Medium :zap:, C-trivial

#5325 fix(test): Add a timeout to the non_blocking_logger test
  zebrad/tests/acceptance.rs
Labels: C-bug, A-rust, P-Medium :zap:, I-heavy, I-slow, I-integration-fail, C-testing, C-feature, C-trivial

#5164 fix(test): Wait for zebrad and lightwalletd to reach the tip in tests, to improve test coverage
  zebrad/tests/acceptance.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/lightwalletd/sync.rs
  zebrad/tests/common/lightwalletd/wallet_grpc.rs
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
  zebrad/tests/common/sync.rs
Labels: C-bug, A-rust, C-enhancement, P-Medium :zap:, C-testing, A-rpc

#5312 fix(docker): Add edge tag to Docker images, document when latest tag will appear
  .github/workflows/build-docker-image.yml
Labels: C-bug, A-devops, P-Medium :zap:, I-usability, C-feature, C-trivial

#5347 fix(test): resolve a timing issue in mempool test
  zebrad/src/components/mempool/tests/vector.rs
Labels: C-bug, A-rust, P-Medium :zap:, C-testing, A-state, C-trivial

#5350 fix(clippy): actually fix clippy::bool_to_int_with_if
  zebra-rpc/src/server/tests/vectors.rs
Labels: C-bug, C-cleanup, P-Low :snowflake:, A-diagnostics, C-trivial

#5355 change(docs): Add links to CI/CD docs in the zebra book's sidebar
  book/src/SUMMARY.md
  book/src/dev/continuous-delivery.md
Labels: C-bug, A-docs, P-Medium :zap:, C-trivial

#5367 ci(ssh): revert using `ssh-compute` action & increase sshd connection limit
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
  .github/workflows/lint.yml
  .github/workflows/scripts/gcp-vm-startup-script.sh
Labels: C-bug, A-infrastructure, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#5360 change(consensus): Update mainnet and testnet checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: A-consensus, C-enhancement, P-Medium :zap:, C-trivial

#5257 change(state): Write non-finalized blocks to the state in a separate thread, to avoid network and RPC hangs
  Cargo.lock
  zebra-consensus/src/chain.rs
  zebra-state/Cargo.toml
  zebra-state/src/error.rs
  zebra-state/src/service.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/block_iter.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/check/tests/anchors.rs
  zebra-state/src/service/check/tests/nullifier.rs
  zebra-state/src/service/check/tests/utxo.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/queued_blocks.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/find.rs
  zebra-state/src/service/tests.rs
  zebra-state/src/service/watch_receiver.rs
  zebra-state/src/service/write.rs
  zebra-state/src/tests/setup.rs
  zebra-state/tests/basic.rs
  zebrad/src/commands/copy_state.rs
  zebrad/src/commands/start.rs
  zebrad/src/commands/tip_height.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
  zebrad/src/components/mempool/tests/vector.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/downloads.rs
  zebrad/src/components/tracing/endpoint.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/configs/v1.0.0-rc.0.toml
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: C-bug, C-enhancement, P-High :fire:, I-slow, A-state

#5383 Release Zebra 1.0.0-rc.0
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/install.md
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: P-Medium :zap:, C-trivial

#5398 fix(test): resolve a timing issue in fake_peer_set setup
  zebrad/src/components/inbound/tests/fake_peer_set.rs
Labels: C-bug, P-High :fire:, I-integration-fail

#5378 chore(clippy): Fix clippy cast and closure warnings
  zebra-chain/src/history_tree.rs
  zebra-chain/src/orchard/shielded_data.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-network/src/protocol/external/codec.rs
Labels: C-bug, A-rust, C-cleanup, P-Low :snowflake:, C-trivial

#5397 fix(sync): Make timeouts shorter to reduce full sync times
  zebrad/src/components/sync.rs
Labels: C-bug, P-Critical :ambulance:, I-slow, I-integration-fail

#5371 ci(disk): use an official GCP image on CI VMs for disk auto-resizing, make CI & CD disks 300GB
  .github/workflows/continous-delivery.yml
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-infrastructure, A-devops, P-High :fire:, I-integration-fail, C-trivial

#5400 change(ci): Allow lwd full syncs to be triggered manually
  .github/workflows/continous-integration-docker.yml
Labels: A-devops, C-enhancement, P-Medium :zap:, C-trivial

#5399 fix(ci): Limit checkpoint and lwd full sync concurrency
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-Medium :zap:, I-slow, I-cost, C-trivial

#5410 build(deps): Remove `arrayvec` and `itoa` from `skip-tree`
  deny.toml
Labels: A-dependencies, P-Low :snowflake:, C-trivial

#5428 Suggestion for "add getblockhash rpc method" PR
  zebra-rpc/src/methods.rs
Labels: C-bug, I-bad-data, A-rpc, C-feature

#5393 ci(sync): only run the `lightwalletd` full sync on the `main` branch
  .github/workflows/continous-integration-docker.patch-always.yml
  .github/workflows/continous-integration-docker.yml
Labels: A-devops, C-enhancement, P-High :fire:, I-usability, C-trivial

#5392 docs(release): add information on how we tag and release
  book/src/dev/release-process.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, C-feature

#5327 change(state): Add block channel metrics, in preparation for block fork metrics
  grafana/block_verification.json
  zebra-state/src/service.rs
  zebra-state/src/service/queued_blocks.rs
Labels: C-enhancement, P-Low :snowflake:, A-diagnostics, A-state, C-feature, C-trivial

#5433 add(doc): Add draft audit process, and update some support docs
  README.md
  book/src/dev/audit.md
  book/src/dev/release-process.md
  book/src/user/install.md
Labels: A-docs, A-devops, P-Medium :zap:, C-feature, C-trivial

#5448 fix(ci): Use correct lwd full sync patch job name
  .github/workflows/continous-integration-docker.patch-always.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, C-trivial

#5443 change(doc): Refactor `README.md`
  README.md
Labels: C-bug, A-docs, C-enhancement, P-Low :snowflake:, C-trivial

#5391 ci(sync): increase the height of blocks for some full sync jobs
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, I-integration-fail, C-feature, C-trivial

#4967 feat(rpc): add getblockhash rpc method
  zebra-rpc/Cargo.toml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_block_hash@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_hash@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebra-state/Cargo.toml
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/block.rs
Labels: P-High :fire:, A-rpc, A-state, C-feature

#5465 fix(ci): Allow extra lookahead blocks in the verifier, state, and block commit task queues
  zebrad/src/components/sync/downloads.rs
Labels: C-bug, A-rust, P-High :fire:, I-integration-fail, C-testing, A-state

#5434 change(mempool) reject transactions with spent outpoints or nullifiers
  zebra-state/src/arbitrary.rs
  zebra-state/src/service/chain_tip.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/storage.rs
  zebrad/src/components/mempool/storage/tests/prop.rs
  zebrad/src/components/mempool/storage/tests/vectors.rs
  zebrad/src/components/mempool/tests/prop.rs
Labels: C-bug, C-enhancement, P-High :fire:, I-slow, I-usability

#5435 ci(getblocktemplate): run getblocktemplate-rpcs feature tests in CI
  .github/workflows/continous-integration-docker.yml
  .github/workflows/continous-integration-os.yml
Labels: A-devops, P-Medium :zap:, C-testing, C-feature, C-trivial

#5460 refactor(config): Move configs to components
  zebra-network/src/isolated.rs
  zebrad/Cargo.toml
  zebrad/src/application.rs
  zebrad/src/components/metrics.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/tracing.rs
  zebrad/src/components/tracing/component.rs
  zebrad/src/config.rs
  zebrad/tests/common/config.rs
Labels: P-Low :snowflake:

#5471 suggestions for list of dependencies
  book/src/dev/zebra-dependencies-for-audit.md
Labels: P-High :fire:

#5464 delete(code): remove dead code from zebra-chain
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/block/error.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/note.rs
  zebra-chain/src/orchard/note/nullifiers.rs
  zebra-chain/src/orchard/tests/vectors/key_components.rs
  zebra-chain/src/primitives/zcash_history.rs
  zebra-chain/src/sapling/commitment/test_vectors.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/note.rs
  zebra-chain/src/sapling/note/nullifiers.rs
  zebra-chain/src/sprout/note.rs
  zebra-chain/src/sprout/note/nullifiers.rs
  zebra-chain/src/transaction.rs
Labels: P-High :fire:, C-removed

#5477 fix(doc): resolve some doc warnings about unquoted HTML tags
  zebra-chain/src/orchard/shielded_data.rs
  zebra-chain/src/serialization/zcash_deserialize.rs
Labels: C-bug, A-docs, C-cleanup, P-Low :snowflake:

#5462 feat(rpc): introduce getblocktemplate rpc call with stub fields
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/coinbase.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/default_roots.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/transaction.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_block_template@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_template@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
Labels: A-rust, P-High :fire:, A-rpc, C-feature

#5480 change(ci): only run the send transaction test on the main branch
  .github/workflows/continous-integration-docker.patch-always.yml
  .github/workflows/continous-integration-docker.yml
Labels: A-devops, C-enhancement, P-Medium :zap:, I-slow, C-testing, I-cost, C-trivial

#5474 change(ci): Add patch jobs for lightwalletd build and getblocktemplate-rpcs tests
  .github/workflows/continous-integration-docker.patch.yml
  .github/workflows/zcash-lightwalletd.patch.yml
  .github/workflows/zcash-lightwalletd.yml
Labels: A-devops, C-enhancement, P-High :fire:, C-feature, C-trivial

#5486 build(deps): upgrade ed5519-zebra from 3.0.0 to 3.1.0
  Cargo.lock
  tower-batch/Cargo.toml
  zebra-chain/Cargo.toml
Labels: A-dependencies, A-rust, C-enhancement, A-cryptography, C-trivial

#5489 cleanup(clippy): Use inline format strings
  zebra-chain/src/block/tests/prop.rs
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/fmt/time.rs
  zebra-chain/src/history_tree.rs
  zebra-chain/src/sapling/arbitrary.rs
  zebra-chain/src/serialization/sha256d.rs
  zebra-chain/src/transaction/memo.rs
  zebra-chain/src/transaction/tests/prop.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-chain/src/transparent/address.rs
  zebra-chain/src/work/difficulty/tests/vectors.rs
  zebra-consensus/examples/get-params-path.rs
  zebra-consensus/src/checkpoint/list.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests/vectors.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/protocol/external/tests/vectors.rs
  zebra-network/src/protocol/internal/response.rs
  zebra-rpc/src/methods.rs
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/check/tests/nullifier.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
  zebra-test/src/command.rs
  zebra-test/src/transcript.rs
  zebra-test/tests/command.rs
  zebra-utils/src/bin/zebra-checkpoints/main.rs
  zebrad/src/application.rs
  zebrad/src/commands/generate.rs
  zebrad/src/components/mempool/storage/eviction_list.rs
  zebrad/src/components/mempool/tests/vector.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/downloads.rs
  zebrad/src/components/sync/progress.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
  zebrad/tests/common/sync.rs
Labels: C-bug, A-rust, C-cleanup, P-High :fire:, A-diagnostics, C-trivial

#5490 fix(ci): Allow extra lookahead in the verifier, state, and block commit queues
  zebrad/src/components/sync/downloads.rs
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, A-state, C-trivial

#5481 build(deps): Bump `zcash_proofs` to 0.8.0
  .codespellrc
  Cargo.lock
  README.md
  deny.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-consensus/src/transaction/tests.rs
  zebra-network/Cargo.toml
  zebra-network/src/isolated.rs
  zebra-network/src/lib.rs
  zebra-network/src/peer/handshake.rs
Labels: A-dependencies, P-High :fire:, I-slow, C-trivial

#5493 1. change(rpc): Add a mempool field to GetBlockTemplateRpcImpl, and cleanup tests
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_count@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_count@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_hash@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_hash@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_count@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_count@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
Labels: A-rust, C-enhancement, P-Medium :zap:, C-testing, A-rpc, C-feature, C-trivial

#5476 cleanup(cryptography): Remove unused shielded key and address code
  zebra-chain/src/orchard.rs
  zebra-chain/src/orchard/address.rs
  zebra-chain/src/orchard/arbitrary.rs
  zebra-chain/src/orchard/commitment.rs
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/orchard/keys/tests.rs
  zebra-chain/src/orchard/note.rs
  zebra-chain/src/orchard/note/nullifiers.rs
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/sapling.rs
  zebra-chain/src/sapling/address.rs
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/commitment/pedersen_hashes.rs
  zebra-chain/src/sapling/commitment/test_vectors.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/keys/test_vectors.rs
  zebra-chain/src/sapling/keys/tests.rs
  zebra-chain/src/sapling/note.rs
  zebra-chain/src/sapling/note/nullifiers.rs
  zebra-chain/src/sprout.rs
  zebra-chain/src/sprout/address.rs
  zebra-chain/src/sprout/keys.rs
  zebra-chain/src/sprout/note.rs
  zebra-chain/src/sprout/note/nullifiers.rs
Labels: A-rust, C-cleanup, P-High :fire:, C-security, I-consensus, A-cryptography, I-lose-funds, C-feature, C-trivial, C-removed

#5507 suggestion: Convert to transparent::Output by serializing
  zebra-chain/src/primitives/zcash_primitives.rs
Labels: P-High :fire:, A-script

#5505 deps(bump): zcash_primitives, zcash_note_encryption, zcash_encoding, orchard, and zcash_script
  Cargo.lock
  deny.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-consensus/Cargo.toml
  zebra-script/Cargo.toml
Labels: A-dependencies, C-enhancement, P-High :fire:, A-script, A-cryptography, C-trivial

#5514 docs(fix): remove task and change name suggestion in release template
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: C-bug, P-Low :snowflake:, C-trivial
