Repository ZcashFoundation/zebra, pull requests merged in 2023-03, with the labels that each got.

#6231 change(doc): Add "incompatible with nightly Rust (1.69)" to the README known issues
  CHANGELOG.md
  README.md
Labels: C-bug, A-docs, A-rust, C-enhancement, P-Low :snowflake:, I-consensus, C-feature, C-trivial, A-compatibility

#6252 change(docs): Document how to get external PRs to merge
  book/src/dev/continuous-integration.md
Labels: A-docs, A-devops, C-enhancement, P-Medium :zap:, C-trivial

#6230 fix(mempool): Stop ignoring some transaction broadcasts
  zebra-network/src/protocol/internal/request.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/gossip.rs
Labels: C-bug, P-Low :snowflake:, I-usability, lightwalletd, A-concurrency, A-mempool

#6251 change(format): improve CommitBlockError message: include underlying ValidateContextError message
  zebra-state/src/error.rs
Labels: C-bug, A-rust, C-enhancement, P-Optional :sparkles:, A-network, A-diagnostics

#6273 change(docs): Update Zebra's build instructions
  README.md
Labels: A-docs, C-enhancement, P-Low :snowflake:

#6285 fix(test): Disable `verify_generated_halo2_proofs` test
  zebra-consensus/src/primitives/halo2/tests.rs
Labels: C-bug, P-High :fire:, I-integration-fail, C-testing

#6297 Halborn 2023 02 20
  zebra-chain/src/serialization.rs
  zebra-chain/src/serialization/zcash_deserialize.rs
  zebra-network/src/peer_set/inventory_registry.rs
  zebra-network/src/peer_set/inventory_registry/tests/vectors.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/codec/tests/vectors.rs
  zebra-network/src/protocol/external/inv.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/external/tests/preallocate.rs
Labels: A-rust, P-Critical :ambulance:, C-security, A-network

#6295 feat(docs): Add elasticsearch section to Zebra book
  book/src/SUMMARY.md
  book/src/user/elastic1.png
  book/src/user/elastic2.png
  book/src/user/elastic3.png
  book/src/user/elasticsearch.md
Labels: A-docs, P-Medium :zap:, C-feature

#6320 fix(network): validate addr length before reading
  zebra-network/src/protocol/external/addr/v2.rs
Labels: C-bug, C-security, C-feature, C-audit

#6328 Fix typo
  zebra-chain/src/block/arbitrary.rs
Labels: A-docs, P-Low :snowflake:, C-trivial

#6337 change(state): Condense CodeTimer::start() and Span::current() calls in state service
  zebra-state/src/service.rs
Labels: C-enhancement, C-cleanup, P-Low :snowflake:, A-state, C-trivial

#6365 fix(ci): Switch CI to a GCP zone with available instances
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-infrastructure, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#6364 fix(ci): Split lightwalletd full sync into two jobs
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-High :fire:, I-slow, I-integration-fail, lightwalletd, C-trivial

#6368 cleanup(net): Simplify types used in `AddrV2` size check
  zebra-network/src/protocol/external/addr/v2.rs
Labels: C-cleanup, P-Low :snowflake:, A-network, C-feature, C-trivial

#6314 v1.0.0-rc.6 release
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/docker.md
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: P-High :fire:, C-trivial

#6398 fix(net): Drop Firo cryptocurrency nodes from Zebra's address book, because they are not compatible with Zcash
  zebra-network/src/peer/priority.rs
Labels: C-bug, P-Medium :zap:, C-security, I-heavy, I-slow, A-network, C-feature

#6375 Suggest making sure the RPC endpoint is enabled for checkpointing
  zebra-consensus/src/checkpoint/README.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, A-rpc

#6335 change(state): Stop re-downloading blocks that are in non-finalized side chains
  zebra-consensus/src/block.rs
  zebra-consensus/src/error.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/queued_blocks.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/find.rs
  zebrad/src/components/inbound/downloads.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/tests/timing.rs
  zebrad/src/components/sync/tests/vectors.rs
Labels: C-bug, C-enhancement, P-Medium :zap:, C-security, I-heavy, I-slow, I-usability, A-state, C-audit

#6228 feat(release): create Docker hub binary with mining enabled on release
  .github/workflows/build-docker-image.yml
  .github/workflows/release-binaries.yml
  docker/Dockerfile
Labels: A-devops, C-enhancement, P-Medium :zap:, A-rpc, C-feature, C-trivial

#6217 change(deps): Update dependencies that only appear in the lock file
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  Cargo.lock
  deny.toml
  zebra-test/tests/command.rs
Labels: C-bug, A-dependencies, C-enhancement, P-Medium :zap:, C-security, I-bad-code, C-trivial, C-audit

#6287 change(rpc): Add confirmations to getrawtransaction method response
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_raw_transaction_verbosity_0@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_raw_transaction_verbosity_0@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_raw_transaction_verbosity_1@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_raw_transaction_verbosity_1@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/queue.rs
  zebra-rpc/src/queue/tests/prop.rs
  zebra-rpc/src/tests/vectors.rs
  zebra-state/src/lib.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/block.rs
  zebra-state/src/service/read/tests/vectors.rs
Labels: C-enhancement, P-Medium :zap:, A-rpc, C-feature

#6401 fix(release): Add missing continuous deployment step to the release checklist
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: C-bug, A-docs, A-devops, C-enhancement, P-Low :snowflake:, C-feature, C-trivial

#6347 feat(script): Add binary for finding references to closed issues
  Cargo.lock
  zebra-utils/Cargo.toml
  zebra-utils/src/bin/search-issue-refs/main.rs
Labels: C-enhancement, C-cleanup, P-Medium :zap:, A-script, C-feature, C-audit

#6417 change(docs): Replaces XXX with TODO
  zebra-chain/src/block/tests.rs
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/serialization/error.rs
  zebra-consensus/src/error.rs
  zebra-network/src/constants.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/policies.rs
Labels: A-docs, C-enhancement, C-cleanup, P-Optional :sparkles:, C-trivial, C-audit

#6330 change(chain): Refactor the handling of height differences
  zebra-chain/src/block.rs
  zebra-chain/src/block/height.rs
  zebra-chain/src/chain_tip.rs
  zebra-chain/src/chain_tip/mock.rs
  zebra-chain/src/chain_tip/network_chain_tip_height_estimator.rs
  zebra-chain/src/chain_tip/tests/prop.rs
  zebra-chain/src/parameters/network.rs
  zebra-consensus/src/block/subsidy/funding_streams.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/checkpoint/list/tests.rs
  zebra-consensus/src/parameters/subsidy.rs
  zebra-rpc/src/methods/get_block_template_rpcs/constants.rs
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebra-state/src/constants.rs
  zebra-state/src/service.rs
  zebra-state/src/service/check/utxo.rs
  zebrad/src/components/inbound/downloads.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/downloads.rs
  zebrad/src/components/sync/progress.rs
Labels: A-rust, C-enhancement, C-cleanup, P-High :fire:, C-feature, C-audit
