Repository ZcashFoundation/zebra, pull requests merged in 2023-07, with the labels that each got.

#7104 fix(panic): Stop panicking on shutdown in the syncer and network init
  zebra-network/src/meta_addr/peer_addr.rs
  zebra-network/src/peer_set/initialize.rs
  zebrad/src/components/sync.rs
Labels: C-bug, P-Critical :ambulance:, I-panic, A-network, A-concurrency

#7090 Release Zebra v1.0.1
  CHANGELOG.md
  Cargo.lock
  README.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: P-Critical :ambulance:, C-trivial, A-release

#7096 fix(docs): Add a few more details to metrics book page
  book/src/user/grafana.png
  book/src/user/metrics.md
Labels: C-bug, A-docs, P-Low :snowflake:, C-feature

#7128 change(release): Update release script and check it in CI
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  .github/workflows/release-crates-io.patch.yml
  .github/workflows/release-crates-io.yml
  CHANGELOG.md
  book/src/user/docker.md
  book/src/user/install.md
  release.toml
  zebra-state/Cargo.toml
  zebrad/Cargo.toml
Labels: C-bug, C-enhancement, P-Medium :zap:, C-trivial, A-release

#7087 fix(log): Remove redundant startup logs, fix progress bar number, order, and wording
  zebra-consensus/src/checkpoint.rs
  zebra-network/src/address_book_updater.rs
  zebra-network/src/peer_set/limit.rs
  zebra-network/src/peer_set/set.rs
  zebra-state/src/service/non_finalized_state.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/sync/progress.rs
  zebrad/src/components/tracing/component.rs
Labels: C-bug, P-Low :snowflake:, I-usability, A-diagnostics, C-removed

#7135 cleanup(rust): Fix new nightly clippy warnings
  zebra-chain/src/block/height.rs
  zebra-chain/src/block/merkle.rs
  zebra-chain/src/orchard/note/ciphertexts.rs
  zebra-chain/src/primitives/proofs/bctv14.rs
  zebra-chain/src/primitives/proofs/groth16.rs
  zebra-chain/src/sapling/note/ciphertexts.rs
  zebra-chain/src/sprout/note/ciphertexts.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/value_balance/tests/prop.rs
  zebra-chain/src/work/equihash.rs
  zebra-consensus/src/checkpoint/list/tests.rs
  zebra-consensus/src/checkpoint/tests.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-network/src/config.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/protocol/external/codec/tests/vectors.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/service/read/address/tx_id.rs
  zebra-state/src/service/read/address/utxo.rs
  zebra-test/src/mock_service.rs
  zebra-utils/src/bin/search-issue-refs/main.rs
  zebrad/tests/common/checkpoints.rs
Labels: C-bug, A-rust, C-cleanup, P-Low :snowflake:, C-trivial

#7056 fix(commands): Require an argument name before the list of tracing filters when used without a subcommand
  CHANGELOG.md
  zebrad/src/commands/entry_point.rs
  zebrad/src/commands/tests.rs
Labels: C-bug, P-Low :snowflake:, I-usability, C-breaking

#7155 change(Docker): Use standard syntax for the `ENV` instruction in Dockerfile
  docker/Dockerfile
Labels: A-devops, C-enhancement, C-cleanup, P-Low :snowflake:, C-trivial

#7147 change(tests): Do round-trip tests for note commitment tree data structure and RPC serialisation
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/sprout/tree.rs
  zebra-state/src/service/finalized_state/tests/vectors.rs
Labels: C-enhancement, P-High :fire:, C-testing, A-state, C-trivial

#7086 fix(ci): Add extra patch job for `cargo deny` checks
  .github/workflows/continous-integration-os.patch.yml
Labels: C-bug, A-devops, P-Low :snowflake:, C-feature, C-trivial

#7029 fix(network): Avoid initiating outbound handshakes with IPs for which Zebra already has an active peer.
  zebra-network/src/address_book.rs
  zebra-network/src/address_book/tests/prop.rs
  zebra-network/src/address_book/tests/vectors.rs
  zebra-network/src/address_book_updater.rs
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/peer_set/candidate_set/tests/prop.rs
  zebra-network/src/peer_set/candidate_set/tests/vectors.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/peer_set/set/tests.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
Labels: C-bug, P-Low :snowflake:, C-security, I-remote-node-overload, A-network, A-concurrency, no-review-reminders, I-remote-trigger

#7162 fix(Docker): Set default `RPC_PORT`
  docker/runtime-entrypoint.sh
Labels: C-bug, A-devops, P-High :fire:

#7169 fix(ci): Increase peer cache startup wait time and test time
  zebra-network/src/peer_cache_updater.rs
  zebrad/tests/common/launch.rs
Labels: C-bug, P-High :fire:, I-integration-fail, A-network, C-testing, C-trivial

#7156 change(devops): Reduce number of dependabot PRs
  .github/dependabot.yml
  .github/workflows/lint.yml
Labels: A-dependencies, A-devops, P-Medium :zap:, I-cost, C-trivial

#7177 fix(Docker): Enable RPC port in general scenarios
  docker/runtime-entrypoint.sh
Labels: C-bug, A-devops, P-Medium :zap:, I-usability, A-rpc

#7178 add(Docker): Enable miners to set their address for mining rewards.
  docker/runtime-entrypoint.sh
Labels: A-devops, C-enhancement, P-Medium :zap:, C-feature

#7158 change(merge): Require 2 reviews for PRs with an extra-reviews label
  .github/mergify.yml
  .github/release-drafter.yml
Labels: A-devops, C-enhancement, P-Medium :zap:, C-trivial

#7196 change(release): Document the release level for RPC and command-line changes
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-docs, C-enhancement, P-Medium :zap:, C-trivial, A-release

#7208 fix(ci): Stop requiring testnet job for CI to pass
  .github/workflows/continous-delivery.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-testing, C-trivial

#6887 cleanup(consensus): Avoid blocking threads by awaiting proof verification results from rayon in async context
  zebra-consensus/src/primitives.rs
  zebra-consensus/src/primitives/ed25519.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/halo2.rs
  zebra-consensus/src/primitives/redjubjub.rs
  zebra-consensus/src/primitives/redpallas.rs
Labels: C-bug, A-consensus, P-Medium :zap:, A-cryptography, C-trivial, A-concurrency, extra-reviews

#7031 change(state): Prepare for in-place database format upgrades, but don't make any format changes yet
  .github/workflows/continous-integration-docker.yml
  .github/workflows/deploy-gcp-tests.yml
  zebra-state/src/config.rs
  zebra-state/src/constants.rs
  zebra-state/src/lib.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-test/src/command.rs
  zebrad/src/application.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/get_block_template_rpcs/get_block_template.rs
  zebrad/tests/common/get_block_template_rpcs/get_peer_info.rs
  zebrad/tests/common/get_block_template_rpcs/submit_block.rs
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/sync.rs
  zebrad/tests/common/test_type.rs
Labels: A-devops, C-enhancement, P-Medium :zap:, A-state, C-trivial, A-concurrency

#7041 fix(network): Rate-limit inbound connections per IP.
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/recent_by_ip.rs
  zebra-network/src/peer_set/initialize/recent_by_ip/tests.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
Labels: C-bug, P-Low :snowflake:, C-security, I-slow, A-network, A-concurrency, I-remote-trigger

#7217 fix(tests): Place coinbase tx as the first tx in fake child blocks
  zebra-state/src/tests.rs
Labels: C-bug, A-rust, P-Low :snowflake:, C-testing

#7200 ref(docker): organize `ENV` and `ARG` values based on their usage
  docker/Dockerfile
  docker/entrypoint.sh
  docker/runtime-entrypoint.sh
Labels: C-bug, A-devops, C-enhancement, P-High :fire:, I-usability

#7053 build(deps): update ecc dependencies for `zcashd` 5.6.0, and create legacy state format compatibility layer
  Cargo.lock
  deny.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/orchard/tree/legacy.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/sapling/tree/legacy.rs
  zebra-chain/src/sprout/tree.rs
  zebra-chain/src/sprout/tree/legacy.rs
  zebra-consensus/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/src/service/finalized_state/tests/vectors.rs
Labels: A-dependencies, A-rust, P-Medium :zap:, A-cryptography, A-compatibility

#7219 fix(panic): Stop panicking on async task cancellation on shutdown in network and state futures
  zebra-chain/Cargo.toml
  zebra-chain/src/diagnostic.rs
  zebra-chain/src/diagnostic/task.rs
  zebra-chain/src/diagnostic/task/future.rs
  zebra-chain/src/diagnostic/task/thread.rs
  zebra-network/Cargo.toml
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-state/Cargo.toml
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
Labels: C-bug, P-Medium :zap:, I-panic, I-usability, A-network, A-state, A-concurrency

#7218 fix(state): Remove workarounds for storing trees
  zebra-chain/src/block/height.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
Labels: C-bug, A-rust, P-Medium :zap:, C-testing, C-trivial

#7241 change(deps): Change dependabot actions schedule and tweak groups
  .github/dependabot.yml
Labels: A-dependencies, A-devops, P-Medium :zap:, C-trivial

#7238 cleanup(deps): Bump sha2 and secp256k1 to remove duplicate dependencies
  Cargo.lock
  deny.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/serialization/sha256d.rs
  zebra-chain/src/transparent/address.rs
Labels: A-dependencies, P-High :fire:, A-cryptography, C-trivial

#7239 change(state): Deduplicate note commitment trees in non-finalized state
  zebra-chain/src/block/height.rs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-rust, I-heavy, I-slow, A-state, C-tech-debt

#7019 add(metrics): Track mempool actions and size bucketed by weight (copy of #6972, credit @str4d)
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/unmined.rs
  zebra-chain/src/transaction/unmined/zip317.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/src/components/mempool/storage/verified_set.rs
Labels: C-enhancement, P-Medium :zap:, A-diagnostics, A-mempool

#7254 ref(issues): use newer template where applicable
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/devops_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/private_security_issue.yml
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/usability_testing_plan.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, I-usability, C-trivial

#7255 build(deps): Update dependencies for release
  Cargo.lock
  deny.toml
Labels: A-dependencies, P-Critical :ambulance:, C-trivial, A-release

#7262 change(test): Refactor the tests of non-finalized state
  zebra-chain/src/block/arbitrary.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
Labels: A-rust, C-testing, C-trivial

#7261 change(doc): Document how to upgrade the database format
  book/src/SUMMARY.md
  book/src/dev/rfcs/0005-state-updates.md
  book/src/dev/state-db-upgrades.md
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
Labels: A-docs, C-enhancement, P-Medium :zap:, A-state, C-trivial

#7265 fix(docker): Fix confusing Docker git commit hash default in Zebra logs
  docker/Dockerfile
Labels: C-bug, A-devops, P-Medium :zap:, I-usability, A-diagnostics, C-trivial

#7257 change(deps): Remove OpenSSL dependency from dev tools
  Cargo.lock
  zebra-utils/Cargo.toml
Labels: A-dependencies, C-cleanup, P-Low :snowflake:, C-trivial

#7258 fix(log): Limit verbose RPC responses in logs
  zebra-chain/src/transaction/serialize.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs
  zebra-state/src/service.rs
  zebrad/tests/common/get_block_template_rpcs/get_block_template.rs
Labels: C-cleanup, P-Low :snowflake:, I-usability, A-diagnostics, C-trivial

#7268 fix(feature): elasticsearch for the Mainnet
  zebra-state/src/service/finalized_state.rs
Labels: C-bug, P-High :fire:, I-panic, C-feature

#7259 Release Zebra v1.1.0
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: P-Critical :ambulance:, C-trivial, A-release

#7247 change(deps): Use larger dependabot groups
  .github/dependabot.yml
Labels: C-bug, A-dependencies, A-devops, P-Low :snowflake:, I-integration-fail, C-trivial

#7231 ref(docker): remove all unrequired docker arguments from CI/CD pipelines
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-delivery.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/release-binaries.yml
  .github/workflows/zcash-params.yml
Labels: A-infrastructure, A-devops, C-enhancement, P-Medium :zap:, I-usability, C-trivial

#7179 add(Docker): Docs for mining with Docker
  book/src/SUMMARY.md
  book/src/user/mining-docker.md
Labels: A-docs, A-devops, C-enhancement, P-Medium :zap:, C-feature
