Repository ZcashFoundation/zebra, pull requests merged in 2023-10, with the labels that each got.

#7662 fix(ci): wait for disk to be mounted in VM
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#7663 change(state): Stop using iterators on column families with many deletions
  zebra-state/src/service/finalized_state/disk_format/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
Labels: C-bug, P-Critical :ambulance:, I-slow, A-state

#7686 fix(ci): Replace busybox with ubuntu to avoid "device or resource busy" failures
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#7665 fix(ci): disk validation for docker volume mount
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-infrastructure, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#7620 change(ci): Create automatic tickets on CI failure for more workflows
  .github/workflows/build-crates-individually.yml
  .github/workflows/continous-delivery.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/continous-integration-os.yml
  .github/workflows/release-binaries.yml
  .github/workflows/release-crates-io.yml
Labels: A-devops, P-Low :snowflake:, C-trivial

#7684 Increase cached state disk sizes to 400 GB
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Low :snowflake:, I-integration-fail, C-trivial

#7704 fix(ci): wait for mounting and show system logs if fail
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#7690 fix(ci): handle disk mounting and logs reading edge-cases
  .github/workflows/continous-delivery.yml
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, C-enhancement, P-Critical :ambulance:, I-integration-fail, C-trivial

#7608 change(state): Put chain data into an inner struct
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-rust, P-Low :snowflake:, A-state, C-tech-debt

#7713 fix(ci): `grep` the Zcash network correctly
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-High :fire:, I-hang, I-integration-fail, C-trivial

#7644 fix(tests): Checking if transactions get into the mempool fails in lightwalletd tests
  .github/workflows/zcash-lightwalletd.yml
  zebrad/tests/common/lightwalletd/proto/service.proto
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
Labels: P-Medium :zap:, C-testing, lightwalletd, C-trivial, A-compatibility

#7709 fix: add `$DISK_NAME` to `launch-without-cached-state`
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-High :fire:, C-trivial

#7724 fix(ci): Handle new cargo machete output format for unused dependencies
  .github/workflows/continous-integration-os.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#7647 fix(rpc): Fix bugs and performance of `getnetworksolps` & `getnetworkhashps` RPCs
  zebra-chain/src/block/height.rs
  zebra-chain/src/work/difficulty.rs
  zebra-rpc/src/constants.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/constants.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/request.rs
  zebra-state/src/service/block_iter.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read/difficulty.rs
  zebra-state/src/service/read/find.rs
Labels: C-bug, P-Low :snowflake:, C-security, I-hang, I-invalid-data, A-rpc, A-compatibility

#7660 ref(docker): combine test and prod entrypoints into one
  .dockerignore
  .github/workflows/continous-integration-docker.yml
  book/src/user/docker.md
  docker/Dockerfile
  docker/entrypoint.sh
  docker/runtime-entrypoint.sh
Labels: A-devops, P-Critical :ambulance:, I-usability, C-feature, C-trivial

#7643 fix(devops): Long branch names fail CI because GCP resource name is too long
  .github/workflows/continous-integration-docker.patch-always.yml
  .github/workflows/continous-integration-docker.patch.yml
  .github/workflows/continous-integration-docker.yml
  zebra-utils/README.md
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, C-trivial

#7726 fix(deps): Remove unused dependency exceptions
  deny.toml
Labels: A-dependencies, C-cleanup, P-Low :snowflake:, C-trivial

#7615 change(ui): Enable the progress bar feature by default, but only show progress bars when the config is enabled
  Cargo.lock
  README.md
  zebra-test/Cargo.toml
  zebra-test/src/command.rs
  zebra-test/src/command/to_regex.rs
  zebrad/Cargo.toml
  zebrad/src/application.rs
  zebrad/src/components/tracing.rs
  zebrad/src/components/tracing/component.rs
  zebrad/src/lib.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/config.rs
  zebrad/tests/common/configs/v1.3.0-progress-bars.toml
Labels: C-enhancement, P-Low :snowflake:, I-usability, A-diagnostics, C-feature, C-trivial

#7734 fix(state): Limit the retrieval of note commitment subtrees
  zebra-chain/src/amount.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/value_balance.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read/tests/vectors.rs
  zebra-state/src/service/read/tree.rs
Labels: C-bug, A-consensus, P-Medium :zap:, I-integration-fail, I-invalid-data, A-state

#7742 chore: Update dependencies
  Cargo.lock
Labels: A-dependencies, P-Critical :ambulance:, C-trivial

#7741 chore: Update checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: P-Critical :ambulance:, C-trivial

#7610 chore: Release v1.3.0
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: P-Critical :ambulance:, C-trivial

#7744 fix(ci): Skip mempool checks if it wasn't queried by lightwalletd
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: P-High :fire:, I-integration-fail, C-testing, A-rpc, C-trivial

#7751 change(doc): Add instructions for new placeholder crates
  book/src/dev/crate-owners.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, C-trivial, A-release

#7616 ref(workflows): consolidate workflows based on their purpose
  .github/workflows/cd-deploy-nodes-gcp.patch.yml
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/chore-delete-gcp-resources.yml
  .github/workflows/chore-project-management.yml
  .github/workflows/ci-build-crates.patch.yml
  .github/workflows/ci-build-crates.yml
  .github/workflows/ci-coverage.patch.yml
  .github/workflows/ci-coverage.yml
  .github/workflows/ci-integration-tests-gcp.patch.yml
  .github/workflows/ci-integration-tests-gcp.yml
  .github/workflows/ci-lint.patch.yml
  .github/workflows/ci-lint.yml
  .github/workflows/ci-unit-tests-docker.patch.yml
  .github/workflows/ci-unit-tests-docker.yml
  .github/workflows/ci-unit-tests-os.patch.yml
  .github/workflows/ci-unit-tests-os.yml
  .github/workflows/continous-delivery.patch.yml
  .github/workflows/continous-integration-docker.patch-always.yml
  .github/workflows/docs-deploy-firebase.patch.yml
  .github/workflows/docs-deploy-firebase.yml
  .github/workflows/docs-dockerhub-description.yml
  .github/workflows/manual-zcashd-deploy.yml
  .github/workflows/release-binaries.yml
  .github/workflows/release-drafter.yml
  .github/workflows/sub-build-docker-image.yml
  .github/workflows/sub-build-lightwalletd.patch.yml
  .github/workflows/sub-build-lightwalletd.yml
  .github/workflows/sub-build-zcash-params.yml
  .github/workflows/sub-deploy-integration-tests-gcp.yml
  .github/workflows/sub-find-cached-disks.yml
  .github/workflows/sub-test-zebra-config.yml
  book/src/dev/continuous-integration.md
  docker/Dockerfile
  docker/entrypoint.sh
Labels: A-devops, C-enhancement, P-High :fire:, I-usability, C-trivial

#7732 change(state): Set upper bound when reading from deleting column family tx_loc_by_transparent_addr_loc
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
Labels: C-bug, P-Medium :zap:, C-security, I-slow, A-state, C-tech-debt, I-remote-trigger

#7761 change(doc): Update README.md for known progress bar issue
  README.md
Labels: C-bug, A-docs, P-Low :snowflake:, C-trivial

#7682 ref(workflows): use a single job to run GCP tests
  .github/workflows/sub-deploy-integration-tests-gcp.yml
Labels: A-infrastructure, A-devops, C-enhancement, C-cleanup, P-High :fire:, I-usability, C-trivial

#7730 fix(ci): Add missing timeouts to CI and CD tests
  .github/workflows/ci-build-crates.yml
  .github/workflows/ci-unit-tests-docker.yml
Labels: C-bug, A-devops, P-Low :snowflake:, I-cost, C-trivial

#7754 fix(ci): Limit parallel jobs launched by the crates workflow
  .github/workflows/ci-build-crates.yml
Labels: C-bug, A-devops, P-Medium :zap:, I-integration-fail, C-trivial

#7774 fix(doc): Fix an incorrect consensus-critical ZIP 212 comment
  zebra-chain/src/parameters/network.rs
Labels: C-bug, A-docs, P-Low :snowflake:, C-trivial

#7731 change(state): Set iterator read bounds where possible in DiskDb
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_db/tests.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
Labels: C-bug, P-Medium :zap:, C-security, I-slow, A-state, C-tech-debt, I-remote-trigger

#7784 build(deps): bump ECC dependencies
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/orchard/tree/legacy.rs
  zebra-chain/src/sapling/tree/legacy.rs
  zebra-chain/src/sprout/tree/legacy.rs
  zebra-consensus/Cargo.toml
  zebra-script/Cargo.toml
Labels: A-dependencies, P-Medium :zap:, A-compatibility

#7739 cleanup(state): Refactor subtree read functions to accept ranges and check memory first
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read/tests/vectors.rs
  zebra-state/src/service/read/tree.rs
Labels: C-cleanup, P-Low :snowflake:, C-testing, A-state, C-trivial

#7753 change(ci): Remove duplicate CI jobs for getblocktemplate-rpcs
  .github/workflows/ci-unit-tests-docker.patch.yml
  .github/workflows/ci-unit-tests-docker.yml
  .github/workflows/ci-unit-tests-os.patch.yml
  .github/workflows/ci-unit-tests-os.yml
  .github/workflows/release-binaries.yml
  .github/workflows/sub-build-docker-image.yml
  docker/entrypoint.sh
Labels: A-devops, C-cleanup, P-Low :snowflake:, C-trivial, extra-reviews

#7773 change(dev doc): Document how to change branch protection rules
  book/src/dev/continuous-integration.md
Labels: A-docs, A-devops, P-Low :snowflake:, C-trivial

#7806 change(doc): Document how to fix deny.toml warnings
  book/src/dev/continuous-integration.md
Labels: A-docs, A-dependencies, C-enhancement, P-Low :snowflake:

#7800 change(consensus): Build Sprout and Sapling parameters into the zebrad binary, so a download server isn't needed
  .github/workflows/ci-coverage.patch.yml
  .github/workflows/ci-coverage.yml
  .github/workflows/ci-unit-tests-os.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  book/src/dev/continuous-integration.md
  book/src/user/parameters.md
  zebra-consensus/Cargo.toml
  zebra-consensus/examples/download-params.rs
  zebra-consensus/examples/get-params-path.rs
  zebra-consensus/src/config.rs
  zebra-consensus/src/primitives/groth16/params.rs
  zebra-consensus/src/primitives/groth16/sprout-groth16.vk
  zebra-test/scripts/shutdown-errors
  zebrad/src/commands/start.rs
Labels: A-consensus, C-enhancement, P-Medium :zap:, I-usability, C-trivial

#7815 fix(doc): Fix outdated Dockerfile features comment
  docker/Dockerfile
Labels: A-devops, C-cleanup, P-Low :snowflake:, C-feature, C-trivial

#7794 docs(build): Add ECC dependencies documentation
  book/src/SUMMARY.md
  book/src/dev/ecc-updates.md
Labels: A-docs, P-Medium :zap:, C-trivial, A-compatibility

#7814 fix(ci): Increase Docker unit test timeout
  .github/workflows/sub-test-zebra-config.yml
Labels: C-bug, A-devops, P-Medium :zap:, I-integration-fail, C-trivial

#7799 change(doc): Document state format upgrade implementation and testing
  book/src/dev/state-db-upgrades.md
Labels: A-docs, C-enhancement, P-Medium :zap:, A-state, C-trivial

#7819 remove(cmd): Remove `zebrad download` command, because it no longer does anything
  .github/workflows/sub-build-zcash-params.yml
  CHANGELOG.md
  docker/Dockerfile
  docker/zcash-params/Dockerfile
  zebrad/src/commands.rs
  zebrad/src/commands/download.rs
Labels: A-devops, P-Medium :zap:, C-removal, A-cli

#7835 docs: Refactor the installation instructions for `s-nomp`
  book/src/user/mining-testnet-s-nomp.md
Labels: A-docs, P-Low :snowflake:

#7851 change(docs): Add macOS M1 as a tier 3 supported platform
  book/src/user/supported-platforms.md
Labels: A-docs, C-enhancement, P-Low :snowflake:

#7849 docs(remove): zebra icon from the state lib doc
  zebra-state/src/lib.rs
Labels: A-docs, P-Low :snowflake:

#7838 fix(doc): Fix broken links to `zebra_network` and `zebra_state` `Config` structs on doc.zebra.zfnd.org
  .github/workflows/docs-deploy-firebase.yml
  zebra-consensus/src/lib.rs
  zebra-network/src/lib.rs
  zebra-state/src/config.rs
  zebra-state/src/lib.rs
  zebrad/src/config.rs
Labels: C-bug, A-docs, P-Medium :zap:, I-usability, C-trivial

#7818 cleanup(deps): Remove unused deny.toml duplicate dependency exceptions
  deny.toml
Labels: A-dependencies, C-cleanup, P-Low :snowflake:, C-trivial

#7844 change(consensus): Remove Sprout and Sapling parameter download task and debug_skip_preload config
  book/src/user/mining-testnet-s-nomp.md
  book/src/user/startup.md
  zebra-consensus/src/config.rs
  zebra-consensus/src/router.rs
  zebra-consensus/src/router/tests.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/config.rs
  zebrad/tests/common/configs/v1.4.0.toml
  zebrad/tests/common/sync.rs
  zebrad/tests/common/test_type.rs
Labels: C-bug, A-consensus, C-cleanup, P-Medium :zap:, I-usability, C-trivial

#7853 fix(network): Reconnect with peers after brief network interruption
  zebra-network/src/peer_set/initialize.rs
Labels: C-bug, P-Medium :zap:, I-hang, I-usability, A-network

#7862 fix(docs): Fix some typos
  zebra-network/src/peer_set/candidate_set/tests/vectors.rs
  zebra-test/src/net.rs
  zebra-utils/README.md
Labels: C-trivial

#7860 cleanup(clippy): Resolve new nightly clippy and rustc lints
  zebra-chain/src/block.rs
  zebra-chain/src/transaction.rs
  zebra-network/src/peer.rs
Labels: A-rust, C-cleanup, P-Optional :sparkles:, A-diagnostics, C-trivial

#7866 chore(consensus): Update mainnet and testnet checkpoints on 2023-10-30
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: A-consensus, P-Medium :zap:, C-trivial

#7868 chore(clippy): Cleanup nightly clippy warnings from 2023-10-30
  zebra-chain/src/orchard/tests/vectors.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/tests.rs
Labels: C-cleanup, P-Low :snowflake:, A-diagnostics, C-trivial

#7830 change(ops): Update full sync test URL in release ticket template
  .github/ISSUE_TEMPLATE/release.md
Labels: A-devops, C-cleanup, P-Low :snowflake:, C-trivial

#7855 change(state): Refactor the naming of note commitment subtrees
  zebra-chain/src/subtree.rs
  zebra-rpc/src/methods.rs
  zebra-state/src/service/finalized_state/disk_format/shielded.rs
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read/tests/vectors.rs
Labels: A-docs, C-cleanup, P-Low :snowflake:, A-state, C-trivial

#7848 change(devops): Split dependency upgrades into 4 large categories
  .github/dependabot.yml
Labels: A-dependencies, A-devops, C-enhancement, C-trivial

#7884 change(doc): Delete fixed macOS known issue from README.md
  README.md
Labels: A-docs, C-cleanup, P-Medium :zap:, C-trivial, A-release
