Repository ZcashFoundation/zebra, pull requests merged in 2023-12, with the labels that each got.

#8038 change(scan): Standardise on the `shielded-scan` feature name
  zebrad/src/commands/start.rs
  zebrad/src/config.rs
  zebrad/tests/acceptance.rs
Labels: C-cleanup, P-Medium :zap:, C-feature, A-blockchain-scanner

#8040 Scan blocks with sapling keys and write the results to the database
  Cargo.lock
  zebra-scan/Cargo.toml
  zebra-scan/src/config.rs
  zebra-scan/src/init.rs
  zebra-scan/src/scan.rs
  zebra-scan/src/storage.rs
  zebra-scan/src/tests.rs
  zebra-state/src/service/chain_tip.rs
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:, C-feature, A-blockchain-scanner

#8052 clippy: fix implied iterator bounds
  zebra-network/src/address_book.rs
Labels: A-rust, C-cleanup, P-Low :snowflake:, C-trivial

#8042 change(ci): Build the crate target by itself in ci-build-crates.yml
  .github/workflows/ci-build-crates.yml
Labels: P-Medium :zap:, C-testing, I-build-fail, C-trivial, A-blockchain-scanner

#8057 change(scan): Store scanned TXIDs in "display order"
  zebra-scan/src/scan.rs
  zebra-scan/src/tests.rs
  zebra-state/src/service/finalized_state/disk_format/scan.rs
Labels: A-rust, C-enhancement, P-Medium :zap:, I-usability, A-state, A-blockchain-scanner

#8039 change(ci): Split experimental feature tests into their own step
  .github/workflows/ci-unit-tests-docker.yml
  zebra-consensus/src/router.rs
Labels: A-devops, C-cleanup, P-Low :snowflake:, C-trivial, A-blockchain-scanner

#8058 change(ci): Delete least used ci-build-crates.yml step and increase concurrency
  .github/workflows/ci-build-crates.yml
Labels: A-devops, P-Low :snowflake:, C-testing, C-trivial, A-blockchain-scanner

#8059 fix(scan): Start scanning task only if there are keys to scan
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/config.rs
  zebrad/tests/common/configs/shieldedscan-v1.5.0.toml
Labels: C-bug, P-Medium :zap:, C-feature, C-trivial, A-blockchain-scanner

#8045 change(scan): Create a function that scans one block by height, and stores the results in the database
  zebra-scan/src/scan.rs
Labels: C-cleanup, P-Medium :zap:, C-trivial, A-blockchain-scanner

#8062 change(scan): Store one transaction ID per database row, to make queries easier
  zebra-scan/src/scan.rs
  zebra-scan/src/storage.rs
  zebra-scan/src/storage/db.rs
  zebra-scan/src/storage/db/sapling.rs
  zebra-scan/src/tests.rs
  zebra-state/src/lib.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/scan.rs
Labels: C-enhancement, P-High :fire:, I-usability, C-trivial, A-blockchain-scanner

#8072 change(log): Silence verbose failed connection logs
  zebra-network/src/peer_set/initialize.rs
Labels: C-bug, P-Low :snowflake:, I-usability, A-network, A-diagnostics, C-testing

#8076 fix(rpc): Make the `verbose` argument of the `getrawtransaction` RPC optional
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/vectors.rs
Labels: C-bug, A-rust, P-Low :snowflake:, A-rpc

#8088 fix(ci): use a bigger machine for config file tests
  .github/workflows/ci-unit-tests-docker.yml
  .github/workflows/sub-test-zebra-config.yml
Labels: C-bug, A-infrastructure, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#8089 imp(ci): fix `codespell` words and ignore others
  .codespellrc
  CHANGELOG.md
  book/src/user/fork-zebra-testnet.md
Labels: C-bug, A-devops, P-Critical :ambulance:, C-trivial

#8086 chore(deps): Missed dependency updates
  Cargo.lock
  deny.toml
Labels: P-Critical :ambulance:, C-trivial, A-release

#8027 Release Zebra 1.5.0
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: P-Critical :ambulance:, C-trivial, A-release

#8009 docs(workflow): adds a description at the top of each file
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/chore-project-management.yml
  .github/workflows/ci-build-crates.yml
  .github/workflows/ci-coverage.yml
  .github/workflows/ci-integration-tests-gcp.yml
  .github/workflows/ci-lint.yml
  .github/workflows/ci-unit-tests-docker.yml
  .github/workflows/ci-unit-tests-os.yml
  .github/workflows/docs-deploy-firebase.yml
  .github/workflows/manual-zcashd-deploy.yml
  .github/workflows/release-drafter.yml
  .github/workflows/sub-build-docker-image.yml
  .github/workflows/sub-find-cached-disks.yml
  .github/workflows/sub-test-zebra-config.yml
Labels: A-docs, A-devops, P-Low :snowflake:, I-usability, C-trivial

#8083 test(scan): Add typed database format snapshots to the scanner
  zebra-chain/src/block/hash.rs
  zebra-chain/src/serialization/error.rs
  zebra-scan/Cargo.toml
  zebra-scan/src/storage/db.rs
  zebra-scan/src/storage/db/tests.rs
  zebra-scan/src/storage/db/tests/snapshot.rs
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_0_results@mainnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_0_results@mainnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_0_results@mainnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_0_results@mainnet_keys.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_0_results@testnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_0_results@testnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_0_results@testnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_0_results@testnet_keys.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@mainnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@mainnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@mainnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@mainnet_keys.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@testnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@testnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@testnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@testnet_keys.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@empty.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@mainnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@mainnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@mainnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@mainnet_keys.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@testnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@testnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@testnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@testnet_keys.snap
  zebra-state/src/service/finalized_state/disk_format/scan.rs
Labels: P-Medium :zap:, C-testing, C-trivial, A-blockchain-scanner

#8005 ref(workflow): move most scripts to their own executables
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/chore-delete-gcp-resources.yml
  .github/workflows/chore-project-management.yml
  .github/workflows/ci-build-crates.yml
  .github/workflows/ci-coverage.yml
  .github/workflows/ci-integration-tests-gcp.yml
  .github/workflows/ci-lint.yml
  .github/workflows/ci-unit-tests-docker.yml
  .github/workflows/ci-unit-tests-os.yml
  .github/workflows/docs-deploy-firebase.yml
  .github/workflows/manual-zcashd-deploy.yml
  .github/workflows/release-crates-io.yml
  .github/workflows/release-drafter.yml
  .github/workflows/scripts/gcp-delete-old-cache-images.sh
  .github/workflows/scripts/gcp-delete-old-disks.sh
  .github/workflows/scripts/gcp-delete-old-instances.sh
  .github/workflows/scripts/gcp-delete-old-templates.sh
  .github/workflows/scripts/gcp-get-available-disks.sh
  .github/workflows/scripts/gcp-get-cached-disks.sh
  .github/workflows/scripts/gcp-vm-startup-script.sh
  .github/workflows/scripts/release-crates-dry-run.sh
  .github/workflows/sub-build-docker-image.yml
  .github/workflows/sub-deploy-integration-tests-gcp.yml
  .github/workflows/sub-find-cached-disks.yml
  .github/workflows/sub-test-zebra-config.yml
Labels: A-devops, C-enhancement, P-Medium :zap:, I-usability, C-trivial

#8095 fix(doc): Add shielded-scan.md to the index
  book/src/SUMMARY.md
Labels: C-bug, A-docs, P-High :fire:, C-trivial, A-blockchain-scanner

#8080 feat(scanner): Restart scanning where left
  zebra-scan/src/config.rs
  zebra-scan/src/scan.rs
  zebra-scan/src/storage.rs
  zebra-scan/src/storage/db.rs
  zebra-scan/src/storage/db/sapling.rs
  zebra-scan/src/storage/db/tests/snapshot.rs
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@mainnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@mainnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@mainnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@mainnet_keys.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@testnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@testnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@testnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_keys@testnet_keys.snap
  zebra-scan/src/tests/vectors.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:, C-feature, A-blockchain-scanner

#8079 change(state): Allow opening the database in a read-only mode
  zebra-scan/src/init.rs
  zebra-scan/src/storage.rs
  zebra-scan/src/storage/db.rs
  zebra-scan/src/storage/db/tests.rs
  zebra-scan/src/tests/vectors.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/vectors.rs
  zebra-state/src/service/read/tests/vectors.rs
  zebra-state/src/tests/setup.rs
Labels: A-rust, C-enhancement, P-Optional :sparkles:, A-state

#8107 fix(test): Ignore segmentation fault errors when shutting down Docker in tests
  .github/workflows/sub-test-zebra-config.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, C-trivial

#8106 test: Add progress markers to the snapshot tests
  zebra-scan/src/storage.rs
  zebra-scan/src/storage/db/sapling.rs
  zebra-scan/src/storage/db/tests.rs
  zebra-scan/src/storage/db/tests/snapshot.rs
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@mainnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@mainnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@mainnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@testnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@testnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_key_1_results@testnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_tx_ids_raw_data@mainnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_tx_ids_raw_data@mainnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_tx_ids_raw_data@mainnet_2.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_tx_ids_raw_data@testnet_0.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_tx_ids_raw_data@testnet_1.snap
  zebra-scan/src/storage/db/tests/snapshots/sapling_tx_ids_raw_data@testnet_2.snap
Labels: P-Medium :zap:, C-testing, C-trivial, A-blockchain-scanner

#8104 Add a scanning results reader
  Cargo.lock
  zebra-chain/src/block/height.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-utils/Cargo.toml
  zebra-utils/README.md
  zebra-utils/src/bin/scanning-results-reader/main.rs
Labels: A-rust, P-Medium :zap:, A-blockchain-scanner

#8112 Make sure scanner database is accessed using the correct types
  zebra-chain/src/block/height.rs
  zebra-scan/src/lib.rs
  zebra-scan/src/scan.rs
  zebra-scan/src/storage.rs
  zebra-scan/src/storage/db.rs
  zebra-scan/src/storage/db/sapling.rs
  zebra-state/src/lib.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/column_family.rs
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: C-cleanup, P-Medium :zap:, A-state, C-trivial, A-blockchain-scanner

#8116 fix(workflows): mass rename worflows to fix readme badges
  .cargo/config.toml
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  .github/workflows/docs-deploy-firebase.yml
  README.md
  book/src/dev/continuous-delivery.md
  book/src/dev/continuous-integration.md
  book/src/user/docker.md
  zebra-utils/README.md
Labels: A-docs, A-devops, P-Low :snowflake:, C-trivial

#8115 Move history tree and value balance to typed column families
  zebra-chain/src/history_tree.rs
  zebra-chain/src/lib.rs
  zebra-consensus/src/lib.rs
  zebra-network/src/lib.rs
  zebra-scan/src/storage/db/sapling.rs
  zebra-state/src/lib.rs
  zebra-state/src/service/finalized_state/column_family.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebrad/src/lib.rs
Labels: A-docs, C-cleanup, P-Medium :zap:, A-state

#8121 feat(scanner): Don't scan and log if we are below sapling height
  zebra-scan/src/scan.rs
  zebrad/tests/acceptance.rs
Labels: P-Low :snowflake:, C-feature, A-blockchain-scanner

#8114 docs(shielded-scan) Improve feature docs
  README.md
  book/src/user/shielded-scan.md
  zebrad/src/lib.rs
Labels: A-docs, P-Medium :zap:, C-feature, A-blockchain-scanner

#8124 change(scan): Refactor the user documentation for scanning
  book/src/user/shielded-scan.md
  zebra-utils/README.md
Labels: A-docs, P-Low :snowflake:, A-blockchain-scanner
