Repository ZcashFoundation/zebra, pull requests merged in 2023-08, with the labels that each got.

#7296 fit(whitespace): Update CODEOWNERS
  .github/CODEOWNERS
Labels: A-devops, C-cleanup, P-Optional :sparkles:, C-trivial

#7303 fix: remove reference to old `zealous-zebra` project
  book/src/user/docker.md
  docker/Dockerfile
Labels: C-bug, A-devops, P-Critical :ambulance:, I-build-fail

#7302 fix(test): Don't include shielded data in genesis blocks
  zebra-chain/src/transaction/arbitrary.rs
Labels: C-bug, A-rust, C-testing, A-state

#7304 fix(state): Fix marking format upgrades
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
Labels: C-bug, A-rust, A-state

#7266 change(state): Insert only the first tree in each series of identical trees into finalized state
  zebra-chain/src/transaction/arbitrary.rs
  zebra-state/src/constants.rs
  zebra-state/src/service/check/anchors.rs
  zebra-state/src/service/check/tests/nullifier.rs
  zebra-state/src/service/check/tests/utxo.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshot.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/orchard_note_commitment_tree_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sapling_note_commitment_tree_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/sprout_note_commitment_tree_raw_data@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
  zebra-state/src/service/finalized_state/tests/prop.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/orchard_trees@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/orchard_trees@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/orchard_trees@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/orchard_trees@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/sapling_trees@mainnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/sapling_trees@mainnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/sapling_trees@testnet_1.snap
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshots/sapling_trees@testnet_2.snap
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/read/tree.rs
  zebra-state/src/service/write.rs
  zebra-state/src/tests/setup.rs
Labels: A-rust, P-High :fire:, I-heavy, I-slow, A-state, C-tech-debt

#7307 change(ci): Update CI to run tests with zcash/lightwalletd instead of adityapk00/lightwalletd
  .github/workflows/zcash-lightwalletd.yml
Labels: P-Low :snowflake:, C-testing, lightwalletd, C-trivial

#7309 fix(ci): Specify Testnet in jobs that require it
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-High :fire:, C-testing, C-trivial

#7315 fix(test): Update expected log in lightwalletd_full_sync test
  zebrad/tests/acceptance.rs
Labels: P-High :fire:, I-integration-fail, C-testing, lightwalletd, C-trivial

#7278 add(rpc): note tree sizes to `getblock` api
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_1@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_1@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_default@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_default@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_1@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_1@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_default@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_default@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/tests/common/lightwalletd/proto/compact_formats.proto
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
Labels: P-Medium :zap:, A-rpc, lightwalletd, C-feature

#7332 fix(ci): Update expected logs in lightwalletd_update_sync test
  zebrad/tests/acceptance.rs
Labels: P-Critical :ambulance:, I-integration-fail, lightwalletd, C-trivial

#7338 fix(docs): deploy external and internal docs with the correct path
  .github/workflows/docs.yml
  firebase.json
Labels: C-bug, A-infrastructure, A-devops, P-Critical :ambulance:, I-build-fail, C-trivial

#7339 ref(docs): consolidate docs linting and publishing
  .cargo/config.toml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
Labels: C-bug, A-devops, P-Low :snowflake:, C-trivial

#6810 fix(state): Avoid temporary failures verifying the first non-finalized block or attempting to fork the chain before the final checkpoint
  zebra-state/src/service.rs
  zebra-state/src/service/queued_blocks.rs
Labels: C-bug, A-consensus, C-cleanup, P-Medium :zap:, I-heavy, I-slow, A-state, C-tech-debt

#7367 Update issue templates to add a custom blank template
  .github/ISSUE_TEMPLATE/custom.md
Labels: P-Low :snowflake:, C-trivial

#7378 fix(docs): Simplify the docs for nodes in Sapling trees
  zebra-chain/src/sapling/tree.rs
Labels: A-docs, A-rust, P-High :fire:, C-trivial

#7381 fix(clippy): Fix clippy and rustfmt after last releases today
  zebra-chain/src/lib.rs
  zebra-consensus/src/lib.rs
  zebra-network/src/address_book.rs
  zebra-network/src/lib.rs
  zebra-state/src/lib.rs
  zebra-state/src/service/chain_tip/tests.rs
  zebrad/src/lib.rs
Labels: A-devops, P-High :fire:, I-integration-fail, C-trivial

#7384 cleanup(clippy): Fix new nightly clippy lints from July and August 2023
  deny.toml
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/transaction/check.rs
  zebra-network/src/peer/handshake.rs
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebrad/src/components/mempool/downloads.rs
Labels: A-rust, C-cleanup, P-Low :snowflake:, C-trivial

#7371 0. Add note commitment subtree types to zebra-chain
  zebra-chain/src/lib.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/parallel/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/subtree.rs
  zebra-state/src/request.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-consensus, C-enhancement, P-Medium :zap:, A-rpc, A-cryptography

#7334 change(state): Add note subtree index handling to zebra-state, but don't write them to the finalized state yet
  book/src/dev/state-db-upgrades.md
  zebra-chain/src/orchard/arbitrary.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/arbitrary.rs
  zebra-chain/src/subtree.rs
  zebra-state/src/request.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format/shielded.rs
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/column_family_names.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@mainnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@no_blocks.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@testnet_0.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/empty_column_families@testnet_2.snap
  zebra-state/src/service/finalized_state/tests/vectors.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read/tree.rs
Labels: C-enhancement, P-Medium :zap:, A-state, A-concurrency, A-compatibility

#7390 fix(ci): Show correct lightwalletd cache heights in CI cached state
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-Medium :zap:, I-integration-fail, lightwalletd, C-trivial

#7402 fix(docs): redundant links in state
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read/tree.rs
Labels: A-docs, P-High :fire:, I-build-fail, C-trivial

#7379 fix(state): Fix the deduplication of note commitment trees
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
Labels: C-bug, A-rust, P-High :fire:, A-state

#7404 fix(build): reintroduce `RUST_LOG` info
  docker/Dockerfile
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, C-trivial

#7413 fix(ci): allow to set docs build as a required test
  .github/workflows/docs.patch.yml
  .github/workflows/docs.yml
  .github/workflows/lint.patch.yml
Labels: C-bug, A-devops, P-High :fire:, I-usability, I-build-fail, C-trivial

#7414 add(docs): Mention the tree deduplication in CHANGELOG.md
  CHANGELOG.md
Labels: A-docs, C-trivial, A-release

#7419 cleanup(clippy): Fix a clippy lint and deny.toml entry after recent changes
  deny.toml
  zebra-rpc/src/server.rs
Labels: C-cleanup, P-Low :snowflake:, A-diagnostics, C-trivial

#7427 change(docs): update docs for new lightwalletd version used in Zebra
  book/src/user/lightwalletd.md
  zebra-rpc/src/constants.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/failure_messages.rs
Labels: A-docs, P-High :fire:, lightwalletd, A-compatibility

#7428 change(checkpoints): Update checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-trivial

#7429 change(deps): Run `cargo update`
  Cargo.lock
  deny.toml
  zebra-chain/src/block/tests/generate.rs
  zebra-chain/src/transaction/tests/vectors.rs
Labels: C-trivial

#7433 fix(ci): Use correct testnet checkpoint job height regex
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, C-trivial

#7434 cleanup(state): Update some outdated comments in the state & rpcs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-state/src/service/finalized_state/disk_format/chain.rs
  zebra-state/src/service/finalized_state/disk_format/shielded.rs
Labels: A-docs, C-cleanup, P-Low :snowflake:, A-state, C-trivial
