Repository ZcashFoundation/zebra, pull requests merged in 2023-05, with the labels that each got.

#6556 feat(mempool): add ZIP-317 rules to mempool
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/unmined.rs
  zebra-chain/src/transaction/unmined/zip317.rs
  zebra-chain/src/transaction/unmined/zip317/tests.rs
  zebra-consensus/src/error.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-consensus/src/transaction/tests/prop.rs
  zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/mempool/storage/tests.rs
  zebrad/src/components/mempool/storage/tests/prop.rs
  zebrad/src/components/mempool/storage/tests/vectors.rs
  zebrad/src/components/mempool/tests/vector.rs
Labels: A-consensus, A-rust, P-High :fire:, C-feature

#6594 change: Add a template for private security issues
  .github/ISSUE_TEMPLATE/private_security_issue.yml
Labels: A-docs, C-enhancement, P-Medium :zap:, C-security, C-feature, C-trivial

#6576 change(ci): Split checking for cached state disks into its own workflow
  .github/workflows/continous-integration-docker.yml
  .github/workflows/find-cached-disks.yml
Labels: A-devops, C-enhancement, P-Medium :zap:, C-trivial

#6581 change(ci): Generate testnet checkpoints in CI
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  .github/workflows/continous-integration-docker.yml
  docker/entrypoint.sh
  zebra-consensus/src/checkpoint/README.md
  zebra-utils/README.md
Labels: A-devops, C-enhancement, P-Medium :zap:, C-testing, C-trivial

#6601 feat(zebra-network): add user agent argument
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  zebra-network/src/constants.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/src/application.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
  zebrad/src/components/sync/end_of_support.rs
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
Labels: A-consensus, A-rust, P-Medium :zap:, C-feature, C-trivial, A-compatibility

#6604 fix: Avoid wrong test results for modified JoinSplits
  zebra-consensus/src/transaction/tests.rs
Labels: C-bug, P-Low :snowflake:, I-integration-fail, C-testing, A-cryptography, I-cost, C-trivial, A-concurrency

#6615 fix(ci): Update cached disk patch job name
  .github/workflows/continous-integration-docker.patch.yml
Labels: C-bug, A-devops, P-Medium :zap:, I-integration-fail, C-trivial

#6634 fix(build): sync LWD builder with our `build-docker-image.yml` workflow
  .github/workflows/zcash-lightwalletd.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, I-build-fail, C-trivial

#6645 ci: unpin specific `buildkit` version and fix deployment subnets
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-delivery.yml
  .github/workflows/deploy-gcp-tests.yml
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#6646 ci(deploy): templates do not allow the `zone` argument
  .github/workflows/continous-delivery.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: C-bug, A-infrastructure, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#6628 refactor(ci): migrate from abandoned `actions-rs/*`
  .github/workflows/build-crates-individually.patch.yml
  .github/workflows/build-crates-individually.yml
  .github/workflows/continous-integration-os.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
Labels: C-bug, A-devops, P-Medium :zap:, C-deprecation, C-trivial, C-deprecated

#6659 fix(ci): Allow testnet syncs to take longer than 6 hours
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#6660 fix(ci): Run all the duplicate dependency checks, even if one fails
  .github/workflows/continous-integration-os.yml
Labels: C-bug, A-dependencies, A-devops, P-Critical :ambulance:, C-trivial

#6664 fix(ci): Stop running multiple full syncs on different branches
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-slow, I-remote-node-overload, I-cost, C-trivial

#6632 v1.0.0-rc.8 release
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/docker.md
  deny.toml
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
  zebra-consensus/src/transaction/tests.rs
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: P-Critical :ambulance:, C-trivial

#6623 fix(clippy): Resolve nightly clippy lints
  zebra-consensus/src/transaction.rs
  zebra-network/src/peer_set/unready_service/tests/vectors.rs
  zebra-state/src/service/check/tests/nullifier.rs
Labels: C-bug, C-cleanup, P-Low :snowflake:, A-diagnostics, C-trivial

#6657 docs(release-checklist): add cargo update steps to task list
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-docs, P-Low :snowflake:, C-feature, C-trivial

#6606 change(log): Report compiler version and Zebra features when starting Zebra
  Cargo.lock
  deny.toml
  zebrad/Cargo.toml
  zebrad/build.rs
  zebrad/src/application.rs
Labels: A-dependencies, C-enhancement, P-Medium :zap:, A-diagnostics, C-feature, C-trivial

#6662 fix(log): Stop logging peer IP addresses, to protect user privacy
  zebra-network/src/address_book.rs
  zebra-network/src/config.rs
  zebra-network/src/isolated.rs
  zebra-network/src/isolated/tests/vectors.rs
  zebra-network/src/lib.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/meta_addr/peer_addr.rs
  zebra-network/src/meta_addr/tests/check.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/meta_addr/tests/vectors.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/connector.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer/priority.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/candidate_set/tests/vectors.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/peer_set/inventory_registry.rs
  zebra-network/src/peer_set/inventory_registry/tests/prop.rs
  zebra-network/src/peer_set/inventory_registry/tests/vectors.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/set/tests.rs
  zebra-network/src/peer_set/set/tests/prop.rs
  zebra-network/src/protocol/external.rs
  zebra-network/src/protocol/external/addr.rs
  zebra-network/src/protocol/external/addr/canonical.rs
  zebra-network/src/protocol/external/addr/in_version.rs
  zebra-network/src/protocol/external/addr/v1.rs
  zebra-network/src/protocol/external/addr/v2.rs
  zebra-network/src/protocol/external/arbitrary.rs
  zebra-network/src/protocol/internal/response.rs
  zebra-network/tests/acceptance.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/peer_info.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
Labels: C-bug, P-Medium :zap:, C-security, I-privacy, A-network, A-diagnostics, C-feature

#6625 fix(security): Rate-limit and size-limit peer transaction ID messages
  zebra-network/src/lib.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/protocol/external.rs
  zebra-network/src/protocol/external/inv.rs
  zebra-network/src/protocol/external/message.rs
  zebra-network/src/protocol/external/tests/preallocate.rs
  zebra-network/src/protocol/internal/request.rs
  zebrad/src/components/inbound.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/gossip.rs
  zebrad/src/components/sync/gossip.rs
Labels: C-bug, NU-5, P-High :fire:, C-security, I-usability, I-remote-node-overload, A-network, A-diagnostics, A-concurrency, A-mempool, I-remote-trigger

#6686 fix(ci): Use valid names for concurrency groups
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#6665 fix(tests): Add an integration test for error conversions from zebra-state to zebra-consensus
  zebra-consensus/src/transaction/tests.rs
  zebra-state/src/error.rs
  zebra-state/src/lib.rs
Labels: C-bug, C-enhancement, P-Low :snowflake:, C-testing, C-feature, C-trivial, C-audit

#6683 docs(book): Update Zebra book summary to include supported platforms, platform tier policy, and versioning
  book/src/SUMMARY.md
  book/src/user/run.md
  book/src/user/supported-platforms.md
Labels: A-docs, P-Low :snowflake:, C-feature

#6679 fix(security): Limit blocks and transactions sent in response to a single request
  zebrad/src/components/inbound.rs
Labels: C-bug, P-Medium :zap:, C-security, I-heavy, I-remote-node-overload, A-network, A-concurrency, A-compatibility

#6691 fix(ci): Give more time to the inbound service when queueing requests
  deny.toml
  zebra-network/src/peer/connection.rs
Labels: C-bug, P-Medium :zap:, I-integration-fail, A-network, C-trivial, A-concurrency

#6616 fix(log): Stop logging potentially sensitive user information from unmined transactions
  zebra-chain/src/transaction/unmined.rs
Labels: C-bug, P-Medium :zap:, I-privacy, A-diagnostics

#6699 fix(security): Stop panicking on state RPC or block requests with very large heights
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_hash_invalid_excessive_height@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_hash_invalid_excessive_height@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_hash_valid@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_hash_valid@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_excessive_height@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_excessive_height@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_future_height@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_future_height@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_tip_height@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_tip_height@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_invalid_excessive_end@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_invalid_excessive_end@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_invalid_excessive_start@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_invalid_excessive_start@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_valid_multi_block@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_valid_multi_block@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_valid_single_block@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_valid_single_block@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_invalid_excessive_height_verbosity_0@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_invalid_excessive_height_verbosity_0@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_invalid_excessive_height_verbosity_1@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_invalid_excessive_height_verbosity_1@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_invalid_excessive_height_verbosity_default@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_invalid_excessive_height_verbosity_default@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_invalid_excessive_height@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_invalid_excessive_height@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_valid@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_valid@testnet_10.snap
  zebra-state/src/lib.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
Labels: C-bug, P-High :fire:, C-security, I-panic, A-rpc, A-state, I-remote-trigger

#6690 change(ci): Turn CI errors into PR annotations for most CI jobs
  .github/workflows/build-crates-individually.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-delivery.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/continous-integration-os.yml
  .github/workflows/deploy-gcp-tests.yml
  .github/workflows/lint.yml
Labels: A-devops, C-enhancement, P-Low :snowflake:, A-diagnostics, C-trivial

#6697 change(docs): Refactor the system requirements
  README.md
  book/src/SUMMARY.md
  book/src/user/requirements.md
Labels: A-docs, C-enhancement, P-High :fire:

#6715 fix(test): Check for early exits in the end of support task test
  zebrad/tests/end_of_support.rs
Labels: C-bug, P-Low :snowflake:, C-testing, C-trivial

#6726 cleanup: Delete unused zebra-cli and zebra-client crates
  Cargo.lock
  Cargo.toml
  book/src/dev/overview.md
  zebra-cli/Cargo.toml
  zebra-cli/src/main.rs
  zebra-client/Cargo.toml
  zebra-client/src/lib.rs
Labels: C-bug, A-rust, A-devops, C-cleanup, P-Medium :zap:, I-integration-fail, C-trivial

#6729 fix(ci): Make job names in build-crates-individually.patch.yml consistent
  .github/workflows/build-crates-individually.patch.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, I-integration-fail, C-trivial

#6723 fix(docs): Fix some inaccuracies in Docker docs
  book/src/user/docker.md
Labels: C-bug, A-docs, A-devops, P-Low :snowflake:

#6728 cleanup(docs): Remove outdated and complex information from the README
  README.md
Labels: A-docs, C-cleanup, P-Low :snowflake:, I-usability, C-trivial, C-removed

#6736 fix(ci): Reduce number of sent transactions in tests
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: C-bug, P-High :fire:, I-integration-fail, C-testing, A-rpc, A-concurrency, A-mempool

#6704 cleanup(gossip): Use a separate named constant for the gossip interval
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/mempool/gossip.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/gossip.rs
Labels: C-cleanup, P-Low :snowflake:, A-network, C-trivial, C-tech-debt

#6737 cleanup(rust): Simplify code using closure capture in Rust 2021 edition
  zebra-consensus/src/transaction/tests.rs
  zebra-network/src/peer_set/set.rs
  zebra-rpc/src/server/tests/vectors.rs
  zebra-state/src/service/non_finalized_state.rs
Labels: A-rust, C-cleanup, P-Low :snowflake:, A-network, C-trivial

#6732 Delete outdated `TODOs` refering to closed issues
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/work/difficulty/tests/vectors.rs
  zebra-consensus/src/transaction.rs
  zebra-network/src/config.rs
  zebra-network/src/peer_set/limit.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/unready_service/tests/vectors.rs
  zebra-network/src/policies.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/message.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-state/src/config.rs
  zebra-state/src/service/check/utxo.rs
  zebra-state/src/service/finalized_state/tests/prop.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
Labels: A-docs, C-cleanup, P-Medium :zap:, C-audit

#6738 fix(net): Rate-limit MetaAddrChange::Responded from peers
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
Labels: C-bug, P-Medium :zap:, C-security, I-hang, A-network, A-concurrency, I-remote-trigger

#6755 fix(release): Allow inbound connections to Zebra running in Docker
  docker/Dockerfile
Labels: C-bug, A-devops, P-High :fire:

#6717 fix(network): Ignore out of order Address Book changes, unless they are concurrent
  zebra-network/src/address_book.rs
  zebra-network/src/constants.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/arbitrary.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/meta_addr/tests/vectors.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
Labels: C-bug, P-Medium :zap:, C-security, I-bad-data, A-network, A-concurrency, C-audit, C-tech-debt, I-remote-trigger

#6754 fix(log): Limit RPC failure log length, add details to RPC failure logs
  zebra-rpc/src/constants.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/server/rpc_call_compatibility.rs
  zebrad/tests/common/get_block_template_rpcs/submit_block.rs
Labels: C-bug, P-Low :snowflake:, I-heavy, I-usability, A-diagnostics, C-feature

#6766 change(doc): Fix TOC in `README.md` and simplify the "About" section
  README.md
Labels: C-bug, A-docs, C-enhancement, P-Low :snowflake:, C-trivial

#6710 fix(release): do not hardcode the name of our images
  .github/workflows/build-docker-image.yml
  .github/workflows/release-binaries.yml
Labels: C-bug, A-devops, C-enhancement, P-Medium :zap:, C-trivial

#6783 change(docs): Add private IP address known issue to README
  README.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, I-privacy, C-feature

#6789 fix(ci): Disable unnecessary GitHub Actions runner checks
  .github/workflows/continous-integration-os.patch.yml
  .github/workflows/continous-integration-os.yml
Labels: C-bug, A-devops, C-cleanup, P-Low :snowflake:, C-testing, C-trivial

#6787 fix(ci): Increase config test timeouts
  .github/workflows/continous-integration-docker.yml
Labels: C-bug, A-devops, P-Low :snowflake:, I-slow, C-testing, C-trivial

#6781 Replace update_chain_state_with ref with update_chain_tip_with in rustdoc
  zebra-state/src/request.rs
Labels: A-docs, P-Low :snowflake:, C-audit

#6790 fix(security): Randomly drop connections when inbound service is overloaded
  zebra-network/src/constants.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests/vectors.rs
  zebra-network/src/peer/error.rs
  zebra-test/src/mock_service.rs
Labels: C-bug, P-Medium :zap:, C-security, I-hang, A-network, C-trivial, A-concurrency, I-remote-trigger
