Repository ZcashFoundation/zebra, pull requests merged in 2023-09, with the labels that each got.

#7442 fix(state): If a format change is cancelled, also cancel the format check, and don't mark the database as upgraded
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
Labels: C-bug, P-Critical :ambulance:, I-panic, A-state, A-concurrency

#7431 Release Zebra v1.2.0
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: P-Critical :ambulance:, C-trivial, A-release

#7408 change(state): Add state requests and support code for the `z_getsubtreesbyindex` RPC
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/parallel/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/subtree.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/disk_format/shielded.rs
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/tree.rs
Labels: C-enhancement, P-Medium :zap:, A-state, lightwalletd, A-concurrency

#7436 change(rpc): Implement the `z_getsubtreesbyindex` RPC
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/trees.rs
Labels: P-Medium :zap:, A-rpc, lightwalletd, C-feature, A-compatibility

#7466 fix(rpc): Format subtree roots in little-endian order
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/tree.rs
Labels: C-bug, P-Critical :ambulance:, I-invalid-data, A-rpc, A-compatibility

#7437 change(state): Add note subtree indexes for new and existing blocks
  zebra-chain/src/block.rs
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/parallel/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/subtree.rs
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/vectors.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read/tree.rs
Labels: P-Critical :ambulance:, A-state, C-feature, A-concurrency, A-compatibility

#7440 change(state): Restrict access to types for database writes
  zebra-state/src/lib.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: C-design, A-rust, P-Optional :sparkles:, A-state, C-tech-debt

#7453 change(dev tools): Add node versions to zcash-rpc-diff
  zebra-utils/zcash-rpc-diff
Labels: P-Low :snowflake:, A-diagnostics, C-testing, C-trivial

#7468 change(devops): Tweak dependabot groups
  .github/dependabot.yml
Labels: A-dependencies, A-devops, C-cleanup, P-Low :snowflake:, C-trivial

#7454 fix(rpc): Match zcashd's getblockchaininfo capitalisation for NU5
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@testnet_10.snap
Labels: P-Optional :sparkles:, A-rpc, A-compatibility

#7496 change(docs): Add code comments to state validity test for subtree format upgrade
  zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs
Labels: C-enhancement, P-Low :snowflake:, C-testing, A-state, C-trivial, C-tech-debt

#7462 change(state): Refactor docs for `z_getsubtreesbyindex` RPC state requests
  zebra-state/src/request.rs
  zebra-state/src/service/read/tree.rs
Labels: A-docs, A-rust, P-Low :snowflake:

#7499 fix(ci): Increase test launch and shutdown times to fix CI failures
  zebrad/src/commands/start.rs
  zebrad/tests/common/launch.rs
Labels: C-bug, P-High :fire:, I-integration-fail, A-diagnostics, A-rpc, C-trivial, A-concurrency

#7500 change(dev tools): Add an OUTPUT_DATA_LINE_LIMIT to zcash-rpc-diff
  zebra-utils/zcash-rpc-diff
Labels: P-Low :snowflake:, A-diagnostics, C-testing, A-rpc, C-trivial

#7511 fix(doc): Fix typos in CHANGELOG.md
  CHANGELOG.md
Labels: A-docs, C-cleanup, P-Low :snowflake:, C-trivial

#7510 change(tools): Show zcash-cli version at the start of zcash-rpc-diff
  zebra-utils/zcash-rpc-diff
Labels: P-Low :snowflake:, C-testing, A-rpc, C-trivial

#7514 Add snapshot tests for the `z_getsubtreesbyindex` RPC
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/z_get_subtrees_by_index_for_orchard@mainnet.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_subtrees_by_index_for_orchard@testnet.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_subtrees_by_index_for_sapling@mainnet.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_subtrees_by_index_for_sapling@testnet.snap
Labels: A-rust, P-Medium :zap:, C-testing, A-rpc

#7521 Test `z_getsubtreesbyindex` using a lightwalletd gRPC request
  Cargo.lock
  zebrad/Cargo.toml
  zebrad/build.rs
  zebrad/tests/common/lightwalletd/proto/service.proto
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
Labels: P-Medium :zap:, C-testing, A-rpc, lightwalletd, A-compatibility

#7507 change(tests): Obtain lightwalletd tip from logs instead of grpc
  .github/workflows/continous-integration-docker.yml
  zebrad/tests/acceptance.rs
  zebrad/tests/common/lightwalletd/sync.rs
Labels: A-rust, P-Medium :zap:, C-testing, lightwalletd, C-trivial

#7520 feat(ci): add self hosted runner for long tests
  .github/workflows/deploy-gcp-tests.yml
Labels: A-devops, P-High :fire:, I-usability, C-feature, C-trivial

#7540 change(dev docs): Delete documentation about fixing job timeouts
  book/src/dev/continuous-integration.md
Labels: A-docs, A-devops, C-cleanup, P-Low :snowflake:, C-trivial

#7537 Add bridgetree to the ECC dependabot group
  .github/dependabot.yml
Labels: A-devops, C-cleanup, P-Low :snowflake:, C-trivial

#7519 change(dev tools): Limit diff length, and mempool check tx count and length
  zebra-utils/zcash-rpc-diff
Labels: C-cleanup, P-Low :snowflake:, A-diagnostics, C-testing, C-trivial, no-review-reminders

#7536 Create ticket template for zcashd dependency upgrades
  .github/ISSUE_TEMPLATE/zcashd_dependencies.yml
Labels: A-devops, P-Low :snowflake:, C-trivial

#7349 change(tests): update tests for new lightwalletd version used in Zebra
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: A-docs, P-Low :snowflake:, lightwalletd, C-trivial

#7555 fix(ci): Temporarily disable panic on subtree validation failure
  zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs
Labels: C-bug, P-High :fire:, I-integration-fail, A-state, C-trivial

#7562 fix(state): Compare subtrees in non-finalized chains when evaluating chain equality
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
Labels: C-bug, A-rust, P-Medium :zap:, A-state

#7560 change(ci): Label cached state disks with the disk they were updated from
  .github/workflows/deploy-gcp-tests.yml
Labels: A-devops, C-enhancement, P-Medium :zap:, A-state, C-trivial

#7567 change(doc): Refactor docs for feature flags
  README.md
  book/src/user/requirements.md
  book/src/user/tracing.md
Labels: A-docs, P-Low :snowflake:, C-feature

#7565 change(ci): Automatically open a ticket for main branch failures in the CI Docker workflow
  .github/workflows/continous-integration-docker.yml
Labels: A-devops, C-enhancement, P-Low :snowflake:, A-diagnostics, C-trivial

#7568 add(docs): add missing elasticsearch flag feature to lib docs
  book/src/user/elasticsearch.md
  zebrad/src/lib.rs
Labels: A-docs, P-Low :snowflake:, C-feature

#7552 imp(doc): add missing Docker variables and examples
  book/src/user/docker.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, I-usability

#7572 add(doc): Add instructions for changing crate owners
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  book/src/dev/crate-owners.md
Labels: A-docs, A-devops, P-Low :snowflake:, C-trivial

#7580 fix(ci): handle `tee` trying to write to a closed pipe
  .github/workflows/deploy-gcp-tests.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, C-trivial

#7587 fix(state): Handle a subtree comparison edge case correctly
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/tree.rs
Labels: C-bug, A-consensus, P-Medium :zap:, A-state, C-trivial, C-tech-debt

#7590 fix(state): Avoid panics and history tree consensus database concurrency bugs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
Labels: C-bug, A-consensus, P-Medium :zap:, I-invalid-data, A-state, A-concurrency, I-remote-trigger

#7515 tests(rpc): Add fixed test vectors for `z_getsubtreesbyindex` from zcashd to zebra
  Cargo.lock
  docker/entrypoint.sh
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
  zebrad/tests/snapshots/z_getsubtreesbyindex_mainnet_orchard_0_1.snap
  zebrad/tests/snapshots/z_getsubtreesbyindex_mainnet_orchard_338_1.snap
  zebrad/tests/snapshots/z_getsubtreesbyindex_mainnet_orchard_585_1.snap
  zebrad/tests/snapshots/z_getsubtreesbyindex_mainnet_sapling_0_1.snap
  zebrad/tests/snapshots/z_getsubtreesbyindex_mainnet_sapling_0_11.snap
  zebrad/tests/snapshots/z_getsubtreesbyindex_mainnet_sapling_1090_6.snap
  zebrad/tests/snapshots/z_getsubtreesbyindex_mainnet_sapling_17_1.snap
Labels: P-Medium :zap:, C-testing, A-rpc, lightwalletd, C-trivial

#7531 change(db): Upgrade subtrees from the tip backwards, for compatibility with wallet syncing
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
Labels: C-enhancement, P-Medium :zap:, A-state, C-trivial, A-compatibility

#7600 fix(test): Remove intermittent asserts in test
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: C-bug, P-Medium :zap:, I-integration-fail, C-testing, A-rpc, C-trivial, A-concurrency

#7591 fix(chain): Return errors instead of panicking in methods for `Height`s
  zebra-chain/src/block/height.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs
  zebra-state/src/service/non_finalized_state/chain.rs
Labels: A-rust, P-Low :snowflake:, C-tech-debt

#7602 change(state): Check database format is valid every 5 minutes, to catch format errors in new block code
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
Labels: P-Medium :zap:, C-testing, A-state, A-concurrency

#7606 change(state): Check database format is valid on shutdown, to catch format errors in new block code
  zebra-state/src/config.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
Labels: A-consensus, P-Medium :zap:, C-testing, A-state

#7609 chore: Update dependencies
  Cargo.lock
Labels: A-dependencies, C-enhancement, P-Medium :zap:, C-trivial

#7611 chore: Update checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: P-Critical :ambulance:, C-trivial

#7626 imp(workflows): use larger runners on time consuming jobs
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/coverage.yml
Labels: A-devops, P-High :fire:, I-slow, C-feature, C-trivial

#7628 fix(test): `roundtrip_sapling_tree_root` and `roundtrip_orchard_tree_root`
  zebra-state/src/service/finalized_state/disk_format/tests/prop.rs
Labels: P-Medium :zap:, C-testing, C-trivial

#7627 change(state): Only do continuous format checks in CI
  Cargo.lock
  zebra-state/Cargo.toml
  zebra-state/src/config.rs
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/config.rs
Labels: P-High :fire:, I-invalid-data, C-testing, A-state

#7612 change(release): Add "wait for a full sync" to the release checklist and ticket template
  .github/ISSUE_TEMPLATE/release.md
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-docs, P-Medium :zap:, C-trivial, A-release
