Repository ZcashFoundation/zebra, pull requests merged in 2023-04, with the labels that each got.

#6439 docs(utilities): remove old comment
  zebra-utils/src/lib.rs
Labels: A-docs, P-Low :snowflake:, C-removed

#6448 fix(mempool): Stop ignoring new transactions after the mempool is newly activated
  zebrad/src/components/mempool.rs
Labels: C-bug, P-Low :snowflake:, I-slow, I-usability, A-mempool

#6449 feat(log): Add a config for writing logs to a file
  zebrad/src/components/tracing.rs
  zebrad/src/components/tracing/component.rs
Labels: I-usability, P-Optional :sparkles:, A-diagnostics, C-feature

#6450 fix(state): Remove an outdated anchor assertion in a comment
  zebra-state/src/service/check/anchors.rs
Labels: C-bug, C-cleanup, P-Medium :zap:, A-state, C-removed, C-audit, C-tech-debt

#6416 fix(rpc): Check that mempool transactions are valid for the state's chain info in getblocktemplate
  zebra-node-services/src/mempool.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/service/chain_tip.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/tests.rs
  zebrad/src/components/mempool/tests/prop.rs
  zebrad/src/components/mempool/tests/vector.rs
Labels: C-bug, C-enhancement, P-Medium :zap:, I-usability, A-diagnostics, A-rpc, I-lose-funds, A-concurrency

#6447 security(state): Limit the number of non-finalized chains tracked by Zebra
  zebra-state/src/constants.rs
  zebra-state/src/service/check/tests/nullifier.rs
  zebra-state/src/service/check/tests/utxo.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/read/find.rs
  zebra-state/src/service/write.rs
Labels: C-bug, P-Low :snowflake:, C-security, I-unbounded-growth, A-state, A-concurrency

#6460 fix(net): Fix off-by-one error in DNS seed peer retries, and clarify logs
  zebra-network/src/config.rs
Labels: C-bug, P-Medium :zap:, A-network, A-concurrency, C-audit

#6464 fix: Inconsistent Docs for Downloading ZKP Params
  zebra-consensus/src/primitives/groth16/params.rs
Labels: C-bug, A-docs, P-Medium :zap:, C-audit

#6477 Revert "fix(net): Drop Firo cryptocurrency nodes from Zebra's address book, because they are not compatible with Zcash"
  zebra-network/src/peer/priority.rs
Labels: C-bug, P-Low :snowflake:, A-network, C-feature, A-compatibility

#6435 fix(release): Use Mergify queue freezes for releases
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: C-bug, A-docs, A-devops, P-Low :snowflake:, C-trivial

#6444 fix(script): updates search-issue-refs to group references by issue and output markdown
  zebra-utils/src/bin/search-issue-refs/main.rs
Labels: C-bug, C-enhancement, C-cleanup, P-Optional :sparkles:, A-script

#6475 fix(chain): Validate header versions when serializing blocks
  zebra-chain/src/block/serialize.rs
  zebra-chain/src/block/tests/vectors.rs
  zebra-consensus/src/checkpoint/tests.rs
Labels: C-bug, A-consensus, P-Medium :zap:, C-security, I-bad-data, C-audit

#6488 doc(net): Explain how we prioritise peer messages, and why it is secure
  zebra-network/src/peer/connection.rs
Labels: A-docs, P-Medium :zap:, C-security, A-network, A-concurrency

#6357 refactor(ci): use GitHub variables for non-sensitive info
  .github/workflows/build-crates-individually.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-delivery.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/continous-integration-os.yml
  .github/workflows/coverage.yml
  .github/workflows/delete-gcp-resources.yml
  .github/workflows/deploy-gcp-tests.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/zcash-lightwalletd.yml
  .github/workflows/zcashd-manual-deploy.yml
Labels: A-devops, C-enhancement, P-Medium :zap:, C-trivial

#6235 feat(ui): Add a terminal-based progress bar to Zebra
  Cargo.lock
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/unmined.rs
  zebra-chain/src/work/difficulty.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/checkpoint/list.rs
  zebra-consensus/src/checkpoint/types.rs
  zebra-consensus/src/config.rs
  zebra-network/Cargo.toml
  zebra-network/src/address_book.rs
  zebra-network/src/address_book_updater.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/limit.rs
  zebra-state/Cargo.toml
  zebra-state/src/config.rs
  zebra-state/src/service.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebrad/Cargo.toml
  zebrad/src/commands/start.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/src/components/mempool/storage.rs
  zebrad/src/components/mempool/storage/verified_set.rs
  zebrad/src/components/sync/progress.rs
  zebrad/src/components/tokio.rs
  zebrad/src/components/tracing.rs
  zebrad/src/components/tracing/component.rs
  zebrad/src/lib.rs
Labels: A-dependencies, I-usability, P-Optional :sparkles:, C-feature, C-trivial

#6494 fix(script): updates search-issue-refs to print permalinks with the latest commit sha on main
  zebra-utils/src/bin/search-issue-refs/main.rs
Labels: C-bug, C-enhancement, C-cleanup, P-Optional :sparkles:, A-script, C-trivial

#6486 fix(ux): Disable issue URLs for a known shutdown panic in abscissa
  deny.toml
  zebrad/src/application.rs
Labels: C-bug, P-Low :snowflake:, I-panic, I-usability, A-diagnostics, C-trivial

#6508 fix(devops): Use A-devops label for dependabot GitHub Actions PRs
  .github/dependabot.yml
Labels: C-bug, A-dependencies, A-devops, P-Low :snowflake:, C-trivial

#6513 change(state): Lookup unspent UTXOs in non-finalized state before checking disk
  zebra-state/src/service/check/utxo.rs
Labels: C-enhancement, P-Low :snowflake:, A-state, C-trivial

#6520 fix(net): Allow each initial peer to send one inbound request before disconnecting any peers
  zebrad/src/components/mempool/downloads.rs
Labels: C-bug, P-High :fire:, I-slow, I-integration-fail, A-network, A-concurrency

#6510 fix(rpc): Omit transactions with transparent coinbase spends that are immature at the next block height from block templates
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/transparent/utxo.rs
  zebra-consensus/src/error.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/check.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-state/src/lib.rs
  zebra-state/src/service.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/check/tests/utxo.rs
  zebra-state/src/service/check/utxo.rs
Labels: C-bug, A-consensus, P-High :fire:, I-consensus, A-rpc, I-lose-funds, A-concurrency

#6534 fix(net): Limit the number of leftover nonces in the self-connection nonce set
  zebra-network/src/constants.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer/handshake/tests.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/candidate_set/tests/prop.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
Labels: C-bug, P-High :fire:, C-security, I-heavy, A-network, A-concurrency, I-remote-trigger

#6521 Increase ZIP-401 mempool cost thresholds for Orchard transactions
  zebra-chain/src/transaction/unmined.rs
Labels: C-enhancement, NU-5, P-Medium :zap:, A-compatibility, A-mempool

#6542 v1.0.0-rc.7 release
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/docker.md
  tower-batch/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
  zebra-network/Cargo.toml
  zebra-network/src/constants.rs
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: P-Critical :ambulance:, C-trivial

#6537 fix(ci): Avoid inbound service overloads in tests
  zebra-consensus/src/chain.rs
  zebra-network/src/constants.rs
  zebra-network/src/peer/connection.rs
  zebrad/src/commands/start.rs
  zebrad/tests/common/sync.rs
Labels: C-bug, P-High :fire:, I-hang, I-integration-fail, A-network, C-testing, A-state, I-cost, C-trivial, A-concurrency

#6565 change(release): Add arborist and comms summaries to the release checklist
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
Labels: A-docs, C-enhancement, P-Low :snowflake:, C-feature, C-trivial

#6566 fix(net): Avoid a rare panic when a connection is dropped
  zebra-network/src/peer/client.rs
Labels: C-bug, P-Low :snowflake:, C-security, I-panic, A-network, A-concurrency, I-remote-trigger

#6516 change(utils): Add a direct connection mode to zebra-checkpoints
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/block.rs
  zebra-chain/src/block/height.rs
  zebra-chain/src/block/height/json_conversion.rs
  zebra-chain/src/transaction/unmined/zip317.rs
  zebra-chain/src/transparent.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/checkpoint/list/tests.rs
  zebra-node-services/Cargo.toml
  zebra-node-services/src/lib.rs
  zebra-node-services/src/rpc_client.rs
  zebra-rpc/Cargo.toml
  zebra-utils/Cargo.toml
  zebra-utils/README.md
  zebra-utils/src/bin/zebra-checkpoints/args.rs
  zebra-utils/src/bin/zebra-checkpoints/main.rs
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/get_block_template_rpcs/get_block_template.rs
  zebrad/tests/common/get_block_template_rpcs/get_peer_info.rs
  zebrad/tests/common/get_block_template_rpcs/submit_block.rs
  zebrad/tests/common/lightwalletd/sync.rs
  zebrad/tests/common/mod.rs
Labels: A-rust, C-enhancement, P-Medium :zap:, A-rpc, C-feature, A-compatibility

#6575 fix(testnet): `listen_addr` default deserialization
  zebra-network/src/config.rs
Labels: C-bug, P-Low :snowflake:, I-usability

#6550 change(ci): Generate mainnet checkpoints in CI
  .github/workflows/build-docker-image.yml
  .github/workflows/continous-integration-docker.patch.yml
  .github/workflows/continous-integration-docker.yml
  .github/workflows/release-binaries.yml
  Cargo.lock
  docker/Dockerfile
  docker/entrypoint.sh
  zebra-test/src/command.rs
  zebra-utils/src/bin/zebra-checkpoints/main.rs
  zebra-utils/tests/build_utils_for_zebrad_tests.rs
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
  zebrad/tests/common/checkpoints.rs
  zebrad/tests/common/failure_messages.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
  zebrad/tests/common/lightwalletd/sync.rs
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
  zebrad/tests/common/mod.rs
  zebrad/tests/common/sync.rs
Labels: A-consensus, A-devops, C-enhancement, P-Medium :zap:, C-testing, A-rpc, C-trivial

#6567 fix(net): Reject nodes using ZClassic ports, and warn if configured with those ports
  zebra-network/src/peer.rs
  zebra-network/src/peer/priority.rs
  zebra-network/src/peer_set/initialize.rs
Labels: C-bug, P-Low :snowflake:, C-security, I-slow, I-usability, A-network, A-diagnostics, A-compatibility

#6579 fix(log): Fix confusing comments and error messages in zebra-checkpoints
  zebra-consensus/src/checkpoint/list/tests.rs
  zebra-utils/src/bin/zebra-checkpoints/main.rs
Labels: C-bug, A-docs, P-Low :snowflake:, A-diagnostics, C-trivial

#6582 fix(ci): Delete mainnet and testnet disks separately
  .github/workflows/delete-gcp-resources.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, I-cost, C-trivial

#6585 change(mempool): Refactor the ZIP-317 minimum fee rate calculation to use usize
  zebra-chain/src/transaction/unmined/zip317.rs
Labels: C-enhancement, C-cleanup, P-Medium :zap:, A-compatibility, A-mempool

#6351 feat(zebrad): Refuse to run zebrad when release is too old
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  Cargo.lock
  book/src/dev/release-process.md
  book/src/user/run.md
  zebra-network/src/constants.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/Cargo.toml
  zebrad/src/application.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/end_of_support.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/failure_messages.rs
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
  zebrad/tests/end_of_support.rs
Labels: A-rust, P-Low :snowflake:, C-deprecation, I-usability, C-feature, C-trivial, C-breaking
