Repository ZcashFoundation/zebra, pull requests merged in 2023-11, with the labels that each got.

#7885 change(deps): `cargo update` on commit bd06294 on 2023-11-01
  Cargo.lock
  deny.toml
  zebra-state/src/service/finalized_state.rs
Labels: A-dependencies, C-cleanup, P-Medium :zap:, C-trivial, A-release

#7886 change(docs): Replace doc.zebra.zfnd.org API documentation with docs.rs
  .github/workflows/docs-deploy-firebase.patch.yml
  .github/workflows/docs-deploy-firebase.yml
  CHANGELOG.md
  README.md
  book/src/api.md
  book/src/dev.md
  book/src/dev/overview.md
  book/src/dev/rfcs/0004-asynchronous-script-verification.md
  book/src/dev/rfcs/0005-state-updates.md
  book/src/user/lightwalletd.md
  book/src/user/metrics.md
  book/src/user/requirements.md
  book/src/user/run.md
  book/src/user/startup.md
  book/src/user/tracing.md
  book/src/user/troubleshooting.md
  zebra-chain/src/lib.rs
  zebra-consensus/src/lib.rs
  zebra-network/src/lib.rs
  zebra-rpc/src/config.rs
  zebra-rpc/src/lib.rs
  zebra-script/src/lib.rs
  zebra-state/src/lib.rs
  zebra-test/src/lib.rs
  zebra-utils/README.md
  zebra-utils/src/lib.rs
  zebrad/src/commands/generate.rs
  zebrad/src/lib.rs
  zebrad/tests/common/configs/getblocktemplate-v1.0.0-rc.1.toml
  zebrad/tests/common/configs/getblocktemplate-v1.0.0-rc.2.toml
  zebrad/tests/common/configs/getblocktemplate-v1.0.0-rc.3.toml
  zebrad/tests/common/configs/getblocktemplate-v1.0.0-rc.4.toml
  zebrad/tests/common/configs/getblocktemplate-v1.0.0-rc.5.toml
  zebrad/tests/common/configs/getblocktemplate-v1.0.0-rc.9.toml
  zebrad/tests/common/configs/getblocktemplate-v1.0.1.toml
  zebrad/tests/common/configs/v1.0.0-beta.12.toml
  zebrad/tests/common/configs/v1.0.0-beta.13.toml
  zebrad/tests/common/configs/v1.0.0-beta.15.toml
  zebrad/tests/common/configs/v1.0.0-rc.0.toml
  zebrad/tests/common/configs/v1.0.0-rc.2.toml
  zebrad/tests/common/configs/v1.0.0-rc.4.toml
  zebrad/tests/common/configs/v1.0.0-rc.9.toml
  zebrad/tests/common/configs/v1.0.1.toml
  zebrad/tests/common/configs/v1.3.0-progress-bars.toml
  zebrad/tests/common/configs/v1.4.0.toml
Labels: A-docs, C-cleanup, P-Medium :zap:, C-trivial

#7869 fix(net): Add outer timeouts for critical network operations to avoid hangs
  zebra-network/src/peer/connection.rs
  zebrad/Cargo.toml
  zebrad/src/components/inbound.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/crawler.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/downloads.rs
Labels: C-bug, P-Medium :zap:, I-hang, A-network, A-concurrency

#7883 doc(devops): Explain how to change branch protection rules
  book/src/dev/continuous-integration.md
Labels: A-docs, A-devops, C-enhancement, P-Low :snowflake:, C-trivial

#7817 change(release): Make the latest tag point to the production build, rather than the build with experimental features
  .github/workflows/ci-unit-tests-os.yml
  .github/workflows/release-binaries.yml
  .github/workflows/sub-build-docker-image.yml
  CHANGELOG.md
Labels: A-devops, P-Medium :zap:, I-usability, C-removal, C-feature, C-trivial, A-release

#7832 change(pr): Add an author checklist to the PR template
  .github/pull_request_template.md
Labels: A-devops, P-Medium :zap:, C-trivial

#7900 fix(ci): In config tests, look for the config being successfully loaded by Zebra
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/ci-unit-tests-docker.yml
Labels: C-bug, P-Critical :ambulance:, C-testing, C-trivial

#7902 fix(net): Fix a potential hang caused by accessing the address book directly
  zebra-network/src/address_book/tests/vectors.rs
  zebra-network/src/address_book_updater.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/tests/vectors.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
Labels: C-bug, P-Low :snowflake:, I-panic, I-hang, A-network, A-concurrency

#7901 cleanup(ci): Delete unused cached state patch job
  .github/workflows/ci-unit-tests-docker.patch.yml
Labels: A-devops, C-cleanup, P-Low :snowflake:, P-Critical :ambulance:, C-trivial

#7911 Release Zebra 1.4.0
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: P-Critical :ambulance:, C-trivial, A-release

#7912 cleanup(net): Delete duplicate negotiated version code
  zebra-network/src/peer/handshake.rs
Labels: C-cleanup, P-Low :snowflake:, A-network, C-trivial

#7917 change(release): Only allow releases from the `main` branch, and update workflow names
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  Cargo.toml
Labels: C-cleanup, P-Low :snowflake:, C-trivial, A-release

#7758 poc(scanner): get started with the blockchain scanner proof of concept
  Cargo.lock
  Cargo.toml
  zebra-scan/Cargo.toml
  zebra-scan/src/lib.rs
  zebra-scan/src/tests.rs
Labels: A-rust, P-High :fire:, C-trivial, A-blockchain-scanner

#7923 change(state): Make the types for finalized blocks consistent
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/parallel/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-chain/src/sprout/tree.rs
  zebra-state/src/request.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/vectors.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
Labels: A-rust, C-enhancement, P-Low :snowflake:, A-state, C-tech-debt

#7916 poc(scanner): add a populated state test for ZECpages viewing key
  zebra-scan/src/tests.rs
Labels: P-Medium :zap:, C-testing, C-trivial, A-blockchain-scanner

#7933 docs(fix): update the node version in debian install details
  book/src/user/mining-testnet-s-nomp.md
Labels: A-docs, P-Low :snowflake:

#7940 cleanup(clippy): Remove unnecessary `try_into()` with `cargo clippy --fix`
  zebra-chain/src/orchard/keys.rs
  zebra-chain/src/sapling/arbitrary.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/primitives/halo2/tests.rs
  zebra-network/src/constants.rs
  zebra-script/src/lib.rs
  zebra-state/src/service/check/utxo.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-utils/src/bin/zebra-checkpoints/main.rs
  zebrad/src/components/mempool/crawler/tests/timing.rs
  zebrad/src/components/sync/tests/timing.rs
  zebrad/tests/common/checkpoints.rs
Labels: A-rust, C-cleanup, P-Low :snowflake:, C-trivial

#7942 feat(scanner): Add a very basic RAM database to store keys and scan results
  zebra-scan/Cargo.toml
  zebra-scan/src/lib.rs
  zebra-scan/src/storage.rs
  zebra-scan/src/tests.rs
Labels: P-Medium :zap:, C-feature, A-blockchain-scanner

#7949 feat(config): Allow to add keys to be scanned by the zebra-scan crate to config
  Cargo.lock
  zebra-scan/Cargo.toml
  zebra-scan/src/config.rs
  zebra-scan/src/lib.rs
  zebrad/Cargo.toml
  zebrad/src/config.rs
Labels: P-Medium :zap:, C-feature, A-blockchain-scanner

#7859 fix(net): Fix potential network hangs, and reduce code complexity
  zebra-chain/src/diagnostic/task.rs
  zebra-chain/src/diagnostic/task/future.rs
  zebra-chain/src/diagnostic/task/thread.rs
  zebra-network/src/peer/client.rs
  zebra-network/src/peer/error.rs
  zebra-network/src/peer/load_tracked_client.rs
  zebra-network/src/peer_set/inventory_registry.rs
  zebra-network/src/peer_set/inventory_registry/tests/prop.rs
  zebra-network/src/peer_set/inventory_registry/update.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/set/tests/vectors.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
Labels: C-bug, P-Medium :zap:, I-hang, A-network, I-remote-trigger

#7952 security: Limit how many addresses we use from each peer address message
  zebra-network/src/constants.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests/prop.rs
  zebra-network/src/peer_set/candidate_set.rs
Labels: P-Medium :zap:, C-security, I-invalid-data, A-network, I-remote-trigger

#7955 security: Rate limit GetAddr responses
  zebra-network/src/address_book.rs
  zebra-network/src/address_book/tests/prop.rs
  zebra-network/src/constants.rs
  zebra-network/src/protocol/internal/response.rs
  zebrad/src/components/inbound.rs
  zebrad/src/components/inbound/cached_peer_addr_response.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
Labels: P-Medium :zap:, C-security, A-network, I-remote-trigger

#7972 fix(db): Fix a sprout/history tree read panic in Zebra 1.4.0, which only happens before the 25.3.0 state upgrade completes
  zebra-state/src/service/finalized_state/disk_format/upgrade/fix_tree_key_type.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
Labels: C-bug, P-High :fire:, I-panic, A-state, A-concurrency

#7976 doc(net): Document how outbound handshakes are rate-limited
  zebra-network/src/peer_set/candidate_set.rs
  zebra-network/src/peer_set/initialize.rs
Labels: A-docs, C-cleanup, P-Low :snowflake:, C-trivial, A-concurrency

#7977 security(net): Stop sending peer addresses from handshakes directly to the address book
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests.rs
  zebra-network/src/peer/handshake.rs
Labels: P-Medium :zap:, C-security, I-invalid-data, A-network, I-remote-trigger

#7995 docs(testing): Add a testnet forking tutorial
  book/src/SUMMARY.md
  book/src/user/fork-zebra-testnet.md
Labels: A-docs, P-Low :snowflake:, C-testing, C-trivial

#7989 feat(zebra-scan): Connect with zebrad
  Cargo.lock
  zebra-scan/Cargo.toml
  zebra-scan/src/lib.rs
  zebra-scan/src/scan.rs
  zebra-scan/src/storage.rs
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
Labels: P-Medium :zap:, C-feature, A-concurrency, A-blockchain-scanner

#8000 fix(ci): Use correct check for external repositories
  .github/workflows/cd-deploy-nodes-gcp.patch-external.yml
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/ci-integration-tests-gcp.patch-external.yml
  .github/workflows/ci-integration-tests-gcp.yml
  .github/workflows/ci-lint.yml
  .github/workflows/ci-unit-tests-docker.patch-external.yml
  .github/workflows/ci-unit-tests-docker.yml
  .github/workflows/docs-deploy-firebase.patch-external.yml
  .github/workflows/docs-deploy-firebase.yml
Labels: C-bug, A-devops, P-Critical :ambulance:, C-trivial

#8010 dependabot(change): Exclude hyper from production dependabot upgrades
  .github/dependabot.yml
Labels: A-dependencies, P-Medium :zap:, C-trivial

#8002 change(state): Expose ZebraDb methods that can create different kinds of databases
  zebra-state/Cargo.toml
  zebra-state/src/config.rs
  zebra-state/src/constants.rs
  zebra-state/src/lib.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/chain.rs
  zebra-state/src/service/finalized_state/disk_format/shielded.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/vectors.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/shielded.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/read/tests/vectors.rs
  zebrad/src/application.rs
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/checkpoints.rs
  zebrad/tests/common/lightwalletd/wallet_grpc_test.rs
Labels: C-enhancement, P-Medium :zap:, A-state, C-trivial, A-blockchain-scanner

#7994 Create a `scan_block` function to use across scanning tasks
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-scan/Cargo.toml
  zebra-scan/src/scan.rs
  zebra-scan/src/tests.rs
Labels: A-rust, P-Medium :zap:, A-blockchain-scanner

#8016 Revert "dependabot(change): Exclude hyper from production dependabot upgrades"
  .github/dependabot.yml
Labels: C-bug, A-devops, P-Medium :zap:, C-trivial

#8029 fix(ci): Temporarily disable validating dependabot
  .github/workflows/ci-lint.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, C-trivial

#8024 change(ci): When building crates individually, build all targets, and run clippy
  .github/workflows/ci-build-crates.patch.yml
  .github/workflows/ci-build-crates.yml
  .github/workflows/ci-lint.yml
  zebra-scan/Cargo.toml
  zebra-scan/src/scan.rs
  zebra-scan/src/tests.rs
  zebrad/tests/common/config.rs
Labels: C-bug, A-devops, P-High :fire:, I-build-fail, C-trivial, A-blockchain-scanner

#8034 change(zebra-scan): Scan only one key per backend call
  zebra-scan/src/scan.rs
  zebra-scan/src/tests.rs
Labels: P-Medium :zap:, A-blockchain-scanner

#8031 change(scan): Create a scanner storage database, but don't use it yet
  Cargo.lock
  zebra-consensus/src/config.rs
  zebra-network/src/config.rs
  zebra-rpc/src/config.rs
  zebra-scan/Cargo.toml
  zebra-scan/src/config.rs
  zebra-scan/src/init.rs
  zebra-scan/src/lib.rs
  zebra-scan/src/scan.rs
  zebra-scan/src/storage.rs
  zebra-scan/src/storage/db.rs
  zebra-scan/src/tests.rs
  zebra-state/src/config.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/mempool/config.rs
  zebrad/src/components/metrics.rs
  zebrad/src/components/sync.rs
  zebrad/src/config.rs
Labels: C-enhancement, P-Medium :zap:, A-state, A-blockchain-scanner

#8036 change(scan): Use the on-disk database for keys and results
  zebra-scan/src/init.rs
  zebra-scan/src/lib.rs
  zebra-scan/src/scan.rs
  zebra-scan/src/storage.rs
  zebra-scan/src/storage/db.rs
  zebra-scan/src/storage/db/sapling.rs
  zebra-scan/src/tests.rs
  zebra-state/src/lib.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/scan.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/finalized_state/zebra_db/arbitrary.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
Labels: C-enhancement, P-Medium :zap:, A-state, A-blockchain-scanner
