Repository ZcashFoundation/zebra, pull requests merged in 2024-04, with the labels that each got.

#8389 fix(feature): Change database logs to human readable forms
  Cargo.lock
  zebra-state/Cargo.toml
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: I-usability, C-feature, P-Low :snowflake:

#8394 chore: Update checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-trivial, A-release, P-Medium :zap:

#8384 add(rpc): Add block times to verbose output of `getblock` RPC method
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/errors.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_block_invalid_excessive_height_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_invalid_excessive_height_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
Labels: C-enhancement, I-usability, A-rpc, A-state, P-Low :snowflake:

#8396 Release v1.6.1
  .github/workflows/scripts/release-crates-dry-run.sh
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: C-trivial, A-release, P-Critical :ambulance:

#8402 build(deps): bump the prod group with 21 updates
  Cargo.lock
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, C-trivial, P-Low :snowflake:

#8368 add(consensus/network): Add an empty `Parameters` struct in `Network::Testnet`
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/history_tree.rs
  zebra-chain/src/history_tree/tests/vectors.rs
  zebra-chain/src/parameters.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests/prop.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/parameters/tests.rs
  zebra-chain/src/primitives/address.rs
  zebra-chain/src/primitives/zcash_history/tests/vectors.rs
  zebra-chain/src/primitives/zcash_note_encryption.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-chain/src/sapling/tests/tree.rs
  zebra-chain/src/sprout/tests/tree.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-chain/src/transparent/address.rs
  zebra-chain/src/transparent/arbitrary.rs
  zebra-chain/src/transparent/tests/vectors.rs
  zebra-chain/src/work/difficulty.rs
  zebra-chain/src/work/difficulty/tests/vectors.rs
  zebra-consensus/src/block/subsidy/funding_streams.rs
  zebra-consensus/src/block/subsidy/funding_streams/tests.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/checkpoint/list.rs
  zebra-consensus/src/checkpoint/list/tests.rs
  zebra-consensus/src/checkpoint/tests.rs
  zebra-consensus/src/parameters/subsidy.rs
  zebra-consensus/src/router.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-grpc/src/tests/snapshot.rs
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
  zebra-network/src/isolated/tests/vectors.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/protocol/external/types.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-scan/src/service/scan_task/scan.rs
  zebra-scan/src/storage/db/tests/snapshot.rs
  zebra-state/src/service/arbitrary.rs
  zebra-state/src/service/check/difficulty.rs
  zebra-state/src/service/finalized_state/disk_format/chain.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshot.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/vectors.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
  zebra-state/tests/basic.rs
  zebra-utils/src/bin/scanning-results-reader/main.rs
  zebrad/src/components/mempool/storage/tests/vectors.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/checkpoints.rs
  zebrad/tests/common/configs/v1.7.0.toml
Labels: A-consensus, A-network, NU-6, C-testing, C-feature, P-Medium :zap:

#8409 fix(elasticsearch): Zebra panics with all features and no elasticsearch server available
  zebra-state/src/service/finalized_state.rs
Labels: I-panic, C-feature, P-Low :snowflake:

#8398 add(consensus): Adds Sapling HRPs as fields on `testnet::Parameters`
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/testnet.rs
Labels: A-consensus, C-enhancement, NU-6, C-testing, C-trivial, P-Medium :zap:

#8383 add(consensus): Add `activation_heights` field to `NetworkParameters` and implement `Parameters` for `Network`
  zebra-chain/src/parameters/arbitrary.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/primitives/zcash_note_encryption.rs
  zebra-network/src/config.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-scan/src/service/scan_task/scan.rs
  zebra-utils/src/bin/scanning-results-reader/main.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/configs/v1.7.0.toml
Labels: A-consensus, C-enhancement, I-usability, A-network, NU-6, C-testing, C-feature, P-Medium :zap:

#8400 Bump `chrono` from 0.4.34 to 0.4.38
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/block/tests/generate.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-state/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, C-trivial, P-Low :snowflake:

#8393 bump(zcash_script): Bump zcash script v0.1.15 and restore Windows support
  .github/workflows/ci-unit-tests-os.yml
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-rpc/src/server/tests/vectors.rs
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/tests/acceptance.rs
Labels: A-dependencies, A-compatibility

#8423 bump(deps): Update what we can from the prod group of deps
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, C-trivial, P-Medium :zap:

#8429 change(release): Adjust estimated release interval and end of support
  README.md
  book/src/dev/release-process.md
  zebrad/src/components/sync/end_of_support.rs
Labels: A-release, P-Low :snowflake:

#8460 fix(rpc): Avoid possibly returning data from different blocks in `z_get_treestate` RPC method
  zebra-rpc/src/methods.rs
Labels: A-rpc, A-concurrency, P-Low :snowflake:

#8462 fix(test): Increases timeout for non-blocking logger test
  zebrad/tests/acceptance.rs
Labels: C-testing, C-trivial, P-Optional :sparkles:

#8413 add(consensus/network): Adds `new_regtest()` constructors to `testnet::Parameters` and `Network`
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-network/src/config.rs
  zebrad/tests/common/configs/v1.7.0.toml
Labels: A-network, NU-6, C-testing, C-feature, C-trivial, P-Medium :zap:

#8468 change(test): Disables `rejection_restores_internal_state_genesis` test on Windows
  zebra-state/src/service/non_finalized_state/tests/prop.rs
Labels: C-testing, C-trivial, P-Medium :zap:

#8421 add(consensus): Adds `disable_pow` and `genesis_hash` fields, converts `equihash::Solution` to an enum
  zebra-chain/src/block.rs
  zebra-chain/src/block/genesis.rs
  zebra-chain/src/block/genesis/block-regtest-0-000-000.txt
  zebra-chain/src/history_tree.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/work/arbitrary.rs
  zebra-chain/src/work/equihash.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/checkpoint/list.rs
  zebra-consensus/src/checkpoint/list/tests.rs
  zebrad/tests/acceptance.rs
Labels: A-consensus, C-enhancement, A-network, NU-6, C-testing, C-feature, P-Medium :zap:
