Repository ZcashFoundation/zebra, pull requests merged in 2024-06, with the labels that each got.

#8578 fix(ci): Add missing jobs to workflows patch
  .github/workflows/cd-deploy-nodes-gcp.patch-external.yml
  .github/workflows/cd-deploy-nodes-gcp.patch.yml
  .github/workflows/ci-unit-tests-docker.patch-external.yml
  .github/workflows/ci-unit-tests-docker.patch.yml
  .github/workflows/ci-unit-tests-os.patch.yml
Labels: C-bug, A-devops, I-integration-fail, C-trivial, P-Critical :ambulance:

#8568 build(ecc):Upgrade remaining ECC dependencies
  Cargo.lock
  deny.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/primitives/address.rs
  zebra-chain/src/primitives/viewing_key/sapling.rs
  zebra-chain/src/primitives/zcash_note_encryption.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-grpc/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-scan/src/lib.rs
  zebra-scan/src/service/scan_task/commands.rs
  zebra-scan/src/service/scan_task/scan.rs
  zebra-scan/src/service/scan_task/scan/scan_range.rs
  zebra-scan/src/tests.rs
  zebra-scan/src/tests/vectors.rs
  zebra-utils/Cargo.toml
  zebra-utils/src/bin/scanning-results-reader/main.rs
Labels: A-dependencies, C-trivial, A-concurrency, A-compatibility, A-blockchain-scanner, P-Medium :zap:

#8602 fix: General conditional compilation attributes
  CHANGELOG.md
  tower-batch-control/Cargo.toml
  zebra-network/src/isolated.rs
  zebra-network/src/lib.rs
  zebrad/Cargo.toml
Labels: extra-reviews, P-Critical :ambulance:, rust

#8374 feat(build): use Docker Build Cloud for image build
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/ci-tests.yml
  .github/workflows/sub-build-docker-image.yml
Labels: A-infrastructure, A-devops, C-enhancement, I-cost, C-feature, C-trivial, P-High 🔥

#8595 change(state): Add an init function for a standalone `ReadStateService`
  zebra-state/src/arbitrary.rs
  zebra-state/src/lib.rs
  zebra-state/src/service.rs
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/finalized_state.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshot.rs
  zebra-state/src/service/finalized_state/tests/prop.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
  zebra-state/src/tests/setup.rs
Labels: A-state, P-Medium :zap:

#8594 change(scan): Remove support for starting the scanner at `zebrad` startup
  .github/workflows/sub-ci-integration-tests-gcp.yml
  CHANGELOG.md
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
Labels: C-trivial, A-blockchain-scanner, P-Medium :zap:, rust

#8611 fix(lint): fix a new lint for the last clippy version
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/serialization/tests/preallocate.rs
  zebra-chain/src/work/difficulty/arbitrary.rs
Labels: I-build-fail, C-trivial, P-High 🔥

#8612 fix(codespell): typos
  book/src/dev/rfcs/0009-zebra-client.md
  zebra-grpc/src/tests/snapshot.rs
Labels: A-docs, I-build-fail, P-Low :snowflake:

#8597 fix(openapi): Remove trailing characters in descriptions
  CHANGELOG.md
  openapi.yaml
  zebra-utils/src/bin/openapi-generator/main.rs
Labels: A-docs, A-rpc, C-trivial, P-Medium :zap:

#8591 chore: Update the PR template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: C-trivial, P-Low :snowflake:

#8614 fix: Stop using `displaydoc`
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/amount.rs
  zebra-chain/src/value_balance.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/router.rs
  zebra-script/Cargo.toml
  zebra-script/src/lib.rs
  zebra-test/src/command/arguments/tests.rs
Labels: C-bug, C-trivial, P-High 🔥, rust

#8566 zebra_script: update to new zcash_script callback API
  Cargo.lock
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/primitives/zcash_note_encryption.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-script/Cargo.toml
  zebra-script/src/lib.rs
Labels: A-script, P-Medium :zap:, rust

#8615 chore: Bump `zcash_primitives`, `orchard` and `zcash_proofs`
  CHANGELOG.md
  Cargo.lock
  deny.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
Labels: A-dependencies, C-trivial, rust

#8616 fix(openapi): Add defaults to rpc methods where needed
  CHANGELOG.md
  Cargo.lock
  openapi.yaml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/get_mining_info.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/peer_info.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/submit_block.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/subsidy.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/unified_address.rs
  zebra-rpc/src/methods/trees.rs
  zebra-utils/Cargo.toml
  zebra-utils/src/bin/openapi-generator/main.rs
Labels: A-docs, A-rpc, C-trivial, P-Low :snowflake:

#8631 fix(ci): do not silently fail integration tests
  .github/workflows/sub-ci-integration-tests-gcp.yml
Labels: C-bug, A-devops, I-integration-fail, C-trivial, P-Critical :ambulance:

#8624 fix(tests): Address port conflict issues and enable related Windows tests
  zebra-grpc/src/server.rs
  zebra-grpc/src/tests/snapshot.rs
  zebra-grpc/src/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebra-rpc/src/server/tests/vectors.rs
  zebra-scan/src/init.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/config.rs
Labels: C-testing, C-trivial, P-High 🔥

#8637 add(support): Include Windows as a tier2 supported platform
  CHANGELOG.md
  book/src/user/supported-platforms.md
Labels: A-docs, C-trivial, P-High 🔥

#8641 change(deps): Initializes `cargo vet` in Zebra
  supply-chain/audits.toml
  supply-chain/config.toml
  supply-chain/imports.lock
Labels: A-dependencies, P-Low :snowflake:

#8643 chore: Manually update dependencies
  Cargo.lock
  deny.toml
Labels: A-dependencies, C-trivial, P-Medium :zap:

#8638 change(chain): Drop transactions with unpaid actions
  CHANGELOG.md
  zebra-chain/src/transaction/unmined/zip317.rs
  zebra-chain/src/transaction/unmined/zip317/tests.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs
Labels: A-rpc, A-mempool, P-Medium :zap:

#8629 change(consensus): Lower mandatory checkpoint height
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/tests/prop.rs
Labels: A-consensus, P-Low :snowflake:

#8652 chore: Update checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-trivial, P-Medium :zap:

#8636 add(book): Describes custom Testnets in the Zebra book
  CHANGELOG.md
  book/src/SUMMARY.md
  book/src/user/custom-testnets.md
  book/src/user/regtest.md
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-network/src/config.rs
  zebrad/tests/common/configs/v1.8.0.toml
Labels: A-docs, C-trivial, P-Low :snowflake:

#8656 fix(test): Increase expected height in sync-past-checkpoint test
  zebrad/tests/acceptance.rs
Labels: C-testing, C-trivial, P-Medium :zap:

#8654 Refactor `README.md` and docs
  README.md
  book/src/user/install.md
  book/src/user/troubleshooting.md
Labels: A-docs, C-trivial, A-release, P-High 🔥
