Repository ZcashFoundation/zebra, pull requests merged in 2024-05, with the labels that each got.

#8425 add(chain): Impl `zcash_protocol::consensus::Parameters` for `Network`
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/primitives.rs
  zebra-chain/src/primitives/address.rs
Labels: A-blockchain-scanner, P-Medium :zap:, rust

#8475 add(consensus): Adds block construction and validation for NU5 from block height 1 for Regtest
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/history_tree.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/work/difficulty.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/checkpoint/list/tests.rs
  zebra-consensus/src/parameters/subsidy.rs
  zebra-consensus/src/transaction/check.rs
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_difficulty_invalid_populated@testnet_10.snap
  zebra-state/src/service.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/check/difficulty.rs
  zebra-state/src/service/read/difficulty.rs
  zebra-state/src/service/read/find.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/sync.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/configs/v1.7.0.toml
  zebrad/tests/common/mod.rs
  zebrad/tests/common/regtest.rs
Labels: A-consensus, NU-6, C-trivial, P-Medium :zap:

#8488 feat(network): Configurable external address for Version network messages
  zebra-network/src/config.rs
  zebra-network/src/peer/handshake.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/config.rs
Labels: A-network, C-feature, P-Low :snowflake:

#8433 change(ci): Updates dependabot.yml
  .github/dependabot.yml
Labels: A-dependencies, A-devops, C-trivial, P-Medium :zap:

#8493 release(checkpoints): Checkpoints for release 1.7.0
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-trivial

#8494 fix(dependabot): Typo in dependabot yaml
  .github/dependabot.yml
Labels: A-dependencies, A-devops, C-trivial, P-Critical :ambulance:

#8498 release(dependencies): Run `cargo update`
  Cargo.lock
  deny.toml
Labels: C-trivial, P-Critical :ambulance:

#8504 change(config): Allow square brackets in network config listen addr and external addr
  zebra-network/src/config.rs
Labels: I-usability, P-Optional :sparkles:

#8491 fix(consensus): Update `median_timespan()` method to align with zcashd implementation
  zebra-state/src/service/check/difficulty.rs
Labels: C-bug, I-consensus, C-trivial, P-Medium :zap:

#8505 change(consensus): Allow configurable NU5 activation height on Regtest
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-consensus/src/checkpoint/list/tests.rs
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs
  zebra-utils/src/bin/block-template-to-proposal/main.rs
  zebrad/src/components/miner.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/get_block_template_rpcs/get_block_template.rs
  zebrad/tests/common/regtest.rs
Labels: A-consensus, NU-6, C-testing, C-trivial, P-Medium :zap:

#8477 add(consensus): Add `slow_start_{interval/shift}` fields to `testnet::Parameters`
  zebra-chain/src/parameters.rs
  zebra-chain/src/parameters/constants.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/parameters/subsidy.rs
Labels: A-consensus, C-cleanup, NU-6, C-trivial, P-Medium :zap:

#8506 change(mining): Restores parts of the internal-miner feature for use on Regtest
  zebra-chain/src/work/equihash.rs
  zebra-rpc/src/config/mining.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/miner.rs
Labels: I-usability, NU-6, C-testing, C-feature, C-trivial, P-Medium :zap:

#8530 change(release): Reduce the end of support time from 20 weeks to 16 weeks
  CHANGELOG.md
  book/src/dev/release-process.md
  zebrad/src/components/sync/end_of_support.rs
Labels: C-trivial, A-release, P-Medium :zap:

#8518 add(consensus): Add a `target_difficulty_limit` field on `testnet::Parameters`
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/work/difficulty.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/lib.rs
  zebrad/tests/common/regtest.rs
Labels: A-consensus, NU-6, C-testing, C-trivial, P-Medium :zap:

#8551 change(test): Disables several tests on Windows to avoid port conflicts
  zebra-grpc/src/tests/snapshot.rs
  zebra-grpc/src/tests/vectors.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-rpc/src/server/tests/vectors.rs
  zebrad/tests/acceptance.rs
Labels: C-testing, C-trivial, P-Medium :zap:

#8524 add(network): Adds a network magic field to `testnet::Parameters` and the config
  zebra-chain/src/parameters.rs
  zebra-chain/src/parameters/constants.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/magic.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/codec/tests/vectors.rs
  zebra-network/src/protocol/external/types.rs
  zebra-state/src/service/read/address/utxo.rs
  zebrad/tests/common/configs/v1.8.0.toml
Labels: A-network, NU-6, C-testing, C-trivial, P-Medium :zap:

#8533 fix(rpc): Refactor the serialization of note commitment trees
  Cargo.lock
  zebra-chain/src/orchard/tree.rs
  zebra-chain/src/sapling/tree.rs
  zebra-rpc/Cargo.toml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_by_hash@custom_testnet.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_by_non_existent_hash@custom_testnet.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_empty_Sapling_treestate@custom_testnet.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_excessive_block_height@custom_testnet.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_no_treestate@custom_testnet.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_unparsable_hash_or_height@custom_testnet.snap
  zebra-rpc/src/methods/tests/snapshots/z_get_treestate_valid@mainnet_10.snap
  zebra-rpc/src/methods/trees.rs
  zebra-utils/src/bin/openapi-generator/main.rs
Labels: C-bug, I-usability, A-rpc, P-Medium :zap:, rust

#8526 add(book): Adds a section on Regtest usage to the Zebra book
  book/src/SUMMARY.md
  book/src/user/regtest.md
  zebrad/Cargo.toml
  zebrad/src/application.rs
  zebrad/src/commands/start.rs
Labels: A-docs, I-usability, C-trivial, P-Medium :zap:
