Repository ZcashFoundation/zebra, pull requests merged in 2024-10, with the labels that each got.

#8910 fix(actions): do not require a cached state for disk regeneration
  .github/workflows/sub-deploy-integration-tests-gcp.yml
Labels: A-devops, I-integration-fail, I-build-fail, C-trivial, P-Critical :ambulance:

#8913 fix(network): Respond to getheaders requests with a maximum of 160 block headers
  zebra-state/src/constants.rs
  zebra-state/src/request.rs
  zebra-state/src/service.rs
Labels: C-bug, A-network, P-Medium :zap:

#8914 change(consensus): Updates post-NU6 Major Grants funding stream address on Mainnet
  zebra-chain/src/parameters/network/subsidy.rs
Labels: A-consensus, NU-6, P-Medium :zap:

#8921 Suggestion for "feat(regtest): Add regtest halving interval and port test"
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-network/src/config.rs
Labels: C-feature, C-trivial

#8924 release(checkpoints): Update checkpoints for `2.0.0.-rc.0`
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-trivial, A-release, P-High 🔥

#8918 build(deps): Upgrade ECC crates for Zebra `v2.0.0-rc.0` release candidate
  Cargo.lock
  Cargo.toml
  deny.toml
  supply-chain/audits.toml
  supply-chain/config.toml
  zebra-chain/Cargo.toml
  zebra-scan/Cargo.toml
Labels: A-dependencies, NU-6, C-trivial, A-compatibility, P-High 🔥

#8888 feat(regtest): Add regtest halving interval and port test
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-network/src/config.rs
  zebra-rpc/qa/base_config.toml
  zebra-rpc/qa/pull-tester/rpc-tests.py
  zebra-rpc/qa/rpc-tests/nuparams.py
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info_future_nu6_height@nu6testnet_10.snap
Labels: C-testing, C-feature, C-trivial, A-compatibility, P-Medium :zap:

#8928 fix(bug): Fixes panic in `new_regtest()`
  zebra-chain/src/parameters/network/testnet.rs
Labels: C-bug, I-panic, C-trivial, P-Critical :ambulance:

#8942 fix(actions): run `get-disk-name` on all workflow events
  .github/workflows/cd-deploy-nodes-gcp.yml
Labels: C-bug, A-devops, I-integration-fail, C-trivial, P-Critical :ambulance:

#8950 fix(clippy): Resolve new clippy lints and use renamed type from Rust std lib
  zebra-chain/src/transaction/serialize.rs
  zebra-test/src/lib.rs
Labels: A-rust, C-cleanup, C-trivial

#8953 fix(codespell): Ignore some directories
  .codespellrc
Labels: C-cleanup, C-trivial, P-Low :snowflake:

#8940 fix(rpc): Refactor the cookie-based RPC authentication
  zebra-rpc/src/server.rs
  zebra-rpc/src/server/cookie.rs
  zebra-rpc/src/server/http_request_compatibility.rs
Labels: C-security, A-rpc, C-feature, A-compatibility, P-Medium :zap:, rust

#8956 fix(build): Update Zebra's MSRV and use the latest Rust Docker image
  docker/Dockerfile
  zebrad/Cargo.toml
Labels: A-rust, A-devops, C-cleanup, C-trivial, P-High 🔥

#8900 feat(rpc): Cookie auth system for the RPC endpoint
  Cargo.lock
  zebra-rpc/Cargo.toml
  zebra-rpc/qa/base_config.toml
  zebra-rpc/src/config.rs
  zebra-rpc/src/server.rs
  zebra-rpc/src/server/cookie.rs
  zebra-rpc/src/server/http_request_compatibility.rs
  zebra-rpc/src/server/tests/vectors.rs
  zebrad/tests/common/config.rs
  zebrad/tests/common/configs/v2.0.0-rc.0.toml
Labels: C-security, A-rpc, C-feature, A-compatibility, P-Medium :zap:

#8949 fix(docs): Fix NU6-related documentation
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/subsidy/funding_streams.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/error.rs
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_future_nu6_height@nu6testnet_10.snap
Labels: C-bug, A-docs, C-enhancement, NU-6, C-trivial, P-Medium :zap:

#8960 change: Set NU6 Mainnet activation height and network protocol version
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-consensus/src/block/subsidy/funding_streams/tests.rs
  zebra-network/src/constants.rs
  zebra-network/src/protocol/external/types.rs
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@mainnet_10.snap
Labels: A-network, NU-6, P-High 🔥

#8966 fix(state): Updates `total_size_on_disk` metric to be the total sst file size
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: I-usability, A-diagnostics, A-state, P-Low :snowflake:

#8968 chore: Update Mainnet and Testnet checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-trivial, A-release, P-High 🔥

#8970 chore: Update docs
  README.md
  book/src/user/troubleshooting.md
Labels: A-docs, C-trivial, A-release, P-High 🔥

#8965 fix(docs): Update documents for cookie auth where needed
  book/src/user/lightwalletd.md
  book/src/user/mining-testnet-s-nomp.md
  book/src/user/mining.md
Labels: A-docs, C-security, A-rpc, P-High 🔥

#8969 chore: Update `Cargo.lock`
  Cargo.lock
  deny.toml
Labels: C-trivial, A-release, P-Critical :ambulance:

#8974 chore: Release v2.0.0
  .github/workflows/scripts/release-crates-dry-run.sh
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: NU-6, C-trivial, A-release, P-Critical :ambulance:

#8978 change(deps): Use ECC deps with activation height for NU6
  Cargo.lock
  Cargo.toml
Labels: A-dependencies, NU-6, C-trivial, A-release, extra-reviews, P-Critical :ambulance:

#8979 chore: Release v2.0.1
  .github/workflows/scripts/release-crates-dry-run.sh
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: NU-6, C-trivial, A-release, P-Critical :ambulance:

#8937 book: add section about private testnet testing
  book/src/SUMMARY.md
  book/src/dev/private-testnet.md
Labels: C-trivial, P-Low :snowflake:
