Repository ZcashFoundation/zebra, pull requests merged in 2024-11, with the labels that each got.

#8985 add(build): Add a `rust-toolchain.toml` file
  rust-toolchain.toml
Labels: A-rust, C-enhancement, C-cleanup, C-trivial, P-Optional :sparkles:

#8986 ref: adjust GCP instances resources to better fit requirements
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/manual-zcashd-deploy.yml
  .github/workflows/sub-deploy-integration-tests-gcp.yml
Labels: A-infrastructure, A-devops, C-enhancement, I-cost, C-trivial, P-Critical :ambulance:

#8987 fix(ci): fail cache disk creation if no db version is found
  .github/workflows/sub-deploy-integration-tests-gcp.yml
Labels: C-bug, A-devops, I-integration-fail, A-script, C-trivial, P-Critical :ambulance:

#8988 fix(actions): do not require the `get-disk-name` job for forks
  .github/workflows/cd-deploy-nodes-gcp.patch-external.yml
  .github/workflows/cd-deploy-nodes-gcp.patch.yml
Labels: C-bug, A-devops, I-integration-fail, C-trivial, P-Critical :ambulance:

#9004 chore(ci): do not default to `tracing` mode in jobs execution
  .github/workflows/sub-deploy-integration-tests-gcp.yml
Labels: A-devops, C-enhancement, I-usability, C-trivial, P-Medium :zap:

#9005 feat(actions): migrate Mergify to GitHub Merge Queue
  .github/workflows/cd-deploy-nodes-gcp.patch-external.yml
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/ci-build-crates.yml
  .github/workflows/ci-tests.patch-external.yml
  .github/workflows/ci-tests.yml
  .github/workflows/ci-unit-tests-os.yml
  .github/workflows/docs-deploy-firebase.patch-external.yml
  .github/workflows/docs-deploy-firebase.yml
  .github/workflows/release-crates-io.yml
  .github/workflows/sub-ci-integration-tests-gcp.yml
  .github/workflows/sub-ci-unit-tests-docker.yml
Labels: A-devops, C-deprecation, I-usability, C-feature, C-trivial, P-High 🔥

#9013 suggestion: Remove an outdated comment
  zebra-consensus/src/transaction.rs
Labels: A-docs, C-trivial

#9018 ref(mergify): use the new configuration format and keys
  .github/mergify.yml
Labels: A-devops, C-enhancement, I-integration-fail, C-trivial, P-Critical :ambulance:

#9015 chore: remove redundant words in comment
  book/src/user/shielded-scan-grpc-server.md
  zebra-network/src/meta_addr/tests/check.rs
  zebrad/src/components/mempool/tests/vector.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/end_of_support.rs
Labels: A-docs, C-trivial, extra-reviews

#9033 fix(mergify): remove deprecated `speculative_checks` option
  .github/mergify.yml
Labels: C-bug, A-devops, I-integration-fail, C-trivial, extra-reviews, P-Critical :ambulance:, C-deprecated

#8857 add(mempool): Verify transactions with unmined inputs in the mempool
  zebra-chain/src/tests/vectors.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/router.rs
  zebra-consensus/src/router/tests.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-consensus/src/transaction/tests/prop.rs
  zebra-node-services/src/mempool.rs
  zebra-node-services/src/mempool/transaction_dependencies.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/long_poll.rs
  zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs
  zebra-rpc/src/methods/get_block_template_rpcs/zip317/tests.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-test/src/mock_service.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/src/components/mempool/pending_outputs.rs
  zebrad/src/components/mempool/storage.rs
  zebrad/src/components/mempool/storage/tests.rs
  zebrad/src/components/mempool/storage/tests/prop.rs
  zebrad/src/components/mempool/storage/tests/vectors.rs
  zebrad/src/components/mempool/storage/verified_set.rs
  zebrad/src/components/mempool/tests/prop.rs
  zebrad/src/components/mempool/tests/vector.rs
  zebrad/tests/acceptance.rs
Labels: A-consensus, C-trivial, A-concurrency, A-mempool, P-Medium :zap:

#9051 fix(test): Update the reference Sapling treestate
  zebra-test/src/vectors/sapling-treestate-main-0-419-201.txt
Labels: C-bug, C-testing, C-trivial, P-Critical :ambulance:

#9050 release(docs): Update the release checklist pull request and issue templates
  .github/ISSUE_TEMPLATE/release.md
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  book/src/SUMMARY.md
Labels: A-docs, A-release

#9055 fix(mergify): align `build` job name across workflows
  .github/workflows/ci-tests.yml
Labels: C-bug, A-devops, I-integration-fail, C-trivial, P-Critical :ambulance:

#9058 fix(network): Upgrade minimum protocol versions for all network kinds
  zebra-network/src/constants.rs
  zebra-network/src/peer_set/set/tests/vectors.rs
Labels: A-network, NU-6, P-Medium :zap:

#8992 add(ci): Check that dependencies have all been published to crates.io on release PRs
  .github/workflows/sub-ci-unit-tests-docker.yml
  docker/entrypoint.sh
  zebrad/tests/acceptance.rs
Labels: A-devops, C-testing, C-trivial, A-release, P-Medium :zap:

#9062 chore: Fix clippy lints
  tower-fallback/tests/fallback.rs
  zebra-chain/src/chain_tip.rs
  zebra-chain/src/orchard/shielded_data.rs
  zebra-chain/src/serialization/tests.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-scan/src/service.rs
  zebra-scan/src/storage/db/sapling.rs
  zebra-scan/tests/scan_task_commands.rs
  zebra-state/src/service/finalized_state/column_family.rs
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebrad/src/commands.rs
  zebrad/src/components/metrics.rs
  zebrad/src/components/tokio.rs
  zebrad/src/components/tracing/endpoint.rs
Labels: C-cleanup, C-trivial, P-High 🔥
