Repository ZcashFoundation/zebra, pull requests merged in 2024-03, with the labels that each got.

#8308 add(test): Check that scan task removes keys, unify scan task acceptance tests, and add test to CI
  .github/workflows/ci-integration-tests-gcp.patch-external.yml
  .github/workflows/ci-integration-tests-gcp.yml
  docker/entrypoint.sh
  zebra-scan/src/service.rs
  zebra-scan/src/service/scan_task/commands.rs
  zebra-scan/src/service/scan_task/tests/vectors.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/shielded_scan.rs
  zebrad/tests/common/shielded_scan/scan_task_commands.rs
  zebrad/tests/common/shielded_scan/scans_for_new_key.rs
Labels: A-devops, C-testing, C-trivial, extra-reviews, A-blockchain-scanner, P-Medium :zap:

#8295 change(tests): Remove Matches on Network From Tests
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/history_tree/tests/vectors.rs
  zebra-chain/src/lib.rs
  zebra-chain/src/primitives/zcash_history/tests/vectors.rs
  zebra-chain/src/sapling/tests/tree.rs
  zebra-chain/src/sprout/tests/tree.rs
  zebra-chain/src/tests.rs
  zebra-chain/src/tests/vectors.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-chain/src/transparent/tests/vectors.rs
  zebra-chain/src/work/difficulty/tests/vectors.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/checkpoint/tests.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-grpc/src/tests/vectors.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/utils.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-scan/src/storage/db/tests.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshot.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
  zebra-state/src/service/tests.rs
  zebra-state/tests/basic.rs
  zebrad/src/components/mempool/storage/tests.rs
  zebrad/src/components/mempool/storage/tests/vectors.rs
Labels: C-trivial, extra-reviews

#8340 change(consensus): Refactor production code for network consensus rules to `Network` methods
  CHANGELOG.md
  zebra-chain/Cargo.toml
  zebra-chain/src/parameters/genesis.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/tests/prop.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/parameters/tests.rs
  zebra-chain/src/primitives/zcash_note_encryption.rs
  zebra-chain/src/transparent/address.rs
  zebra-chain/src/work/difficulty.rs
  zebra-chain/src/work/difficulty/tests/vectors.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/subsidy/funding_streams.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/checkpoint/list.rs
  zebra-consensus/src/checkpoint/list/tests.rs
  zebra-consensus/src/lib.rs
  zebra-consensus/src/parameters/subsidy.rs
  zebra-consensus/src/router.rs
  zebra-network/src/protocol/external/codec.rs
  zebra-network/src/protocol/external/types.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/service/check.rs
  zebra-state/src/service/check/difficulty.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/progress.rs
  zebrad/tests/end_of_support.rs
Labels: A-consensus, C-enhancement, A-network, C-tech-debt, P-Medium :zap:

#8348 fix(docs): Use automatic links in docs
  zebra-chain/src/parameters/network/tests/prop.rs
  zebra-consensus/src/parameters/subsidy.rs
Labels: A-docs, C-trivial, P-Low :snowflake:

#8351 fix(docs): Add openapi book page to the summary
  book/src/SUMMARY.md
Labels: A-docs, A-rpc, P-Medium :zap:

#8318 fix(scan): Improve gRPC method errors and add timeout to scan service to avoid hanging
  zebra-grpc/src/server.rs
  zebra-node-services/src/scan_service/request.rs
  zebra-scan/src/init.rs
  zebra-scan/src/service.rs
  zebra-scan/src/service/scan_task/commands.rs
  zebra-scan/src/service/scan_task/tests/vectors.rs
  zebra-scan/src/service/tests.rs
  zebrad/tests/common/shielded_scan/scan_task_commands.rs
Labels: C-bug, I-usability, A-rpc, A-blockchain-scanner, P-Medium :zap:

#8353 change(ci): Remove automatic addition of new issues to GitHub projects
  .github/workflows/chore-project-management.yml
Labels: A-devops, C-trivial

#8370 build(deps): Bump prod group
  Cargo.lock
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, C-trivial, low

#8373 cleanup(clippy): Remove an unnecessary `vec!` with `cargo clippy --fix`
  zebrad/src/application.rs
Labels: C-cleanup, C-trivial, P-High 🔥

#8376 fix(rpc): Await state service requests in `getblock` method in parallel
  zebra-rpc/src/methods.rs
Labels: C-cleanup, A-rpc, C-trivial, A-concurrency, P-Low :snowflake:

#8336 Adds logging of column family size and database size on startup and s…
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebrad/src/commands/start.rs
Labels: C-feature
