Repository ZcashFoundation/zebra, pull requests merged in 2024-02, with the labels that each got.

#8219 add(scan): Implement `ClearResults` `ScanService` request
  zebra-node-services/src/scan_service/request.rs
  zebra-node-services/src/scan_service/response.rs
  zebra-scan/src/service.rs
  zebra-scan/src/service/tests.rs
  zebra-scan/src/storage/db/sapling.rs
  zebra-scan/src/storage/db/tests/vectors.rs
Labels: C-feature, A-blockchain-scanner, P-Medium :zap:

#8215 feat(docker): allow users to use Zebra + LWD with persistent states
  .gitignore
  book/src/user/docker.md
  book/src/user/lightwalletd.md
  docker/.env
  docker/Dockerfile
  docker/docker-compose.lwd.yml
  docker/docker-compose.yml
  docker/test.env
  docker/zcash-lightwalletd/zcash.conf
Labels: A-devops, C-enhancement, I-usability, C-feature, P-Medium :zap:

#8224 add(scan): Implement `Results` request
  zebra-node-services/src/scan_service/request.rs
  zebra-node-services/src/scan_service/response.rs
  zebra-scan/src/service.rs
  zebra-scan/src/service/tests.rs
Labels: A-blockchain-scanner, P-Medium :zap:

#8228 Remove `rfc.md` file
  .github/PULL_REQUEST_TEMPLATE/rfc.md
Labels: C-trivial, extra-reviews

#8234 fix(ci): Uses lightwalletd v0.4.16 in tests
  .github/workflows/sub-build-lightwalletd.yml
Labels: A-devops, C-trivial, P-Medium :zap:

#8222 add(scan): Handle RegisterKeys messages in scan task
  zebra-scan/src/init.rs
  zebra-scan/src/lib.rs
  zebra-scan/src/service.rs
  zebra-scan/src/service/scan_task.rs
  zebra-scan/src/service/scan_task/commands.rs
  zebra-scan/src/service/scan_task/executor.rs
  zebra-scan/src/service/scan_task/scan.rs
  zebra-scan/src/service/scan_task/scan/scan_range.rs
  zebra-scan/src/service/scan_task/tests.rs
  zebra-scan/src/service/scan_task/tests/vectors.rs
  zebra-scan/src/service/tests.rs
  zebra-scan/src/storage/db/sapling.rs
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/config.rs
  zebrad/tests/common/mod.rs
  zebrad/tests/common/shielded_scan.rs
  zebrad/tests/common/shielded_scan/scans_for_new_key.rs
Labels: C-feature, C-trivial, A-concurrency, A-blockchain-scanner, P-Medium :zap:

#8237 add(scan): Add `ClearResults` and `DeleteKeys` gRPC methods
  zebra-grpc/proto/scanner.proto
  zebra-grpc/src/server.rs
Labels: A-rpc, C-feature, A-blockchain-scanner, P-Medium :zap:

#8241 add(scan): Start scanner gRPC server with `zebrad`
  Cargo.lock
  zebra-grpc/src/lib.rs
  zebra-grpc/src/server.rs
  zebra-scan/src/bin/rpc_server.rs
  zebra-scan/src/config.rs
  zebra-scan/src/init.rs
  zebra-scan/src/lib.rs
  zebra-scan/src/service.rs
  zebra-scan/src/service/scan_task.rs
  zebra-scan/src/service/scan_task/scan.rs
  zebrad/Cargo.toml
  zebrad/src/commands/start.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/config.rs
  zebrad/tests/common/shielded_scan/scans_for_new_key.rs
Labels: A-rpc, C-feature, A-blockchain-scanner, P-Medium :zap:

#8247 change(release.toml): new crates owners list
  release.toml
Labels: A-release, P-Low :snowflake:

#8252 Fix formatting in `proptest` macros
  zebra-chain/src/work/tests/prop.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
Labels: A-devops, C-trivial, P-High 🔥

#8251 add(scan): Implement `RegisterKeys` service request to register new keys
  zebra-chain/src/parameters/network.rs
  zebra-node-services/src/scan_service/request.rs
  zebra-node-services/src/scan_service/response.rs
  zebra-scan/src/service.rs
  zebra-scan/src/service/scan_task/commands.rs
  zebra-scan/src/service/scan_task/scan.rs
  zebra-scan/src/service/scan_task/scan/scan_range.rs
  zebra-scan/src/service/scan_task/tests/vectors.rs
  zebra-scan/src/storage.rs
  zebra-scan/src/storage/db/sapling.rs
  zebra-scan/src/tests.rs
  zebra-scan/src/tests/vectors.rs
  zebrad/tests/common/shielded_scan/scans_for_new_key.rs
Labels: A-blockchain-scanner, P-Medium :zap:

#8255 add(grpc): `get_results`
  zebra-grpc/build.rs
  zebra-grpc/proto/scanner.proto
  zebra-grpc/src/server.rs
Labels: A-rpc, A-blockchain-scanner, P-Medium :zap:

#8273 ci: Update Debian from Bullseye to Bookworm
  book/src/user/supported-platforms.md
  book/src/user/troubleshooting.md
  docker/Dockerfile
  docker/zcash-lightwalletd/Dockerfile
Labels: A-devops, P-Medium :zap:

#8276 fix(test): Improve error message in `non_blocking_logger` test
  zebrad/tests/acceptance.rs
Labels: C-testing, P-Low :snowflake:

#8277 test(grpc): Add snapshots
  Cargo.lock
  zebra-grpc/Cargo.toml
  zebra-grpc/build.rs
  zebra-grpc/src/lib.rs
  zebra-grpc/src/tests.rs
  zebra-grpc/src/tests/snapshot.rs
  zebra-grpc/src/tests/snapshots/get_info@mainnet.snap
  zebra-grpc/src/tests/snapshots/get_info@testnet.snap
  zebra-grpc/src/tests/snapshots/get_results@mainnet.snap
  zebra-grpc/src/tests/snapshots/get_results@testnet.snap
  zebra-scan/src/storage/db/sapling.rs
Labels: C-testing, C-trivial, A-blockchain-scanner, P-Medium :zap:

#8282 Enable optional fields for Protocol Buffers older than v3.15.0
  zebra-grpc/build.rs
Labels: A-blockchain-scanner, P-High 🔥

#8269 fix(docker): set log rotation to avoid docker bugs
  docker/docker-compose.yml
Labels: C-bug, A-devops, C-enhancement, I-usability, P-Medium :zap:

#8296 Suggestion for 'tests(grpc): Unit tests'
  zebra-grpc/src/server.rs
  zebra-grpc/src/tests/vectors.rs
Labels: C-trivial

#8293 tests(grpc): Unit tests
  zebra-grpc/src/server.rs
  zebra-grpc/src/tests.rs
  zebra-grpc/src/tests/vectors.rs
Labels: C-testing, C-trivial, A-blockchain-scanner, P-Medium :zap:

#8305 fix(ci): keep `gcloud` arguments consistency
  .github/workflows/sub-deploy-integration-tests-gcp.yml
Labels: C-bug, A-infrastructure, A-devops, I-build-fail, C-trivial, P-Critical :ambulance:

#8303 fix(scan): Fix minor concurrency bug in the `scan` gRPC method
  zebra-grpc/src/server.rs
  zebra-grpc/src/tests/snapshot.rs
  zebra-scan/src/service.rs
  zebra-scan/src/service/scan_task/commands.rs
  zebra-scan/src/service/scan_task/executor.rs
  zebra-scan/src/service/scan_task/scan.rs
  zebra-scan/src/service/scan_task/scan/scan_range.rs
  zebra-scan/src/service/scan_task/tests/vectors.rs
  zebra-scan/src/service/tests.rs
  zebrad/tests/common/shielded_scan/subscribe_results.rs
Labels: C-bug, A-rpc, A-concurrency, A-blockchain-scanner, P-Medium :zap:

#8310 chore: Update Dependencies
  Cargo.lock
Labels: C-trivial, A-release, P-Critical :ambulance:

#8304 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: extra-reviews

#8309 chore: Update Checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-trivial, A-release, P-Critical :ambulance:

#8298 release(tests): update dry-run release commands
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  .github/workflows/scripts/release-crates-dry-run.sh
Labels: A-devops, C-trivial, A-release, P-Medium :zap:

#8288 add(scan): Adds gRPC reflection and documents how to use the zebra-scan gRPC server
  Cargo.lock
  book/src/SUMMARY.md
  book/src/user/shielded-scan-grpc-server.md
  zebra-grpc/Cargo.toml
  zebra-grpc/build.rs
  zebra-grpc/src/lib.rs
  zebra-grpc/src/server.rs
  zebra-scan/src/init.rs
Labels: A-docs, I-usability, A-rpc, A-blockchain-scanner, P-Medium :zap:

#8171 chore: allow crater runs
  Cargo.lock
  tower-batch-control/Cargo.toml
  tower-batch-control/tests/ed25519.rs
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-consensus/src/primitives/ed25519/tests.rs
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, A-rust, C-enhancement, C-testing, C-trivial

#8315 chore: Update docs for building Zebra
  README.md
  book/src/user/shielded-scan.md
Labels: A-docs, A-blockchain-scanner, P-Critical :ambulance:

#8319 chore: Release v1.6.0
  .github/workflows/scripts/release-crates-dry-run.sh
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: C-trivial, A-release, P-Critical :ambulance:

#8330 change(CI): Refactor creating GCP disks
  .github/workflows/sub-deploy-integration-tests-gcp.yml
Labels: A-devops, C-trivial, C-tech-debt, P-Low :snowflake:
