Repository ZcashFoundation/zebra, pull requests merged in 2024-01, with the labels that each got.

#8128 tests(sinsemilla): Minor changes to sinsemilla tests
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/orchard/tests/vectors/sinsemilla.rs
Labels: P-Low :snowflake:, P-Optional :sparkles:, C-testing, A-cryptography, C-trivial

#8127 fix(elasticsearch): Make bulk size the same for testnet and mainnet
  zebra-state/src/service/finalized_state.rs
Labels: P-Low :snowflake:, I-panic, C-feature, C-trivial

#8134 Update copyright year to 2024
  LICENSE-APACHE
  LICENSE-MIT
  tower-batch-control/LICENSE
  zebra-network/LICENSE
Labels: A-docs, P-Low :snowflake:, C-trivial, A-legal

#8133 fix(ci): revert script changes causing workflow failures
  .github/workflows/sub-find-cached-disks.yml
Labels: C-bug, A-devops, P-High :fire:, I-integration-fail, C-trivial

#8139 build(deps): bump `jsonrpc` from 0.16.0 to 0.17.0
  Cargo.lock
  zebra-utils/Cargo.toml
  zebra-utils/src/bin/scanning-results-reader/main.rs
Labels: A-dependencies, P-Low :snowflake:, C-trivial

#8140 refactor: remove obsolete clippy allows in non_finalized_state
  zebra-state/src/service/non_finalized_state.rs
Labels: C-cleanup, P-Low :snowflake:, A-diagnostics, A-state, C-trivial

#8136 feat(mine): Add an internal Zcash miner to Zebra
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  deny.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/block/header.rs
  zebra-chain/src/primitives.rs
  zebra-chain/src/primitives/byte_array.rs
  zebra-chain/src/work/equihash.rs
  zebra-consensus/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-rpc/src/config.rs
  zebra-rpc/src/config/mining.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/long_poll.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebra-state/Cargo.toml
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/watch_receiver.rs
  zebrad/Cargo.toml
  zebrad/src/application.rs
  zebrad/src/commands/start.rs
  zebrad/src/components.rs
  zebrad/src/components/miner.rs
  zebrad/src/components/sync.rs
  zebrad/src/lib.rs
  zebrad/tests/common/get_block_template_rpcs/get_block_template.rs
Labels: A-dependencies, P-Optional :sparkles:, A-rpc, C-feature, A-concurrency

#8148 cleanup: Fix unused code lints
  zebra-chain/src/orchard/note.rs
  zebra-chain/src/sprout/tree.rs
Labels: C-cleanup, P-Low :snowflake:, A-diagnostics, C-trivial

#8149 change(doc): Document how to add a column family
  book/src/dev/state-db-upgrades.md
Labels: A-docs, C-enhancement, P-Medium :zap:, I-panic, A-state, C-trivial, A-blockchain-scanner

#8150 fix(miner): Avoid some duplicate block errors
  Cargo.lock
  zebrad/src/components/miner.rs
Labels: C-bug, P-Medium :zap:, I-usability, A-concurrency

#8145 change(doc): Refactor user & dev docs
  README.md
  book/src/api.md
  book/src/dev.md
  book/theme/css/custom.css
  zebrad/src/lib.rs
Labels: A-docs, C-cleanup, P-Medium :zap:

#8157 fix(scan): Fix the RPC tx fetching in the scanning results reader
  zebra-utils/src/bin/scanning-results-reader/main.rs
Labels: A-rust, P-Medium :zap:, A-blockchain-scanner

#8160 change(docs): Point to a manually created list of Zebra crates in docs
  README.md
  book/src/api.md
  book/src/dev.md
Labels: C-bug, A-docs, P-Low :snowflake:

#8159 Prepare zebra release 1.5.1
  Cargo.lock
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-trivial, A-release, P-Critical 🚑

#8165 Release v1.5.1
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: C-trivial, A-release, P-Critical 🚑

#8184 feat(remove): Temporally remove the internal miner functionality
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/work/equihash.rs
  zebra-rpc/src/config/mining.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/src/components/miner.rs
Labels: C-feature, A-release, P-Critical 🚑

#8187 chore: Hotfix v1.5.2
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: C-trivial, A-release, P-Critical 🚑

#8167 build(crate): Add a new `zebra-grpc` crate
  Cargo.lock
  Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-grpc/src/lib.rs
Labels: A-rpc, A-blockchain-scanner

#8172 add(scan): Add the `scan_start_where_left` test to CI
  .github/workflows/ci-integration-tests-gcp.patch-external.yml
  .github/workflows/ci-integration-tests-gcp.yml
  docker/entrypoint.sh
Labels: A-devops, C-testing, A-blockchain-scanner, P-Medium ⚡

#8192 fix(CI): Pin `cargo-deny-action` to v1.5.10
  .github/workflows/ci-unit-tests-os.yml
Labels: A-devops, C-trivial, P-Critical 🚑

#8185 add(scan): Create a tower Service in zebra-scan
  Cargo.lock
  zebra-node-services/src/lib.rs
  zebra-node-services/src/scan_service.rs
  zebra-node-services/src/scan_service/request.rs
  zebra-node-services/src/scan_service/response.rs
  zebra-scan/Cargo.toml
  zebra-scan/src/init.rs
  zebra-scan/src/lib.rs
  zebra-scan/src/service.rs
Labels: A-rpc, A-concurrency, A-blockchain-scanner, P-Medium ⚡

#8197 change(CI): Unpin `cargo-deny-action`
  .github/workflows/ci-unit-tests-os.yml
Labels: A-devops, C-trivial, P-Low :snowflake:

#8178 feat(grpc): Add initial `Getinfo` grpc
  .github/workflows/scripts/release-crates-dry-run.sh
  Cargo.lock
  zebra-grpc/Cargo.toml
  zebra-grpc/build.rs
  zebra-grpc/proto/scanner.proto
  zebra-grpc/src/lib.rs
  zebra-grpc/src/server.rs
  zebra-node-services/src/scan_service/request.rs
  zebra-node-services/src/scan_service/response.rs
  zebra-scan/Cargo.toml
  zebra-scan/src/bin/rpc_server.rs
  zebra-scan/src/init.rs
  zebra-scan/src/lib.rs
  zebra-scan/src/scan.rs
  zebra-scan/src/service.rs
Labels: A-rpc, C-feature, C-trivial, A-blockchain-scanner, P-Medium :zap:

#8175 ref(docker): Consolidate all tests in the `entrypoint.sh` script
  .github/workflows/ci-unit-tests-docker.yml
  docker/Dockerfile
  docker/entrypoint.sh
Labels: A-devops, C-enhancement, I-usability, C-feature, C-trivial, P-Medium :zap:

#8217 add(scan): Implement `DeleteKeys` `ScanService` request
  zebra-node-services/src/scan_service/request.rs
  zebra-node-services/src/scan_service/response.rs
  zebra-scan/Cargo.toml
  zebra-scan/src/bin/rpc_server.rs
  zebra-scan/src/init.rs
  zebra-scan/src/lib.rs
  zebra-scan/src/scan.rs
  zebra-scan/src/service.rs
  zebra-scan/src/service/tests.rs
  zebra-scan/src/storage/db/sapling.rs
  zebra-scan/src/storage/db/tests.rs
  zebra-scan/src/storage/db/tests/vectors.rs
  zebrad/src/commands/start.rs
Labels: C-feature, A-concurrency, A-blockchain-scanner, P-Medium :zap:
