Repository ZcashFoundation/zebra, pull requests merged in 2024-08, with the labels that each got.

#8694 change(consensus): Add lockbox funding stream
  zebra-chain/Cargo.toml
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/subsidy/funding_streams.rs
  zebra-consensus/src/block/subsidy/funding_streams/tests.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
Labels: A-consensus, NU-6, C-trivial, P-Medium :zap:

#8738 chore: Fix `cargo check` annotations on Windows
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-scan/tests/scanner.rs
  zebra-state/src/service/non_finalized_state/tests/prop.rs
  zebrad/tests/acceptance.rs
Labels: C-cleanup, C-trivial, P-Low :snowflake:

#8741 fix: Cache Sprout tree roots in tests
  zebra-state/src/service/finalized_state/zebra_db/arbitrary.rs
Labels: C-bug, C-testing, A-state, C-trivial, P-Critical :ambulance:

#8729 change: Track the balance of the deferred chain value pool
  zebra-chain/src/block.rs
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/value_balance.rs
  zebra-chain/src/value_balance/arbitrary.rs
  zebra-chain/src/value_balance/tests/prop.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/subsidy/funding_streams.rs
  zebra-consensus/src/block/subsidy/funding_streams/tests.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/block/tests.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/lib.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/subsidy.rs
  zebra-state/src/arbitrary.rs
  zebra-state/src/constants.rs
  zebra-state/src/request.rs
  zebra-state/src/service/chain_tip.rs
  zebra-state/src/service/finalized_state/disk_format/chain.rs
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tip_chain_value_pool_raw_data@mainnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tip_chain_value_pool_raw_data@mainnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tip_chain_value_pool_raw_data@testnet_1.snap
  zebra-state/src/service/finalized_state/disk_format/tests/snapshots/tip_chain_value_pool_raw_data@testnet_2.snap
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/vectors.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/tests.rs
Labels: NU-6, A-state, P-Medium :zap:, rust

#8735 change: Refactor error handling for block subsidies
  zebra-chain/src/amount.rs
  zebra-chain/src/value_balance.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/error.rs
Labels: P-Medium :zap:

#8727 change(consensus): Require that coinbase transactions balance exactly after NU6 activation
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/check.rs
  zebra-consensus/src/block/subsidy/general.rs
  zebra-consensus/src/block/tests.rs
  zebrad/tests/acceptance.rs
Labels: A-consensus, NU-6, C-trivial, P-Medium :zap:

#8748 change(state): Support in-place disk format upgrades for major database version bumps
  zebra-state/src/config.rs
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
Labels: A-state, P-Medium :zap:

#8750 chore(actions): remove warnings related to gcp and docker steps
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/chore-delete-gcp-resources.yml
  .github/workflows/docs-deploy-firebase.yml
  .github/workflows/manual-zcashd-deploy.yml
  .github/workflows/sub-build-docker-image.yml
  .github/workflows/sub-deploy-integration-tests-gcp.yml
  .github/workflows/sub-find-cached-disks.yml
Labels: A-devops, C-cleanup, I-usability, C-trivial, extra-reviews, P-Medium :zap:

#8746 deps(librustzcash): Upgrade zcash dependencies for NU6
  Cargo.lock
  deny.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-rpc/Cargo.toml
  zebra-scan/src/bin/scanning-results-reader/main.rs
  zebra-scan/src/service/scan_task/scan.rs
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
Labels: A-dependencies, NU-6, C-trivial

#8762 fix(test): Renames `regtest_submit_blocks` test to avoid an RPC port conflict
  zebrad/tests/acceptance.rs
Labels: C-cleanup, C-testing, C-trivial, P-Low :snowflake:

#8760 fix(bug): Reduces `Debug` output for `Network` on Regtest and default Testnet
  zebra-chain/src/parameters/network.rs
Labels: C-bug, A-devops, C-cleanup, I-usability, C-testing, C-trivial, P-Medium :zap:

#8742 change(rpc): Modify `getblocksubsidy` for NU6
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-network/src/protocol/external/types.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/subsidy.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/zec.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_excessive_height@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_excessive_height@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_future_height@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_future_height@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_future_nu6_height@nu6testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_tip_height@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_subsidy_tip_height@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_difficulty_invalid_populated@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info_future_nu6_height@nu6testnet_10.snap
Labels: NU-6, A-rpc, P-Medium :zap:

#8769 change(rpc): Add value pool balances to `getblockchaininfo` RPC method response
  zebra-chain/src/chain_tip.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/subsidy.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info_future_nu6_height@nu6testnet_10.snap
  zebra-rpc/src/methods/types.rs
  zebra-rpc/src/methods/types/get_blockchain_info.rs
  zebra-rpc/src/methods/types/zec.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/find.rs
Labels: C-enhancement, C-cleanup, NU-6, A-rpc, A-state, P-High 🔥

#8774 docs(openapi): Update the spec for RPC changes done for NU6
  openapi.yaml
Labels: A-docs, NU-6, A-rpc, P-Low :snowflake:

#8776 docs(fix): `reject_and_remove_same_effects` docs is wrong
  zebrad/src/components/mempool/storage.rs
Labels: A-docs, C-cleanup, C-trivial, P-Low :snowflake:

#8733 change(network): Updates minimum protocol version for NU6 on Testnet and Mainnet
  zebra-network/src/protocol/external/types.rs
Labels: NU-6, C-trivial, P-High 🔥

#8784 fix(test): Updates ignored failure messages in `lightwalletd_integration` test
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebrad/tests/common/failure_messages.rs
  zebrad/tests/common/test_type.rs
Labels: C-bug, C-cleanup, C-testing, A-rpc, lightwalletd, C-trivial, P-Low :snowflake:

#8785 fix(openapi): Order of the generated openapi.yaml spec
  Cargo.lock
  openapi.yaml
  zebra-utils/Cargo.toml
  zebra-utils/src/bin/openapi-generator/main.rs
Labels: A-docs, P-Low :snowflake:, P-Optional :sparkles:

#8794 fix(docs): sample configurations in the custom testnet book page
  book/src/user/custom-testnets.md
Labels: A-docs, C-testing, C-trivial, P-Low :snowflake:

#8792 build(deps): make librustzcash crates workspace dependencies
  Cargo.lock
  Cargo.toml
  deny.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/primitives/address.rs
  zebra-chain/src/primitives/viewing_key/sapling.rs
  zebra-chain/src/primitives/zcash_note_encryption.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-scan/src/lib.rs
  zebra-scan/src/service/scan_task/commands.rs
  zebra-scan/src/service/scan_task/scan.rs
  zebra-scan/src/service/scan_task/scan/scan_range.rs
  zebra-scan/src/tests.rs
  zebra-scan/src/tests/vectors.rs
  zebra-utils/Cargo.toml
Labels: A-dependencies, C-cleanup, C-trivial, P-High 🔥

#8802 feat(docker): Add SBOM and provenance attestations
  .github/workflows/sub-build-docker-image.yml
Labels: A-devops, C-security, I-usability, C-feature, C-trivial, P-Low :snowflake:

#8803 fix(docker): do not run the Zebra nodes with the root user
  docker/Dockerfile
Labels: A-devops, C-security, P-High 🔥

#8808 fix(docker): add `gosu` and remove unsupported flag in `adduser`
  docker/Dockerfile
  docker/entrypoint.sh
Labels: C-bug, A-devops, I-build-fail, P-Critical :ambulance:

#8810 build(deps): Upgrade ECC dependencies
  Cargo.lock
  Cargo.toml
  deny.toml
  zebra-scan/Cargo.toml
Labels: A-dependencies, NU-6, C-trivial, P-Critical :ambulance:

#8804 change(consensus/network): Updates `CURRENT_NETWORK_PROTOCOL_VERSION` and adds an NU6 activation height on Testnet
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-network/src/constants.rs
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info_future_nu6_height@nu6testnet_10.snap
Labels: A-consensus, A-network, NU-6, C-trivial, P-Critical :ambulance:

#8734 chore: Release v1.9.0
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: C-trivial, A-release, P-Critical :ambulance:

#8811 chore: Update checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: C-trivial, P-Critical :ambulance:

#8817 fix(docker): allow the `zebra` user access to relevant dirs
  docker/Dockerfile
  docker/entrypoint.sh
Labels: A-devops, C-enhancement, I-usability, P-Critical :ambulance:

#8795 fix(state): Write database format version to disk atomically to avoid a rare panic
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/common.rs
  zebra-chain/src/lib.rs
  zebra-network/src/config.rs
  zebra-network/src/config/cache_dir.rs
  zebra-state/src/config.rs
Labels: C-bug, I-panic, A-state, P-Low :snowflake:

#8788 fix(rpc): Return verification errors from `sendrawtransaction` RPC method
  zebra-node-services/Cargo.toml
  zebra-node-services/src/mempool.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/queue/tests/prop.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/crawler/tests/prop.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/src/components/mempool/tests/vector.rs
Labels: C-bug, C-enhancement, I-usability, A-rpc, lightwalletd, A-mempool, P-High 🔥
