Repository ZcashFoundation/zebra, pull requests merged in 2025-09, with the labels that each got.

#9859 add(rpc): Expose `z_validateaddress` logic for library consumers
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/types/z_validate_address.rs
Labels: I-usability, A-rpc

#9854 feat(rpc): support single-string or object params in getaddresstxids (#9784)
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/vectors.rs
Labels: C-feature

#9871 fix(serialization): correct at_least_one! count-form and add unit test
  zebra-chain/src/serialization/constraint.rs
Labels: C-feature

#9870 feat(rpc): add getmempoolinfo RPC method
  zebra-node-services/src/mempool.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_mempool_info.snap
  zebra-rpc/src/methods/types.rs
  zebra-rpc/src/methods/types/get_mempool_info.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/tests/vector.rs
Labels: C-feature

#9875 feature: support chainInfo in getaddressutxos
  Cargo.lock
  zebra-rpc/src/client.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/tests/serialization_tests.rs
  zebra-state/Cargo.toml
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-state/src/service/read/address/utxo.rs
  zebra-utils/zcash-rpc-diff
Labels: C-feature

#9908 change(rpc): Always return `1.0` from `getblockchaininfo` as the verification progress on Regtest
  zebra-rpc/src/methods.rs
Labels: C-trivial, P-Optional :sparkles:

#9912 fix(ci): add missing permissions and protoc dependencies
  .github/workflows/book.yml
  .github/workflows/coverage.yml
  .github/workflows/release-binaries.yml
  .github/workflows/zfnd-ci-integration-tests-gcp.yml
  .github/workflows/zfnd-deploy-nodes-gcp.yml
Labels: C-bug, A-devops, I-integration-fail, P-Critical :ambulance:

#9928 fix(ci): resolve multiple CI workflow issues and required status checks
  .github/workflows/status-checks.patch.yml
  .github/workflows/test-crates.yml
  .github/workflows/test-docker.yml
  .github/workflows/zfnd-ci-integration-tests-gcp.yml
Labels: C-bug, A-devops, P-Critical :ambulance:

#9886 feat(docker): add `curl` for health-check validation
  docker/Dockerfile
Labels: A-devops, C-enhancement, I-usability, C-feature, C-trivial, P-Medium :zap:, queued

#9934 qa(suggestion): Remove one call to `connect_nodes`.
  zebra-rpc/qa/rpc-tests/test_framework/util.py
Labels: extra-reviews

#9936 test(lwd): ensure lwd full sync populates the cache disk
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/lightwalletd/sync.rs
  zebrad/tests/common/test_type.rs
Labels: C-bug, A-infrastructure, A-devops, I-integration-fail, P-Critical :ambulance:, queued
