Repository ZcashFoundation/zebra, pull requests merged in 2025-08, with the labels that each got.

#9684 [#9427] Fix: possibly change "lockbox" vs "deferred" value pool name
  CHANGELOG.md
  zebra-rpc/CHANGELOG.md
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_1@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_1@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_default@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_default@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_1@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_1@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_default@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_default@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info_future_nu6_height@nu6testnet_10.snap
  zebra-rpc/src/methods/types/get_blockchain_info.rs
Labels: A-rpc, A-compatibility, P-High 🔥

#9754 fix(crash): Fix Nu6.1 blocks crash
  zebra-consensus/src/block/check.rs
Labels: C-security, I-panic, P-High 🔥, NU-6.1

#9753 release(checkpoints): Add checkpoints for release 2.5.0
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: A-release, P-High 🔥, C-exclude-from-changelog

#9757 deps(librustzcash): Update ECC dependencies
  Cargo.lock
  Cargo.toml
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-rpc/src/methods/types/get_block_template/zip317/tests.rs
  zebra-utils/Cargo.toml
Labels: A-compatibility, A-release, P-High 🔥, dependencies, NU-6.1

#9759 chore(chain): remove output_amounts()
  zebra-chain/src/parameters/network/subsidy.rs
Labels: extra-reviews

#9763 build(clippy): New lints
  zebra-network/src/peer_set/inventory_registry.rs
  zebra-script/src/lib.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/zebra_db/chain.rs
  zebra-state/src/service/finalized_state/zebra_db/transparent.rs
  zebra-test/src/service_extensions.rs
Labels: I-build-fail, A-release, P-High 🔥

#9766 update crate changelogs for 2.5.0 release
  zebra-chain/CHANGELOG.md
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-consensus/CHANGELOG.md
  zebra-network/CHANGELOG.md
  zebra-rpc/CHANGELOG.md
  zebra-script/CHANGELOG.md
  zebra-state/CHANGELOG.md
  zebra-test/CHANGELOG.md
  zebra-utils/CHANGELOG.md
Labels: P-Critical :ambulance:

#9765 chore(release): Zebra 2.5.0
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/CHANGELOG.md
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: A-release, P-Critical :ambulance:

#9435 feat(ci): implement nextest and optimize Docker test builds
  .config/nextest.toml
  .dockerignore
  .github/workflows/README.md
  .github/workflows/sub-ci-integration-tests-gcp.yml
  .github/workflows/sub-ci-unit-tests-docker.yml
  .github/workflows/sub-deploy-integration-tests-gcp.yml
  docker/Dockerfile
  docker/entrypoint.sh
  zebrad/Cargo.toml
  zebrad/tests/acceptance.rs
Labels: A-rust, A-devops, C-enhancement, C-feature, P-Critical :ambulance:

#9773 chore: Bump MSRV from 1.85 to 1.89
  docker/Dockerfile
  zebrad/Cargo.toml
Labels: P-Medium :zap:, C-exclude-from-changelog

#9786 change(consensus): Use the correct number of addresses for the FPF funding stream extension on Testnet
  zebra-chain/src/parameters/network/subsidy.rs
Labels: C-cleanup, C-trivial, P-Low :snowflake:

#9764 change(deps): Bump `tonic` from 0.12 to 0.14
  Cargo.lock
  Cargo.toml
  deny.toml
  zebra-rpc/Cargo.toml
  zebra-rpc/build.rs
  zebra-rpc/src/indexer/server.rs
  zebrad/Cargo.toml
  zebrad/build.rs
Labels: P-Medium :zap:, C-exclude-from-changelog, dependencies

#9783 Replace light wallet .proto files with canonical versions obtained from https://github.com/zcash/lightwallet-protocol
  zebrad/tests/common/lightwalletd/lightwallet-protocol/LICENSE
  zebrad/tests/common/lightwalletd/lightwallet-protocol/walletrpc/compact_formats.proto
  zebrad/tests/common/lightwalletd/lightwallet-protocol/walletrpc/service.proto
  zebrad/tests/common/lightwalletd/proto/compact_formats.proto
  zebrad/tests/common/lightwalletd/proto/service.proto
Labels: do-not-merge

#9820 change(docs): Adds references to NU6.1 ZIPs
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-consensus/src/block/check.rs
Labels: A-docs, C-cleanup, P-Low :snowflake:

#9678 change: Refactor Sapling parameters loading
  Cargo.lock
  Cargo.toml
  deny.toml
  zebra-chain/src/primitives/address.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/groth16/params.rs
  zebra-consensus/src/primitives/groth16/params/parse_parameters.rs
  zebra-rpc/src/methods/types/get_block_template.rs
  zebra-rpc/src/methods/types/get_block_template/zip317/tests.rs
Labels: P-Medium :zap:

#9830 Removes `ZEBRA_NETWORK__NETWORK` env var from `Run all tests`
  .config/nextest.toml
  .github/workflows/sub-ci-unit-tests-docker.yml
Labels: C-trivial

#9737 change(consensus): Switch Sapling verifier
  Cargo.lock
  Cargo.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/error.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/keys.rs
  zebra-chain/src/sapling/output.rs
  zebra-chain/src/sapling/shielded_data.rs
  zebra-chain/src/sapling/spend.rs
  zebra-chain/src/serialization/error.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/primitives.rs
  zebra-consensus/src/primitives/groth16.rs
  zebra-consensus/src/primitives/groth16/params.rs
  zebra-consensus/src/primitives/groth16/tests.rs
  zebra-consensus/src/primitives/sapling.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
Labels: A-consensus, P-Medium :zap:
