Repository ZcashFoundation/zebra, pull requests merged in 2025-05, with the labels that each got.

#9466 chore: Add checkpoints
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
Labels: A-release, P-Critical :ambulance:, C-exclude-from-changelog

#9467 chore: Update deps
  Cargo.lock
Labels: A-dependencies, A-release, P-Critical :ambulance:, P-High 🔥, C-exclude-from-changelog

#9441 fix(usability): Improve the cache dir and database startup panics
  zebra-state/src/constants.rs
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: I-panic, I-usability, P-Low :snowflake:

#9481 fix(ci): check, create and mount lwd cached state for tests
  .github/workflows/sub-ci-integration-tests-gcp.yml
  .github/workflows/sub-deploy-integration-tests-gcp.yml
  .github/workflows/sub-find-cached-disks.yml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebrad/tests/common/lightwalletd.rs
Labels: C-bug, A-rust, A-devops, I-integration-fail, lightwalletd, P-Critical :ambulance:

#9458 feat(rpc): Add `time` and `size` field to `TransactionObject`
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/getrawtransaction_verbosity=1@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/getrawtransaction_verbosity=1@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/methods/types/transaction.rs
  zebra-rpc/src/queue/tests/prop.rs
  zebra-rpc/src/tests/vectors.rs
  zebra-state/src/response.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/finalized_state/zebra_db/block/tests/snapshot.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/read/block.rs
  zebra-state/src/service/read/tests/vectors.rs
Labels: A-rpc, C-feature, A-compatibility, P-Medium :zap:

#9485 docs(openapi): Remove getblocktemplate file from scrtipt
  zebra-utils/src/bin/openapi-generator/main.rs
Labels: C-bug, A-docs

#9521 fix(rpc): Regroup imports
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/types/get_block_template.rs
  zebra-rpc/src/methods/types/get_block_template/zip317.rs
  zebra-rpc/src/methods/types/get_blockchain_info.rs
  zebra-rpc/src/methods/types/get_raw_mempool.rs
  zebra-rpc/src/methods/types/transaction.rs
  zebra-rpc/src/server/tests/vectors.rs
  zebra-utils/src/bin/block-template-to-proposal/args.rs
  zebra-utils/src/bin/block-template-to-proposal/main.rs
  zebra-utils/src/bin/openapi-generator/main.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/miner.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/get_block_template_rpcs/get_block_template.rs
  zebrad/tests/common/regtest.rs
Labels: P-Medium :zap:, C-exclude-from-changelog

#9530 fix(ci): delete scan-test
  .github/workflows/sub-ci-integration-tests-gcp.yml
Labels: C-testing, extra-reviews, P-High 🔥

#9531 fix(clippy, build): fix latest Clippy lints introduced in v1.87.0 and migrate from vergen to vergen_git
  Cargo.lock
  Cargo.toml
  zebra-chain/src/block/serialize.rs
  zebra-chain/src/transparent/serialize.rs
  zebra-test/src/command.rs
  zebrad/Cargo.toml
  zebrad/build.rs
Labels: P-High 🔥, C-exclude-from-changelog

#9538 Add `raw_value` feature to serde_json
  zebra-rpc/Cargo.toml
Labels: C-cleanup, A-rpc, C-feature, P-Low :snowflake:

#9483 feat(rpc): Update `(z_)validateaddress` to validate TEX addresses
  Cargo.lock
  Cargo.toml
  zebra-chain/Cargo.toml
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/primitives/address.rs
  zebra-chain/src/transparent/address.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
Labels: A-rpc, A-cryptography, C-feature, P-Medium :zap:

#9544 add(process): Add hotfix release checklist
  .github/PULL_REQUEST_TEMPLATE/hotfix-release-checklist.md
Labels: A-docs, C-trivial, P-Medium :zap:, C-exclude-from-changelog

#9362 refactor(ci): Run standard GitHub runners in forks and clones
  .github/workflows/ci-build-crates.yml
  .github/workflows/ci-coverage.yml
  .github/workflows/sub-ci-unit-tests-docker.yml
Labels: A-devops, C-enhancement, I-integration-fail, extra-reviews, P-Low :snowflake:, C-exclude-from-changelog
