Repository ZcashFoundation/zebra, pull requests merged in 2025-10, with the labels that each got.

#9895 feat(health): add HTTP `/healthy` and `/ready` endpoints
  CHANGELOG.md
  Cargo.lock
  README.md
  book/src/SUMMARY.md
  book/src/user/docker.md
  book/src/user/health.md
  book/src/user/run.md
  docker/default-zebra-config.toml
  docker/docker-compose.yml
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebrad/Cargo.toml
  zebrad/src/commands/start.rs
  zebrad/src/components.rs
  zebrad/src/components/health.rs
  zebrad/src/components/health/config.rs
  zebrad/src/components/health/tests.rs
  zebrad/src/components/sync/progress.rs
  zebrad/src/config.rs
  zebrad/tests/common/configs/v2.6.0.toml
Labels: A-devops, I-usability, C-feature, P-Medium :zap:

#9735 test(fix): Uncomment & update `disconnects_from_misbehaving_peers`
  zebra-chain/src/parameters/network/testnet.rs
  zebrad/tests/acceptance.rs
Labels: queued

#9951 fix(state): Avoid heap allocations in `expand_zero_be_bytes()`
  zebra-state/src/service/finalized_state/disk_format.rs
  zebra-state/src/service/finalized_state/disk_format/block.rs
  zebra-state/src/service/finalized_state/disk_format/transparent.rs
Labels: I-slow, A-state, P-Low :snowflake:, queued

#9810 feat: introduce `BytesInDisplayOrder` trait to standardize byte-reversed encoding in RPC (#9806)
  zebra-chain/src/block/arbitrary.rs
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/block/hash.rs
  zebra-chain/src/block/merkle.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/serialization.rs
  zebra-chain/src/serialization/display_order.rs
  zebra-chain/src/transaction/auth_digest.rs
  zebra-chain/src/transaction/hash.rs
  zebra-chain/src/work/difficulty.rs
  zebra-rpc/src/indexer.rs
  zebra-rpc/src/indexer/methods.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/types/get_block_template.rs
  zebra-rpc/src/methods/types/get_block_template/proposal.rs
  zebra-rpc/tests/serialization_tests.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/lightwalletd/send_transaction_test.rs
Labels: C-feature, external-contribution, queued

#9952 cleanup: Apply suggestions for code cleanup from NU6.1 audit.
  zebra-chain/src/parameters/constants.rs
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-chain/src/parameters/network_upgrade.rs
Labels: C-cleanup, C-trivial, P-Medium :zap:, queued

#9964 cleanup(feature): Fully remove `getblocktemplate-rpcs` feature flag
  CHANGELOG.md
  zebrad/Cargo.toml
Labels: C-cleanup, A-release, queued

#9967 fix(clippy): Change `println!` to `tracing::info!` in test
  zebrad/src/components/health/tests.rs
Labels: extra-reviews, queued
