Repository ZcashFoundation/zebra, pull requests merged in 2025-04, with the labels that each got.

#9336 feat: Add Mempool Specification to Zebra Book
  book/src/SUMMARY.md
  book/src/dev/diagrams/mempool-architecture.md
  book/src/dev/mempool-specification.md
Labels: C-feature

#9316 feat(rpc): Support negative heights in `HashOrHeight`
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/request.rs
Labels: A-rpc, C-feature, A-compatibility, P-Medium :zap:

#9387 Update `zcash_transparent` to version 0.2.3
  Cargo.lock
  Cargo.toml
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-scan/Cargo.toml
  zebra-scan/src/bin/scanning-results-reader/main.rs
  zebra-scan/src/service/scan_task/scan.rs
Labels: P-Medium :zap:, dependencies

#9214 rpc(getpeerinfo): Add inbound peers to method response
  zebra-network/src/address_book_peers/mock.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/peer_info.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_peer_info@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_peer_info@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
Labels: A-network, A-rpc, P-Medium :zap:

#9397 fix(warning): could not canonicalize startup warning
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: C-cleanup, P-Low :snowflake:

#9222 refactor!: remove experimental features from release builds
  .github/workflows/ci-unit-tests-os.yml
  .github/workflows/release-binaries.yml
  book/src/user/docker.md
Labels: A-docs, A-devops, C-cleanup, C-feature, C-trivial, extra-reviews, P-High 🔥

#9401 Remove the `getblocktemplate-rpcs` Cargo feature
  .github/workflows/sub-ci-integration-tests-gcp.yml
  book/src/dev/overview.md
  zebra-chain/Cargo.toml
  zebra-chain/src/transaction.rs
  zebra-chain/src/transparent.rs
  zebra-consensus/Cargo.toml
  zebra-consensus/src/block.rs
  zebra-consensus/src/block/request.rs
  zebra-consensus/src/router.rs
  zebra-node-services/Cargo.toml
  zebra-node-services/src/mempool.rs
  zebra-rpc/Cargo.toml
  zebra-rpc/src/config.rs
  zebra-rpc/src/config/mining.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/methods/types/get_raw_mempool.rs
  zebra-rpc/src/server.rs
  zebra-rpc/src/server/error.rs
  zebra-state/Cargo.toml
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
  zebrad/src/components/mempool.rs
  zebrad/src/config.rs
  zebrad/src/lib.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/config.rs
  zebrad/tests/common/mod.rs
Labels: C-feature, extra-reviews, P-Medium :zap:

#9329 feat(rpc): Add some missing fields to transaction object
  zebra-chain/src/sapling/commitment.rs
  zebra-chain/src/sapling/note/ciphertexts.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-chain/src/transparent.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/getrawtransaction_verbosity=1@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/getrawtransaction_verbosity=1@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/methods/types.rs
  zebra-rpc/src/methods/types/transaction.rs
  zebra-rpc/src/tests/vectors.rs
  zebra-state/src/lib.rs
Labels: A-rpc, C-feature, A-compatibility, P-Medium :zap:

#9388 refactor(ci): Centralize Docker configuration testing using matrix strategy
  .github/workflows/README.md
  .github/workflows/cd-deploy-nodes-gcp.patch-external.yml
  .github/workflows/cd-deploy-nodes-gcp.patch.yml
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/ci-tests.patch-external.yml
  .github/workflows/ci-tests.patch.yml
  .github/workflows/sub-ci-unit-tests-docker.yml
  .github/workflows/sub-test-zebra-config.yml
  docs/decisions/devops/004-improve-docker-conf-tests.md
Labels: C-feature

#9408 feat(getaddresstxids): Make start and end fields optional and apply range rules to match zcashd
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_invalid_end_greater_start@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_invalid_end_greater_start@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_invalid_excessive_start@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_invalid_excessive_start@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_valid_excessive_end@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_valid_excessive_end@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_valid_excessive_start@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_address_tx_ids_valid_excessive_start@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
Labels: A-rpc, C-feature, A-compatibility, P-Medium :zap:

#9344 refactor(docker): Enhance Zebra configuration options and entrypoint logic
  book/src/user/docker.md
  docker/.env
  docker/Dockerfile
  docker/docker-compose.yml
  docker/entrypoint.sh
Labels: C-bug, A-devops, I-integration-fail, I-usability, P-High 🔥

#9423 feat(ci): Centralize zebra configuration testing with Docker
  .github/workflows/README.md
  .github/workflows/cd-deploy-nodes-gcp.patch-external.yml
  .github/workflows/cd-deploy-nodes-gcp.patch.yml
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/ci-tests.patch-external.yml
  .github/workflows/ci-tests.patch.yml
  .github/workflows/sub-ci-unit-tests-docker.yml
  .github/workflows/sub-test-zebra-config.yml
  docs/decisions/devops/004-improve-docker-conf-tests.md
Labels: C-feature

#9433 fix(cd): deploy long-lived instances without health-checks
  .github/workflows/cd-deploy-nodes-gcp.yml
Labels: C-bug, A-infrastructure, A-devops, P-Critical :ambulance:, C-exclude-from-changelog

#9311 add(mining): Restore internal miner
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/work/equihash.rs
  zebra-rpc/src/config/mining.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/src/components/miner.rs
  zebrad/tests/common/configs/v1.9.0-internal-miner.toml
  zebrad/tests/common/configs/v2.2.0.toml
Labels: C-testing, A-rpc, P-Medium :zap:

#9434 fix(ci): set `ZEBRA_CACHE_DIR` in full and checkpoint syncs
  .github/workflows/sub-ci-integration-tests-gcp.yml
Labels: C-bug, A-devops, I-integration-fail, P-Critical :ambulance:, C-exclude-from-changelog

#9446 docs: remove consecutive duplicate words
  zebra-chain/src/block/serialize.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebrad/tests/common/get_block_template_rpcs/get_block_template.rs
Labels: A-docs, C-trivial, P-Low :snowflake:

#9448 fix(log): Downgrade verbose info message
  zebra-state/src/service/finalized_state/disk_db.rs
Labels: I-usability, P-Low :snowflake:

#9256 NU7 constants
  zebra-chain/src/block/commitment.rs
  zebra-chain/src/history_tree.rs
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/primitives/zcash_history.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-consensus/src/checkpoint/list/tests.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-consensus/src/transaction/tests/prop.rs
  zebra-network/src/config.rs
  zebra-network/src/constants.rs
  zebra-network/src/protocol/external/types.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/subsidy.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/configs/v1.9.0.toml
  zebrad/tests/common/regtest.rs
Labels: P-Medium :zap:, NU-7

#9431 fix(publish)!: simplify Docker tagging to remove redundant tags
  .github/workflows/release-binaries.yml
  .github/workflows/sub-build-docker-image.yml
Labels: C-bug, A-devops, C-cleanup, extra-reviews, P-Critical :ambulance:

#9426 refactor(chain): replace sinsemilla with external library
  Cargo.lock
  zebra-chain/Cargo.toml
  zebra-chain/src/orchard/sinsemilla.rs
  zebra-chain/src/orchard/tests/vectors/sinsemilla.rs
Labels: P-Medium :zap:

#9469 chore: Update docs
  .github/pull_request_template.md
  README.md
  book/src/user/troubleshooting.md
Labels: A-docs, A-release, C-exclude-from-changelog
