Repository ZcashFoundation/zebra, pull requests merged in 2025-02, with the labels that each got.

#9139 fix(consensus): Verify consensus branch ID in SIGHASH precomputation
  book/src/dev/rfcs/0003-inventory-tracking.md
  book/src/dev/rfcs/0006-contextual-difficulty.md
  book/src/dev/rfcs/drafts/0005-treestate.md
  zebra-chain/src/error.rs
  zebra-chain/src/lib.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-chain/src/parameters/network/tests/vectors.rs
  zebra-chain/src/parameters/network_upgrade.rs
  zebra-chain/src/primitives/zcash_note_encryption.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-chain/src/serialization/error.rs
  zebra-chain/src/tests/vectors.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/serialize.rs
  zebra-chain/src/transaction/sighash.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-chain/src/transaction/txid.rs
  zebra-consensus/src/script.rs
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-scan/Cargo.toml
  zebra-script/src/lib.rs
  zebra-test/src/net.rs
  zebrad/src/commands/copy_state.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/mempool/storage/tests/prop.rs
  zebrad/src/components/mempool/storage/tests/vectors.rs
  zebrad/src/components/sync.rs
  zebrad/tests/common/test_type.rs
Labels: C-bug, A-consensus, NU-6, C-trivial, P-Medium :zap:

#9041 Run `cargo autoinherit`
  Cargo.toml
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-dependencies, P-Critical :ambulance:

#9198 chore: Minor cleanups
  book/src/user/tracing.md
  zebra-consensus/src/transaction.rs
  zebra-rpc/src/server.rs
  zebra-script/src/lib.rs
  zebrad/src/commands/start.rs
Labels: A-docs, C-testing, C-trivial, P-Critical :ambulance:

#9202 docs: add CI/CD architecture documentation
  .github/workflows/README.md
  README.md
Labels: A-docs, C-design, A-devops, do-not-merge, C-trivial, P-Medium :zap:

#9195 chore(release): Zebra release v2.2.0
  CHANGELOG.md
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
  zebrad/src/components/sync/end_of_support.rs
Labels: C-trivial, A-release, P-Critical :ambulance:

#9176 fix(mining): Advertise mined blocks
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebra-rpc/src/methods/get_block_template_rpcs/types/submit_block.rs
  zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebra-rpc/src/server/error.rs
  zebra-rpc/src/server/tests/vectors.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
  zebrad/src/components/sync/gossip.rs
  zebrad/tests/acceptance.rs
Labels: A-network, A-rpc, A-concurrency, P-Medium :zap:

#9207 fix(ci): pin release-drafter to v6.0.0 to prevent duplicate drafts
  .github/workflows/release-drafter.yml
Labels: C-bug, A-devops, C-trivial, P-Critical :ambulance:

#9175 fix(chain): Use network kind of `TestnetKind` in transparent addresses on Regtest
  zebra-chain/src/parameters/network.rs
  zebra-chain/src/primitives/zcash_primitives.rs
  zebra-consensus/src/error.rs
Labels: C-bug, I-usability, C-testing, A-rpc, A-state, C-trivial, P-High 🔥

#9167 Add invalidate block method and invalidated_blocks field to NonFinalizedState
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
Labels: I-usability, C-testing, A-rpc, A-state, C-feature, P-Medium :zap:

#9217 feat(rpc); Add `blockcommitments` field to `getblock` output
  zebra-chain/src/block/header.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshots/get_block_header_hash_verbose@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_header_hash_verbose@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_header_height_verbose@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_header_height_verbose@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_1@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_1@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_default@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_default@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_1@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_1@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_default@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_default@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
Labels: A-rpc, C-feature, P-Medium :zap:

#9224 fix(config): Correctly serialize testnet parameters into toml config format
  zebra-chain/src/parameters/network/subsidy.rs
  zebra-chain/src/parameters/network/testnet.rs
  zebra-network/src/config.rs
  zebra-network/src/config/tests/vectors.rs
Labels: C-enhancement, C-cleanup, C-testing, C-trivial, C-tech-debt, P-Medium :zap:

#9242 change(rpc): Accept an unused second param in `sendrawtransaction` RPC
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
Labels: C-cleanup, A-rpc, C-trivial, P-Low :snowflake:

#9215 feat(rpc): Add fields to `getblockchaininfo` RPC output
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_blockchain_info_future_nu6_height@nu6testnet_10.snap
  zebra-rpc/src/methods/types.rs
  zebra-rpc/src/methods/types/get_blockchain_info.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/disk_db.rs
  zebra-state/src/service/finalized_state/zebra_db.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/difficulty.rs
  zebra-state/src/service/read/tree.rs
Labels: I-integration-fail, A-rpc, A-state, lightwalletd, C-feature, P-High 🔥

#8923 ci: Refactor Dockerfile & entrypoint
  .dockerignore
  .github/workflows/README.md
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/ci-tests.yml
  .github/workflows/sub-build-docker-image.yml
  .github/workflows/sub-ci-integration-tests-gcp.yml
  .github/workflows/sub-ci-unit-tests-docker.yml
  .github/workflows/sub-deploy-integration-tests-gcp.yml
  .github/workflows/sub-test-zebra-config.yml
  book/src/user/docker.md
  book/src/user/mining-docker.md
  docker/Dockerfile
  docker/default_zebra_config.toml
  docker/docker-compose.test.yml
  docker/docker-compose.yml
  docker/entrypoint.sh
  zebra-scan/tests/scan_task_commands.rs
  zebra-scan/tests/scanner.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/cached_state.rs
  zebrad/tests/common/configs/v2.1.0.toml
  zebrad/tests/common/launch.rs
  zebrad/tests/common/lightwalletd.rs
  zebrad/tests/common/sync.rs
  zebrad/tests/common/test_type.rs
Labels: C-bug, A-devops, C-trivial, P-Medium :zap:

#9252 fix(ci): prevent duplicate draft releases in release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: C-trivial

#9251 fix(tests): Check if a cached state is present in scanner tests
  docker/entrypoint.sh
  zebra-scan/tests/scan_task_commands.rs
  zebra-scan/tests/scanner.rs
Labels: C-bug, C-trivial, A-blockchain-scanner, P-High 🔥

#9249 feat(rpc): add verbose support to getrawmempool
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/unmined.rs
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/methods/types.rs
  zebra-rpc/src/methods/types/get_raw_mempool.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/storage.rs
  zebrad/src/components/mempool/storage/tests/prop.rs
  zebrad/src/components/mempool/storage/tests/vectors.rs
  zebrad/src/components/mempool/storage/verified_set.rs
  zebrad/src/components/mempool/tests/prop.rs
  zebrad/src/components/mempool/tests/vector.rs
Labels: C-feature, P-Medium :zap:

#9201 feat(network): Track misbehaving peer connections and ban them past a threshold
  zebra-chain/src/tests/vectors.rs
  zebra-consensus/src/block.rs
  zebra-consensus/src/checkpoint.rs
  zebra-consensus/src/checkpoint/list.rs
  zebra-consensus/src/error.rs
  zebra-consensus/src/router.rs
  zebra-network/src/address_book.rs
  zebra-network/src/address_book_updater.rs
  zebra-network/src/config/cache_dir.rs
  zebra-network/src/constants.rs
  zebra-network/src/meta_addr.rs
  zebra-network/src/meta_addr/tests/prop.rs
  zebra-network/src/meta_addr/tests/vectors.rs
  zebra-network/src/peer/connection.rs
  zebra-network/src/peer/connection/tests/prop.rs
  zebra-network/src/peer/handshake.rs
  zebra-network/src/peer_set/initialize.rs
  zebra-network/src/peer_set/initialize/tests/vectors.rs
  zebra-network/src/peer_set/set.rs
  zebra-network/src/peer_set/set/tests.rs
  zebra-network/src/protocol/internal/response.rs
  zebra-rpc/src/methods/get_block_template_rpcs.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/inbound.rs
  zebrad/src/components/inbound/downloads.rs
  zebrad/src/components/inbound/tests/fake_peer_set.rs
  zebrad/src/components/inbound/tests/real_peer_set.rs
  zebrad/src/components/mempool.rs
  zebrad/src/components/mempool/downloads.rs
  zebrad/src/components/mempool/storage.rs
  zebrad/src/components/mempool/tests/prop.rs
  zebrad/src/components/mempool/tests/vector.rs
  zebrad/src/components/sync.rs
  zebrad/src/components/sync/downloads.rs
  zebrad/src/components/sync/tests/timing.rs
  zebrad/src/components/sync/tests/vectors.rs
  zebrad/tests/acceptance.rs
  zebrad/tests/common/get_block_template_rpcs/get_block_template.rs
  zebrad/tests/common/get_block_template_rpcs/get_peer_info.rs
Labels: C-bug, C-enhancement, C-security, I-heavy, I-invalid-data, A-network, C-feature, A-mempool, P-Medium :zap:

#9261 feature(rpc): Extend `getinfo`
  Cargo.lock
  zebra-rpc/Cargo.toml
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/prop.rs
  zebra-rpc/src/methods/tests/snapshot.rs
  zebra-rpc/src/methods/tests/snapshots/get_info@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_info@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-rpc/src/server.rs
  zebra-rpc/src/server/tests/vectors.rs
  zebrad/src/application.rs
  zebrad/src/commands/start.rs
  zebrad/src/components/tracing/component.rs
  zebrad/tests/acceptance.rs
Labels: A-rpc, C-feature, P-Medium :zap:

#9257 refactor(ci): do not run workflows tied to `ZcashFoundation` infra in forks
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/chore-delete-gcp-resources.yml
  .github/workflows/ci-unit-tests-os.yml
  .github/workflows/docs-deploy-firebase.yml
  .github/workflows/docs-dockerhub-description.yml
  .github/workflows/sub-build-docker-image.yml
  .github/workflows/sub-ci-integration-tests-gcp.yml
Labels: C-bug, A-devops, I-integration-fail, C-trivial, P-Critical :ambulance:

#9269 docs(docker): update examples for running Zebra in Docker
  .dockerignore
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/sub-ci-unit-tests-docker.yml
  book/src/user/docker.md
  book/src/user/mining-docker.md
  docker/.env
  docker/Dockerfile
  docker/default-zebra-config.toml
  docker/docker-compose.grafana.yml
  docker/docker-compose.lwd.yml
  docker/docker-compose.test.yml
  docker/docker-compose.yml
  docker/entrypoint.sh
  docker/test.env
  docker/zcash.conf
  prometheus.yaml
  zebrad/tests/common/configs/custom-conf.toml
  zebrad/tests/common/configs/v2.1.0.toml
Labels: A-docs, A-devops, P-Critical :ambulance:

#9274 fix(ci): improve workflow conditions for cached disk jobs
  .github/workflows/cd-deploy-nodes-gcp.patch-external.yml
  .github/workflows/cd-deploy-nodes-gcp.patch.yml
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/chore-delete-gcp-resources.yml
Labels: C-bug, A-infrastructure, A-devops, C-trivial, P-Critical :ambulance:

#9279 fix(ci): temporarily disable `test-zebra-conf-path`
  .github/workflows/cd-deploy-nodes-gcp.yml
Labels: C-bug, A-devops, C-trivial, P-Critical :ambulance:

#9277 chore: Update the PR template
  .github/ISSUE_TEMPLATE/release.md
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/release-drafter.yml
Labels: A-devops, C-trivial, P-Low :snowflake:, C-exclude-from-changelog

#9280 change(ci): Remove check for custom configs from GCP deployments
  .github/workflows/cd-deploy-nodes-gcp.patch-external.yml
  .github/workflows/cd-deploy-nodes-gcp.patch.yml
  .github/workflows/cd-deploy-nodes-gcp.yml
Labels: C-bug, A-devops, C-trivial, P-Medium :zap:, C-exclude-from-changelog

#9289 chore: Fix Clippy lints for Rust 1.85
  zebra-consensus/src/checkpoint.rs
  zebra-rpc/src/server/http_request_compatibility.rs
  zebra-state/src/service.rs
Labels: P-High 🔥, C-exclude-from-changelog

#9290 chore: Bump Rust from 1.84.0 to 1.85.0 in Docker
  docker/Dockerfile
Labels: A-devops, P-Low :snowflake:, C-exclude-from-changelog

#9288 chore(CI): Update codespell's config
  .codespellrc
  zebra-state/src/request.rs
Labels: P-Low :snowflake:, C-exclude-from-changelog

#9309 fix: fix redundant #[non_exhaustive] attributes on enum variants
  zebra-script/src/lib.rs
Labels: A-script, P-Optional :sparkles:, C-exclude-from-changelog
