Repository ZcashFoundation/zebra, pull requests merged in 2025-01, with the labels that each got.

#9117 fix(workflows): update patch jobs conditions and naming
  .github/workflows/cd-deploy-nodes-gcp.patch-external.yml
  .github/workflows/cd-deploy-nodes-gcp.patch.yml
  .github/workflows/ci-tests.patch-external.yml
  .github/workflows/ci-tests.patch.yml
  .github/workflows/docs-deploy-firebase.patch-external.yml
  .github/workflows/docs-deploy-firebase.patch.yml
Labels: C-bug, A-devops, I-hang, C-trivial, P-High 🔥

#9119 fix(CI): Remove the "Release crates" workflow
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  .github/workflows/release-crates-io.patch.yml
  .github/workflows/release-crates-io.yml
  .github/workflows/scripts/release-crates-dry-run.sh
Labels: C-bug, A-devops, C-trivial, extra-reviews, P-High 🔥

#9114 chore: Fix new clippy lints
  .github/PULL_REQUEST_TEMPLATE/release-checklist.md
  .github/workflows/release-crates-io.patch.yml
  .github/workflows/release-crates-io.yml
  .github/workflows/scripts/release-crates-dry-run.sh
  Cargo.lock
  book/src/user/docker.md
  book/src/user/install.md
  tower-batch-control/Cargo.toml
  tower-fallback/Cargo.toml
  zebra-chain/Cargo.toml
  zebra-consensus/Cargo.toml
  zebra-grpc/Cargo.toml
  zebra-network/Cargo.toml
  zebra-network/src/protocol/external/codec.rs
  zebra-node-services/Cargo.toml
  zebra-rpc/Cargo.toml
  zebra-rpc/src/server/http_request_compatibility.rs
  zebra-scan/Cargo.toml
  zebra-script/Cargo.toml
  zebra-state/Cargo.toml
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-test/Cargo.toml
  zebra-utils/Cargo.toml
  zebrad/Cargo.toml
Labels: A-rust, C-trivial, P-High 🔥

#9098 add(test): Add serialized NU5 blocks to test vectors
  zebra-chain/src/block/tests/vectors.rs
  zebra-chain/src/tests/vectors.rs
  zebra-chain/src/transaction.rs
  zebra-chain/src/transaction/arbitrary.rs
  zebra-chain/src/transaction/tests/vectors.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-test/src/vectors/block-main-1-687-106.txt
  zebra-test/src/vectors/block-main-1-687-107.txt
  zebra-test/src/vectors/block-main-1-687-108.txt
  zebra-test/src/vectors/block-main-1-687-113.txt
  zebra-test/src/vectors/block-main-1-687-118.txt
  zebra-test/src/vectors/block-main-1-687-121.txt
  zebra-test/src/vectors/block-test-1-842-421.txt
  zebra-test/src/vectors/block-test-1-842-432.txt
  zebra-test/src/vectors/block-test-1-842-462.txt
  zebra-test/src/vectors/block-test-1-842-467.txt
  zebra-test/src/vectors/block-test-1-842-468.txt
  zebra-test/src/vectors/block.rs
Labels: C-testing, C-trivial, P-Medium :zap:

#9126 change(consensus): Optimize checks for coinbase transactions
  zebra-consensus/src/error.rs
  zebra-consensus/src/transaction/check.rs
  zebra-consensus/src/transaction/tests.rs
Labels: A-consensus, P-Low :snowflake:

#9003 feat(actions): use GitHub `environments` for infra deployments
  .github/workflows/cd-deploy-nodes-gcp.yml
  .github/workflows/chore-delete-gcp-resources.yml
  .github/workflows/sub-build-docker-image.yml
  .github/workflows/sub-deploy-integration-tests-gcp.yml
  .github/workflows/sub-find-cached-disks.yml
Labels: C-design, A-infrastructure, A-devops, I-usability, C-feature, C-trivial, P-High 🔥

#9131 chore: delete repetitive words
  book/src/dev/zebra-dependencies-for-audit.md
  tower-batch-control/src/worker.rs
  zebra-chain/src/history_tree/tests/vectors.rs
  zebra-chain/src/transaction/builder.rs
  zebra-consensus/src/checkpoint.rs
  zebra-rpc/src/queue.rs
Labels: C-trivial

#9151 fix(rpc): Use `jsonrpsee` in `zebra-node-services`
  Cargo.lock
  zebra-node-services/Cargo.toml
  zebra-node-services/src/rpc_client.rs
  zebra-rpc/Cargo.toml
Labels: C-cleanup, A-rpc, P-Low :snowflake:

#9153 Docs: fix typos in documentation files
  .github/ISSUE_TEMPLATE/usability_testing_plan.md
  book/src/dev/rfcs/0000-template.md
  book/src/dev/rfcs/0009-zebra-client.md
  book/src/dev/rfcs/drafts/xxxx-basic-integration-testing.md
  zebra-network/src/address_book.rs
Labels: C-trivial

#9171 Run dependabot monthly instead of weekly
  .github/dependabot.yml
Labels: C-trivial

#9177 fix spelling issues
  .github/workflows/chore-delete-gcp-resources.yml
  book/src/dev/rfcs/drafts/data-flow-2020-07-22.md
Labels: C-trivial

#9180 chore(checkpoints): Update the mainnet and testnet checkpoints for v2.2.0
  zebra-consensus/src/checkpoint/main-checkpoints.txt
  zebra-consensus/src/checkpoint/test-checkpoints.txt
  zebra-utils/README.md
Labels: C-trivial

#9118 fix(consensus): Avoid a concurrency bug when verifying transactions in blocks that are already present in the mempool
  zebra-consensus/src/transaction.rs
  zebra-consensus/src/transaction/tests.rs
  zebra-node-services/src/mempool/transaction_dependencies.rs
  zebra-state/src/request.rs
Labels: C-bug, C-trivial, A-concurrency, P-Medium :zap:

#9189 docs: corrections
  .github/workflows/sub-ci-unit-tests-docker.yml
  .github/workflows/sub-test-zebra-config.yml
Labels: C-trivial

#9188 release(maintenance): Run cargo update for v2.2.0
  Cargo.lock
  deny.toml
Labels: C-trivial
