Repository ZcashFoundation/zebra, pull requests merged in 2025-03, with the labels that each got.

#9281 refactor(docker): allow r/w access in mounted volumes
  book/src/user/docker.md
  docker/Dockerfile
  docker/entrypoint.sh
Labels: A-devops, P-High 🔥, C-exclude-from-changelog

#9310 docs(decisions): add architectural decision records structure
  docs/decisions/README.md
  docs/decisions/devops/0001-docker-high-uid.md
  docs/decisions/devops/0002-docker-use-gosu.md
  docs/decisions/devops/0003-filesystem-hierarchy.md
  docs/decisions/template.md
Labels: A-docs, C-design, C-feature, P-Low :snowflake:

#9318 fix(ci): Add Rust environment variables to Docker test workflows
  .github/workflows/sub-build-docker-image.yml
  .github/workflows/sub-ci-unit-tests-docker.yml
  .github/workflows/sub-deploy-integration-tests-gcp.yml
  docker/Dockerfile
Labels: A-devops, C-enhancement, I-usability, C-feature, P-High 🔥, C-exclude-from-changelog

#9323 fix(ci): Better permission and cache dirs handling in Docker
  .github/workflows/sub-ci-integration-tests-gcp.yml
  .github/workflows/sub-ci-unit-tests-docker.yml
  docker/Dockerfile
  docker/entrypoint.sh
Labels: C-bug, A-devops, P-Critical :ambulance:, C-exclude-from-changelog

#9333 fix(docker): set `HOME` environment variable explicitly in Dockerfile
  docker/Dockerfile
Labels: C-bug, A-devops, P-Critical :ambulance:, C-exclude-from-changelog

#9260 feat(state): Implements reconsider_block method
  zebra-state/src/constants.rs
  zebra-state/src/error.rs
  zebra-state/src/service/non_finalized_state.rs
  zebra-state/src/service/non_finalized_state/chain.rs
  zebra-state/src/service/non_finalized_state/tests/vectors.rs
Labels: A-state, C-feature, P-Medium :zap:

#9272 fix(rpc): getblocktemplate coinbase outputs order
  zebra-rpc/src/methods/get_block_template_rpcs/get_block_template.rs
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template_basic.coinbase_tx@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template_basic.coinbase_tx@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template_basic@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template_basic@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template_long_poll.coinbase_tx@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template_long_poll.coinbase_tx@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template_long_poll@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template_long_poll@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
Labels: A-rpc, A-compatibility, P-Medium :zap:, A-block-explorer

#9263 change(state): Refactor format upgrades into trait
  zebra-state/src/constants.rs
  zebra-state/src/lib.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade/no_migration.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade/prune_trees.rs
  zebra-state/src/service/finalized_state/disk_format/upgrade/tree_keys_and_caches_upgrade.rs
Labels: C-cleanup, A-state, C-tech-debt, P-Medium :zap:

#9327 feat(rpc): fill size field in getblock with verbosity=2
  zebra-rpc/src/methods.rs
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_hash_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@mainnet_10.snap
  zebra-rpc/src/methods/tests/snapshots/get_block_verbose_height_verbosity_2@testnet_10.snap
  zebra-rpc/src/methods/tests/vectors.rs
  zebra-state/src/lib.rs
  zebra-state/src/request.rs
  zebra-state/src/response.rs
  zebra-state/src/service.rs
  zebra-state/src/service/finalized_state/zebra_db/block.rs
  zebra-state/src/service/read.rs
  zebra-state/src/service/read/block.rs
Labels: C-feature

#9110 CI: Add workflow that runs zizmor latest
  .github/workflows/zizmor.yml
Labels: A-devops, A-diagnostics, C-trivial, P-Low :snowflake:

#9334 fix(docker): add default CMD to test stage in Dockerfile
  docker/Dockerfile
Labels: C-bug, A-devops, P-Low :snowflake:
